### PR TITLE
fix(secret): allows several units having the same label for owned secret

### LINKED ISSUE #21344: Juju 4.0.1: second+ unit cannot create Juju Secret with the same label. Error: secret with label "database-peers.postgresql.unit" already exists
### Description

Hi,

Branched from [here](https://github.com/canonical/postgresql-operator/pull/1318#issuecomment-3585861173) on @anvial request.

TL;DR: it looks like Juju 4 doesn't allow the same Juju Secrets **label** for different units, while it used to work well in Juju 3.6:
```
> juju version
3.6.12-genericlinux-amd64

> juju secrets
ID                    Name  Owner         Rotation  Revision  Last updated
d4k4mdm05d8c5p9k29r0  -     postgresql    never            1  10 minutes ago  
d4k4mem05d8c5p9k29rg  -     postgresql/0  never            1  9 minutes ago   
d4k4q7u05d8c5p9k29s0  -     postgresql/1  never            1  2 minutes ago   

> juju show-secret d4k4mem05d8c5p9k29rg
d4k4mem05d8c5p9k29rg:
  revision: 1
  owner: postgresql/0
  label: database-peers.postgresql.unit
  created: 2025-11-27T12:59:47Z
  updated: 2025-11-27T12:59:47Z
> juju show-secret d4k4q7u05d8c5p9k29s0
d4k4q7u05d8c5p9k29s0:
  revision: 1
  owner: postgresql/1
  label: database-peers.postgresql.unit
  created: 2025-11-27T13:07:44Z
  updated: 2025-11-27T13:07:44Z
```

On juju 4:
```
unit-postgresql-2: 13:35:52 ERROR juju.worker.uniter.context cannot apply changes: creating secrets: secret with label "database-peers.postgresql.unit" already exists                                                                                  
unit-postgresql-2: 13:35:52 ERROR juju.worker.uniter.operation hook "start" (via hook dispatching script: dispatch) failed: creating secrets: secret with label "database-peers.postgresql.unit" already exists 
```

Image

### Juju version

4.0.1

### Cloud

LXD

### Expected behaviour

`juju deploy postgresql --channel 16/edge/juju4` works well on Juju 3.6 and Juju 4.0.

### Reproduce / Test

Preared the charmhub branch for amd64:
```
juju deploy postgresql --channel 16/edge/juju4 --base ubuntu@24.04 # wait for ALL OK
juju add-unit postgresql -n 1 # will fail on Juju 4.0.1, but works well on 3.6.12
```

If charmhub branch `16/edge/juju4 ` got cleaned:
```
git clone https://github.com/canonical/postgresql-operator/pull/1318
charmcraftcache pack
juju deploy ./postgresql_ubuntu@24.04-amd64.charm # it will be OK on Juju 3.6 and 4.0
juju add-unit postgresql -n 1 # will fail on Juju 4.0.1, but works well on 3.6.12
```

### Notes & References

I am not sure about the bugreport here, maybe it is a new Juju 4 feature, but I see nothing in release notes about it.

### PR DESCRIPTION
**Pull request by gfouillet**
This is a minimal changes on the sql to fix #21344

I am working on an ongoing PR which will remove RunAtomic from secret domain, but it is a huge work even for simple paths so i choose to split the work.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

follow step from joined bug, ie:

* deploy postgresql, wait for up
* add unit

Should works without error, and two secrets with label `database-peers.postgresql.unit` should exists, one for each unit.

## Links

**Issue:** Fixes #21344.

**Jira card:** [JUJU-8871](https://warthogs.atlassian.net/browse/JUJU-8871)

[JUJU-8871]: https://warthogs.atlassian.net/browse/JUJU-8871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/secret/state/state.go [hunk 1]
```diff
@@ -192,17 +192,15 @@ func (st State) CheckUnitSecretLabelExists(ctx domain.AtomicContext, unitUUID co
...
     UNION
-    SELECT DISTINCT secret_id
-    FROM   secret_unit_owner suo
-           JOIN unit u ON suo.unit_uuid = u.uuid
-           JOIN unit peer ON peer.application_uuid = u.application_uuid
+    SELECT secret_id
+    FROM   secret_unit_owner AS suo
     WHERE  label = $secretUnitOwner.label
-    AND peer.uuid != u.uuid
+    AND    suo.unit_uuid = $secretUnitOwner.unit_uuid
```
[the remark this answers is not in the document]
Comment (gfouillet) [reply domain/secret/state/state.go:203]: No that the point. We want to count secrets that exists for the same unit, same label.

File: domain/secret/state/state_test.go [hunk 2]
```diff
@@ -157,7 +157,7 @@ func (s *stateSuite) TestCheckUnitSecretLabelExistsAlreadyUsedByUnit(c *tc.C) {
 	c.Assert(exists, tc.IsTrue)
 	exists, err = checkUnitSecretLabelExists(ctx, st, unitUUID1, "my label")
 	c.Assert(err, tc.ErrorIsNil)
-	c.Assert(exists, tc.IsTrue)
+	c.Assert(exists, tc.IsFalse)
```
Comment (wallyworld) [inline domain/secret/state/state_test.go:161]: Let's add a proper test that 2 different units can create the same label
ie we have a test `TestCreateManyUnitSecretsNoLabelClash`. We can do something similar to this test but instead of keeping the unit the same and using different labels, we can use the same label for different units

File: domain/secret/state/state.go [hunk 3]
```diff
@@ -192,17 +192,15 @@ func (st State) CheckUnitSecretLabelExists(ctx domain.AtomicContext, unitUUID co
 SELECT COUNT(*) AS &count.num
 FROM (
     SELECT secret_id
-    FROM   secret_application_owner sao
-           JOIN unit u ON sao.application_uuid = u.application_uuid
+    FROM   secret_application_owner AS sao
+           JOIN unit AS u ON sao.application_uuid = u.application_uuid
     WHERE  label = $secretUnitOwner.label
     AND    u.uuid = $secretUnitOwner.unit_uuid
     UNION
```
Comment (manadart) [inline domain/secret/state/state.go]: `UNION` does an implicit de-dup, so in this case, where unit/app owners are disjoint, `UNION ALL` will be faster.

File: domain/secret/state/state_test.go (hunk 2 above)
Comment (gfouillet) [reply domain/secret/state/state_test.go:161]: Make sense thanks.

Will do.
