### PR TITLE
fix: gracefully handle error when security group is disabled in openstack

### LINKED ISSUE #20513: juju 3.6.9 openstack provider regression when bootstrapping
### Description

With 3.6.9 when i bootstrap a controller using a network with `port_security_disabled = false` it fails because juju is trying to find a security group when running openSSH.

15:17:27 DEBUG goose logger.go:44 TRACE: MakeServiceURL: https://neutron.acme.com:9696/v2.0/security-groups?name=juju-67e72a20-ffbe-4db2-8cc8-340e3fabb4b1-d10d25f1-eeb8-4866-8abd-771853dd9a1e
15:17:27 ERROR juju.cmd.juju.commands bootstrap.go:1032 failed to bootstrap model: cannot open SSH: failed to find security group with name: juju-67e72a20-ffbe-4db2-8cc8-340e3fabb4b1-d10d25f1-eeb8-4866-8abd-771853dd9a1e
15:17:27 DEBUG juju.cmd.juju.commands bootstrap.go:1033 (error details: [{github.com/juju/juju/cmd/juju/commands.(*bootstrapCommand).Run:1131: failed to bootstrap model} {github.com/juju/juju/environs/bootstrap.Bootstrap:729: } {github.com/juju/juju/environs/bootstrap.bootstrapIAAS:597: } {github.com/juju/juju/provider/common.Bootstrap:63: } {github.com/juju/juju/provider/common.BootstrapInstance:299: cannot open SSH} {github.com/juju/juju/provider/openstack.(*Environ).OpenModelPorts:2152: } {github.com/juju/juju/provider/openstack.(*neutronFirewaller).OpenModelPorts:563: } {github.com/juju/juju/provider/openstack.(*neutronFirewaller).openPortsInGroup:692: } {github.com/juju/retry.Call:188: } {failed to find security group with name: juju-67e72a20-ffbe-4db2-8cc8-340e3fabb4b1-d10d25f1-eeb8-4866-8abd-771853dd9a1e}])

This worked fine in 3.6.8 and I suspect it may be related to the SG api efficiency fixes that landed in 3.6.9

### Juju version

3.6.9

### Cloud

OpenStack

### Expected behaviour

Juju should not attempt to use a security group when an OpenStack network with `port_security_disabled = false` is used.

### Reproduce / Test

#!/bin/bash -eux
: ${controller_name:=test}
: ${controller_series:=jammy}

declare -a model_config=()
declare -a model_defaults=( 'use-default-secgroup=true'
                            'network=net_psd'
                            'image-metadata-url=https://radosgw.acme.com:443/swift/v1/simplestreams/data/'
                           )
for d in ${model_defaults[@]}; do model_config+=( "--config $d" ); done
juju bootstrap --debug --verbose prodstack --bootstrap-series ${controller_series} ${model_config[@]} ${controller_name}
juju model-defaults ${model_defaults[@]}

### Notes & References

https://github.com/juju/juju/releases/tag/v3.6.9

### PR DESCRIPTION
**Pull request by adisazhar123**
When bootstrapping to openstack with **security group disabled**, we should be gracefully handling the missing security group error when trying to open the model. However, in 3.6.9, we made a change to fetch a security group by name in which the error wasn't propagated correctly, which caused the bootstrap to fail.

We have a check to exit early if a security group was not found ([ref](https://github.com/juju/juju/blob/5964c59b095522ac796eb37afc3f136cff3e1248/internal/provider/openstack/firewaller.go#L557-L560)) , but due to the change in 3.6.9, the error propagated was different, thus the check to ` errors.IsNotFound(err) ` resolves to false, and juju mistakenly thinks it's a fatal error.

This PR translates the Goose API not found error ([ref](https://github.com/go-goose/goose/blob/6428799c7cac05d7106fdfa7bb17a7bea0f8655e/neutron/neutron.go#L409)) to Juju not found error, so that we can exit early if a security group was not found.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [ ] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

Unit tests passes.

To test the functionality, this requires a specific Openstack deployment where security group is disabled. I don't think we have access to this AFAIK.

## Documentation changes

N/A

## Links

**Issue:** Fixes #20513.

**Jira card:** [JUJU-8432](https://warthogs.atlassian.net/browse/JUJU-8432)

**Goose PR:** https://github.com/go-goose/goose/pull/103

[JUJU-8432]: https://warthogs.atlassian.net/browse/JUJU-8432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: internal/provider/openstack/firewaller.go [hunk 1]
```diff
@@ -665,7 +665,9 @@ func (c *neutronFirewaller) getSecurityGroupByName(ctx context.ProviderCallConte
 	}
 	retryStrategy.Func = func() error {
 		groups, err := neutronClient.SecurityGroupByNameV2(name)
-		if err != nil {
+		if gooseerrors.IsNotFound(err) {
```
Comment (wallyworld) [inline internal/provider/openstack/firewaller.go:668]: Let's ensure we have a juju unit test

**Comment by CodingCookieRookie** [comment]
thanks for the change adis, will take a look again after the unit test is added

**Comment by adisazhar123** [comment]
@wallyworld @CodingCookieRookie unit test changes pushed. Can take another look please?

File: internal/provider/openstack/firewaller.go [hunk 2]
```diff
@@ -554,8 +557,13 @@ func (c *neutronFirewaller) IngressRules(ctx context.ProviderCallContext) (firew
 // OpenModelPorts implements Firewaller interface
 func (c *neutronFirewaller) OpenModelPorts(ctx context.ProviderCallContext, rules firewall.IngressRules) error {
 	err := c.openPortsInGroup(ctx, c.jujuGroupName(c.environ.controllerUUID), rules)
-	if errors.IsNotFound(err) && !c.environ.usingSecurityGroups {
+	if errors.Is(err, errors.NotFound) && !c.environ.usingSecurityGroups {
 		logger.Warningf("attempted to open %v but network port security is disabled. Already open", rules)
+
+		// Only used for tests.
+		if c.NotifySecGroupNotFoundWhenDisabled != nil {
```
Comment (wallyworld) [inline internal/provider/openstack/firewaller.go]: We don't need any of this. We just want to test that OpenModelPorts returns nil when goose gives not found and the using sec groups bool is false.

File: internal/provider/openstack/local_test.go [hunk 3]
```diff
@@ -2058,8 +2058,70 @@ func (s *localServerSuite) TestGetSecurityGroupByName(c *gc.C) {
 	c.Assert(err, jc.ErrorIsNil)
 	c.Assert(group2.Id, gc.Equals, groupResult.Id)
 
-	groupResult, err = openstack.GetSecurityGroupByName(s.env, s.callCtx, "juju-unknown-machine-name")
-	c.Assert(err, gc.ErrorMatches, "failed to find security group with name: juju-unknown-machine-name")
+	// The goose error returned by Neutron service should be translated to an errors.NotFound.
+	_, err = openstack.GetSecurityGroupByName(s.env, s.callCtx, "juju-unknown-machine-name")
+	c.Assert(err, jc.ErrorIs, errors.NotFound)
```
Comment (wallyworld) [inline internal/provider/openstack/local_test.go:2063]: This is really all we need - check for the error type
Plus a test that err is nil if usingSecurityGroups is false

File: internal/provider/openstack/local_test.go [hunk 4]
```diff
@@ -2058,8 +2058,70 @@ func (s *localServerSuite) TestGetSecurityGroupByName(c *gc.C) {
...
+	notifySecGroupMissing := func() {
+		secGroupMissingAndDisabled = true
+	}
+
+	err = openstack.OpenModelPorts(s.env, s.callCtx, enableSecurityGroup, controllerUUID, rules, notifySecGroupMissing)
+	c.Assert(err, gc.IsNil)
+	c.Assert(secGroupMissingAndDisabled, gc.Equals, false)
+}
+
+// TestOpenModelPortsSecurityGroupDisabled returns nil when security group is disabled
```
Comment (CodingCookieRookie) [inline internal/provider/openstack/local_test.go]: nit: do you mean the err returns nil?

File: internal/provider/openstack/firewaller.go (hunk 2 above)
Comment (adisazhar123) [reply internal/provider/openstack/firewaller.go]: Addressed. Thanks.

File: internal/provider/openstack/local_test.go (hunk 3 above)
Comment (adisazhar123) [reply internal/provider/openstack/local_test.go:2063]: Addressed in `TestOpenModelPorts*` test cases below.

File: internal/provider/openstack/local_test.go (hunk 4 above)
Comment (adisazhar123) [reply internal/provider/openstack/local_test.go]: Yup, have reworded the comments to make it more clear. Thanks.

**Comment by adisazhar123** [comment]
@CodingCookieRookie @wallyworld I have pushed new changes to address your comments. Proceeding to merge. Thank you.

File: internal/provider/openstack/export_test.go [hunk 5]
```diff
@@ -81,6 +82,22 @@ func GetSecurityGroupByName(e environs.Environ, ctx context.ProviderCallContext,
...
 }
 
+func OpenModelPorts(
+	e environs.Environ,
+	ctx context.ProviderCallContext,
+	enableSecurityGroup bool,
+	controllerUUID string,
+	rules firewall.IngressRules,
+) error {
+	environ := e.(*Environ)
```
Comment (jameinel) [inline internal/provider/openstack/export_test.go:92]: Shouldn't this be a "environ, ok :=" check returning an error if it is the wrong type rather than causing a runtime panic?
