### PR TITLE
fix: deploy local charm with local resource 

### LINKED ISSUE #22121: Juju 4.0.x: Deploying local charm with a local resource fails — "resource not found"
### Description

While working on a local k8s charm that includes an OCI image, 

$ juju deploy ./juju-norma-k8s_amd64.charm --resource juju-norma-image=ghcr.io/sinanawad/juju-norma:latest
Located local charm "juju-norma-k8s", revision 0
ERROR resource "juju-norma-image": Put https://127.0.0.1:39007/model/.../applications/juju-norma-k8s/resources/juju-norma-image?pendingid=1a6a8223-d58b-4a79-82fb-f35e62efaac3: resource juju-norma-image of application juju-norma-k8s not found

Charmhub deploys work fine of the same charm, only local charm deploys with `--resource` are affected.

### Juju version

4.0.6

### Cloud

Kubernetes

### Expected behaviour

juju deploy ./local.charm --resource foo=registry/image:tag should succeed 

### Reproduce / Test

juju bootstrap microk8s k8s
juju add-model test microk8s -c k8s

juju deploy ./my-charm_amd64.charm --resource my-image=ghcr.io/org/image:latest
# ERROR resource "my-image": Put https://.../resources/my-image?pendingid=<uuid>: resource my-image of application my-charm not found

## What Would Uncle Claude Do??

Uncle Claude speculates this is a continuation of  this [issue](https://github.com/juju/juju/issues/21456)  and a partial fix in [this](https://github.com/juju/juju/pull/21775) PR  - see the analysis below

### Root Cause

The deploy flow for local charms with OCI resources is:

1. Client calls `AddPendingResources` → server inserts into `resource` table + `pending_application_resource` table → returns UUID
2. Client uploads resource blob via HTTP PUT with `?pendingid=<uuid>`
3. Server upload handler (`apiserver/internal/handlers/resources/resources.go`) calls `resourceService.GetResource(ctx, uuid)`

PR #21775 fixed step 3 so that `ApplicationNotFound` no longer short-circuits the handler. But immediately after, at line 274, the handler calls `GetResource` which delegates to `Service.GetResource` in `domain/resource/service/resource.go:364`:

```go
func (s *Service) GetResource(ctx context.Context, resourceUUID coreresource.UUID) (coreresource.Resource, error) {
    // ...
    return s.st.GetApplicationResource(ctx, resourceUUID)  // <<<<< BUG: queries v_application_resource
}
```

`GetApplicationResource` queries the `v_application_resource` view, which joins `resource` → `application_resource` → `application`. For pending resources, there is **no row in `application_resource`** (the application doesn't exist yet), so the query returns zero rows → `ResourceNotFound`.

The state layer already has the correct method — `State.GetResource()` (at `domain/resource/state/resource.go:605`) which queries `v_resource` with LEFT JOINs and works without an application link.

### Verified Fix on local machine

One-line change in `domain/resource/service/resource.go`:

```diff
 func (s *Service) GetResource(
     ctx context.Context,
     resourceUUID coreresource.UUID,
 ) (coreresource.Resource, error) {
     if err := resourceUUID.Validate(); err != nil {
         return coreresource.Resource{}, errors.Errorf("resource id: %w", err)
     }
-    return s.st.GetApplicationResource(ctx, resourceUUID)
+    return s.st.GetResource(ctx, resourceUUID)
 }
```

`State.GetResource` is already defined, already in the `State` interface (line 84), and already used elsewhere (e.g. `StoreResource` at line 402). It queries `v_resource` with LEFT JOINs to `application_resource` and `application`, so it returns the resource regardless of whether the application exists yet.

### PR DESCRIPTION
**Pull request by hmlanigan**
#22025 reintroduced a bug where local charms with local resources fail to deploy. The resource is uploaded before the application is created via an old code path in the juju client. This code path is not used when deploying a repository charm with a local resource.

When uploading a resource there is no guarantee that the application exists yet. Use a new `GetResourceWithoutApplication` service method to do the upload. This is the only time a resource will not have an application. Pending resources only exist when an application is not running for the charm it's part of. Checking for a pending resource at this time will cause a failure when uploading resources after an application is running.

There is an integration test which covers this scenario, however it has not been running in Jenkins due to failures before it: `run_charmhub_download_with_resources` which downloads then deploys a charm and its resource.

For clarity in the domain, the state methods for GetResource where renamed to mimic the service versions.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

```
$ juju download juju-qa-test-resources --resources
Base "ubuntu@24.04" is not supported for charm "juju-qa-test-resources", trying base "ubuntu@22.04"
Fetching charm "juju-qa-test-resources" revision 2 using "stable" channel and base "amd64/ubuntu/22.04"
Install the "juju-qa-test-resources" charm with:
    juju deploy ./juju-qa-test-resources_r2.charm --resource runnable=./resource_runnable_r1_runnable

$  juju deploy ./juju-qa-test-resources_r2.charm --resource runnable=./resource_runnable_r1_runnable
Located local charm "juju-qa-test-resources", revision 0
Deploying "juju-qa-test-resources" from local charm "juju-qa-test-resources", revision 0 on ubuntu@22.04/stable
```

```
$ (cd tests ; ./main.sh -l bug-fix-test charmhub test_charmhub_download)

==> Checking for dependencies
==> Using Juju located at /home/heather/work/bin/juju
==> Running subtest test_charmhub_download for charmhub suite
==> TEST BEGIN: charmhub (tmp.SeW)
==> Checking for dependencies
==> TEST SKIPPED: charmhub find
==> TEST SKIPPED: charmhub info
====> Reusing bootstrapped juju (4.0.6:localhost)
Error: SSH key file '/home/heather/.local/share/juju/ssh/juju_id_ed25519.pub' not found.
====> Bootstrapped juju (1s)
===> [ ✔ ] Success: charmhub download (79s)
===> [ ✔ ] Success: charmhub download with resources (61s)
===> [ ✔ ] Success: charmstore download (3s)
===> [ ✔ ] Success: unknown download (3s)
====> Destroying model (test-charmhub)
====> Destroyed model (test-charmhub)
==> TEST DONE: charmhub (150s)
==> Cleaning up
====> Cleaning up pids
includes/pids.sh: line 1: 1347921 Killed                  juju debug-log -m "${ctrl_arg}" --replay --tail 2>&1 > "${TEST_DIR}/${log_file}"
====> Completed cleaning up pids
====> Cleaning up jujus
====> Completed cleaning up jujus

==> Test result: success
==> Tests Removed: /home/heather/work/src/github.com/juju/juju/tests/tmp.SeW
==> TEST COMPLETE
```

Run the resource tests to ensure nothing else has been broken by this change
```
$ (cd tests ; ./main.sh -l bug-fix-test resources)

==> Checking for dependencies
==> Using Juju located at /home/heather/work/bin/juju
==> TEST BEGIN: test_resources (tmp.ikT)
==> Checking for dependencies
====> Reusing bootstrapped juju (4.0.6:localhost)
Error: SSH key file '/home/heather/.local/share/juju/ssh/juju_id_ed25519.pub' not found.
====> Bootstrapped juju (1s)
===> [ ✔ ] Success: deploy local resource (88s)
===> [ ✔ ] Success: deploy repo resource (82s)
===> [ ✔ ] Success: resource attach (79s)
===> [ ✔ ] Success: resource attach large (80s)
===> [ ✔ ] Success: resource refresh (90s)
===> [ ✔ ] Success: resource refresh no new charm rev (100s)
===> [ ✔ ] Success: resource no upgrade after upload (84s)
===> [ ✔ ] Success: resource refresh no new charm rev supply res rev (100s)
===> [ ✔ ] Success: empty resource fileobjectstore (70s)
==> TEST SKIPPED: test_container_resources - tests for k8s only
====> Destroying model (test-resources)
====> Destroyed model (test-resources)
==> TEST DONE: test_resources (791s)
==> Cleaning up
====> Cleaning up pids
includes/pids.sh: line 1: 1455480 Killed                  juju debug-log -m "${ctrl_arg}" --replay --tail 2>&1 > "${TEST_DIR}/${log_file}"
====> Completed cleaning up pids
====> Cleaning up jujus
====> Completed cleaning up jujus

==> Test result: success
==> Tests Removed: /home/heather/work/src/github.com/juju/juju/tests/tmp.ikT
==> TEST COMPLETE
```

## Links

Fixes #22121

**Jira card:** [JUJU-9558](https://warthogs.atlassian.net/browse/JUJU-9558)

[JUJU-9558]: https://warthogs.atlassian.net/browse/JUJU-9558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apiserver/internal/handlers/resources/resources.go [hunk 1]
```diff
@@ -173,13 +173,17 @@ func (h *ResourceHandler) upload(service ResourceService, req *http.Request, use
...
+	ctx := req.Context()
 
 	appService, err := h.applicationServiceGetter.Application(req)
 	if err != nil {
 		return nil, jujuerrors.Trace(err)
 	}
 
-	appDetails, err := appService.GetApplicationDetailsByName(req.Context(), application)
+	// When uploading a resource during deployment, an application
+	// may not exist yet. The check for synthetic application's is
```
Comment (iyiguncevik) [inline apiserver/internal/handlers/resources/resources.go]:
```suggestion
	// may not exist yet. The check for synthetic application is
```
