### PR TITLE
fix: ensure controller app is exposed on upgrade

### LINKED ISSUE #22293: 3.6 upgrades can firewall the Juju API port
### Description

We have a 3-node HA cluster on OpenStack that's currently running 3.6.21, but has been upgraded multiple times (3.6.0, 3.6.1, 3.6.5, 3.6.8, 3.6.9, 3.6.11, 3.6.12 and 3.6.14 tools all exist on a controller node, which is likely the upgrade history).

Historically Juju added OpenStack security group rules to open TCP port 17070 to the world, this was amended in I think 3.6.19 to be managed via `juju expose` on the `controller` charm so as to add tighter controls on which networks it should be opened up to.

In this deployment, the most recent upgrade to 3.6.21 seems to have left things in a confused state where the charm was set to unexposed, and the old security group rules were removed, effectively firewalling off the controllers from the network.

Manually recreating the security group rules worked as a temporary workaround until the leader (and only the leader) controller unit had its jujud restarted, at which point it would delete the rules again.

Better workaround: `juju expose controller`.

### Juju version

3.6.21

### Cloud

OpenStack

### Expected behaviour

Upgrading an older 3.6 controller where security group rules currently allow unrestricted access to the controller API ports should result in an exposed charm, continuing the expected behaviour.

### Reproduce / Test

We have a live controller environment on an internal Canonical cloud where this can be tested if need be.

### Notes & References

Logs showing the leader automatically closing TCP 17070 after a restart (internal link):

https://pastebin.canonical.com/p/JJ3BXBcYGW/

### PR DESCRIPTION
**Pull request by wallyworld**
Depending on the version of 3.6, bootstrapping doesn't always result in the (built in) controller app being exposed.
eg bootstrapping 3.6.4 it wasn't exposed, 3.6.14 it was.

Starting in 3.6.19, the firewaller is used to manage the api port, so the controller app must be exposed.
This PR adds an upgrade step to ensure old versions are updated to have the controller app exposed.

## QA steps

Use a 3.6.4 client to bootstrap
juju status shows controller app not exposed

Upgrade controller
juju status shows controller app exposed

## Links

**Issue:** Fixes #22293.

**Jira card:** [JUJU-9737](https://warthogs.atlassian.net/browse/JUJU-9737)

[JUJU-9737]: https://warthogs.atlassian.net/browse/JUJU-9737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: upgrades/steps_3622_test.go [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+var v3622 = version.MustParse("3.6.22")
+
+type steps3622Suite struct {
+	testing.BaseSuite
+}
+
+var _ = gc.Suite(&steps3622Suite{})
+
+func (s *steps3621Suite) TestExposeControllerApplication(c *gc.C) {
```
Comment (adisazhar123) [inline upgrades/steps_3622_test.go]: typo: use steps3622Suite

Comment (wallyworld) [reply upgrades/steps_3622_test.go]: oops, ty

**Review by adisazhar123 — APPROVED** [review]
Thank you. QA passes.

**Review by hpidcock — APPROVED** [review]
