### PR TITLE
fix: azure storage provisioning

### LINKED ISSUE #21073: Juju 4.0 failing to create filesystem paritions on Azure
### Description

When testing the bootstrap and deployment on Azure I noticed we have a storage provisioning problem with filesystems.

```
machine-0: 10:34:48 INFO juju.services.status.status-history namespace_id:467acafc-9eea-4f6d-8b9e-3050f73d5b5e,since:2025-11-02T10:34:47Z,status:pending,category:status-history,data:null,kind:filesystem,logger-tags:status-history,message:sgdisk failed: The specified path is a directory!
Problem opening '' for writing! Program will now terminate.
Warning! MBR not overwritten! Error is 21!: exit status 2 status-history (status: "pending", status-message: "sgdisk failed: The specified path is a directory!\nProblem opening '' for writing! Program will now terminate.\nWarning! MBR not overwritten! Error is 21!: exit status 2")
machine-0: 10:35:18 INFO juju.services.status.status-history kind:filesystem,logger-tags:status-history,message:sgdisk failed: The specified path is a directory!
Problem opening '' for writing! Program will now terminate.
Warning! MBR not overwritten! Error is 21!: exit status 2,namespace_id:467acafc-9eea-4f6d-8b9e-3050f73d5b5e,since:2025-11-02T10:35:17Z,status:pending,category:status-history,data:null status-history (status: "pending", status-message: "sgdisk failed: The specified path is a directory!\nProblem opening '' for writing! Program will now terminate.\nWarning! MBR not overwritten! Error is 21!: exit status 2")
```

This looks to be that the path value is empty for the volume and so creating the partition fails.

### Juju version

4.0-beta8

### Cloud

Azure

### Expected behaviour

Filesystem for the database should get provisioned by the machine storage provisioner.

### Reproduce / Test

```
juju bootstrap azure
juju add-model foo
juju deploy postgresql
```

Watch the debug log once the machine comes up and the error will surface.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by hpidcock**
This contains two changes to fix the Azure storage issue #21073.

On Azure, volumes are matched to an observed blockdevice by a non-standard
device link prefixed by `/dev/disk/azure/scsi1`. In the existing implementation,
this device link prefix was not seen as a strong identifier for matching
observed blockdevices (those seen by the diskmanager worker) and the partial
block device information sourced from the storage provider. This uncovered a
race condition with partial blockdevices that did not have a name yet and the
not provisioned check in the storageprovisioner facade.

The result of this race condition is that sometimes (all the time on Azure) when
creating a fileystem, a call to sgdisk to create a partition table would fail
due to missing the device name.

The fix here for Azure is to add the `/dev/disk/azure/scsi1` device link prefix
to the  block device matching algorithm as a strong identifier that can be used
for matching block devices. This ensures that the device name and the rest of
the block device information is populated.

As for the race condition, the fix here is to simply extend the logic to return
a not provisioned when either the device name or the device links are empty. In
the future, it would be ideal to extend the block_device schema to identify the
source of the information as either from the diskmanager (observed block device)
or from the storage provider (expected block device).

This includes a drive-by fix to ensure volume attachment plan re-creation does
not fail on agent reboot. Including a comment to re-visit this in the near future to
handle changes in the volume attachment plan.

## QA steps

- Bootstrap Azure
- Add model
- Deploy postgresql
- Storage should come up and be attached and healthy.

> [!NOTE]  
> postgresql does not stop using the disk after the unit is removed, so the
> filesystem attachment cannot be removed. A PR is coming that deals with
> force removal issues.

## Links

**Issue:** Fixes #21073.

### CODE REVIEW

File: apiserver/facades/agent/storageprovisioner/storageprovisioner.go [hunk 1]
```diff
@@ -2122,7 +2122,11 @@ func (s *StorageProvisionerAPIv4) createVolumeAttachmentPlan(
 	_, err = s.storageProvisioningService.CreateVolumeAttachmentPlan(
 		ctx, attachmentUUID, planDeviceType, planInfo.DeviceAttributes,
 	)
-	if errors.Is(err, storageprovisioningerrors.VolumeAttachmentNotFound) {
+	if errors.Is(err, storageprovisioningerrors.VolumeAttachmentPlanAlreadyExists) {
```
Comment (tlm) [inline apiserver/facades/agent/storageprovisioner/storageprovisioner.go:2125]: Ideally this would be an ensure operation when we do this.

Comment (hpidcock) [reply apiserver/facades/agent/storageprovisioner/storageprovisioner.go:2125]: Hence the TODO, I'll get to it after 4.0.0
