### PR TITLE
fix(ssh): disable PTY allocation when remote command is provided

### LINKED ISSUE #19576: `juju ssh` converts line ending to DOS format ("\n" -> "\r\n")
### Description

When running remote commands with `juju ssh`, the line endings of the commands' stdout are converted to to dos format, i.e. the line feed '\n' is appended with a carriage return '\r'. This is mostly invisible, has some side-effects when parsing the output.

### Juju version

3.5.7

### Cloud

_No response_

### Expected behaviour

```
$ testarr01=($(juju ssh $hostname -- echo -e '"test\ntest2"'))
$ declare -p testarr01
declare -a testarr01=([0]="test" [1]="test2")
$ echo "${testarr01[@]}"
test test2
```

### Reproduce / Test

```
$ testarr01=($(juju ssh $hostname -- echo -e '"test\ntest2"'))
Connection to 10.10.10.195 closed.
$ declare -p testarr01
declare -a testarr01=([0]=$'test\r' [1]=$'test2\r')
$ echo "${testarr01[@]}"
 test2
```
Note that only the last element is printed, because of the carriage return at the end of the elements. Instead of appending the next element, each one is overwritten on the cli.

### Notes & References

FTR, `ssh` does not show the same behaviour:
```
$ testarr02=($(ssh $hostname -- echo -e '"test\ntest2"'))
$ declare -p testarr02
declare -a testarr02=([0]="test" [1]="test2")
$ echo "${testarr02[@]}"
test test2
```

### PR DESCRIPTION
**Pull request by kooltuoehias**
Fixes #19576

This PR fixes an issue where juju ssh would unconditionally allocate a PTY (pseudo-terminal) even when a remote command was provided. This caused stdout to contain DOS-style line endings (\r\n), which breaks downstream automation scripts and parsing logic (e.g., populating Bash arrays).

This change aligns juju ssh behavior with standard OpenSSH:

Interactive (No command): PTY allocated (unchanged).

Non-interactive (Command provided): PTY NOT allocated (new behavior).

Explicit Override: Users can still force PTY allocation using -t / --pty if needed.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

specific unit tests are added.

## Links

**Issue:** Fixes #19576.

**Jira card:** [JUJU-7914](https://warthogs.atlassian.net/browse/JUJU-7914)

[JUJU-7914]: https://warthogs.atlassian.net/browse/JUJU-7914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by kooltuoehias** [comment]
@jack-w-shaw may I ask for some help to unblock the ci ?

**Comment by kooltuoehias** [comment]
> Thanks !

My pleasure :)
Hmm I still have gci issue:
Error:     | ../cmd/juju/ssh/pty_test.go:9:1: File is not properly formatted (gci)
    | "github.com/juju/juju/api/client/client"
    | ^
    | 1 issues:
    | * gci: 1
make: *** [Makefile:717: static-analysis] Error 1

My bad, I should have fixed it locally

**Comment by gfouillet** [comment]
> > Thanks !
> 
> My pleasure :) Hmm I still have gci issue: Error: | ../cmd/juju/ssh/pty_test.go:9:1: File is not properly formatted (gci) | "github.com/juju/juju/api/client/client" | ^ | 1 issues: | * gci: 1 make: *** [Makefile:717: static-analysis] Error 1
> 
> My bad, I should have fixed it locally

Please GCI this file with:

```sh
gci write -s standard -s default -s "prefix(github.com/juju/juju)" <path to file>
```

**Comment by hmlanigan** [comment]
@kooltuoehias Thank you for moving to 3.6. The static analysis error needs to be resolved before this PR can merge.
```
==> TESTS DONE: test_static_analysis
==> RUN OUTPUT: test_static_analysis
    | 
    | Error: linter has issues:
    | 
Error:     | ../cmd/juju/ssh/pty_test.go:9:1: File is not properly formatted (gci)
    | "github.com/juju/juju/api/client/client"
    | ^
    | 1 issues:
    | * gci: 1
make: *** [Makefile:717: static-analysis] Error 1
```

**Comment by kooltuoehias** [comment]
> ```shell
> gci write -s standard -s default -s "prefix(github.com/juju/juju)" <path to file>
> ```

thanks for the message, just updated the pr after gci write -s standard -s default -s "prefix(github.com/juju/juju)" <path to file>

**Comment by kooltuoehias** [comment]
> > > Thanks !
> > 
> > 
> > My pleasure :) Hmm I still have gci issue: Error: | ../cmd/juju/ssh/pty_test.go:9:1: File is not properly formatted (gci) | "github.com/juju/juju/api/client/client" | ^ | 1 issues: | * gci: 1 make: *** [Makefile:717: static-analysis] Error 1
> > My bad, I should have fixed it locally
> 
> Please GCI this file with:
> 
> ```shell
> gci write -s standard -s default -s "prefix(github.com/juju/juju)" <path to file>
> ```

Thanks for the command! I just updated the pr after gci write -s standard -s default -s "prefix(github.com/juju/juju)" <path to file>

**Comment by kooltuoehias** [comment]
> @kooltuoehias Thank you for moving to 3.6. The static analysis error needs to be resolved before this PR can merge.
> 
> ```
> ==> TESTS DONE: test_static_analysis
> ==> RUN OUTPUT: test_static_analysis
>     | 
>     | Error: linter has issues:
>     | 
> Error:     | ../cmd/juju/ssh/pty_test.go:9:1: File is not properly formatted (gci)
>     | "github.com/juju/juju/api/client/client"
>     | ^
>     | 1 issues:
>     | * gci: 1
> make: *** [Makefile:717: static-analysis] Error 1
> ```

Now I've fixed the gci and the ci flows are all green. Thanks for the help!

**Comment by kooltuoehias** [comment]
> /merge

Thanks !

**Comment by hmlanigan** [comment]
The unit tests are now failing in unrelated places, e.g. :
```
15:05:58 FAIL: <autogenerated>:1: DebugCodeSuite.SetUpSuite
15:05:58 
15:05:58 /home/jenkins/go/pkg/mod/github.com/juju/mgo/v3@v3.0.8/testing/mgo.go:597:
15:05:58     c.Fatalf("No Mongo Server Address, MgoSuite tests must be run with MgoTestPackage")
15:05:58 ... Error: No Mongo Server Address, MgoSuite tests must be run with MgoTestPackage
```

**Comment by SimonRichardson** [comment]
@kooltuoehias can you rebase this, so we can land it.

**Comment by kooltuoehias** [comment]
> @kooltuoehias can you rebase this, so we can land it.

oh yeah sure.

**Comment by kooltuoehias** [comment]
> > @kooltuoehias can you rebase this, so we can land it.
> 
> oh yeah sure.

Just make a rebase push.

**Comment by SimonRichardson** [comment]
@kooltuoehias thanks. Will land it once CI has run.

File: cmd/juju/ssh/pty_test.go [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+	"github.com/juju/juju/rpc/params"
+)
+
+type PTYSuite struct{}
+
+var _ = gc.Suite(&PTYSuite{})
+
+func TestPTY(t *testing.T) {
+	gc.TestingT(t)
+}
```
Comment (wallyworld) [inline cmd/juju/ssh/pty_test.go]: This needs to be deleted

Comment (kooltuoehias) [reply cmd/juju/ssh/pty_test.go]: > This needs to be deleted

Thanks for pointing it out.

Comment (kooltuoehias) [reply cmd/juju/ssh/pty_test.go]: > This needs to be deleted

now there is one CI failure left, may I ask for some suggestions :) ?

File: cmd/juju/ssh/pty_test.go [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+func (m *mockSSHProvider) setArgs(args []string) {
+	m.args = args
+}
+
+func (m *mockSSHProvider) setRetryStrategy(retry.CallArgs)          {}
+func (m *mockSSHProvider) setPublicKeyRetryStrategy(retry.CallArgs) {}
+
+func (s *PTYSuite) TestRunPTYLogic(c *gc.C) {
+	s.JujuConnSuite.SetUpTest(c)
```
Comment (wallyworld) [inline cmd/juju/ssh/pty_test.go]: This shouldn't be here. Setup of embedded suites needs to be done in a corresponding SetUpTest on this suite. And we only need to explicitly call SetUpTest on the embedded suite if there's more than one embedded or if there's other logic involved.

File: cmd/juju/ssh/pty_test.go [hunk 3]
```diff
@@ -0,0 +1,152 @@
...
+	gc "gopkg.in/check.v1"
+
+	"github.com/juju/juju/api/client/client"
+	"github.com/juju/juju/juju/testing"
+	jujussh "github.com/juju/juju/network/ssh"
+	"github.com/juju/juju/rpc/params"
+)
+
+type PTYSuite struct {
+	testing.JujuConnSuite
```
Comment (wallyworld) [inline cmd/juju/ssh/pty_test.go]: Is there a reason JujuConnSuite is being used? ie do we need to spin up mongo and a controller api?
Since a mock is being used, would IsolationSuite suffice?

Comment (kooltuoehias) [reply cmd/juju/ssh/pty_test.go]: > Is there a reason JujuConnSuite is being used? ie do we need to spin up mongo and a controller api? Since a mock is being used, would IsolationSuite suffice?

thanks for the comment, I will use IsolationSuite instead.

File: cmd/juju/ssh/pty_test.go (hunk 2 above)
Comment (kooltuoehias) [reply cmd/juju/ssh/pty_test.go]: > This shouldn't be here. Setup of embedded suites needs to be done in a corresponding SetUpTest on this suite. And we only need to explicitly call SetUpTest on the embedded suite if there's more than one embedded or if there's other logic involved.

oh thanks ! I will update the code now.

**Comment by kooltuoehias** [comment]
@wallyworld sorry for the late reply, I did the fix you pointed out and a rebase. I was struggling with how to test it on my macbook and I could not fix the mango db setup. This time I temporarily changed the package_test.go and only run the test I added and it worked. Thanks for the comment again.

**Comment by kooltuoehias** [comment]
> /merge

Thank you for your time.
