### PR TITLE
fix: use sqlair Preparer for space constraints

### LINKED ISSUE #20423: Deploy with space constraints fails
### Description

The initial creation of an application with space constraints fails:
```
$ juju deploy ubuntu-lite --to lxd:0 --constraints spaces=primary,secondary
ERROR creating IAAS application "ubuntu-lite": creating IAAS application "ubuntu-lite": inserting IAAS units for application "34c6d161-784d-4d6a-8bef-958ab014bfaf": inserting IAAS unit 0: inserting unit for application "34c6d161-784d-4d6a-8bef-958ab014bfaf": setting constraints for unit "ubuntu-lite/0": invalid input parameter: parameter with type "state.setConstraintSpace" missing, have type with same name: "state.setConstraintSpace"
ERROR failed to deploy charm "ubuntu-lite"
```

### Juju version

4.0-beta7.1 (main HEAD)

### Cloud

MAAS

### Expected behaviour

Juju should create the application entry and attempt to provision a container for the first unit.

### Reproduce / Test

See description.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
This patch addresses an issue that prevents deploying an app using space constraints. The reason for this being that we have the same db struct name in two different packages, which creates a conflict on the prepared statements cache. The fix is therefore (as it was already done before) to use sqlair.Prepare instead of the injected preparer.

Also, the prepare statements on the `insertMachine` method which runs within a transaction, have been moved out as global variables. This might become a standard in our path to better state layer performance.

As a flyby, unit tests were added.

## QA steps

```
$ juju add-space beta 
# use the subnets you have on your system:
$ juju move-to-space beta 10.254.213.0/24
$ juju deploy ubuntu --constraints "spaces=beta" 
```
Previously, the deploy step would have failed.

## Links

**Issue:** Fixes #20423.

**Jira card:** [JUJU-8751](https://warthogs.atlassian.net/browse/JUJU-8751)

[JUJU-8751]: https://warthogs.atlassian.net/browse/JUJU-8751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/machine/state/placement.go [hunk 1]
```diff
@@ -584,12 +589,6 @@ VALUES ($setConstraint.*)
 		return errors.Errorf("preparing select space query: %w", err)
 	}
 
-	insertConstraintSpacesQuery := `INSERT INTO constraint_space(*) VALUES ($setConstraintSpace.*)`
-	insertConstraintSpacesStmt, err := preparer.Prepare(insertConstraintSpacesQuery, setConstraintSpace{})
-	if err != nil {
-		return errors.Capture(err)
-	}
-
 	insertConstraintZonesQuery := `INSERT INTO constraint_zone(*) VALUES ($setConstraintZone.*)`
```
Comment (gfouillet) [inline domain/machine/state/placement.go]: **todo:** While you are here, actually the only non problematic one is selectSpaceQuery. both

`insertConstraintZonesQuery` and `selectContainerTypeIDQuery` have the same issue after double check.

File: domain/machine/state/placement.go [hunk 2]
```diff
@@ -566,16 +566,21 @@ VALUES ($setConstraint.*)
...
 	insertConstraintTagsQuery := `INSERT INTO constraint_tag(*) VALUES ($setConstraintTag.*)`
 	insertConstraintTagsStmt, err := sqlair.Prepare(insertConstraintTagsQuery, setConstraintTag{})
 	if err != nil {
 		return errors.Capture(err)
 	}
+	insertConstraintSpacesQuery := `INSERT INTO constraint_space(*) VALUES ($setConstraintSpace.*)`
+	insertConstraintSpacesStmt, err := sqlair.Prepare(insertConstraintSpacesQuery, setConstraintSpace{})
+	if err != nil {
+		return errors.Capture(err)
+	}
```
Comment (SimonRichardson) [inline domain/machine/state/placement.go]: Just so I'm happy with this change, but each state base has it's own cache, which we instantiate for every new state - ModelState, MachineState and so forth. Where *exactly* are we clobbering the statements in which methods?

Comment (SimonRichardson) [reply domain/machine/state/placement.go]: Essentially, I'm not happy with, we just need to skip the cache. It generally means that either we don't have enough guard rails, or the statements are duplicated for some reason, that isn't required else where.

Comment (gfouillet) [reply domain/machine/state/placement.go]: Around here: 

https://github.com/juju/juju/blob/46e300f4debf16a9e397afa552ad3585e0c90056/domain/application/state/application.go#L2850-L2863

Through the placement code in application state:

https://github.com/juju/juju/blob/dbe8b3531fb5f4b6b73f6478d5762dd0e104da78/domain/application/state/unit.go#L1479-L1481

Comment (SimonRichardson) [reply domain/machine/state/placement.go]: So this probably goes to show that this is exactly why we should use state code from another state code.

**Review by manadart — COMMENTED** [review]
We will soon have to do an exercise in squeezing as much efficiency out of Dqlite as possible.

To this end, should we not be able to use the cache, I do not want us to be preparing from scratch in these methods, which are already inside transactions (`insertMachineConstraints` receives a `*sqlair.TX`).

To this end, immediately prior to this method, prepare any non-cached statements into package-private variables (done on init) and use those in the method.

We will explore this optimisation elsewhere too.

**Review by SimonRichardson — CHANGES_REQUESTED** [review]
Move these `sqlair.Prepare`s out of the transactions and place them as variables at the top level in the state packages. You can call `sqlair.MustPrepare` to make you life easier.

File: domain/machine/state/placement.go (hunk 1 above)
Comment (nvinuesa) [reply domain/machine/state/placement.go]: No longer applicable, these were all moved to the global vars.

**Comment by nvinuesa** [comment]
@manadart @SimonRichardson I moved the prepare statements out of the tx into package variables.

**Review by SimonRichardson — APPROVED** [review]

**Review by gfouillet — APPROVED** [review]
Thanks

File: domain/machine/state/placement.go [hunk 3]
```diff
@@ -29,6 +29,18 @@ import (
 	"github.com/juju/juju/internal/uuid"
 )
 
+// We prepare these statements globally to avoid having them prepared inside
+// a transaction.
+var (
```
Comment (manadart) [inline domain/machine/state/placement.go]: Locate these immediately above the method where they are used.

**Review by manadart — APPROVED** [review]
One change, otherwise OK.

File: domain/machine/state/placement.go (hunk 3 above)
Comment (nvinuesa) [reply domain/machine/state/placement.go]: Sure, done.
