### PR TITLE
fix: persist controller node agent version

### LINKED ISSUE #21256: Juju 4.0 has empty controller_node_agent_version table
### Description

The juju controller has a means to report their currently running agent version by persisting it in `controller_node_agent_version` table. This is particularly useful for model upgrades in which it consults `controller_node_agent_version` table to determine the highest version the model should upgrade do.

There is a bug in which this table is empty after a performing a bootstrap.

### Juju version

4.0

### Cloud

LXD

### Expected behaviour

After a bootstrap, the `controller_node_agent_version` table should record what agent version the controller is running.

### Reproduce / Test

Bootstrap and login to the machine
```
juju bootstrap localhost testctrl
juju switch controller
juju ssh 0
```

Query the table
```
juju_db_repl
select * from controller_node_agent_version
```

Image

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by adisazhar123**
As part of this PR, we make upgradedatabase worker responsible for setting the controller agent version. We had an existing bug where the `controller_node_agent_version` table has empty records because the upgrader worker incorrectly assumes that it has a controller tag kind, where in reality it receives a machine tag kind ([ref](https://github.com/juju/juju/blob/11c786836b08f0c1393c87d52e82f242ef142901/apiserver/facades/agent/upgrader/upgrader.go#L263-L275)). This causes it to miss invoking `controllerNodeService.SetControllerNodeReportedAgentVersion` func.

The fix here is to call `controllerNodeService.SetControllerNodeReportedAgentVersion` in a worker that runs on a controller hence the reason for choosing upgradedatabase worker.

The controller agent version is important because we use it to lookup the recommended version when we perform a model upgrade. That's why as part of this PR, I've also uncommented the function body where we lookup `controller_node_agent_version` table to determine which version a model should upgrade to.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

Split this into two scenarios. The first ensures the version is populated in the table. The second ensures that the model upgrade reads from the table.

##### A) Ensuring the controller node agent version is populated

1. Bootstrap a controller

```
juju bootstrap localhost agentversionfix
```

Check the `controller_node_agent_version` table is populated with `4.0.1.x`

```
select * from controller_node_agent_version
```
Screenshot from 2025-11-23 21-05-17

---

##### B) Ensuring model upgrade reads from the table

2. Add a model and machine

```
juju add-model m1
juju add-machine 
```

3. Bump up the version in `core/version/version.go` to `4.0.2`

```
const version = "4.0.2"
```

4. Build and upload the binary

```
juju switch controller
make simplestreams
juju sync-agent-binary --agent-version 4.0.2
```

5. Upgrade the controller

Make sure dry run works. It should show 4.0.2 in the output.

```
juju upgrade-controller --agent-version=4.0.2  --dry-run
```

Screenshot from 2025-11-23 21-17-57

Now perform the real upgrade.

```
juju upgrade-controller --agent-version=4.0.2 
```

Screenshot from 2025-11-23 21-17-46

Check the new version is reflected in the controller.
```
juju show-controller
```

Screenshot from 2025-11-23 21-11-00

Check the `controller_node_agent_version` table is reflected with the new version.

Screenshot from 2025-11-23 21-11-44

6. Upgrade the model

Make sure dry run works. It should show version `4.0.2` which is read from the `controller_node_agent_version` table.

```
juju switch m1
juju upgrade-model --dry-run 
```

Screenshot from 2025-11-23 21-17-13

Now perform the real upgrade.

```
juju upgrade-model
```

Screenshot from 2025-11-23 21-19-06

After the upgrade is done, verify the agent version shows `4.0.2`

```
juju show-model
```

Screenshot from 2025-11-23 21-19-54

## Documentation changes

N/A.

## Links

**Issue:** Fixes #21256.

**Jira card:** [JUJU-8782](https://warthogs.atlassian.net/browse/JUJU-8782)

[JUJU-8782]: https://warthogs.atlassian.net/browse/JUJU-8782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/modelagent/service/service_test.go [hunk 1]
```diff
@@ -836,7 +836,10 @@ func (s *modelUpgradeSuite) TestUpgradeModelTargetAgentVersionWithStreamControll
 	defer s.setupMocks(c).Finish()
 
 	currentTargetVersion := s.getVersionMinorLess()
-
+	desiredVersion := semversion.MustParse("4.0.1")
```
Comment (tlm) [inline domain/modelagent/service/service_test.go:871]: Would you mind either adding to one of the existing tests or creating some new ones so the we have some confidence in the following scenarios long term?

- Multiple controller versions reported by state of the same value.
- Multiple controller versions reported by state of different values. Confirm that the highest one is picked.

File: internal/services/interface.go [hunk 2]
```diff
@@ -255,6 +255,8 @@ type ObjectStoreServicesGetter interface {
 type UpgradeServices interface {
 	// Upgrade returns the upgrade service.
 	Upgrade() *upgradeservice.WatchableService
+	// ControllerNode returns the controller node service.
+	ControllerNode() *controllernodeservice.WatchableService
```
Comment (tlm) [inline internal/services/interface.go]: Nit: bang these in alphabetical order.

File: domain/modelagent/service/service.go [hunk 3]
```diff
@@ -1003,27 +1002,22 @@ func (s *Service) validateModelCanBeUpgradedTo(
...
-	//
-	//return versions[0], nil
-	return jujuversion.Current, nil
+	if len(versions) == 0 {
+		return semversion.Zero, errors.New("no recommended versions found")
+	}
+
+	// Sort it descendingly so the highest version is the first element.
+	slices.SortFunc(versions, func(a, b semversion.Number) int {
+		return a.Compare(b) * -1
```
Comment (CodingCookieRookie) [inline domain/modelagent/service/service.go:1017]: nit: can this be rewritten to b.Compare(a)?

File: internal/worker/upgradedatabase/worker.go [hunk 4]
```diff
@@ -502,3 +529,24 @@ func (w *upgradeDBWorker) addWatcher(ctx context.Context, watcher eventsource.Wa
 
 	return nil
 }
+
+// reportControllerNodeAgentVersion persists the version of the agent when the
+// worker starts.
+func (w *upgradeDBWorker) reportControllerNodeAgentVersion(
```
Comment (CodingCookieRookie) [inline internal/worker/upgradedatabase/worker.go]: curious why do we call this reportControllerNodeAgentVersion? Seems to do more of setting/storing version in state rather than reporting something.

Maybe sth like "recordControllerNodeAgentVersion"? wdyt

File: internal/worker/upgradedatabase/manifold.go [hunk 5]
```diff
@@ -100,13 +100,16 @@ func Manifold(cfg ManifoldConfig) dependency.Manifold {
...
-				UpgradeService:        upgradeServicesGetter.ServicesForController().Upgrade(),
-				DBGetter:              dbGetter,
-				Tag:                   currentConfig.Tag(),
-				FromVersion:           fromVersion,
-				ToVersion:             toVersion,
-				Logger:                cfg.Logger,
-				Clock:                 cfg.Clock,
+				UpgradeService: upgradeServicesGetter.
+					ServicesForController().Upgrade(),
+				ControllerNodeService: upgradeServicesGetter.
```
Comment (tlm) [inline internal/worker/upgradedatabase/manifold.go:103]: Nit: alphabetical order if we are in a position to control it.

File: internal/worker/upgradedatabase/worker.go [hunk 6]
```diff
@@ -80,6 +96,10 @@ type Config struct {
 	// UpgradeService is the upgrade service used to drive the upgrade.
 	UpgradeService UpgradeService
 
+	// ControllerNodeService provides a means to communicate the controller's
+	// running agent version.
+	ControllerNodeService ControllerNodeService
```
Comment (tlm) [inline internal/worker/upgradedatabase/worker.go:98]: Same Nit as above.

File: internal/worker/upgradedatabase/worker.go [hunk 7]
```diff
@@ -502,3 +529,24 @@ func (w *upgradeDBWorker) addWatcher(ctx context.Context, watcher eventsource.Wa
 
 	return nil
 }
+
+// reportControllerNodeAgentVersion persists the version of the agent when the
```
Comment (tlm) [inline internal/worker/upgradedatabase/worker.go]:
```suggestion
// reportControllerNodeAgentVersion ensures that this controllers current running version is correctly recorded in the controller database against the controller's id.
// This method MUST be called every time the worker starts regardless of database upgrades to perform. This ensures the database is always a correct reflection of the controller' version.
```

File: internal/worker/upgradedatabase/worker.go [hunk 8]
```diff
@@ -68,6 +71,19 @@ type UpgradeService interface {
 	WatchForUpgradeState(ctx context.Context, upgradeUUID domainupgrade.UUID, state upgrade.State) (watcher.NotifyWatcher, error)
 }
 
+// ControllerNodeService provides the subset of methods of
+// [github.com/juju/juju/domain/controllernode/service.Service] .
+type ControllerNodeService interface {
+	// SetControllerNodeReportedAgentVersion sets the agent version for the
+	// supplied controllerID. Version represents the version of the controller
+	// node's agent binary.
+	SetControllerNodeReportedAgentVersion(
```
Comment (CodingCookieRookie) [inline internal/worker/upgradedatabase/worker.go:80]: would this code block here be redundant then? based on the PR comment

https://github.com/juju/juju/blob/cb372ecae9ac325a8441ae42c2a1265829b6da00/apiserver/facades/agent/upgrader/upgrader.go#L270-L275

File: internal/worker/upgradedatabase/worker.go [hunk 9]
```diff
@@ -502,3 +529,24 @@ func (w *upgradeDBWorker) addWatcher(ctx context.Context, watcher eventsource.Wa
...
+		Number: jujuversion.Current,
+		Arch:   arch.HostArch(),
+	}
+	err := w.controllerNodeService.SetControllerNodeReportedAgentVersion(
+		ctx,
+		w.controllerID,
+		version,
+	)
+	if err != nil {
+		return errors.Annotate(err, "setting controller node agent version")
```
Comment (tlm) [inline internal/worker/upgradedatabase/worker.go]: s/setting/reporting

File: internal/worker/upgradedatabase/worker_test.go [hunk 10]
```diff
@@ -718,13 +850,35 @@ func (s *workerSuite) TestUpgradeFailsWhenKilled(c *tc.C) {
...
+			Number: jujuversion.Current,
+			Arch:   arch.HostArch(),
+		},
+	).Return(coreerrors.NotValid)
+
+	w, err := NewUpgradeDatabaseWorker(s.getConfig())
+	c.Assert(err, tc.ErrorIsNil)
+
+	err = workertest.CheckKill(c, w)
+	c.Check(err, tc.ErrorIs, coreerrors.NotValid)
```
Comment (tlm) [inline internal/worker/upgradedatabase/worker_test.go]: I want to avoid the connotation that a NotValid error is part of the contract here. To do this we just create a local error to the test and use that instead.

```suggestion
	defer s.setupMocks(c).Finish()

    settingError := errors.New("setting controller node agent version")
	s.controllerNodeService.EXPECT().SetControllerNodeReportedAgentVersion(
		gomock.Any(),
		"0",
		coreagentbinary.Version{
			Number: jujuversion.Current,
			Arch:   arch.HostArch(),
		},
	).Return(settingError)

	w, err := NewUpgradeDatabaseWorker(s.getConfig())
	c.Assert(err, tc.ErrorIsNil)

	err = workertest.CheckKill(c, w)
	c.Check(err, tc.ErrorIs, settingError)
```

File: domain/services/upgrade.go [hunk 11]
```diff
@@ -37,3 +39,12 @@ func (s *UpgradeServices) Upgrade() *upgradeservice.WatchableService {
...
 	)
 }
+
+// ControllerNode returns the controller node service.
+func (s *UpgradeServices) ControllerNode() *controllernodeservice.WatchableService {
+	return controllernodeservice.NewWatchableService(
+		controllernodestate.NewState(changestream.NewTxnRunnerFactory(s.controllerDB)),
+		s.controllerWatcherFactory("controllernode"),
+		s.logger.Child("controllernode"),
+	)
```
Comment (tlm) [inline domain/services/upgrade.go]: I think in this instance we should just construct and return the non watcher service. We do have the watcher dep infra for the upgrade service. However I want to make sure that with this service factory in particular we keep it on a very lean diet of dependencies where possible.

We do this so that we don't accidentality get ourselves into a siltation of requiring the world to get a database done and another dead lock scenario. It also reduce the surface error of mistakes providing more stability in upgrades.

```suggestion
	return controllernodeservice.NewService(
		controllernodestate.NewState(changestream.NewTxnRunnerFactory(s.controllerDB)),
		s.logger.Child("controllernode"),
	)
```

**Review by tlm — APPROVED** [review]
Thanks @adisazhar123,

This is some nice work! My comments are only nits bar 1. Feel free to treat the Nits however you see fit.

I would appreciate @SimonRichardson to have a look over this before we merge.

The justification for having done this is the upgrade database worker always runs on startup and is the perfect spot to ensure consistency for the controller version value. We can be sure that this value will exist and be correct when everything else becomes alive.

We could introduce a new worker to perform this action as a separate task but I am not sure that task it self is big enough to justify doing this. 

QA looks good, I also did an upgrade just to make sure this all works as expected.

File: internal/worker/upgradedatabase/worker.go [hunk 12]
```diff
@@ -189,6 +211,11 @@ func (w *upgradeDBWorker) loop() error {
 	ctx, cancel := w.scopedContext()
 	defer cancel()
 
+	err := w.reportControllerNodeAgentVersion(ctx)
+	if err != nil {
+		return err
+	}
```
Comment (SimonRichardson) [inline internal/worker/upgradedatabase/worker.go]: This needs to be idempotent. Also Annotate the error.

----

Having looked at the method `SetRunningAgentBinaryVersion` we allow for the upsert of the architecture of the controller node agent.

https://github.com/juju/juju/blob/2c36c946fe3e2054f715c29ba569cfcbb2d60c19/domain/controllernode/state/state.go#L182-L184

I don't think we should allow that. We should insert with an architecture, but never allow the upsert to change it. There will never be a time when the same controller node will change it's underlying architecture.

You don't have to do it in this PR, but it can be done in a follow up.

**Review by SimonRichardson — APPROVED** [review]

File: domain/modelagent/service/service.go (hunk 3 above)
Comment (adisazhar123) [reply domain/modelagent/service/service.go:1017]: I ordered desc intentionally so that I can grab the highest first by the first index. I think it's matter of preference.

For e.g. ascendingly I can do => `versions[len(versions)-1]` whereas descendingly I can do => `versions[0]` which is a tad simpler

File: domain/modelagent/service/service_test.go (hunk 1 above)
Comment (adisazhar123) [reply domain/modelagent/service/service_test.go:871]: > Multiple controller versions reported by state of different values. Confirm that the highest one is picked.

We have one here:
https://github.com/juju/juju/blob/8b51005b6288e34510e17f4a22349c390f73c5a7/domain/modelagent/service/service_test.go#L795


> Multiple controller versions reported by state of the same value.

Added here:
https://github.com/juju/juju/blob/54b9e87fb70f34f963b0fdb4fb0060a3bc079eb0/domain/modelagent/service/service_test.go#L833

File: internal/worker/upgradedatabase/worker.go (hunk 9 above)
Comment (adisazhar123) [reply internal/worker/upgradedatabase/worker.go]: Changed to `recording` based on Alvin's comment

File: internal/services/interface.go (hunk 2 above)
Comment (adisazhar123) [reply internal/services/interface.go]: Done

File: internal/worker/upgradedatabase/manifold.go (hunk 5 above)
Comment (adisazhar123) [reply internal/worker/upgradedatabase/manifold.go:103]: Done

File: internal/worker/upgradedatabase/worker.go (hunk 6 above)
Comment (adisazhar123) [reply internal/worker/upgradedatabase/worker.go:98]: Done

File: internal/worker/upgradedatabase/worker.go (hunk 7 above)
Comment (adisazhar123) [reply internal/worker/upgradedatabase/worker.go]: Done

File: internal/worker/upgradedatabase/worker_test.go (hunk 10 above)
Comment (adisazhar123) [reply internal/worker/upgradedatabase/worker_test.go]: Thank you. Done.

File: domain/services/upgrade.go (hunk 11 above)
Comment (adisazhar123) [reply domain/services/upgrade.go]: Good idea. Done.

File: internal/worker/upgradedatabase/worker.go (hunk 4 above)
Comment (adisazhar123) [reply internal/worker/upgradedatabase/worker.go]: Done

File: internal/worker/upgradedatabase/worker.go (hunk 8 above)
Comment (adisazhar123) [reply internal/worker/upgradedatabase/worker.go:80]: I did some code reading and found this code path.

If `IsAllowedControllerTag` ([ref1](https://github.com/juju/juju/blob/bb703f21289609a506cc80ac5e951dded3da5001/core/agent/tag.go#L8-L12)) returns true it will call the upgrader facade ([ref2](https://github.com/juju/juju/blob/bb703f21289609a506cc80ac5e951dded3da5001/internal/worker/caasupgrader/upgrader.go#L98)).

The `IsAllowedControllerTag` has a comment saying the check is needed because IAAS controllers are still using the `machine` tag. That comment tells me that `CAAS` controllers are already using `controller` tag so that facade code block is needed.

File: internal/worker/upgradedatabase/worker.go (hunk 12 above)
Comment (adisazhar123) [reply internal/worker/upgradedatabase/worker.go]: Done annotating the error.

I can exclude the architecture on upsert separately.
