### PR TITLE
fix: exclude empty checksum from backup metadata json

### LINKED ISSUE #22250: juju create-backup contains an empty checksum in metadata.json in the backup tarball
### Description

When attempting to create a backup on a Juju 3.6.14 controller, We encountered an error related to checksum validation: https://pastebin.canonical.com/p/vyqHGscRKY/

We confirmed the backup is present on the controller unit, but inside the metadata.json of the backup file, there is missing data 
```
~/$ tar -xzvf juju-backup-20260414-225316.tar.gz
~/$ cd juju-backup/
~/juju-backup$ cat metadata.json | jq
{
  "ID": "",
  "FormatVersion": 1,
  "Checksum": "",
  "ChecksumFormat": "",
  "Size": 0,
  "Stored": "0001-01-01T00:00:00Z",
  "Started": "2026-04-14T22:53:15.999070324Z",
  "Finished": "0001-01-01T00:00:00Z",
  "Notes": "",
  "ModelUUID": "6250aca6-c266-4d09-8276-8ae8436cfe02",
  "Machine": "2",
  "Hostname": "juju-6cfe02-controller-2",
  "Version": "3.6.14",
  "Base": "ubuntu@24.04",
  "ControllerUUID": "d66608ca-d6c9-4911-899e-37da71c3a6f8",
  "HANodes": 3,
  "ControllerMachineID": "2",
  "ControllerMachineInstanceID": "a5edf150-650d-420f-bd3e-30af12d8cf96"
}
```

we also checked `sha1sum <backup file> | base64 -d`, and found this did not match the printed checksum shown in the pastebin output.

### Juju version

3.6.14

### Cloud

_No response_

### Expected behaviour

Backup succeeds and properly downloads to local machine.

### Reproduce / Test

Unclear. 

Occurred on 3.6.14 controller, with 3.6.21 CLI. MongoDB v4.4.24

### Notes & References

Occurred during attempted backup of `juju-controller-36-staging-ps5` with @wallyworld

### PR DESCRIPTION
**Pull request by wallyworld**
The backup metadata.json embedded in the archive tarball previously included Checksum, ChecksumFormat, and Size fields. These fields could never be correct because metadata.json is serialized and injected into the archive before the archive itself is built and checksummed - making those fields always empty strings in practice.

Introduce metadata format version 2 which intentionally omits those fields.
The checksum and size are still available to the create-backup command and printed to stdout etc.

## QA steps

```
$ juju create-backup    

backup format version: 2 
juju version:          3.6.22.1 
base:                  ubuntu@24.04 

controller UUID:       2f76b0ce-fe24-493d-80bf-99c780b75b4d
model UUID:            4c3ceb23-c764-4bed-8a1c-fcbd9368e0bb 
machine ID:            0 
created on host:       ip-172-31-13-17 

checksum:              7uLUojbHvHxAtHMi5I6+68KyfKI= 
checksum format:       SHA-1, base64 encoded 
size (B):              128677432 
stored:                0001-01-01 00:00:00 +0000 UTC 
started:               2026-04-16 05:48:44.081668069 +0000 UTC 
finished:              2026-04-16 05:48:51.005676976 +0000 UTC 

notes:                  

Downloaded to juju-backup-20260416-054844.tar.gz
```
The metadata.json file from the backup:
```
{"ID":"","FormatVersion":2,"Stored":"0001-01-01T00:00:00Z","Started":"2026-04-17T02:09:37.207644023Z","Finished":"0001-01-01T00:00:00Z","Notes":"","ModelUUID":"7f8b672a-2994-4c87-85f8-d06571bba1bd","Machine":"0","Hostname":"ip-172-31-7-89","Version":"3.6.22.1","Base":"ubuntu@24.04","ControllerUUID":"c3d2dc23-240d-41fe-8943-f40a4f070a0e","HANodes":1,"ControllerMachineID":"0","ControllerMachineInstanceID":"i-07c91fb773da3866d"}
```

## Links

**Issue:** Fixes #22250.

**Jira card:** [JUJU-9676](https://warthogs.atlassian.net/browse/JUJU-9676)

[JUJU-9676]: https://warthogs.atlassian.net/browse/JUJU-9676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: state/backups/metadata_test.go [hunk 1]
```diff
@@ -218,10 +209,49 @@ func (s *metadataSuite) TestNewMetadataJSONReaderV1(c *gc.C) {
...
+		`"ControllerMachineInstanceID":"inst-10101010"` +
+		`}` + "\n")
+	meta, err := backups.NewMetadataJSONReader(file)
+	c.Assert(err, jc.ErrorIsNil)
+
+	c.Check(meta.ID(), gc.Equals, "20140909-115934.asdf-zxcv-qwe")
+	c.Check(meta.Checksum(), gc.Equals, "")
+	c.Check(meta.ChecksumFormat(), gc.Equals, "")
+	c.Check(meta.Size(), gc.Equals, int64(0))
+	c.Check(meta.Stored(), gc.IsNil)
```
Comment (CodingCookieRookie) [inline state/backups/metadata_test.go:236]: nit: would comparing struct be cleaner here?

**Review by CodingCookieRookie — APPROVED** [review]
LGTM thanks ian

File: state/backups/metadata_test.go (hunk 1 above)
Comment (wallyworld) [reply state/backups/metadata_test.go:236]: This is based on code from 2014!!!
I suspect the reason it was dome this way was to check that the function calls on the meta struct returned the expected result.

**Review by adisazhar123 — APPROVED** [review]
LGTM. QA passes.
