### PR TITLE
fix: retry caas provisoning if charm not ready

### LINKED ISSUE #21735: Juju forgets to scale application on deployment (Canonical K8s)
### Description

Hi,

Reproducible 100% on my side, but it looks to strange to pass Juju CI tests, so please re-confirm.

Issue: once scaling happens immediately to deployment, juju stuck in 1/3 scale with 1 pod/unit running:

STR:
```
juju deploy postgresql-k8s --trust ; juju scale-application postgresql-k8s 3
```

Expected results: postgresql cluster deployed with 3 units.

Actual: one unit/pod has been deployed and juju status says 1/3 permanently:

Image

No errors in logs.

### Juju version

3.6.14

### Cloud

Kubernetes

### Expected behaviour

See above

### Reproduce / Test

See above

### Notes & References

Note: tested on Canonical K8s here:

```
> sudo snap list
Name     Version         Rev    Tracking             Publisher   Notes
core20   20251031        2686   latest/stable        canonical✓  base
core22   20260113        2292   latest/stable        canonical✓  base
core24   20260107        1349   latest/stable        canonical✓  base
jhack    0.4.4.0.24      601    latest/edge          ppasotti    -
juju     3.6.14          33784  3/stable             canonical✓  -
k8s      v1.32.11        4754   1.32-classic/stable  canonical✓  classic
kubectl  1.34.3          3715   latest/stable        canonical✓  classic
lxd      5.21.4-de343be  37395  5.21/stable/…        canonical✓  -
snapd    2.73            25935  latest/stable        canonical✓  snapd

> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.3 LTS
Release:        24.04
Codename:       noble

> uname -a
Linux juju3613 6.8.0-94-generic #96-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan  9 20:36:55 UTC 2026 x86_64 x86_64 x86_64 GNU/Linux
```

Note: `juju deploy postgresql-k8s --trust -n 3` works well and as expected (all 3 units/pods have been created).

### PR DESCRIPTION
**Pull request by wallyworld**
This backports the key fix from #19203 and adds a unit test.
If a scale notification is received before the app is marked as provisioned, it never retries.

As a drive by, also add the engine report from #20007

## QA steps

bootstrap k8s
```
juju deploy snappass-test && juju scale-application snappass-test 3
```

## Links

**Issue:** Fixes #21735.

**Jira card:** [JUJU-9177](https://warthogs.atlassian.net/browse/JUJU-9177)

[JUJU-9177]: https://warthogs.atlassian.net/browse/JUJU-9177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: internal/worker/caasapplicationprovisioner/application.go [hunk 1]
```diff
@@ -419,8 +438,32 @@ func (a *appWorker) loop() error {
...
 			}
-		case <-a.clock.After(10 * time.Second):
+		case <-refreshTimer.Chan():
 			// Force refresh of application status.
+		case reportChan := <-a.engineReportRequest:
+			// Respond to engine reports.
+			var reportErrors []string
+			ps, err := a.facade.ProvisioningState(a.name)
+			if err != nil {
+				return errors.Trace(err)
```
Comment (CodingCookieRookie) [inline internal/worker/caasapplicationprovisioner/application.go]: hi ian, just a question about this here. Was wondering if we would want to crash the worker if there is an error in getting the values for the report. And should we send the err in the report instead? I assumed that might be what the reportErrors variable was for

**Review by CodingCookieRookie — APPROVED** [review]
LGTM thanks ian, just a discussion point on the report. Would be great if you could take a look at it :D

File: internal/worker/caasapplicationprovisioner/application.go (hunk 1 above)
Comment (hpidcock) [reply internal/worker/caasapplicationprovisioner/application.go]: Good catch.

Comment (wallyworld) [reply internal/worker/caasapplicationprovisioner/application.go]: Good pickup, was a backport error. The err should have been added to the report errors

Comment (CodingCookieRookie) [reply internal/worker/caasapplicationprovisioner/application.go]: thanks for looking into it 👍
