### PR TITLE
fix: make EnterScope truly idempotent

### LINKED ISSUE #21194: [4/candidate] Units in relations do not tear down gracefully
### Description

Removing units often sends them into an error:

```
unit-charmed-etcd-2: 18:00:28 DEBUG juju.worker.dependency "uniter" manifold worker stopped: failed to initialize uniter for "unit-charmed-etcd-2": cannot create relation state tracker: checking unit valid in relation: cannot enter scope, unit or relation not alive
stack trace:
checking unit valid in relation: cannot enter scope, unit or relation not alive
github.com/juju/juju/api/agent/uniter.(*RelationUnit).EnterScope:73:
github.com/juju/juju/internal/worker/uniter/relation.(*relationStateTracker).joinRelation:206:
github.com/juju/juju/internal/worker/uniter/relation.(*relationStateTracker).loadInitialState:132:
github.com/juju/juju/internal/worker/uniter/relation.NewRelationStateTracker:86:
github.com/juju/juju/internal/worker/uniter.(*Uniter).init:711: cannot create relation state tracker
github.com/juju/juju/internal/worker/uniter.(*Uniter).loop:299: failed to initialize uniter for "unit-charmed-etcd-2"
unit-charmed-etcd-2: 18:00:28 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: failed to initialize uniter for "unit-charmed-etcd-2": cannot create relation state tracker: checking unit valid in relation: cannot enter scope, unit or relation not alive
```

This prevents the unit from setting itself to `dying`.

### Juju version

4.0-rc1

### Cloud

LXD

### Expected behaviour

Dying units should not cause the uniter to bounce when initialising state.

### Reproduce / Test

- `juju deploy postgresql -n 3`.
- Once settled, `juju destroy-mode <name> --no-prompt`.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by hmlanigan**
Model tear down was cleaning prevented if the runner context canceled during remove relation operations causing the uniter to restart. During uniter start up, it attempts to reenter all known relations. This was failing as the relation was in a dying state. 

EnterScope was only idempotent if neither the relation nor unit were dying. However the uniter expects it to always be idempotent as it is in 3.x. This allows for proper removal of a relation from a unit, if it must restart at any point.

If the same thing occurs when a relation is being removed without the model being removed, the unit could never exist the relation. This prevented the relation from being recreated later.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

To reproduce the conditions which produces this issue, add the following wrench before compiling
```
diff --git a/internal/worker/uniter/operation/executor.go b/internal/worker/uniter/operation/executor.go
index bfeedc0381..58bdf22a3b 100644
--- a/internal/worker/uniter/operation/executor.go
+++ b/internal/worker/uniter/operation/executor.go
@@ -7,12 +7,15 @@ import (
        "context"
        "fmt"
        "runtime/pprof"
+       "sync/atomic"

        "github.com/juju/errors"

        "github.com/juju/juju/core/logger"
        "github.com/juju/juju/core/trace"
+       "github.com/juju/juju/internal/charm/hooks"
        "github.com/juju/juju/internal/worker/uniter/remotestate"
+       "github.com/juju/juju/internal/wrench"
 )

 type executorStep struct {
@@ -177,6 +180,8 @@ func (x *executor) do(ctx context.Context, op Operation, step executorStep) (err
        return errors.Annotate(firstErr, message)
 }

+var flag atomic.Bool
+
 func (x *executor) writeState(ctx context.Context, newState State) error {
        if err := newState.Validate(); err != nil {
                return err
@@ -184,6 +189,16 @@ func (x *executor) writeState(ctx context.Context, newState State) error {
        if x.state != nil && x.state.match(newState) {
                return nil
        }
+       if x.state != nil && x.state.Hook != nil {
+               if x.state.Hook.Kind == hooks.RelationBroken && wrench.IsActive("contextfail", "relation-broken") {
+                       if !flag.Load() {
+                               flag.Store(true)
+                               c, cancel := context.WithCancel(ctx)
+                               ctx = c
+                               cancel()
+                       }
+               }
+       }
        if err := x.stateOps.Write(ctx, &newState); err != nil {
                return errors.Annotatef(err, "writing state")
        }
```

Due to the atomic boolean in the wrench, both tests require a new controller. 
```
$ juju bootstrap testme
$ juju add-model test ; juju deploy juju-qa-dummy-source source ; juju deploy juju-qa-dummy-sink sink; juju relate sink source ; juju import-ssh-key lp:<username>

# once the machines are up and running, enable the wrench
for i in `seq 0 1`; do juju ssh $i 'sudo mkdir /var/lib/juju/wrench && echo "relation-broken" | sudo tee /var/lib/juju/wrench/contextfail' ; done

# remove the relation and re-create it, validate both are successful.
$ juju remove-relation sink source
$ juju relate sink source
```

```
$ juju bootstrap testme
$ juju add-model test ; juju deploy juju-qa-dummy-source source ; juju deploy juju-qa-dummy-sink sink; juju relate sink source ; juju import-ssh-key lp:<username>

# once the machines are up and running, enable the wrench
for i in `seq 0 1`; do juju ssh $i 'sudo mkdir /var/lib/juju/wrench && echo "relation-broken" | sudo tee /var/lib/juju/wrench/contextfail' ; done

# remove the model successfully
$ juju remove-model test
```

## Links

**Issue:** Fixes #21194

**Jira card:** [JUJU-8756](https://warthogs.atlassian.net/browse/JUJU-8756)

[JUJU-8756]: https://warthogs.atlassian.net/browse/JUJU-8756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/relation/state/relation.go [hunk 1]
```diff
@@ -1617,6 +1619,16 @@ func (st *State) EnterScope(
 	if err != nil {
 		return errors.Capture(err)
 	}
+	st.logger.Criticalf(ctx, "EnterScope(%q, %q)", relationUUID, unitName)
```
Comment (SimonRichardson) [inline domain/relation/state/relation.go]: Delete me.

File: domain/relation/state/relation.go [hunk 2]
```diff
@@ -1631,6 +1643,23 @@ WHERE  name = $getUnit.name
 	}
 
 	err = db.Txn(ctx, func(ctx context.Context, tx *sqlair.TX) error {
+		// If the unit is already in scope, return nil to be idempotent.
+		// Settings will not be changed. Even when the unit or relation is
```
Comment (SimonRichardson) [inline domain/relation/state/relation.go:1649]: > // Settings will not be changed.

Is that true? Should we not be updating the settings? How do you know we didn't drop any settings?

File: domain/relation/state/relation.go [hunk 3]
```diff
@@ -1631,6 +1643,23 @@ WHERE  name = $getUnit.name
...
+			Name: unitName.String(),
+			UUID: relationUUID.String(),
+		}
+		err = tx.Query(ctx, alreadyInScopeStmt, exists).Get(&count)
+		if err != nil && !errors.Is(err, sqlair.ErrNoRows) {
+			return errors.Capture(err)
+		}
+		if count.Count == 1 {
+			return relationerrors.RelationUnitAlreadyExists
+		}
```
Comment (SimonRichardson) [inline domain/relation/state/relation.go:1667]: I'd probably be slightly more defensive here and state that it's not equal to zero.

File: domain/relation/state/migration.go [hunk 4]
```diff
@@ -97,7 +97,7 @@ WHERE name = $applicationUUIDAndName.name
 		} else if err != nil {
 			return errors.Errorf("looking up UUID for application %q: %w", appName, err)
 		}
-		id = app.ID
+		id = application.UUID(app.UUID)
```
Comment (gfouillet) [inline domain/relation/state/migration.go:100]: **todo:** Actually in state layer the right move is to drop types and use primitive type (here, strings).

File: domain/relation/state/relation.go [hunk 5]
```diff
@@ -1617,6 +1619,16 @@ func (st *State) EnterScope(
...
+	alreadyInScopeStmt, err := st.Prepare(`
+SELECT COUNT(*) AS &rows.count
+FROM   relation_unit AS ru
+JOIN   relation_endpoint AS re ON ru.relation_endpoint_uuid = re.uuid
+JOIN   unit AS u ON ru.unit_uuid = u.uuid
+WHERE  u.name = $nameAndUUID.name
+AND    re.relation_uuid = $nameAndUUID.uuid
+`, nameAndUUID{}, rows{})
 
 	unitArgs := getUnit{
```
Comment (gfouillet) [inline domain/relation/state/relation.go:1635]: **todo:** getUnit is strictly the same type than nameAndUUID. Pick one, remove the other.

**Review by gfouillet — COMMENTED** [review]
I think Simon may have a valid concern about settings. 

Those are fetched from network domain by the uniter, when the unit enter scope.

This change without updating the settings would fix the issue during removal job (we don't care if the settings  since it will be dropped anyway), but I wonder what happens if the uniter restart due to a machine restart... And if a machine restart may trigger a change on network layer (changing IPs) on some providers.

File: domain/relation/state/relation.go (hunk 2 above)
Comment (hmlanigan) [reply domain/relation/state/relation.go:1649]: The only unit settings ever written by EnterScope are the ingress and egress addresses. This is hidden from the uniter in the facade method. Those set by the charm are not touched here.  EnterScope technically updates settings due to a shared code path with the state Set*Settings methods. There is a `conflict on` in the insert query.

The ingress and egress addresses are "updated" when CommitHookChanges is run, so twice for every hook run, before and after. Therefore no need to update them again in this case.

This is the current behavior in 3.6. https://github.com/juju/juju/blob/dcf8dd6853c9df237af4a898a70493fdbcad8017/state/relationunit.go#L58-L60

File: domain/relation/state/relation.go (hunk 3 above)
Comment (hmlanigan) [reply domain/relation/state/relation.go:1667]: Can only happen if someone makes a bad change to the SQL for the table by removing:

```
CREATE UNIQUE INDEX idx_relation_unit
ON relation_unit (relation_endpoint_uuid, unit_uuid);
```

Allowing for more than one is not correct either, as juju only allows one relation unit per relation unit pair.

File: domain/relation/state/migration.go (hunk 4 above)
Comment (hmlanigan) [reply domain/relation/state/migration.go:100]: This was done solely to use a generic structure. I didn't intend to make the drive-by more complex by adding in other changes.

File: domain/relation/state/relation.go (hunk 5 above)
Comment (hmlanigan) [reply domain/relation/state/relation.go:1635]: Technically true, however requires another struct update as getUnit does not use basic types either. Outside of the scope of this change and the drive-by.

File: domain/relation/state/relation.go (hunk 2 above)
Comment (hmlanigan) [reply domain/relation/state/relation.go:1649]: Update: The addresses are updated when the `hooks.ConfigChanged` is run.

ConfigChanged is run when the remote and local addresses do not match or if the config is changed.

File: domain/relation/state/relation.go (hunk 3 above)
Comment (hpidcock) [reply domain/relation/state/relation.go:1667]: The other case is if someone removes the unit name uniqueness, since this query uses names not a UUID to resolve the unit.

So we should defend against both of those cases. If `count > 1` return `errors.Errorf("unexpected relation unit count...`.

File: domain/relation/service/relation.go [hunk 6]
```diff
@@ -499,7 +501,10 @@ func (s *Service) EnterScope(
 	}
 
 	// Enter the unit into the relation scope.
-	if err := s.st.EnterScope(ctx, relationUUID, unitName, settings); err != nil {
+	err := s.st.EnterScope(ctx, relationUUID, unitName, settings)
+	if errors.Is(err, relationerrors.RelationUnitAlreadyExists) {
+		return nil
+	} else if err != nil {
```
Comment (hpidcock) [inline domain/relation/service/relation.go:507]: This is wrong, we must go on to check if a subordinate unit needs to be created below.

Comment (hmlanigan) [reply domain/relation/service/relation.go:507]: I have a new card for the work around subordinates and retrying based on the TODO below in the same method.  If we fail to make the subordinate the first time in a way which can be retried, the unit should not enter scope. Unfortunately it does today. The uniter is setup to retry if they get an error of type `params.CodeCannotEnterScopeYet`. 

I plan to work it next: https://warthogs.atlassian.net/browse/JUJU-8773

**Review by SimonRichardson — APPROVED** [review]
