### PR TITLE
fix: add controller ports in status output

### LINKED ISSUE #21818: missing port in status
### Description

`juju status -m controller 0` doesn't show the port for the unit when running in a 4.x controller.

### Juju version

4.0 HEAD

### Cloud

LXD

### Expected behaviour

`juju status` shows the port.

### Reproduce / Test

Missing the port.

```sh
$ juju status -m controller
Model       Controller  Cloud/Region       Version  Timestamp
controller  dst         localhost/default  4.0.2.5  13:11:36Z

App         Version  Status  Scale  Charm            Channel     Rev  Exposed  Message
controller           active      1  juju-controller  4.0/stable  157  no

Unit           Workload  Agent  Machine  Public address  Ports  Message
controller/0*  active    idle   0        10.232.51.180

Machine  State    Address        Inst id        Base          AZ          Message
0        started  10.232.51.180  juju-2d7f92-0  ubuntu@24.04  simon-work  Running
```

Showing the port:

```sh
$ juju status -m src:controller
Model       Controller  Cloud/Region       Version  Timestamp
controller  src         localhost/default  3.6.14   13:11:43Z

App         Version  Status  Scale  Charm            Channel     Rev  Exposed  Message
controller           active      1  juju-controller  3.6/stable  116  yes

Unit           Workload  Agent  Machine  Public address  Ports      Message
controller/0*  active    idle   0        10.232.51.28    17022/tcp

Machine  State    Address       Inst id        Base          AZ          Message
0        started  10.232.51.28  juju-cbdbf3-0  ubuntu@24.04  simon-work  Running
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by iyiguncevik**
`juju status` shows unit open ports from model port state. In the controller
model, the controller application does not publish its API/SSH ports through
the normal open-port path, so those ports are missing from status output even
though they are active and configurable at bootstrap (api-port,
ssh-server-port).

What changed:

This PR creates a workaround in Client.FullStatus facade:
  - For controller-model status requests, read controller config from the controller config service.
  - Augment `controller/*` unit open ports with API + SSH ports.
  - Keep values dynamic (no hard-coded ports), deduplicated, and sorted.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [x] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

```sh
❯ juju bootstrap lxd src \
  --config ssh-server-port=18888 api-port=17777

❯ juju status -m src:controller
Model       Controller  Cloud/Region         Version  Timestamp
controller  src         localhost/localhost  4.0.6.4  16:31:37+02:00

App         Version  Status  Scale  Charm            Channel     Rev  Exposed  Message
controller           active      1  juju-controller  4.0/stable  157  no

Unit           Workload  Agent  Machine  Public address  Ports            Message
controller/0*  active    idle   0        10.179.172.11   17777,18888/tcp

Machine  State    Address        Inst id        Base          AZ      Message
0        started  10.179.172.11  juju-a2eaa9-0  ubuntu@24.04  tuxedo  Running

❯ juju status -m src:controller --format=json | jq '.applications.controller.units["controller/0"]."open-ports".[]'
"17777/tcp"
"18888/tcp"
```

## Links

**Issue:** Fixes #21818

**Jira card:** [JUJU-9249](https://warthogs.atlassian.net/browse/JUJU-9249)

[JUJU-9249]: https://warthogs.atlassian.net/browse/JUJU-9249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apiserver/facades/client/client/status.go [hunk 1]
```diff
@@ -428,6 +437,42 @@ func (c *statusContext) fetchAllOpenPortRanges(ctx context.Context, portService
 	return err
 }
 
+func (c *statusContext) populateControllerPorts(controllerConfig controller.Config) {
+	const controllerAppName = "controller"
```
Comment (gfouillet) [inline apiserver/facades/client/client/status.go]: **todo:** use coreapplication.ControllerApplicationName

note: can be changed also here:

https://github.com/juju/juju/blob/d127f7a5bba964cddcf9e752f84ea61e5da46fa8/domain/application/service/exposed.go#L80-L83

File: apiserver/facades/client/client/status.go [hunk 2]
```diff
@@ -428,6 +437,42 @@ func (c *statusContext) fetchAllOpenPortRanges(ctx context.Context, portService
...
+	controllerApp, ok := c.allAppsUnitsCharmBindings.applications[controllerAppName]
+	if !ok || len(controllerApp.Units) == 0 {
+		return
+	}
+
+	if c.allOpenPortRanges == nil {
+		c.allOpenPortRanges = make(port.UnitGroupedPortRanges)
+	}
+	controllerPorts := []network.PortRange{
+		network.MustParsePortRange(strconv.Itoa(controllerConfig.APIPort())),
```
Comment (gfouillet) [inline apiserver/facades/client/client/status.go]: **issue:** Don't use must there. THis will panic if APIPort or SSHServerPort are not parsable, which may be possible unless we already have validate them in this package. 

zero confidence with outside package, even those we own.

File: apiserver/facades/client/client/status.go [hunk 3]
```diff
@@ -428,6 +437,42 @@ func (c *statusContext) fetchAllOpenPortRanges(ctx context.Context, portService
...
+		network.MustParsePortRange(strconv.Itoa(controllerConfig.SSHServerPort())),
+	}
+	for unitName := range controllerApp.Units {
+		existing := c.allOpenPortRanges[unitName]
+		// Build a lookup of currently-open ports for this unit.
+		existingSet := make(map[network.PortRange]struct{}, len(existing))
```
Comment (gfouillet) [inline apiserver/facades/client/client/status.go:457]: **question:** Is it expected that if ssh or api port are included in any port range, we show them in the openPortRanges anyway ?

Comment (iyiguncevik) [reply apiserver/facades/client/client/status.go:457]: I don't understand the question. At the moment, controller doesn't open ports and therefore SSH and API server ports are not listed in the open port ranges. But if someone fixes this in the charm etc and controller charm open ports, this would duplicate them. This is a precaution for that situation.

Comment (gfouillet) [reply apiserver/facades/client/client/status.go:457]: We are comparing port range (xxxx-yyyy) by string, not doing inclusion. So having, like "5000-6000" range and another port like "5555" will not be merged as expected (since 5555 belong to the range).
