### PR TITLE
fix: api connection flakiness

### LINKED ISSUE #21664: Juju CLI intermittently exits with "ERROR connection is shut down" under high CPU load
### Description

Over https://github.com/canonical/jubilant/issues/241 several teams have described seeing `juju status` and other CLI commands crash with `ERROR connection is shut down` under heavy CPU load. This problem can usually be mitigated by just retrying the command, which points to the error message being bogus and/or the CLI being too "impatient".

In the case of Charmed MySQL, we weren't seeing this until we migrated our integration tests to Jubilant. OpsTest uses the Juju API (I believe) whereas Jubilant uses the Juju CLI.

Retrying commands is problematic because not all of them are idempotent. On top of that, there's ongoing discussion on whether some retry logic should be provided by Jubilant, or whether this should be addressed here.

### Juju version

3.6.\*, 2.9.\*

### Cloud

Kubernetes

### Expected behaviour

CLI commands should not immediately fail under high CPU load.

### Reproduce / Test

This is difficult to reproduce reliably, but you can see how we had to wrap several Juju CLI commands in https://github.com/canonical/mysql-k8s-operator/pull/710 for `test_multi_relations_new.py`.

I have never been able to reproduce this locally, only on CI.

See other comments in https://github.com/canonical/jubilant/issues/241 for examples from other teams.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by wallyworld**
This PR backports the key api connection fixes from #21080. Not everything came back cleanly due to the significant divergence between 3.x and 4.x. For many client api implementations, the context is not passed in by the caller in 3.x so we use a TODO() context instead as the parent context.

Also backports the core work from #21089 to deal with slow controllers at bootstrap.

## QA steps

The pre merge smoke tests are sufficient.

## Links

**Issue:** Fixes #21664.

**Jira card:** [JUJU-9193](https://warthogs.atlassian.net/browse/JUJU-9193)

[JUJU-9193]: https://warthogs.atlassian.net/browse/JUJU-9193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: api/agent/uniter/resource_test.go [hunk 1]
```diff
@@ -60,13 +60,13 @@ func (s *ResourcesFacadeClientSuite) TestUnitDoer(c *gc.C) {
...
 	var resp *http.Response
-	doer := uniter.NewUnitHTTPClient(context.Background(), s.api, "spam/1")
+	doer := uniter.NewUnitHTTPClient(s.api, "spam/1")
 
 	err = doer.Do(context.Background(), req, &resp)
 	c.Assert(err, jc.ErrorIsNil)
 
 	s.stub.CheckCallNames(c, "Do")
-	//s.stub.CheckCall(c, 0, "Do", expected, body, resp)
+	// s.stub.CheckCall(c, 0, "Do", expected, body, resp)
```
Comment (adisazhar123) [inline api/agent/uniter/resource_test.go]: I'm assuming IDE ran auto-format. Probably can remove this line if unused?

File: api/agent/uniter/resource_test.go [hunk 2]
```diff
@@ -100,7 +100,7 @@ func (s *stubAPI) BestFacadeVersion(_ string) int {
 
 func (s *stubAPI) HTTPClient() (*httprequest.Client, error) {
 	return &httprequest.Client{
-		//Doer: func,
+		// Doer: func,
```
Comment (adisazhar123) [inline api/agent/uniter/resource_test.go]: Same here

**Review by adisazhar123 — APPROVED** [review]
This is a monster. Thank you!
