### PR TITLE
fix(modelmanager): finds valid credentials when creating a model

### LINKED ISSUE #20881: Juju 4 beta 7 - cannot deploy Kubeflow on AKS using terraform - credentials not found
### Description

> [!NOTE]
> Preliminary testing for Juju 4 by Solutions QA

1. Deployed Solutions QA's AKS cluster using Terraform (we don't use juju for it)
2. `add-k8s` with the cluster's credentials, and create a new controller for it.
3. Attempt to deploy Charmed Kubeflow+MLFlow using their [terraform solution](https://github.com/canonical/charmed-kubeflow-solutions/tree/track/1.10/modules/kubeflow-mlflow) --- **FAILS**

```console
module.kubeflow.juju_model.kubeflow[0]: Creating...
╷
│ Error: Client Error
│ 
│   with module.kubeflow.juju_model.kubeflow[0],
│   on ../kubeflow/main.tf line 1, in resource "juju_model" "kubeflow":
│    1: resource "juju_model" "kubeflow" {
│ 
│ Unable to create model "\"kubeflow\"", got error: cloud credential for new
│ model is not valid (not found)
╵
Error: Process completed with exit code 1.
```

### Juju version

4 beta 7

### Cloud

Kubernetes

### Expected behaviour

The Kubeflow+MLFlow deployment using Terraform works with Juju 4/beta as it already does with Juju 3/stable.

### Reproduce / Test

See above, also reproducible in SQA tests.

### Notes & References

The specific run in SQA: https://solutions.qa.canonical.com/testruns/78b8c172-5646-46f4-9ca2-4fb9dcab0696

Also, I am not sure if the cloud should be Kubernetes in this case or Azure.  AKS is deployed by SQA without using Juju, and then it is `add-k8s`-ed.

### PR DESCRIPTION
**Pull request by alesstimec**
In case user did not specify cloud credentials this code will use the first valid credential to create a model.

fix #20881

## QA steps

 1. Bootstrap a 4 controller
 2. create the following main.tf 
```terraform
terraform {
  required_providers {
    juju = {
      version = "0.23.1"
      source  = "juju/juju"
    }
  }
}

provider "juju" {
 <fill in configuration>
}

resource "juju_model" "test" {
  name = "test"
}

```
3. run `terraform apply -auto-approve`
4. observe the model was created

### CODE REVIEW

**Review by luci1900 — APPROVED** [review]

File: apiserver/facades/client/modelmanager/modelmanager.go [hunk 1]
```diff
@@ -220,9 +221,26 @@ func (m *ModelManagerAPI) CreateModel(ctx context.Context, args params.ModelCrea
 			return result, errors.Trace(err)
 		}
 		creationArgs.Credential = credential.KeyFromTag(cloudCredentialTag)
+	} else {
+		// we're looking up credentials for the apiUser - what if JIMM is creating a model on behalf of another user (JIMM always
```
Comment (ale8k) [inline apiserver/facades/client/modelmanager/modelmanager.go:225]: Do we need this comment?

File: apiserver/facades/client/modelmanager/modelmanager.go [hunk 2]
```diff
@@ -220,9 +221,26 @@ func (m *ModelManagerAPI) CreateModel(ctx context.Context, args params.ModelCrea
...
+		// specifies the credential, so we should be fine)
+		creds, err := m.credentialService.CloudCredentialsForOwner(ctx, coreuser.NameFromTag(m.apiUser), cloudTag.Id())
```
Comment (ale8k) [inline apiserver/facades/client/modelmanager/modelmanager.go]: We're getting many credentials here, but I wonder if on L160 we can get a default credential name here?

**Review by ale8k — COMMENTED** [review]
Some Q's about how we get the cred

File: apiserver/facades/client/modelmanager/modelmanager.go (hunk 2 above)
Comment (alesstimec) [reply apiserver/facades/client/modelmanager/modelmanager.go]: credentials do not have a "default" property.. and getting credentials is not the same as getting the default cloud/region. each user has their own set of credentials and i think choosing the first valid, non-revoked credentials is a valid approach.

File: apiserver/facades/client/modelmanager/modelmanager.go (hunk 1 above)
Comment (alesstimec) [reply apiserver/facades/client/modelmanager/modelmanager.go:225]: i think it's worth keeping so we don't forget that JIMM always creates model on behalf of other users and does so as `admin` user

File: apiserver/facades/client/modelmanager/modelmanager.go (hunk 2 above)
Comment (ale8k) [reply apiserver/facades/client/modelmanager/modelmanager.go]: Ah sorry yes, CloudCredentials hold a default "Credential".

**Review by ale8k — APPROVED** [review]

File: apiserver/facades/client/modelmanager/modelmanager.go [hunk 3]
```diff
@@ -220,9 +220,26 @@ func (m *ModelManagerAPI) CreateModel(ctx context.Context, args params.ModelCrea
...
+		for credName, cred := range creds {
+			if !cred.Invalid && !cred.Revoked {
+				key, err := credential.KeyFromString(credName)
+				if err != nil {
+					return result, errors.Trace(err)
+				}
+				creationArgs.Credential = key
+				break
+			}
+		}
```
Comment (SimonRichardson) [inline apiserver/facades/client/modelmanager/modelmanager.go:234]: Can we make a service method for this. So it's standardised. `FirstValidCloudCredentialsForOwner` or some such (not sold on the name).

What I don't like is that we're getting all the credentials at once, iterating through all of them, and that could easily be baked into the state layer.

Comment (alesstimec) [reply apiserver/facades/client/modelmanager/modelmanager.go:234]: just a service method or a state method, too, with a specialized query?

Comment (alesstimec) [reply apiserver/facades/client/modelmanager/modelmanager.go:234]: as for you other comment: do we need to connect to the environment to ensure credentials are valid? can't we trust the `Invalid` field of the credential?

Comment (SimonRichardson) [reply apiserver/facades/client/modelmanager/modelmanager.go:234]: > just a service method or a state method, too, with a specialized query?

If we can make it state method, then we should, otherwise service should suffice for now.

> as for you other comment: do we need to connect to the environment to ensure credentials are valid? can't we trust the Invalid field of the credential?

We do attempt to query a provider that has just been created using the model, though not all providers support the interface we're attempting to access. So that won't suffice for all substrates.

https://github.com/juju/juju/blob/bffc91236ce1068d21afe480389db48c114a21f2/domain/model/service/modelservice.go#L988-L995

I think we potentially want this to land first https://github.com/juju/juju/pull/19781

Then we can circle back around and ensure the credentials are valid in a follow up PR.

Comment (alesstimec) [reply apiserver/facades/client/modelmanager/modelmanager.go:234]: Implemented state and service methods.. the names i'm not too attached to..

File: apiserver/facades/client/modelmanager/modelmanager.go [hunk 4]
```diff
@@ -220,9 +220,17 @@ func (m *ModelManagerAPI) CreateModel(ctx context.Context, args params.ModelCrea
 			return result, errors.Trace(err)
 		}
 		creationArgs.Credential = credential.KeyFromTag(cloudCredentialTag)
+	} else {
+		// we're looking up credentials for the apiUser - what if JIMM is creating a model on behalf of another user (JIMM always
+		// specifies the credential, so we should be fine)
+		credKey, _, err := m.credentialService.SingleValidCloudCredentialsForOwner(ctx, coreuser.NameFromTag(m.apiUser), cloudTag.Id())
```
Comment (tlm) [inline apiserver/facades/client/modelmanager/modelmanager.go]: This should be on the model service. Rename it to `SuggestUserCredentialForNewModel`. Turn around and make a call directly into state and do it all in sql. You only want to get credentials where the user has 1 of them for the cloud. Otherwise return a not found error.

The multiple error adds to this problem because the facades uses the service to delegate the problem to. Not receive an error back that makes it harder.

You will probably need to maintain a boolean in this func for if we have picked the default cloud for the new model. This is so that if we don't find a credential to use we can tailor the response to the caller.

We need to tell the user specify both a cloud and credential if we have used the default cloud. If they supplied the cloud we need to tell them to just supply a credential to use.

File: apiserver/facades/client/modelmanager/modelmanager.go [hunk 5]
```diff
@@ -220,9 +220,17 @@ func (m *ModelManagerAPI) CreateModel(ctx context.Context, args params.ModelCrea
...
+		if err != nil {
+			return result, errors.Trace(err)
```
Comment (tlm) [inline apiserver/facades/client/modelmanager/modelmanager.go]: We can probably forgoe some error handling here because we know things will be checked in other places like user and cloud. But if we are doing this properly they need to be asserted and errors handled.

File: apiserver/testing/credential.go [hunk 6]
```diff
@@ -36,3 +38,10 @@ func (credentialGetter) InvalidateCredential(_ context.Context, _ credential.Key
 func (credentialGetter) WatchCredential(ctx context.Context, key credential.Key) (watcher.NotifyWatcher, error) {
 	return nil, nil
 }
+
+func (c credentialGetter) SingleValidCloudCredentialsForOwner(ctx context.Context, owner user.Name, cloudName string) (credential.Key, cloud.Credential, error) {
```
Comment (tlm) [inline apiserver/testing/credential.go]: If we move to the model service we don't have to keep this on life support. This should be deleted and not extended :)

File: core/credential/credential.go [hunk 7]
```diff
@@ -122,3 +122,21 @@ func (u UUID) Validate() error {
 	}
 	return nil
 }
+
+// KeyFromString returns a credential key parsed from the specified string.
+func KeyFromString(key string) (Key, error) {
```
Comment (tlm) [inline core/credential/credential.go]: I don't know what this is for I am sorry. We are actively running away from natural keys and I would really like to see us not adding to it. Are you able to show the why behind this ?

File: domain/credential/errors/errors.go [hunk 8]
```diff
@@ -24,4 +24,8 @@ const (
 
 	// UserNotFound describes an error that occurs when a user is not found.
 	UserNotFound = errors.ConstError("user not found")
+
+	// MultipleCloudCredentialsFound describes an error that occurs when an owner
+	// has multiple valid cloud credentials.
+	MultipleCloudCredentialsFound = errors.ConstError("multiple cloud credentials found")
```
Comment (tlm) [inline domain/credential/errors/errors.go]: As stated above this shouldn't be the error. The error should be we don't have a suggested/default credential available to support creating this model.

File: domain/credential/service/service.go [hunk 9]
```diff
@@ -60,6 +60,10 @@ type State interface {
 	// for a given owner.
 	AllCloudCredentialsForOwner(ctx context.Context, owner user.Name) (map[corecredential.Key]credential.CloudCredentialResult, error)
 
+	// ValidCloudCredentialsForOwner returns the owner's cloud credentials for a given
+	// cloud, keyed by credential name.
+	ValidCloudCredentialsForOwner(ctx context.Context, owner user.Name, cloudName string) (map[string]credential.CloudCredentialResult, error)
```
Comment (tlm) [inline domain/credential/service/service.go]: Valid should be implied in the contract and not the func name. Credentials should already be valid if they are in the database. I would suggest `DefaultUserCloudCredential`. You can then only supply a credential if it is the only credential available in state.

File: domain/credential/service/service.go [hunk 10]
```diff
@@ -145,6 +149,34 @@ func (s *Service) CloudCredentialsForOwner(ctx context.Context, owner user.Name,
 	return result, nil
 }
 
+// SingleValidCloudCredentialsForOwner returns the owner's valid (and non-revoked) credential key and cloud credentials for a given cloud
+// if only one credential exists. Where owner has multiple valid cloud credentials an error is returned.
+func (s *Service) SingleValidCloudCredentialsForOwner(ctx context.Context, owner user.Name, cloudName string) (corecredential.Key, cloud.Credential, error) {
```
Comment (tlm) [inline domain/credential/service/service.go]: As stated above I think this should move over to the model service. Another consideration for either this func or the caller is that you have to consider that some cloud support empty credentials.

In this case we should proceed with empty credentials. It is a supported cased by CreateModel in the domain today.

File: domain/credential/service/service.go [hunk 11]
```diff
@@ -145,6 +149,34 @@ func (s *Service) CloudCredentialsForOwner(ctx context.Context, owner user.Name,
...
+
+	creds, err := s.st.ValidCloudCredentialsForOwner(ctx, owner, cloudName)
+	if err != nil {
+		return returnError(errors.Capture(err))
+	}
+	if len(creds) > 1 {
+		return returnError(credentialerrors.MultipleCloudCredentialsFound)
+	}
+	for name, credInfoResult := range creds {
+		key, err := corecredential.KeyFromString(name)
```
Comment (tlm) [inline domain/credential/service/service.go]: We have concrete structs to pass this value upwards instead of using a string.

File: domain/credential/service/service.go [hunk 12]
```diff
@@ -145,6 +149,34 @@ func (s *Service) CloudCredentialsForOwner(ctx context.Context, owner user.Name,
...
+		if err != nil {
+			return returnError(errors.Capture(err))
+		}
+		return key, cloudCredentialFromCredentialResult(credInfoResult), nil
+	}
+
+	return returnError(credentialerrors.NotFound)
```
Comment (tlm) [inline domain/credential/service/service.go]: We don't return raw error types with no context. This will be extremely hard to trace down in the future.

File: apiserver/testing/credential.go (hunk 6 above)
Comment (alesstimec) [reply apiserver/testing/credential.go]: removed

File: core/credential/credential.go (hunk 7 above)
Comment (alesstimec) [reply core/credential/credential.go]: removed

File: domain/credential/errors/errors.go (hunk 8 above)
Comment (alesstimec) [reply domain/credential/errors/errors.go]: removed

File: domain/credential/service/service.go (hunk 9 above)
Comment (alesstimec) [reply domain/credential/service/service.go]: renamed

File: domain/credential/service/service.go (hunk 10 above)
Comment (alesstimec) [reply domain/credential/service/service.go]: moved

File: domain/credential/service/service.go (hunk 11 above)
Comment (alesstimec) [reply domain/credential/service/service.go]: done, i think

File: domain/credential/service/service.go (hunk 12 above)
Comment (alesstimec) [reply domain/credential/service/service.go]: ack

File: domain/model/errors/errors.go [hunk 13]
```diff
@@ -34,6 +34,10 @@ const (
 	// a model is not considered valid.
 	CredentialNotValid = errors.ConstError("model credential not valid")
 
+	// CredentialNotFound describes an error that occurs when the credential for
+	// a model is not found.
+	CredentialNotFound = errors.ConstError("credential not found")
```
Comment (tlm) [inline domain/model/errors/errors.go]: I know you won't enjoy this but can you delete this as it is a double up and use the NotFound error from the credential domain.

File: domain/model/service/service.go [hunk 14]
```diff
@@ -575,6 +580,25 @@ func (s *Service) UpdateCredential(
...
 }
 
+// DefaultCloudCredentialKeyForOwner returns the owner's valid (and non-revoked) credential key for a given cloud
+// if only one credential exists. If owner has multiple valid cloud credentials a NotFound error is returned as
+// we cannot determine the default credential.
+func (s *Service) DefaultCloudCredentialKeyForOwner(ctx context.Context, owner coreuser.Name, cloudName string) (credential.Key, error) {
+	ctx, span := trace.Start(ctx, trace.NameFromFunc())
+	defer span.End()
+
+	label, err := s.st.DefaultCloudCredentialLabelForOwner(ctx, owner, cloudName)
```
Comment (tlm) [inline domain/model/service/service.go]: Why did we pick label here? Name would have been better and matches the rest of the naming we have.

File: domain/model/state/controller/state.go [hunk 15]
```diff
@@ -2176,3 +2176,53 @@ WHERE uuid = $dbModelUUID.uuid;`,
...
+// we cannot determine the default credential.
+func (st *State) DefaultCloudCredentialLabelForOwner(ctx context.Context, owner user.Name, cloudName string) (string, error) {
+	db, err := st.DB(ctx)
+	if err != nil {
+		return "", errors.Capture(err)
+	}
+
+	var credNames []dbName
+	credQuery := `
+SELECT DISTINCT (cc.name) AS (&dbName.*)
```
Comment (tlm) [inline domain/model/state/controller/state.go]: Selecting on this view requires the distinct and a lot of joins for no reason. Selecting off of `v_cloud_credential` instead avoids this.

File: domain/model/state/controller/state.go [hunk 16]
```diff
@@ -2176,3 +2176,53 @@ WHERE uuid = $dbModelUUID.uuid;`,
...
+// DefaultCloudCredentialLabelForOwner returns the owner's default cloud credential label for a given
+// cloud. If user has multiple (or no) credentials for the specified cloud a NotFound error is returned as
+// we cannot determine the default credential.
+func (st *State) DefaultCloudCredentialLabelForOwner(ctx context.Context, owner user.Name, cloudName string) (string, error) {
+	db, err := st.DB(ctx)
+	if err != nil {
+		return "", errors.Capture(err)
+	}
+
+	var credNames []dbName
```
Comment (tlm) [inline domain/model/state/controller/state.go]: We already have a type in this domain ready to go for this `dbCredKey`.

File: domain/model/state/controller/state.go [hunk 17]
```diff
@@ -2176,3 +2176,53 @@ WHERE uuid = $dbModelUUID.uuid;`,
...
+			return errors.Errorf("loading cloud credentials: %w", err)
+		}
+		return nil
+	})
+	if err != nil {
+		return "", errors.Capture(err)
+	}
+
+	if len(credNames) != 1 {
+		return "", modelerrors.CredentialNotFound
```
Comment (tlm) [inline domain/model/state/controller/state.go]: You need to add context to this with New or Errorf. It is not good enough to just return the error.

**Review by tlm — APPROVED** [review]

File: domain/model/errors/errors.go (hunk 13 above)
Comment (alesstimec) [reply domain/model/errors/errors.go]: done

File: domain/model/service/service.go (hunk 14 above)
Comment (alesstimec) [reply domain/model/service/service.go]: done

File: domain/model/state/controller/state.go (hunk 16 above)
Comment (alesstimec) [reply domain/model/state/controller/state.go]: done

File: domain/model/state/controller/state.go (hunk 17 above)
Comment (alesstimec) [reply domain/model/state/controller/state.go]: done, ptal
