### PR TITLE
fix: handle empty credential for kill-controller

### LINKED ISSUE #21479: juju cli Panic when trying to kill a controller
### Description

trying to kill a juju controller results in the panic of the juju CLI:

```
juju --debug kill-controller lxd --no-prompt -t 0s
12:15:02 INFO  juju.cmd supercommand.go:56 running juju [3.6.12 d8a727fd219fea140f915a24ac267cc7b64e751a gc go1.25.4]
12:15:02 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/33252/bin/juju", "--debug", "kill-controller", "lxd", "--no-prompt", "-t", "0s"}
12:15:02 INFO  juju.juju api.go:90 connecting to API addresses: [10.206.54.30:17070]
12:15:02 DEBUG juju.api apiclient.go:1089 successfully dialed "wss://10.206.54.30:17070/api"
12:15:02 INFO  juju.api apiclient.go:610 connection established to "wss://10.206.54.30:17070/api"
12:15:02 INFO  juju.juju api.go:90 connecting to API addresses: [10.206.54.30:17070]
12:15:02 DEBUG juju.api apiclient.go:1089 successfully dialed "wss://10.206.54.30:17070/api"
12:15:02 INFO  juju.api apiclient.go:610 connection established to "wss://10.206.54.30:17070/api"
12:15:02 INFO  cmd kill.go:161 Destroying controller "lxd"
Waiting for resources to be reclaimed
12:15:02 INFO  cmd kill.go:233 Killing sunbeam/openstack directly
12:15:02 DEBUG juju.kubernetes.provider provider.go:164 opening model "openstack".
12:15:04 WARN  juju.cmd.juju.controller kill.go:266 unable to determine model label version for namespace "openstack": Get "https://192.167.98.137:6443/api/v1/namespaces/openstack": dial tcp 192.167.98.137:6443: connect: no route to host
12:15:04 INFO  cmd kill.go:233 Killing sunbeam/openstack-machines directly
12:15:04 DEBUG juju.api monitor.go:35 RPC connection died
12:15:04 DEBUG juju.api monitor.go:35 RPC connection died
12:15:04 DEBUG juju.rpc server.go:343 error closing codec: write tcp 10.206.54.1:45084->10.206.54.30:17070: write: broken pipe
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x239f91b]

goroutine 1 [running]:
github.com/juju/juju/cmd/juju/controller.transformModelCloudSpecForInstanceRoles({_, _}, {{0xc000ffa480, 0x6}, {0xc000ffa488, 0x8}, {0xc000ffa490, 0x7}, {0xc000ffa4a0, 0xc}, ...}, ...)
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/cmd/juju/controller/kill.go:296 +0x5b
github.com/juju/juju/cmd/juju/controller.(*killCommand).DirectDestroyRemaining(0xc000645c20, 0xc000b4c8a0, {0x7363bb0, 0xc000142b00}, {{0xc0011f4ab8, 0x3}, {0xc0011f4aa0, 0x9}, {0xc0011f4ad0, 0x9}, ...})
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/cmd/juju/controller/kill.go:247 +0x478
github.com/juju/juju/cmd/juju/controller.(*killCommand).Run(0xc000645c20, 0xc000b4c8a0)
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/cmd/juju/controller/kill.go:171 +0x9f8
github.com/juju/juju/cmd/modelcmd.(*controllerCommandWrapper).Run(0xc000641020, 0xc000b4c8a0)
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/cmd/modelcmd/controller.go:403 +0xf1
github.com/juju/juju/cmd/modelcmd.(*baseCommandWrapper).Run(0xc0000d3270, 0xc000b4c8a0)
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/cmd/modelcmd/base.go:571 +0x95
github.com/juju/cmd/v3.(*SuperCommand).Run(0xc000280160, 0xc000b4c8a0)
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/vendor/github.com/juju/cmd/v3/supercommand.go:557 +0x369
github.com/juju/cmd/v3.Main({0x735d230, 0xc000280160}, 0xc000b4c8a0, {0xc000b4ca20, 0x6, 0x6})
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/vendor/github.com/juju/cmd/v3/cmd.go:468 +0x232
github.com/juju/juju/cmd/juju/commands.jujuMain.Run({0xc000142500?}, {0xc0000b4070, 0x7, 0x7})
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/cmd/juju/commands/main.go:214 +0xa07
github.com/juju/juju/cmd/juju/commands.Main(...)
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/cmd/juju/commands/main.go:124
main.main()
	/build/snapcraft-juju-d777f81320d9c4ab00979d9c7321b1c7/parts/juju/build/cmd/juju/main.go:29 +0x6c
```

### Juju version

3.6.12

### Cloud

_No response_

### Expected behaviour

Juju should be able to kill the controller, or at least not panic and fail gracefully.

### Reproduce / Test

My setup:
- Laptop running a Juju controller as a LXD container, bootstrapped with:
`juju bootstrap localhost lxd --config apt-http-proxy=http://10.206.54.1:3128 --config apt-https-proxy=http://10.206.54.1:3128 --model-default apt-http-proxy=http://10.206.54.1:3128 --model-default apt-https-proxy=http://10.206.54.1:3128 --config caas-image-repo="ghcr.io/juju"`
- A LXD VM on the same laptop, with a Sunbeam deployed using a remote controller
- The sunbeam client will register the host as a manual cloud and deploy k8s and register this k8s as a k8s cloud on the remote controller
- delete the VM
- try to destroy the controller `juju --debug kill-controller lxd --no-prompt -t 0s`

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by wallyworld**
In some cases, it's possible that there's no cloud credential known when killing a controller.
There's a code path where the credential type is used to perform a check. If there's no credential, the check can be skipped. This PR makes that trivial change.

## QA steps

Fix is trivial - added a unit test.

## Links

**Issue:** Fixes #21479.

**Jira card:** [JUJU-8990](https://warthogs.atlassian.net/browse/JUJU-8990)

[JUJU-8990]: https://warthogs.atlassian.net/browse/JUJU-8990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: cmd/juju/controller/kill_test.go [hunk 1]
```diff
@@ -384,6 +385,31 @@ func (s *KillSuite) TestKillWithAPIConnection(c *gc.C) {
...
+	s.api.envStatus[test1UUID] = m1
+	_, err := s.runKillCommand(c, "test1", "--no-prompt", "-t", "0")
+	c.Assert(err, jc.ErrorIsNil)
+	s.api.CheckCallNames(c, "DestroyController", "AllModels", "ModelStatus", "HostedModelConfigs", "ControllerConfig", "Close")
+	destroyStorage := true
+	s.api.CheckCall(c, 0, "DestroyController", apicontroller.DestroyControllerParams{
+		DestroyModels:  true,
+		DestroyStorage: &destroyStorage,
+	})
+	checkControllerRemovedFromStore(c, "test1", s.store)
```
Comment (CodingCookieRookie) [inline cmd/juju/controller/kill_test.go]: nit: perhaps this could be renamed to assertControllerRemovedFromStore to be clearer as a drive-by since the underlying implementation uses an assert

**Review by CodingCookieRookie — APPROVED** [review]
LGTM thanks ian!

File: cmd/juju/controller/kill_test.go (hunk 1 above)
Comment (wallyworld) [reply cmd/juju/controller/kill_test.go]: sure
