### PR TITLE
fix(k8s): filter invalid kubeconfig contexts from local clouds

### LINKED ISSUE #21715: Cannot bootstrap Juju: "cloud name not valid"
### Description

```
controlplane:~$ juju clouds --client
Since Juju 3 is being run for the first time, it has downloaded the latest public cloud information.
Only clouds with registered credentials are shown.
There are more clouds, use --all to see them.
You can bootstrap a new controller using one of these clouds...

Clouds available on the client:
Cloud                        Regions  Default    Type  Credentials  Source    Description
kubernetes-admin@kubernetes  0                   k8s   0            built-in  A local Kubernetes context
localhost                    1        localhost  lxd   0            built-in  LXD Container Hypervisor
controlplane:~$ juju bootstrap k8s jujuc-k8s
ERROR unknown cloud "k8s", please try "juju update-public-clouds"
controlplane:~$ juju bootstrap jujuc-k8s
ERROR unknown cloud "jujuc-k8s", please try "juju update-public-clouds"
controlplane:~$ juju bootstrap kubernetes-admin@kubernetes jujuc-k8s
ERROR cloud name "kubernetes-admin@kubernetes" not valid
controlplane:~$ juju bootstrap
Clouds
aws
aws-china
aws-gov
azure
azure-china
equinix
google
kubernetes-admin@kubernetes
localhost
oracle

Select a cloud [localhost]: kubernetes-admin@kubernetes

ERROR cloud name "kubernetes-admin@kubernetes" not valid
```

### Juju version

3.6.14

### Cloud

Kubernetes

### Expected behaviour

Given that `juju clouds --client` yields the `kubernetes-admin@kubernetes` name, and so does the interactive version of `juju bootstrap`, I would expect `juju bootstrap kubernetes-admin@kubernetes jujuc-k8s` to just work.

### Reproduce / Test

```
$ juju bootstrap kubernetes-admin@kubernetes jujuc-k8s
```

### Notes & References

Tried this in https://killercoda.com/playgrounds/scenario/kubernetes

### PR DESCRIPTION
**Pull request by kooltuoehias**
When parsing `~/.kube/config` to discover local Kubernetes clouds, Juju would previously include contexts with names that violate Juju's strict cloud naming requirements (e.g., names containing `@` or `_`). This caused subsequent commands like `juju bootstrap` or `juju clouds` to either display unusable options or fail with validation errors.

This PR updates the `CloudsFromKubeConfigContextsWithParams` parsing logic to silently filter out any context names that do not pass `names.IsValidCloud()`. A unit test is also included to ensure contexts like `kubernetes-admin@kubernetes` are properly ignored while valid names are successfully registered.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

add specific unit test to cover this scenario

## Links

Issue: Fixes #21715

**Jira card:** [JUJU-9151](https://warthogs.atlassian.net/browse/JUJU-9151)

[JUJU-9151]: https://warthogs.atlassian.net/browse/JUJU-9151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: caas/kubernetes/cloud/cloud.go [hunk 1]
```diff
@@ -74,6 +75,9 @@ func CloudsFromKubeConfigContextsWithParams(
 ) ([]cloud.Cloud, error) {
 	clouds := []cloud.Cloud{}
 	for ctxName := range config.Contexts {
+		if !names.IsValidCloud(ctxName) {
```
Comment (hpidcock) [inline caas/kubernetes/cloud/cloud.go:81]: This should probably provide some debug log so a user could figure out why their context is filtered out.

File: caas/kubernetes/cloud/cloud.go [hunk 2]
```diff
@@ -11,6 +11,7 @@ import (
 	clientcmdapi "k8s.io/client-go/tools/clientcmd/api"
 
 	"github.com/juju/juju/cloud"
+	"github.com/juju/names/v5"
```
Comment (hpidcock) [inline caas/kubernetes/cloud/cloud.go]: This is an external import, so it needs to be in the stanza above.

File: caas/kubernetes/cloud/cloud.go (hunk 1 above)
Comment (kooltuoehias) [reply caas/kubernetes/cloud/cloud.go:81]: > This should probably provide some debug log so a user could figure out why their context is filtered out.

Thanks for the comment, I will update this today.

File: caas/kubernetes/cloud/cloud.go (hunk 2 above)
Comment (kooltuoehias) [reply caas/kubernetes/cloud/cloud.go]: > This is an external import, so it needs to be in the stanza above.

I thought I had ran gci but apparently I didn't , will change it today. Thanks for the comment and I am sorry for being careless again ;)

File: caas/kubernetes/cloud/cloud.go [hunk 3]
```diff
@@ -74,6 +78,10 @@ func CloudsFromKubeConfigContextsWithParams(
 ) ([]cloud.Cloud, error) {
 	clouds := []cloud.Cloud{}
 	for ctxName := range config.Contexts {
+		if !names.IsValidCloud(ctxName) {
+			logger.Debugf("ignoring context %1v because it is not a valid cloud name", ctxName)
```
Comment (wallyworld) [inline caas/kubernetes/cloud/cloud.go]: nit: this can be `%q`  so we get `ignoring context "foo"  because...`

Comment (kooltuoehias) [reply caas/kubernetes/cloud/cloud.go]: > nit: this can be `%q` so we get `ignoring context "foo" because...`

Thanks, I updated the code.
