### PR TITLE
fix(sort): return insertion sorting to spaces, tags and zone

### LINKED ISSUE #22017: juju 4 and juju 3 spaces,tags,zones ordering
### Description

juju 4 reorders the spaces in the constraints, and juju 3 doesn't.
`juju deploy ubuntu-lite --constraints "spaces=public,management" asdas`

juju 3:
```
[2:29:52] ➜  jimm git:(v3) ✗ juju show-application asdas                                           
asdas:
  charm: ubuntu-lite
  base: ubuntu@24.04
  channel: latest/stable
  constraints:
    arch: amd64
    spaces:
    - public
    - management
  principal: true
  exposed: false
  remote: false
  life: alive
  endpoint-bindings:
    "": alpha
    ubuntu: alpha
```

juju 4:
```
[2:19:59] ➜  jimm git:(v3) ✗ juju show-application asdas                                           
asdas:
  charm: ubuntu-lite
  base: ubuntu@24.04
  channel: latest/stable
  constraints:
    arch: amd64
    spaces:
    - management
    - public
  principal: true
  exposed: false
  remote: false
  life: alive
  endpoint-bindings:
    "": alpha
    juju-info: alpha
    ubuntu: alpha
```

This is not done in the client, it's done in the controller from my initial testing.

### Juju version

4.0.4

### Cloud

_No response_

### Expected behaviour

.

### Reproduce / Test

Commands to create the lxc network:
```
sudo lxc network create public-br ipv4.address=10.170.80.1/24 ipv4.nat=true ipv6.address=none ipv6.nat=false
sudo lxc network create management-br ipv4.address=10.150.40.1/24 ipv4.nat=true ipv6.address=none ipv6.nat=false
```

```
juju add-space management 10.150.40.0/24
juju add-space public "10.170.80.0/24"
```

```
juju deploy ubuntu-lite --constraints "spaces=public,management" asdas
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by SimoneDutto**
# Description

Fix #22017.

Sort spaces, tags, and zone by insertion order. This is achieved by sorting by row_id in the view and using a slice with a `seen` map to avoid duplicates. We need the filtering over duplicates is that the LEFT JOIN is doing a Cartesian product of all zones, tags and spaces combinations.

The reason why we need this sorting is because the Juju Terraform implements a semantic comparison for constraints to make sure to require replace of an application is a drift is detected (See https://github.com/SimoneDutto/terraform-provider-juju/blob/use-juju-4-edge/internal/provider/custom_type_constraints.go#L170).

# QA

```
juju bootstrap lxd test-spaces
juju add-model test
juju add-space management  "10.170.90.0/24"
juju add-space public "10.170.80.0/24"
juju deploy ubuntu-lite --constraints "spaces=public,management" asdas
```

```
juju show-application asdas
```

Before returned spaces in a random order.

Now it returns the spaces always in insertion order.

### CODE REVIEW

**Comment by alesstimec** [comment]
As @kian99 stated, the code looks OK. I am not fond of server side sorting if it does not change the semantic meaning of the result. Sorting can be done by the client that cares about the order of returned items. This also means slightly less load on the server in cases where the list to be sorted is long.

**Comment by SimoneDutto** [comment]
> The correct way to solve this is to do this in state layer.
> 
> https://github.com/juju/juju/blob/ec7a96bd14de5736aa070c904ecd99419e9ca8d0/domain/application/state/application.go#L2758-L2762

Sorting in the state layer wouldn't really solve it because later one we use sets and maps to `decodeConstraints` and it would still randomly order the output of stuff. So we would also need to change this method to preserve the order. Right?

Since Terraform is the only one caring about the semantic equality do we really need to put the burden of sorting in the API server. Just sorting in the `String()` method (client-side) should be OK.
What do you think?

**Comment by SimoneDutto** [comment]
I've amended the description with the new  approach, dismissing approvals and asking for re-review.

File: domain/application/state/application.go [hunk 1]
```diff
@@ -3180,10 +3179,13 @@ func decodeConstraints(cons applicationConstraints) constraints.Constraints {
 		return res
 	}
 
-	// Unique spaces, tags and zones:
-	spaces := make(map[string]constraints.SpaceConstraint)
-	tags := set.NewStrings()
-	zones := set.NewStrings()
+	// Unique spaces, tags and zones, preserving insertion order:
+	var spaces []constraints.SpaceConstraint
+	seenSpaces := make(map[string]bool)
```
Comment (SimonRichardson) [inline domain/application/state/application.go]:
```suggestion
	seenSpaces := make(map[string]struct{})
```

We don't have to pay the cost of the bool, we can just use the presence of the value in the map to indicate if it's been seen before.

Comment (SimoneDutto) [reply domain/application/state/application.go]: ok

Comment (SimoneDutto) [reply domain/application/state/application.go]: done

File: domain/application/state/application.go
Comment (hpidcock) [inline domain/application/state/application.go:2831]: Update the comment here to document the sorted behaviour. Now it forms a part of the contract.

File: domain/application/state/application.go [hunk 2]
```diff
@@ -3228,34 +3230,37 @@ func decodeConstraints(cons applicationConstraints) constraints.Constraints {
...
-		res.Tags = &tagsSlice
+	if len(tagsList) > 0 {
+		res.Tags = &tagsList
 	}
-	if len(zones) > 0 {
-		zonesSlice := zones.SortedValues()
-		res.Zones = &zonesSlice
+	if len(zonesList) > 0 {
+		res.Zones = &zonesList
 	}
```
Comment (hpidcock) [inline domain/application/state/application.go:3350]: Use slices, no need for the maps. Since they are apparently already sorted, you can use `slices.Compact`.

File: domain/application/state/application.go
Comment (hpidcock) [inline domain/application/state/application.go:3257]: Update the comment to require that the argument passed in is already sorted.

File: domain/application/state/application_test.go [hunk 3]
```diff
@@ -3435,6 +3435,49 @@ func (s *applicationStateSuite) TestSetConstraintsReplacesPreviousSameZone(c *tc
...
+			{"gamma-uuid", "gamma"},
+			{"beta-uuid", "beta"},
+			{"aaa-uuid", "aaa"},
+		} {
+			if _, err := tx.ExecContext(ctx, "INSERT INTO space (uuid, name) VALUES (?, ?)", sp.uuid, sp.name); err != nil {
+				return err
+			}
+		}
+		return nil
+	})
```
Comment (hpidcock) [inline domain/application/state/application_test.go]: We can avoid multi-statement transactions in tests.
```suggestion
	for _, sp := range []struct{ uuid, name string }{
		{"gamma-uuid", "gamma"},
		{"beta-uuid", "beta"},
		{"aaa-uuid", "aaa"},
	} {
		err := s.DB().ExecContext(c.Context(), "INSERT INTO space (uuid, name) VALUES (?, ?)", sp.uuid, sp.name)
		c.Assert(err, tc.ErrorIsNil)
	}
```

File: domain/application/state/application.go (hunk 2 above)
Comment (SimoneDutto) [reply domain/application/state/application.go:3350]: I don't think it would work, slices.Compact() removes consecutive duplicates.

In this specific case it could happen something like:
`zone1,space1`
`zone2,space1`
`zone1,space2`

in which case `slices.Compat` would leave us with `zone1,zone2,zone1` right?

File: domain/application/state/application.go
Comment (SimoneDutto) [reply domain/application/state/application.go:2831]: done

Comment (SimoneDutto) [reply domain/application/state/application.go:3257]: done

File: domain/application/state/application.go (hunk 2 above)
Comment (SimonRichardson) [reply domain/application/state/application.go:3350]: You should always do a sort before a `slices.Compat`, but I get what you're saying.

Comment (SimoneDutto) [reply domain/application/state/application.go:3350]: if i do a sort, i loose the insertion order

File: domain/application/state/application.go [hunk 4]
```diff
@@ -3312,34 +3316,37 @@ func decodeConstraints(cons applicationConstraints) constraints.Constraints {
...
+					Exclude:   row.SpaceExclude.Bool,
+				})
 			}
 		}
 		if row.Tag.Valid {
-			tags.Add(row.Tag.String)
+			if _, ok := seenTags[row.Tag.String]; !ok {
+				seenTags[row.Tag.String] = struct{}{}
+				tagsList = append(tagsList, row.Tag.String)
+			}
```
Comment (kian99) [inline domain/application/state/application.go:3331]: So tag names, spaces names and zone names are all unique? And that's why we use the seen map?

Comment (SimoneDutto) [reply domain/application/state/application.go:3331]: the seen map is to make sure the returned list contains unique values, yes
