### PR TITLE
fix(uniter): add support for peer relations in Uniter API

### LINKED ISSUE #20590: Deployment failed because of peer relation-created failed
### Description

The deployment of the Kyuubi-k8s charm is triggering a failure of peer relation created event.

```
Model  Controller          Cloud/Region        Version    Timestamp
t1     microk8s-localhost  microk8s/localhost  4.0-beta6  11:13:23+02:00

App         Version  Status   Scale  Charm       Channel     Rev  Address  Exposed  Message
kyuubi-k8s  1.10     waiting      3  kyuubi-k8s  3.4/stable  113           no       waiting for units to settle down

Unit           Workload  Agent  Address  Ports      Message
kyuubi-k8s/0   blocked   idle            10009/tcp  Missing integration hub relation
kyuubi-k8s/1   blocked   idle            10009/tcp  Missing integration hub relation
kyuubi-k8s/2*  error     idle                       hook failed: "refresh-v-three-relation-created"
```

### Juju version

4.0.0

### Cloud

Kubernetes

### Expected behaviour

The charm should be deployed with no errors and be into blocked status after the initial setup phase.

### Reproduce / Test

```
juju deploy kyuubi-k8s -n 3 --channel=3.4/stable --trust
```

This results in this error in the debug-log: 

```
unit-kyuubi-k8s-2: 10:03:24 ERROR unit.kyuubi-k8s/2.juju-log refresh-v-three:1: root:Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kyuubi-k8s-2/charm/src/charm.py", line 325, in <module>
    ops.main(KyuubiCharm)
  File "/var/lib/juju/agents/unit-kyuubi-k8s-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 356, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-kyuubi-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 500, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-kyuubi-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 313, in __init__
    self.charm = self._charm_class(self.framework)
  File "/var/lib/juju/agents/unit-kyuubi-k8s-2/charm/src/charm.py", line 104, in __init__
    self.refresh = charm_refresh.Kubernetes(
  File "/var/lib/juju/agents/unit-kyuubi-k8s-2/charm/venv/lib/python3.10/site-packages/charm_refresh/_main.py", line 1803, in __init__
    original_versions = _OriginalVersions.from_app_databag(self._relation.my_app_ro)
  File "/var/lib/juju/agents/unit-kyuubi-k8s-2/charm/venv/lib/python3.10/site-packages/charm_refresh/_main.py", line 502, in from_app_databag
    workload=databag["original_workload_version"],
  File "/var/lib/juju/agents/unit-kyuubi-k8s-2/charm/venv/lib/python3.10/site-packages/charm_json/_main.py", line 61, in __getitem__
    return self._freeze(json.loads(self._databag[key]))
  File "/var/lib/juju/agents/unit-kyuubi-k8s-2/charm/venv/lib/python3.10/site-packages/charm_/_main.py", line 112, in __getitem__
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['relation-get', '--format', 'json', '--relation', '1', 'original_workload_version', '', '--app']' returned non-zero exit status 1.
```

### Notes & References

Deployed on microk8s v1.32.4, Juju 4 beta6,  on a multipass instance.

### PR DESCRIPTION
**Pull request by gfouillet**
This patch fixes #20590 which prevents peer relation from being created. This was because the Uniter API doesn't return the "otherApplicationName" in case of peer relation, which causes various side effects, especially in `relation-get` and `relation-list` hook commands.

This fix simply returns the current application name as otherApplicationName for peer relation, since this type of relation is one self.

- Updated `Relation` in `apiserver/facades/agent/uniter/uniter.go` to handle scenarios where the `otherAppName` for peer relations defaults to the current application name when only one endpoint is present.
- Added a new test, `TestPeerRelation`, in `apiserver/facades/agent/uniter/uniter_test.go` to verify correct handling of peer relations. The test validates that the relation details, life, and endpoints are accurately processed and returned.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

Follow reproduce step from #20590 

## Links

**Jira card:** [JUJU-8517](https://warthogs.atlassian.net/browse/JUJU-8517)

[JUJU-8517]: https://warthogs.atlassian.net/browse/JUJU-8517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apiserver/facades/agent/uniter/uniter.go [hunk 1]
```diff
@@ -2204,6 +2209,10 @@ func (u *UniterAPI) prepareRelationResult(
 			otherAppName = v.ApplicationName
 		}
 	}
+	// In case of peer relation, the other application name is the current one
+	if len(rel.Endpoints) == 1 {
```
Comment (hpidcock) [inline apiserver/facades/agent/uniter/uniter.go]: This should be checking the relation scope == peer.

Comment (gfouillet) [reply apiserver/facades/agent/uniter/uniter.go]: Ok, I am good with that, but I will add an error if the otherAppName is not populated, to make future breakage easier to understand.
