### PR TITLE
fix: do not retry transaction rollbacks

### LINKED ISSUE #21187: [4/candidate] `Secret-get` fails: `cannot start a transaction within a transaction`
### Description

When deploying an example charm with Juju 4 release candidate, multiple occurrences of the following error can be seen and lead to failed startup:

```
unit-charmed-etcd-0: 13:29:08 WARNING unit.charmed-etcd/0.etcd-peers-relation-changed ERROR attempt count exceeded: cannot start a transaction within a transaction
unit-charmed-etcd-0: 13:29:08 ERROR unit.charmed-etcd/0.juju-log etcd-peers:0: root:Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-charmed-etcd-0/charm/src/charm.py", line 415, in <module>
    ops.main(EtcdOperatorCharm)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-0/charm/venv/lib/python3.12/site-packages/ops/__init__.py", line 356, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-0/charm/venv/lib/python3.12/site-packages/ops/_main.py", line 502, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-0/charm/venv/lib/python3.12/site-packages/ops/_main.py", line 315, in __init__
    self.charm = self._charm_class(self.framework)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-0/charm/src/charm.py", line 72, in __init__
    self.refresh = charm_refresh.Machines(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-0/charm/venv/lib/python3.12/site-packages/charm_refresh/_main.py", line 3032, in __init__
    charm.set_app_workload_version(self._pinned_workload_version)
  File "/var/lib/juju/agents/unit-charmed-etcd-0/charm/venv/lib/python3.12/site-packages/charm_/_main.py", line 606, in set_app_workload_version
    subprocess.run(["application-version-set", version], check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['application-version-set', '3.6.5']' returned non-zero exit status 1.
unit-charmed-etcd-2: 13:29:08 ERROR unit.charmed-etcd/2.juju-log etcd-peers:0: root:Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/venv/lib/python3.12/site-packages/ops/model.py", line 3637, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-charmed-etcd-2/secret-get', '--label', 'etcd-peers.charmed-etcd.app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/src/charm.py", line 415, in <module>
    ops.main(EtcdOperatorCharm)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/venv/lib/python3.12/site-packages/ops/__init__.py", line 356, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/venv/lib/python3.12/site-packages/ops/_main.py", line 502, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/venv/lib/python3.12/site-packages/ops/_main.py", line 315, in __init__
    self.charm = self._charm_class(self.framework)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/src/charm.py", line 60, in __init__
    self.cluster_manager = ClusterManager(state=self.state, workload=self.workload)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/src/managers/cluster.py", line 44, in __init__
    self.admin_password = self.state.cluster.internal_user_credentials.get(INTERNAL_USER, "")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/src/core/models.py", line 293, in internal_user_credentials
    if self.model and (password := self.model.root_password):
                                   ^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/src/core/models.py", line 288, in model
    return self.data_interface.build_model(self.relation.id) if self.relation else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/lib/charms/data_platform_libs/v1/data_interfaces.py", line 1700, in build_model
    return build_model(self.repository_type(self._model, relation, component), model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/lib/charms/data_platform_libs/v1/data_interfaces.py", line 1782, in build_model
    return model.model_validate(data, context={"repository": repository})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/venv/lib/python3.12/site-packages/pydantic/main.py", line 705, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/lib/charms/data_platform_libs/v1/data_interfaces.py", line 699, in extract_secrets
    secret = repository.get_secret(secret_group, secret_uri=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/lib/charms/data_platform_libs/v1/data_interfaces.py", line 1438, in get_secret
    return self.secrets.get(label=label, uri=secret_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/lib/charms/data_platform_libs/v1/data_interfaces.py", line 641, in get
    if secret.meta:
       ^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/lib/charms/data_platform_libs/v1/data_interfaces.py", line 536, in meta
    self._secret_meta = self._model.get_secret(label=self.label)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/venv/lib/python3.12/site-packages/ops/model.py", line 325, in get_secret
    content = self._backend.secret_get(id=id, label=label)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/venv/lib/python3.12/site-packages/ops/model.py", line 4023, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-charmed-etcd-2/charm/venv/lib/python3.12/site-packages/ops/model.py", line 3639, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR attempt count exceeded: cannot start a transaction within a transaction
```

### Juju version

4.0-rc1

### Cloud

LXD

### Expected behaviour

In previous versions such as 3.6.11, this error does not occur.

### Reproduce / Test

```
lxd init --auto
lxc network set lxdbr0 ipv6.address none
sudo snap install juju --channel 4/candidate
mkdir -p ~/.local/share
juju bootstrap localhost dev-controller
juju deploy charmed-etcd -n 3 --channel 3.6/stable
```

On cluster startup, the issue occurs.

### Notes & References

Full debug logs of the deployment test:
[juju_4_controller_model.log](https://github.com/user-attachments/files/23524965/juju_4_controller_model.log)
[juju_4_charm_model.log](https://github.com/user-attachments/files/23524964/juju_4_charm_model.log)

### PR DESCRIPTION
**Pull request by manadart**
This patch addresses observations of the following errors:
- `transaction has already been committed or rolled back`
- `cannot start a transaction within a transaction`

We no longer apply a retry strategy to rollbacks. The first call to commit or rollback marks the transaction as done whether or not an error is returned, so retrying is pointless.

Rollbacks are now traced in the same fashion as commits.

If we get a transaction-in-transaction error, we attempt a hard `ROLLBACK` against the database directly. From observation it is possible to get into this state when Dqlite is performing a checkpoint operation. LXD uses the same strategy. This is should avoid ending up with a poisoned database. We return a const error when this situation is encountered, so that the tracker worker may detect it and take its own action if we deem that appropriate in the future.

Both commit and rollback ignore errors if the transaction is indicated as done due to context cancellation.

## QA steps

I could previously get these errors reliably during set-up and tear-down of a model with a reasonable workload.
- Bootstrap to LXD.
- `juju add-model work`.
- Begin streaming the debug-logs for the controller and workload models.
- `juju deploy charmed-etcd -n 3 --channel 3.6/stable`.
- Wait for all units to be idle.
- `juju remove-application charmed-etcd --no-prompt`.
- If any units do not remove themselves (model logs show an enter-scope error for them), remove them individually with `--force`.
- Once the application is gone, `juju destroy-model work --no-prompt`.
- Repeat.

## Links

**Issue:** Fixes #21187.

### CODE REVIEW

File: internal/database/txn/transaction.go [hunk 1]
```diff
@@ -167,39 +182,59 @@ func (t *RetryingTxnRunner) StdTxn(ctx context.Context, db *sql.DB, fn func(cont
...
+}
+
+// rollback, as with commit above facilitates tracing transaction rollbacks.
+func (t *RetryingTxnRunner) rollback(ctx context.Context, tx rollbackable) {
+	if t.logger.IsLevelEnabled(logger.TRACE) {
+		t.logger.Tracef(ctx, "running txn (id: %d) with query: ROLLBACK", ctx.Value(txnIDKey))
+	}
+
+	_, span := trace.Start(ctx, traceName("rollback"))
+	defer func() { span.End() }()
```
Comment (SimonRichardson) [inline internal/database/txn/transaction.go]: It would be nice to record the error here as well. That way when you're looking at the traces, we could see if it was for a particular reason (same as commit).

**Review by SimonRichardson — APPROVED** [review]

File: internal/database/txn/transaction.go [hunk 2]
```diff
@@ -23,15 +23,24 @@ import (
...
 )
 
-// committable represents a transaction interface that can be used for
-// committing a transaction.
+const (
+	DefaultTimeout = time.Second * 30
+	txnInTxn       = "cannot start a transaction within a transaction"
+
+	// ErrTxnInTxn is an error indicating that an attempt was made
+	// to start atransaction when we already had one in flight.
```
Comment (nvinuesa) [inline internal/database/txn/transaction.go]:
```suggestion
	// to start a transaction when we already had one in flight.
```

File: internal/database/txn/transaction.go [hunk 3]
```diff
@@ -167,39 +182,68 @@ func (t *RetryingTxnRunner) StdTxn(ctx context.Context, db *sql.DB, fn func(cont
 	return t.run(ctx, func(ctx context.Context) error {
 		tx, err := db.BeginTx(ctx, nil)
 		if err != nil {
+			// This was lifted from the LXD code.
+			// It has been observed that we can get into a strange state when
+			// Dqlite is busy performing a checkpoint operation.
+			// This is an attempt to save an otherwise poisoned database.
+			if strings.Contains(err.Error(), txnInTxn) {
+				_, _ = db.Exec("ROLLBACK")
```
Comment (nvinuesa) [inline internal/database/txn/transaction.go:190]: Shouldn't we at least log the error when trying to rollback?

File: internal/database/txn/transaction.go [hunk 4]
```diff
@@ -167,39 +182,68 @@ func (t *RetryingTxnRunner) StdTxn(ctx context.Context, db *sql.DB, fn func(cont
 	return t.run(ctx, func(ctx context.Context) error {
 		tx, err := db.BeginTx(ctx, nil)
 		if err != nil {
+			// This was lifted from the LXD code.
+			// It has been observed that we can get into a strange state when
+			// Dqlite is busy performing a checkpoint operation.
+			// This is an attempt to save an otherwise poisoned database.
```
Comment (nvinuesa) [inline internal/database/txn/transaction.go:188]: Since this error is an inconsistent state, maybe it should be part of a TODO so we remove it when/if dqlite fixes it.

File: internal/database/txn/transaction.go (hunk 1 above)
Comment (manadart) [reply internal/database/txn/transaction.go]: OK.

File: internal/database/txn/transaction.go (hunk 3 above)
Comment (manadart) [reply internal/database/txn/transaction.go:190]: If you can't roll back here, you're hosed for a while. You'll get a burst of transaction-in-transaction errors. It will be obvious.
