### PR TITLE
fix(remoterelationconsumer): clean up orphaned offer_connection when local relation is removed during registration

### LINKED ISSUE #21771: Offer connection count doesn't decrement correctly
### Description

On 3.6, when a CMR is established, removing a relation between an app and a consumed offer decrements the connection count as seen in the offering model (most of the time, sometimes we encounter a bug where the connection count doesn't decrement). I.e. the SAAS app still exists in the consuming model, but any relations to it have been removed.

In 4.0, after running `juju remove-relation` between the synthetic app and the local app, we can switch to the offering model and observe that the connection count has not changed. Even after removing the SAAS entirely with `juju remove-saas`, the connection count doesn't decrement.

This is related to https://github.com/juju/juju/issues/21766 but regardless of whether consuming models can be torn down with/without connections, the connection count should also be accurate.

### Juju version

Head of main (SHA 36710459c3)

### Cloud

LXD

### Expected behaviour

The connection count of an offer decrements when a relation is removed.

### Reproduce / Test

- juju add-model offering
- juju add-model consuming
- juju switch offering
- juju deploy juju-qa-dummy-source --config token=abc
- juju offer dummy-source:sink
- juju switch consuming
- juju deploy juju-qa-dummy-sink 
- juju relate dummy-sink admin/offering.dummy-source

The apps are successfully related. Then,
- juju switch offering
- Check the connection count in the offering model, it should be 1.
- juju switch consuming
- juju remove-relation dummy-source dummy-sink
- juju status --relations (wait for relation to be removed)
- juju switch offering
- juju status

Observe that the connection count is still 1. Removing the SAAS app in the consuming model also doesn't change anything.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
When a consuming model is destroyed, the removal worker may delete a CMR relation while the localConsumerWorker is registering it on the offering side. RegisterRemoteRelations succeeds (creating the offer_connection), but SaveMacaroonForRelation then fails with an FK constraint error because the local relation is gone. The macaroon is never cached, so no cleanup notification is ever sent, leaving the offer_connection permanently orphaned and the connection count stuck at 1/1.

Fix by immediately notifying the offering model with ForceCleanup when SaveMacaroonForRelation fails after a successful registration. Also add a shutdown notification path for relations with cached macaroons, and use background contexts in best-effort notification methods to avoid failures from cancelled catacomb contexts.

## QA steps

Bootstrap and add `offering` and `consuming` model with a CMR, then remove the consumer model before the unit reaches a idle status:

```
$ juju add-model offering
$ juju deploy juju-qa-dummy-source --config token=abc
$ juju offer dummy-source:sink
$ juju add-model consuming
$ juju deploy juju-qa-dummy-sink
$ juju relate dummy-sink admin/offering.dummy-source
# Don't wait until the unit gets to idle to:
$ juju destroy-model consuming
```
When you switch to the offering model, after a few moments you should see this status:
```
juju status --relations
Model     Controller  Cloud/Region         Version  Timestamp
offering  c           localhost/localhost  4.0.2.1  15:16:44+01:00

App           Version  Status       Scale  Charm                 Channel        Rev  Exposed  Message
dummy-source           maintenance      1  juju-qa-dummy-source  latest/stable    6  no       Started

Unit             Workload     Agent  Machine  Public address  Ports  Message
dummy-source/0*  maintenance  idle   0        10.42.73.62            Started

Machine  State    Address      Inst id        Base          AZ        Message
0        started  10.42.73.62  juju-4ee384-0  ubuntu@20.04  thinkpad  Running

Offer         Application   Charm         Rev  Connected  Endpoint  Interface    Role
dummy-source  dummy-source  dummy-source  6    0/0        sink      dummy-token  requirer
```
(see the `Connected` tab in the offer)
and also check the db:
```
repl (controller)> .switch model-offering
repl (model-offering)> select * from offer_connection
uuid	offer_uuid	remote_relation_uuid	username	

```

## Links

**Issue:** Fixes #21771.

**Jira card:** [JUJU-9194](https://warthogs.atlassian.net/browse/JUJU-9194)

[JUJU-9194]: https://warthogs.atlassian.net/browse/JUJU-9194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 1]
```diff
@@ -505,6 +523,97 @@ func (w *localConsumerWorker) handleRelationRemoved(ctx context.Context, relatio
...
+// publishRelationDyingForRemovedRelation notifies the offering model that a
+// relation has been removed from the consuming model. This handles the race
+// condition where the local removal worker deletes the relation before the
+// localConsumerWorker can send the dying notification via the normal
+// handleRelationConsumption → handleRelationDying path.
+// This is a best-effort notification: errors are logged but not propagated.
+// publishRelationDyingChange sends a ForceCleanup notification to the offering
+// model for a relation. This is a best-effort notification: errors are logged
+// but not propagated. Uses a fresh context since the catacomb context may be
+// cancelled.
```
Comment (kian99) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]: Removed the duplicated bit about this being best-effort.
```suggestion
// This is a best-effort notification: errors are logged but not propagated.
// publishRelationDyingChange sends a ForceCleanup notification to the offering
// model for a relation. Uses a fresh context since the catacomb context may be
// cancelled.
```

File: internal/worker/remoterelationconsumer/localconsumerworker_test.go [hunk 2]
```diff
@@ -2834,3 +2981,256 @@ func (s *localConsumerWorkerSuite) waitForWorkerStarted(c *tc.C, runner *worker.
 		}
 	}
 }
+
+// TestRelationRemovedNotifiesOfferingModel tests the fix for
+// https://github.com/juju/juju/issues/21771.
+// When the local removal worker deletes a CMR relation before the
+// localConsumerWorker can send the dying notification via the normal path,
```
Comment (kian99) [inline internal/worker/remoterelationconsumer/localconsumerworker_test.go:2979]: I'm not too clued up on everything, but it feels like a smell that the removal worker is allowed to race with other operations. It seems like a similar problem to storage where the removal worker would need to wait for certain things (I'm thinking like un-mounting a volume) to take place before it can proceed.

I'm not sure if there is a better approach as its all pretty complicated so no blocker from me, but it might be worth thinking about a way to block the removal logic until certain "required" operations are completed.

With the caveat that with all these things, you might never be able to complete the "best-effort" attempt to notify the other side so you need to stop retrying eventually. And similarly on the other side (the offerrer), if it doesn't receive some kind of heartbeat to say this connection is active, we might want it to eventually disconnect the consumer.

**Comment by kian99** [comment]
Ty for this btw!

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 3]
```diff
@@ -284,6 +292,7 @@ func (w *localConsumerWorker) loop() (err error) {
 	for {
 		select {
 		case <-w.catacomb.Dying():
+			w.notifyOfferingModelOnShutdown()
```
Comment (SimonRichardson) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]: We don't want to do this here. This is the wrong approach. We would want to know when we're going away *and* then fire it then. Adding it here, means that for any reason the worker goes away will notify the offering model that something happened, and that isn't right.

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 4]
```diff
@@ -145,6 +145,12 @@ type localConsumerWorker struct {
 	// consume the remote application to which this worker pertains.
 	offerMacaroon *macaroon.Macaroon
 
+	// relationMacaroons caches relation-specific macaroons obtained from
+	// registerConsumerRelation. These are used in handleRelationRemoved to
+	// notify the offering model when the consuming model's relation has
+	// already been deleted by the removal worker (race condition).
+	relationMacaroons map[corerelation.UUID]*macaroon.Macaroon
```
Comment (SimonRichardson) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]: We don't want a local cache, instead the workers have this already.

**Review by SimonRichardson — CHANGES_REQUESTED** [review]
Instead we want to inspect the workers as they hold the correct values:

```diff
diff --git a/internal/worker/remoterelationconsumer/localconsumerworker.go b/internal/worker/remoterelationconsumer/localconsumerworker.go
index 30fb87a6ff..fe1da8c3f6 100644
--- a/internal/worker/remoterelationconsumer/localconsumerworker.go
+++ b/internal/worker/remoterelationconsumer/localconsumerworker.go
@@ -6,6 +6,7 @@ package remoterelationconsumer
 import (
 	"context"
 	"fmt"
+	"strings"
 	"time"
 
 	"github.com/go-macaroon-bakery/macaroon-bakery/v3/bakery"
@@ -145,12 +146,6 @@ type localConsumerWorker struct {
 	// consume the remote application to which this worker pertains.
 	offerMacaroon *macaroon.Macaroon
 
-	// relationMacaroons caches relation-specific macaroons obtained from
-	// registerConsumerRelation. These are used in handleRelationRemoved to
-	// notify the offering model when the consuming model's relation has
-	// already been deleted by the removal worker (race condition).
-	relationMacaroons map[corerelation.UUID]*macaroon.Macaroon
-
 	consumerRelationUnitChanges chan consumerunitrelations.RelationUnitChange
 	offererRelationUnitChanges  chan offererunitrelations.RelationUnitChange
 	offererRelationChanges      chan offererrelations.RelationChange
@@ -197,8 +192,6 @@ func NewLocalConsumerWorker(config LocalConsumerWorkerConfig) (ReportableWorker,
 		consumeVersion:    config.ConsumeVersion,
 		offerMacaroon:     config.Macaroon,
 
-		relationMacaroons: make(map[corerelation.UUID]*macaroon.Macaroon),
-
 		remoteRelationClientGetter: config.RemoteRelationClientGetter,
 
 		consumerRelationUnitChanges: make(chan consumerunitrelations.RelationUnitChange),
@@ -258,6 +251,44 @@ func (w *localConsumerWorker) Report() map[string]interface{} {
 	return result
 }
 
+// PublishModelDying notifies the offering model that the consuming model is
+// dying, so that it can mark all relations to the remote application as dying.
+// This is a best-effort notification: errors are logged but not propagated.
+// Uses a fresh context since the catacomb context may be cancelled.
+func (w *localConsumerWorker) PublishModelDying(ctx context.Context) error {
+	for _, workerName := range w.runner.WorkerNames() {
+		if !isOffererUnitRelationWorker(workerName) {
+			continue
+		}
+
+		rw, err := w.runner.Worker(workerName, ctx.Done())
+		if errors.Is(err, errors.NotFound) {
+			continue
+		} else if err != nil {
+			return err
+		}
+
+		type RelationMacaroonGetter interface {
+			RelationUUID() corerelation.UUID
+			Macaroon() *macaroon.Macaroon
+		}
+
+		relationWorker, ok := rw.(RelationMacaroonGetter)
+		if !ok {
+			return errors.Errorf("worker %q is not a RelationMacaroonGetter", relationWorker)
+		}
+
+		w.publishRelationDyingChange(
+			relationWorker.RelationUUID(),
+			relationWorker.Macaroon(),
+			"model is dying",
+			"model dying",
+		)
+	}
+
+	return nil
+}
+
 func (w *localConsumerWorker) loop() (err error) {
 	ctx := w.catacomb.Context(context.Background())
 
@@ -292,7 +323,6 @@ func (w *localConsumerWorker) loop() (err error) {
 	for {
 		select {
 		case <-w.catacomb.Dying():
-			w.notifyOfferingModelOnShutdown()
 			return w.catacomb.ErrDying()
 
 		case changes, ok := <-relationsWatcher.Changes():
@@ -321,18 +351,9 @@ func (w *localConsumerWorker) loop() (err error) {
 				// change appropriately.
 				details, err := w.crossModelService.GetRelationDetails(ctx, relationUUID)
 				if errors.Is(err, relationerrors.RelationNotFound) {
-					// The relation has been removed from the local
-					// (consuming) model. Notify the offering model so
-					// it can clean up the offer_connection and
-					// associated data. This covers the race where the
-					// local removal worker deletes the relation before
-					// we can send the dying notification via the normal
-					// handleRelationConsumption path.
-					w.publishRelationDyingForRemovedRelation(ctx, relationUUID)
-
-					// Ensure that we don't have any workers still
-					// running for the removed relation.
-					if err := w.handleRelationRemoved(ctx, relationUUID, 0); err != nil {
+					// Ensure that we don't have any workers still running for
+					// the removed relation.
+					if err := w.handleRelationNotFound(ctx, relationUUID); err != nil {
 						// If we fail to remove the relation, we must kill the
 						// worker, as nothing will come around and try again.
 						// Thus, kill it and force the application worker to
@@ -495,6 +516,19 @@ func (w *localConsumerWorker) remoteOfferRemoved(ctx context.Context) error {
 	return nil
 }
 
+func (w *localConsumerWorker) handleRelationNotFound(ctx context.Context, relationUUID corerelation.UUID) error {
+	// The relation has been removed from the local (consuming) model. Notify
+	// the offering model so it can clean up the offer_connection and associated
+	// data. This covers the race where the local removal worker deletes the
+	// relation before we can send the dying notification via the normal
+	// handleRelationConsumption path.
+	if err := w.publishRelationDyingForRemovedRelation(ctx, relationUUID); err != nil {
+		return errors.Annotatef(err, "notifying offering model of removed relation %q", relationUUID)
+	}
+
+	return w.handleRelationRemoved(ctx, relationUUID, 0)
+}
+
 func (w *localConsumerWorker) handleRelationRemoved(ctx context.Context, relationUUID corerelation.UUID, inScopeUnits int) error {
 	w.logger.Debugf(ctx, "relation %q removed", relationUUID)
 
@@ -563,12 +597,22 @@ func (w *localConsumerWorker) publishRelationDyingChange(
 	}
 }
 
-func (w *localConsumerWorker) publishRelationDyingForRemovedRelation(_ context.Context, relationUUID corerelation.UUID) {
-	mac, ok := w.relationMacaroons[relationUUID]
-	if !ok {
-		return
+func (w *localConsumerWorker) publishRelationDyingForRemovedRelation(ctx context.Context, relationUUID corerelation.UUID) error {
+	offererUnitRelationWorker, err := w.runner.Worker(offererUnitRelationWorkerName(relationUUID), ctx.Done())
+	if err != nil {
+		return errors.Annotatef(err, "stopping offerer unit relation worker for %q", relationUUID)
+	} else if errors.Is(err, errors.NotFound) {
+		// If the worker doesn't exist, then it either hasn't been created yet,
+		// or has already been removed, in either case, we can skip sending the
+		// notification.
+		return nil
+	}
+
+	type MacaroonGetter interface {
+		Macaroon() *macaroon.Macaroon
 	}
-	defer delete(w.relationMacaroons, relationUUID)
+
+	mac := offererUnitRelationWorker.(MacaroonGetter).Macaroon()
 
 	w.publishRelationDyingChange(
 		relationUUID,
@@ -576,6 +620,8 @@ func (w *localConsumerWorker) publishRelationDyingForRemovedRelation(_ context.C
 		"relation %q removed locally, notifying offering model",
 		"removal",
 	)
+
+	return nil
 }
 
 // publishRelationDyingWithMacaroon sends a ForceCleanup notification to the
@@ -594,26 +640,6 @@ func (w *localConsumerWorker) publishRelationDyingWithMacaroon(relationUUID core
 	)
 }
 
-// notifyOfferingModelOnShutdown sends ForceCleanup notifications for all
-// relations that still have cached macaroons when the worker is shutting down.
-// Relations that had their dying notification sent successfully via the normal
-// path will have had their macaroons removed from the cache already.
-// This uses a fresh context since the catacomb context is cancelled on shutdown.
-func (w *localConsumerWorker) notifyOfferingModelOnShutdown() {
-	if len(w.relationMacaroons) == 0 || w.remoteModelClient == nil {
-		return
-	}
-
-	for relationUUID, mac := range w.relationMacaroons {
-		w.publishRelationDyingChange(
-			relationUUID,
-			mac,
-			"worker shutting down, notifying offering model about relation %q",
-			"on shutdown",
-		)
-	}
-}
-
 // handleConsumerRelationChange processes changes to the relation as recorded in
 // the local model when a change event arrives from the remote model.
 func (w *localConsumerWorker) handleConsumerRelationChange(ctx context.Context, details relation.RelationDetails) error {
@@ -706,12 +732,6 @@ func (w *localConsumerWorker) handleRelationConsumption(
 
 	w.logger.Debugf(ctx, "consumer relation registered for %q: %v", details.UUID, result)
 
-	// Cache the relation-specific macaroon so that it can be used to notify
-	// the offering model if the relation is removed locally before the
-	// localConsumerWorker can process the dying event (race with the removal
-	// worker).
-	w.relationMacaroons[details.UUID] = result.macaroon
-
 	// Start the remote relation worker to watch for offerer relation changes.
 	// The aim is to ensure that we can track the suspended status of the
 	// relation so we can correctly react to that.
@@ -738,10 +758,6 @@ func (w *localConsumerWorker) handleRelationConsumption(
 		if err := w.handleRelationDying(ctx, details.UUID, result.macaroon, !relationKnown); err != nil {
 			return err
 		}
-		// Clean up the cached macaroon since the offering model has been
-		// successfully notified via the normal path. This avoids sending
-		// a duplicate forced notification from handleRelationRemoved later.
-		delete(w.relationMacaroons, details.UUID)
 		return nil
 	}
 
@@ -1250,6 +1266,10 @@ func offererUnitRelationWorkerName(relationUUID corerelation.UUID) string {
 	return fmt.Sprintf("offerer-unit-relation:%s", relationUUID)
 }
 
+func isOffererUnitRelationWorker(name string) bool {
+	return strings.HasPrefix(name, "offerer-unit-relation:")
+}
+
 func offererRelationWorkerName(relationUUID corerelation.UUID) string {
 	return fmt.Sprintf("offerer-relation:%s", relationUUID)
 }
diff --git a/internal/worker/remoterelationconsumer/offererunitrelations/worker.go b/internal/worker/remoterelationconsumer/offererunitrelations/worker.go
index ffe71b09e6..ea731bd55f 100644
--- a/internal/worker/remoterelationconsumer/offererunitrelations/worker.go
+++ b/internal/worker/remoterelationconsumer/offererunitrelations/worker.go
@@ -185,6 +185,12 @@ func (w *remoteWorker) Wait() error {
 	return w.catacomb.Wait()
 }
 
+// Macaroon returns the macaroon used by this worker to authenticate with the
+// remote model.
+func (w *remoteWorker) Macaroon() *macaroon.Macaroon {
+	return w.macaroon
+}
+
 func (w *remoteWorker) loop() error {
 	ctx := w.catacomb.Context(context.Background())
 
diff --git a/internal/worker/remoterelationconsumer/worker.go b/internal/worker/remoterelationconsumer/worker.go
index 6b4b57a44a..151c1aee5d 100644
--- a/internal/worker/remoterelationconsumer/worker.go
+++ b/internal/worker/remoterelationconsumer/worker.go
@@ -49,6 +49,10 @@ type OffererApplicationWorker interface {
 	// ConsumeVersion returns the consume version for the remote application
 	// worker.
 	ConsumeVersion() int
+
+	// PublishModelDying notifies the worker that the model is dying, so it can
+	// perform any necessary cleanup.
+	PublishModelDying(ctx context.Context) error
 }
 
 // RemoteModelRelationsClient instances publish local relation changes to the
@@ -323,11 +327,19 @@ func (w *Worker) loop() (err error) {
 
 	// Watch for new remote application offerers. This is the consuming side,
 	// so the consumer model has received an offer from another model.
-	watcher, err := w.crossModelService.WatchRemoteApplicationOfferers(ctx)
+	offersWatcher, err := w.crossModelService.WatchRemoteApplicationOfferers(ctx)
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if err := w.catacomb.Add(offersWatcher); err != nil {
+		return errors.Trace(err)
+	}
+
+	modelWatcher, err := w.crossModelService.WatchDyingModel(ctx)
 	if err != nil {
 		return errors.Trace(err)
 	}
-	if err := w.catacomb.Add(watcher); err != nil {
+	if err := w.catacomb.Add(modelWatcher); err != nil {
 		return errors.Trace(err)
 	}
 
@@ -335,7 +347,13 @@ func (w *Worker) loop() (err error) {
 		select {
 		case <-w.catacomb.Dying():
 			return w.catacomb.ErrDying()
-		case _, ok := <-watcher.Changes():
+
+		case <-modelWatcher.Changes():
+			if err := w.handleModelDying(ctx); err != nil {
+				return errors.Trace(err)
+			}
+
+		case _, ok := <-offersWatcher.Changes():
 			if !ok {
 				return errors.New("change channel closed")
 			}
@@ -439,6 +457,30 @@ func (w *Worker) hasRemoteAppChanged(remoteApp crossmodelrelation.RemoteApplicat
 	return appWorker.ConsumeVersion() != 0, nil
 }
 
+func (w *Worker) handleModelDying(ctx context.Context) error {
+	w.logger.Debugf(ctx, "model is dying, stopping all offerer application workers")
+
+	for _, appUUID := range w.runner.WorkerNames() {
+		worker, err := w.runner.Worker(appUUID, ctx.Done())
+		if errors.Is(err, errors.NotFound) {
+			continue
+		} else if err != nil {
+			return errors.Trace(err)
+		}
+
+		appWorker, ok := worker.(OffererApplicationWorker)
+		if !ok {
+			return errors.Errorf("worker %q is not a OffererApplicationWorker", appWorker)
+		}
+
+		if err := appWorker.PublishModelDying(ctx); err != nil {
+			w.logger.Warningf(ctx, "error publishing model dying for worker %q: %v", appWorker, err)
+		}
+	}
+
+	return nil
+}
+
 // Report provides information for the engine report.
 func (w *Worker) Report() map[string]interface{} {
 	return w.runner.Report()
```

File: internal/worker/remoterelationconsumer/localconsumerworker.go (hunk 3 above)
Comment (nvinuesa) [reply internal/worker/remoterelationconsumer/localconsumerworker.go]: Applied your patch, which addresses this.

File: internal/worker/remoterelationconsumer/localconsumerworker.go (hunk 4 above)
Comment (nvinuesa) [reply internal/worker/remoterelationconsumer/localconsumerworker.go]: See https://github.com/juju/juju/pull/21802#discussion_r2840068206

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 5]
```diff
@@ -620,7 +749,10 @@ func (w *localConsumerWorker) handleRelationConsumption(
 	// Handle the case where the relation is dying, and ensure we have no
 	// workers still running for it.
 	if life.IsNotAlive(details.Life) {
-		return w.handleRelationDying(ctx, details.UUID, result.macaroon, !relationKnown)
+		if err := w.handleRelationDying(ctx, details.UUID, result.macaroon, !relationKnown); err != nil {
+			return err
+		}
+		return nil
```
Comment (kian99) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]:
```suggestion
		return w.handleRelationDying(ctx, details.UUID, result.macaroon, !relationKnown)
```

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 6]
```diff
@@ -827,6 +959,12 @@ func (w *localConsumerWorker) registerConsumerRelation(
 	// We have a new macaroon attenuated to the relation.
 	// Save for the firewaller.
 	if err := w.crossModelService.SaveMacaroonForRelation(ctx, relationUUID, registerResult.Macaroon); err != nil {
+		// If saving the macaroon fails because the local relation was deleted
+		// by the removal worker (FK constraint), the offer_connection was
+		// already created on the offering side by RegisterRemoteRelations
+		// above. Immediately notify the offering model to clean it up,
+		// using the macaroon we just received.
```
Comment (kian99) [inline internal/worker/remoterelationconsumer/localconsumerworker.go:966]: What if we fail to save the macaroon for another reason? Seems fine to still run `publishRelationDyingWithMacaroon`, but will the relation actually be cleaned up on the consuming side?

File: internal/worker/remoterelationconsumer/localconsumerworker_test.go [hunk 7]
```diff
@@ -2834,3 +2978,251 @@ func (s *localConsumerWorkerSuite) waitForWorkerStarted(c *tc.C, runner *worker.
...
+// the worker should use the cached macaroon to notify the offering model.
```
Comment (kian99) [inline internal/worker/remoterelationconsumer/localconsumerworker_test.go]: Does this comment about using a cached macaroon need to be updated?

**Review by kian99 — APPROVED** [review]
Ran the QA steps and it worked, the connection count reflected 0/0

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 8]
```diff
@@ -250,6 +251,44 @@ func (w *localConsumerWorker) Report() map[string]interface{} {
...
+		}
+
+		rw, err := w.runner.Worker(workerName, ctx.Done())
+		if errors.Is(err, errors.NotFound) {
+			continue
+		} else if err != nil {
+			return err
+		}
+
+		type RelationMacaroonGetter interface {
```
Comment (gfouillet) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]: **thought:** That's unusual, but I am fine with it

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 9]
```diff
@@ -250,6 +251,44 @@ func (w *localConsumerWorker) Report() map[string]interface{} {
...
+			RelationUUID() corerelation.UUID
+			Macaroon() *macaroon.Macaroon
+		}
+
+		relationWorker, ok := rw.(RelationMacaroonGetter)
+		if !ok {
+			return errors.Errorf("worker %q is not a RelationMacaroonGetter", workerName)
+		}
```
Comment (gfouillet) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]: **todo:** At least remove the concept of RelationMacaroonGetter from the error message, since it is a unexported type (local).

You can just specify in error message that relation worker need to expose both `RelationUUID` and `Macaroon` method to be valid.

**note:** there is no need of a local type, you can also directly cast with an anonymous interface:

```suggestion
		relationWorker, ok := rw.(interface {
			RelationUUID() corerelation.UUID
			Macaroon() *macaroon.Macaroon
		})
		if !ok {
			return errors.Errorf("worker %q is not a RelationMacaroonGetter", workerName)
		}
```

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 10]
```diff
@@ -505,6 +557,83 @@ func (w *localConsumerWorker) handleRelationRemoved(ctx context.Context, relatio
...
+		return nil
+	} else if err != nil {
+		return errors.Annotatef(err, "stopping offerer unit relation worker for %q", relationUUID)
+	}
+
+	type MacaroonGetter interface {
+		Macaroon() *macaroon.Macaroon
+	}
+
+	mac := offererUnitRelationWorker.(MacaroonGetter).Macaroon()
```
Comment (gfouillet) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]: **todo:** May panic. Inline interface and handle error by saying that the worker should expose a `Macaroon()` method

**Review by gfouillet — COMMENTED** [review]
I wonder what happens if the notification fails to be sent ? 
I mean, is there a mechanism which clean up such kind of leaks ?

In other word, what happens if the offerer is never notified of the death of a consuming model ? Has it a way to decide to cleanup anyway (like healthcheck are something like that) ?

**Comment by kian99** [comment]
> I wonder what happens if the notification fails to be sent ?
> I mean, is there a mechanism which clean up such kind of leaks ?

I was wondering the same thing. While I believe it's impossible to make such a mechanism without a reasonable time window, I don't think we need it. The issue in https://github.com/juju/juju/issues/21766 mentions that we should eventually be able to destroy a model with connected offers. Once that is true the connection count becomes purely informational. Perhaps we don't even display the connected count, as it's more of a "best effort" connection count anyway.

File: internal/worker/remoterelationconsumer/localconsumerworker.go (hunk 6 above)
Comment (SimonRichardson) [reply internal/worker/remoterelationconsumer/localconsumerworker.go:966]: If we get an error whilst saving the macaroon, we'll crash the worker which means we need to notify the offerer that the relation is dying. When the worker starts back up, it'll re-register the relation and we'll get another chance to save the macaroon.

This is correct.

Comment (SimonRichardson) [reply internal/worker/remoterelationconsumer/localconsumerworker.go:966]: It would be nice to test this workflow somehow so we can bake it in.

**Comment by SimonRichardson** [comment]
> I wonder what happens if the notification fails to be sent ?

It depends. If we error out, it will crash the worker and we'll re-register the CMR and start the process again.

> In other word, what happens if the offerer is never notified of the death of a consuming model ? Has it a way to decide to cleanup anyway (like healthcheck are something like that) ?

Not at the moment. Even if there is a health check, what is the outcome? We can't clean up the CMR, the network might be slow or other issues might occur. What happens if we remove a CMR and it then causes a database to be clean up. Ultimately the operator needs to take these actions (cleanups). CMRs do put an unexpected burden on the operator to ensure everything is running. Having said all that, I think it maybe it's possible to show a health of a CMR so that an operator might want to investigate if it starts to go bad. Simple checks, like last received message - if it's over 10 or 15 minutes, show amber, if it's 1 day, maybe red (I've picked these numbers out of thin air!). 

What we don't want to do is create a connection mesh for health checks, where offerers connect to consumers and vice-versa.

**Comment by gfouillet** [comment]
> > I wonder what happens if the notification fails to be sent ?
> 
> It depends. If we error out, it will crash the worker and we'll re-register the CMR and start the process again.
> 
> > In other word, what happens if the offerer is never notified of the death of a consuming model ? Has it a way to decide to cleanup anyway (like healthcheck are something like that) ?
> 
> Not at the moment. Even if there is a health check, what is the outcome? We can't clean up the CMR, the network might be slow or other issues might occur. What happens if we remove a CMR and it then causes a database to be clean up. Ultimately the operator needs to take these actions (cleanups). CMRs do put an unexpected burden on the operator to ensure everything is running. Having said all that, I think it maybe it's possible to show a health of a CMR so that an operator might want to investigate if it starts to go bad. Simple checks, like last received message - if it's over 10 or 15 minutes, show amber, if it's 1 day, maybe red (I've picked these numbers out of thin air!).
> 
> What we don't want to do is create a connection mesh for health checks, where offerers connect to consumers and vice-versa.

That's interesting. Maybe we should keep that subject in mind while we address observability in Juju. I believe that after having shift Juju 4 in a place where it is shiny production ready, we should provide a easy-to-plug easy-to-use observability dashboard or something... And known unhealthy things that requires operator to do something could be something we want address... 

(And in the future we will have observability agent, and then, skynet, and then :boom:

**Comment by SimonRichardson** [comment]
> I believe that after having shift Juju 4 in a place where it is shiny production ready, we should provide a easy-to-plug easy-to-use observability dashboard or something.

We have [COS-lite](https://charmhub.io/cos-lite) for this.

**Review by SimonRichardson — APPROVED** [review]
Thanks. This does what we want, but we'll need a follow up issue where the dummy-source application in the offering side ends up in an error state that is stuck. 

The error is a bit weird, as it's a permission on error.

```sh
Model     Controller  Cloud/Region       Version  Timestamp
offering  src         localhost/default  4.0.3.1  12:26:59Z

App           Version  Status  Scale  Charm                 Channel        Rev  Exposed  Message
dummy-source           error       1  juju-qa-dummy-source  latest/stable    6  no       hook failed: "sink-relation-joined"

Unit             Workload  Agent  Machine  Public address  Ports  Message
dummy-source/0*  error     idle   0        10.232.51.52           hook failed: "sink-relation-joined"

Machine  State    Address       Inst id        Base          AZ          Message
0        started  10.232.51.52  juju-2ea20e-0  ubuntu@20.04  simon-work  Running

Offer         Application   Charm                 Rev  Connected  Endpoint  Interface    Role
dummy-source  dummy-source  juju-qa-dummy-source  6    0/1        sink      dummy-token  requirer
```

```
unit-dummy-source-0: 12:26:48 DEBUG juju.worker.uniter.runner starting jujuc server {unix /var/lib/juju/agents/unit-dummy-source-0/agent.socket <nil>}
unit-dummy-source-0: 12:26:48 WARNING unit.dummy-source/0.sink-relation-joined + juju-log -l INFO 'Getting token'
unit-dummy-source-0: 12:26:48 INFO unit.dummy-source/0.juju-log sink:1: Getting token
unit-dummy-source-0: 12:26:48 WARNING unit.dummy-source/0.sink-relation-joined + status-set maintenance 'Getting token'
machine-0: 12:26:48 INFO juju.services.status.status-history status:maintenance,category:status-history,data:null,kind:workload,logger-tags:status-history,message:Getting token,namespace_id:dummy-source/0,since:2026-02-27T12:26:48Z status-history (status: "maintenance", status-message: "Getting token")
unit-dummy-source-0: 12:26:48 WARNING unit.dummy-source/0.sink-relation-joined ++ config-get token
unit-dummy-source-0: 12:26:48 WARNING unit.dummy-source/0.sink-relation-joined + token=iii
unit-dummy-source-0: 12:26:48 WARNING unit.dummy-source/0.sink-relation-joined ++ relation-ids sink
unit-dummy-source-0: 12:26:48 WARNING unit.dummy-source/0.sink-relation-joined + for relation_id in $(relation-ids sink)
unit-dummy-source-0: 12:26:48 WARNING unit.dummy-source/0.sink-relation-joined + relation-set -r sink:1 token=iii
unit-dummy-source-0: 12:26:48 WARNING unit.dummy-source/0.sink-relation-joined ERROR cannot read relation settings: permission denied
unit-dummy-source-0: 12:26:48 ERROR juju.worker.uniter.operation hook "sink-relation-joined" (via explicit, bespoke hook script) failed: exit status 1
```

Note: bouncing the controller fixes it :scream: 

We need a follow up issue for this please @nvinuesa

**Comment by nvinuesa** [comment]
> Note: bouncing the controller fixes it 😱

This is going to be fun. I'll create a separate issue for this and follow-up(s).

**Comment by nvinuesa** [comment]
@SimonRichardson how did you got to that error? I never reproduced it. This is the status at the end (after removing the consuming model):
```
juju status --relations --color 
Model     Controller  Cloud/Region         Version  Timestamp
offering  c           localhost/localhost  4.0.3.1  15:30:43+01:00

App           Version  Status  Scale  Charm                 Channel        Rev  Exposed  Message
dummy-source           active      1  juju-qa-dummy-source  latest/stable    6  no       Token is abc

Unit             Workload  Agent  Machine  Public address  Ports  Message
dummy-source/0*  active    idle   0        10.134.1.123           Token is abc

Machine  State    Address       Inst id        Base          AZ                                Message
0        started  10.134.1.123  juju-58a347-0  ubuntu@20.04  nvinuesa-ThinkPad-P16s-Gen-4-AMD  Running

Offer         Application   Charm                 Rev  Connected  Endpoint  Interface    Role
dummy-source  dummy-source  juju-qa-dummy-source  6    0/0        sink      dummy-token  requirer
```
