### PR TITLE
fix(operation): improve error handling for undefined charm actions

### LINKED ISSUE #21446: Exit code when running an invalid action changed in Juju 4
### Description

In 3.6, if you `juju run` an action that doesn't exist, you get an understandable error message and a zero (success) exit code. In 4.0.0, you get a difficult-to-understand error message and a non-zero exit code.

### Juju version

4.0.0

### Cloud

LXD

### Expected behaviour

The non-zero exit code makes sense to me (the command failed). However, @SimonRichardson suggested in https://github.com/canonical/jubilant/pulls/232 that this might not be an intentional change and asked for an issue.

Whether or not the exit code changes, if the message could be more similar to 3.6 that would definitely be a UX improvement.

### Reproduce / Test

On Juju 3.6:

```
$ juju deploy ubuntu
Deployed "ubuntu" from charm-hub charm "ubuntu", revision 26 in channel latest/stable on ubuntu@24.04/stable
$ juju actions ubuntu
No actions defined for ubuntu.
$ juju run ubuntu/0 something

Operation 1 failed to schedule any tasks:
no actions defined on charm "ch:amd64/ubuntu-26"
$ echo $?
0
```

On Juju 4.0.0:

```
$ juju deploy ubuntu
Deployed "ubuntu" from charm-hub charm "ubuntu", revision 26 in channel latest/stable on ubuntu@24.04/stable
$ juju actions ubuntu
No actions defined for ubuntu.
$ juju run ubuntu/0 something
ERROR adding action operation: adding action operation: inserting operation action: inserting action "something" for charm "a91d56d5-7dc3-421c-8518-9b80d8da6911" and operation "6d7eda9e-b44c-48f1-8e24-be8c2611eeb5"
$ echo $?
1
```

Similarly, if there's an action defined but you try to run something else:

Juju 3:

```
$ juju deploy ubuntu-lite
Deployed "ubuntu-lite" from charm-hub charm "ubuntu-lite", revision 4 in channel latest/stable on ubuntu@24.04/stable
$ juju actions ubuntu-lite
Action  Description
load    Report the current load on the machine
$ juju run ubuntu-lite/0 badaction

Operation 3 failed to schedule any tasks:
action "badaction" not defined on unit "ubuntu-lite/0"
$ echo $?
0
```

Juju 4.0.0:

```
$ juju deploy ubuntu-lite
Deployed "ubuntu-lite" from charm-hub charm "ubuntu-lite", revision 4 in channel latest/stable on ubuntu@24.04/stable
$ juju actions ubuntu-lite
Action  Description
load    Report the current load on the machine
$ juju run ubuntu-lite/0 badaction
ERROR adding action operation: adding action operation: inserting operation action: inserting action "badaction" for charm "668f379a-1ed9-476e-82c0-9d749c9f2334" and operation "3b4f83f0-72c9-4da3-862c-0107282f7f84"
$ echo $?
1
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by gfouillet**
This patch refines the handling of errors when actions are undefined for a charm.

Key changes include:
- Adding `ActionNotDefined` error type to provide detailed context (charm name, unit name, and action existence).
- Enhancing error propagation in `AddActionOperation` and related methods.
- Updating tests to cover scenarios where actions are missing, both with and without other actions defined in the charm.
- Refactoring error messages in the `apiserver` to improve clarity for end-users.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

bootstrap a controller, add a model.

```sh
juju deploy ubuntu foo
juju deploy juju-qa-test bar
```

Wait for everything fired up.

```sh
juju run foo/0 dontact
juju run bar/0 dontact
```

This should behave as in #21446  (clean error message), except it return a non zero exit code.

## Links

**Issue:** fixes #21446 .

**Jira card:** [JUJU-8967](https://warthogs.atlassian.net/browse/JUJU-8967)

[JUJU-8967]: https://warthogs.atlassian.net/browse/JUJU-8967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/operation/state/start.go [hunk 1]
```diff
@@ -143,6 +144,11 @@ func (st *State) AddActionOperation(ctx context.Context,
 		}
 
 		err = st.insertOperationAction(ctx, tx, operationUUID.String(), charmUUID, args.ActionName)
+		if notDefined, ok := errors.AsType[operationerrors.ActionNotDefined](err); ok {
```
Comment (SimonRichardson) [inline domain/operation/state/start.go]: Fancy.

File: apiserver/facades/client/action/operation.go [hunk 2]
```diff
@@ -95,6 +96,15 @@ func (a *ActionAPI) EnqueueOperation(ctx context.Context, arg params.Actions) (p
 	}
 
 	result, err := a.operationService.AddActionOperation(ctx, receivers, taskParams)
+	if notDefined, ok := errors.AsType[operationerrors.ActionNotDefined](err); ok {
+		if notDefined.HasActions {
+			return params.EnqueuedActions{}, apiservererrors.ServerError(errors.Errorf(
+				"action %q not defined for unit %q.", taskParams.ActionName, notDefined.UnitName))
+		}
+		return params.EnqueuedActions{}, apiservererrors.ServerError(errors.Errorf(
```
Comment (tlm) [inline apiserver/facades/client/action/operation.go]: To avoid `ServerError` you can just use apiservererrors.ParamsErrorf. Same result and more explicit FYI.

File: domain/operation/errors/errors.go [hunk 3]
```diff
@@ -17,3 +21,28 @@ const (
...
+	UnitName string
+	// HasActions is true if the charm defines some actions.
+	HasActions bool
+}
+
+func (a ActionNotDefined) Error() string {
+	return fmt.Sprintf("action not defined for charm %q", a.CharmName)
+}
+
+func (a ActionNotDefined) Is(target error) bool {
```
Comment (tlm) [inline domain/operation/errors/errors.go]: You shouldn't need to implement this. We have `HasType` helper in the error package which is the correct way to check if it exists in a chain. Suggestion would be to delete this.

File: domain/operation/errors/errors.go [hunk 4]
```diff
@@ -17,3 +21,28 @@ const (
...
 	TaskNotPending = errors.ConstError("task not pending")
 )
+
+// ActionNotDefined describes an error that occurs when the given charm does
+// not define the given action.
+type ActionNotDefined struct {
+	// CharmName is the name of the charm missing the action.
+	CharmName string
+	// UnitName is the name of the unit where the action has been requested.
+	UnitName string
```
Comment (tlm) [inline domain/operation/errors/errors.go:31]: You already have unit name / id in the context that this error is received. The error also talks about charms and not a unit. It is a given that if a charm does not have an action then neither would the unit.

Suggest just removing this bit of information.

File: domain/operation/errors/errors.go [hunk 5]
```diff
@@ -17,3 +21,28 @@ const (
...
+	// HasActions is true if the charm defines some actions.
+	HasActions bool
+}
+
+func (a ActionNotDefined) Error() string {
```
Comment (tlm) [inline domain/operation/errors/errors.go:37]: Comment please

File: domain/operation/state/start.go [hunk 6]
```diff
@@ -143,6 +144,11 @@ func (st *State) AddActionOperation(ctx context.Context,
...
+			// Enhance the error with the unit name.
+			notDefined.UnitName = targetUnits[0].String()
```
Comment (tlm) [inline domain/operation/state/start.go]: This is interesting. You are in affect throwing away the whole error chain before this error. Not sure that is correct. I don't think you should have the unit name as I can't see the value so maybe this comment just becomes null.

File: domain/operation/state/start.go [hunk 7]
```diff
@@ -389,14 +399,65 @@ VALUES ($insertOperationAction.*)
...
+	type search struct {
+		CharmUUID      string `db:"charm_uuid"`
+		CharmActionKey string `db:"charm_action_key"`
+	}
+	type found struct {
+		CharmName   string `db:"charm_name"`
+		ActionCount int    `db:"action_count"`
+	}
+	queryFound := `
+SELECT key AS &search.charm_action_key FROM charm_action
```
Comment (tlm) [inline domain/operation/state/start.go]: nit, break the `FROM` on to a new line.

**Comment by tlm** [comment]
Deleting the custom error also gets rid of a database call.

File: domain/operation/errors/errors.go (hunk 4 above)
Comment (gfouillet) [reply domain/operation/errors/errors.go:31]: Not exactly, because of `my-app/leader`

In this case, we expect to get in the error return the actual unit where the action has failed, which is solved in the domain. That's why I did that, there is actual information that are only available on the domain layer.

File: domain/operation/state/start.go (hunk 6 above)
Comment (gfouillet) [reply domain/operation/state/start.go]: Oh, thanks, I didn't see that that way. I replied on unit name above.

On the fact I am throwing away the whole error chain, I believe it is correct : if this is an ActionNotDefined error, we actually don't care of what is the exact cause (because the root cause is that the action is not defined, whatever the underlying logic has done to decide that). In this case, underlying error chain is implementation details.

**Comment by gfouillet** [comment]
> My two cents would be make a ConstError and get on with life.

I have evaluated this possibility, but to stick to 3.6 behavior, using only const error would requires one or two errors (to differentiate cases where the charm has an action or not), and specific domain calls to forge the error (to compute the charm and the exact unit in case of leader). This would be worse.

**Comment by tlm** [comment]
Ta for the explanation @gfouillet, Re-working my thoughts my suggestion would only be then to either define a second error or use composition for the unit name.

i.e for the part where we are extracting the error out to then add a unit id/name to the error. Instead we should define one error that excludes the unit information and then another error error that adds the unit name through either composition or by defining a new sets of fields that match.

The choice at the point where you are currently injecting the unit name then becomes one of:
- Throw the whole error chain away and just return an error of the new type. This one makes the most amount of sense I think.
- Create the new error and add it to the chain and return.

Having an error type with optional fields that may or may not be present adds a degree of complexity I don't think we want. It tends to sprawl out and makes consumer perform logic and tests on values. Easier to keep it simple and add composition to the problem.

**Review by tlm — APPROVED** [review]
Sorry I didn't mean to close the PR. Fat finger click.

Thank you for the work an explaining it to me.

**Comment by gfouillet** [comment]
> Ta for the explanation @gfouillet, Re-working my thoughts my suggestion would only be then to either define a second error or use composition for the unit name.
> 
> i.e for the part where we are extracting the error out to then add a unit id/name to the error. Instead we should define one error that excludes the unit information and then another error error that adds the unit name through either composition or by defining a new sets of fields that match.
> 
> The choice at the point where you are currently injecting the unit name then becomes one of:
> 
>     * Throw the whole error chain away and just return an error of the new type. This one makes the most amount of sense I think.
> 
>     * Create the new error and add it to the chain and return.
> 
> 
> Having an error type with optional fields that may or may not be present adds a degree of complexity I don't think we want. It tends to sprawl out and makes consumer perform logic and tests on values. Easier to keep it simple and add composition to the problem.

Good stuff, thank you. I was not a fan of this update of the error, and your suggestion helps.

If nothing goes along the way, I will create an internal error for passing error from state to service and translate it in domain error in the service layer. This is the pure approach, which cost a bit more in term in terms of code volume but helps for clarity.

File: domain/operation/errors/errors.go [hunk 8]
```diff
@@ -35,5 +35,5 @@ type ActionNotDefined struct {
 
 // Error implements builtin.error
 func (a ActionNotDefined) Error() string {
-	return fmt.Sprintf("action not defined for charm %q", a.CharmName)
+	return fmt.Sprintf("action not defined for charm %q (target unit: %q)", a.CharmName, a.UnitName)
```
Comment (hmlanigan) [inline domain/operation/errors/errors.go:38]: question: why add the target unit here? The error will be the same for every unit.

Comment (gfouillet) [reply domain/operation/errors/errors.go:38]: To be exactly consistent with Juju 3.

The error mention the unit.

Wrapping my head around that question, I can think of:

* rolling upgrade: If you run an action on all unit, you may have some unit who doesn't provide the action (yet), which implies that some specific units can be in error while other won't. 
* exec on leader: Since the leader unit will be defined inside the service layer, the outbound error should provide insight of which exact unit cause an error, it can't rely on params only.

**Review by hmlanigan — APPROVED** [review]
