### PR TITLE
fix: ensure create backup works after upgrade

### LINKED ISSUE #22249: `juju create-backup` fails to take a backup on  upgraded controllers from 3.6.14
### Description

When taking a backup on a Juju 3.6.19 controller (with mongo 4.4.24), with the Juju cli on version 3.6.21, the backup fails with a mongodump command failure: https://pastebin.canonical.com/p/MNTxPghVj6/

We entered the state of "Mongo 4.4.24 with Juju 3.6.19" by deploying e.g. a 3.6.14 Juju controller and running an in-place upgrade to 3.6.19.

### Juju version

3.6.19

### Cloud

OpenStack

### Expected behaviour

Controller backup command succeeds

### Reproduce / Test

1. Deploy 3.6.14 controller
2. `juju upgrade-controller --agent-version 3.6.19`
3. ensure upgrade complete. Confirm using MongoDB version 4.4.24
4. attempt to create backup using `juju create-backup --debug --verbose`

### Notes & References

Occurred during upgrade of `juju-controller-36-staging-ps6` with @wallyworld

### PR DESCRIPTION
**Pull request by wallyworld**
There are 2 fixes:

1. Fix create-backup on upgraded controllers
2. Backport fix from https://github.com/juju/juju/pull/22261 to omit empty checksum from backup metadata

`juju create-backup` was failing on upgraded controllers for 2 reasons. Firstly, we were only passing the SSL args if the mongo version was 4.4.30 but we need to always to it. Second, on startup of jujud, we are updating the DNS names of the cert used for mongod
https://github.com/juju/juju/blob/main/cmd/jujud/agent/machine.go#L383

Writing the `server.pem` file was including the TLS cert and also CA cert. We now separately pass the CA cert as an arg to the mongo binaries (mongod, mongodump) and mongodump complains if the `server.pem` file contains the CA cert. So we strip it out when writing the `server.pem` file.

We also need to account for upgrading from older 2.8 controllers where mongo was installed from deb - the dir used to write the certs is different to that when snap is used.

The second commit backports a fix proposed for 3.6. We were writing an empty checksum to the `metadata.json` file inside the backup archive.

## QA steps

1. Start with old 2.8 controller with uses mongo from deb
juju bootstrap with juju CLI 2.8.13
juju upgrade-controller --build-agent
juju create-backup

2. Start with older 2.9 controller
juju bootstrap --agent-version 2.9.51
juju upgrade-controller --build-agent
juju create-backup

3. Start with controller from this PR
juju bootstrap
juju create-backup

You can ssh to the controller and inspec the `server.pem` to see the CA cert is omitted.

## Links

**Issue:** Fixes #22249 .

**Jira card:** [JUJU-9675](https://warthogs.atlassian.net/browse/JUJU-9675)

[JUJU-9675]: https://warthogs.atlassian.net/browse/JUJU-9675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CodingCookieRookie — APPROVED** [review]
LGTM thanks ian, verified that two certs existed in 2.9 before fix, and only one cert exists in server.perm after fix

File: mongo/mongo.go [hunk 1]
```diff
@@ -664,14 +665,31 @@ func tweakSysctlForMongo(editables map[string]string) {
...
+	err := utils.AtomicWriteFile(sslKeyPath(dataDir), []byte(GenerateSSLKey(leafCertificatePEM(cert), privateKey)), 0600)
 	if err != nil {
 		return errors.Annotate(err, "cannot write SSL key")
 	}
 	err = utils.AtomicWriteFile(caCertKeyPath(dataDir), []byte(cacert), 0600)
 	return errors.Annotate(err, "cannot write CA Cert")
 }
 
+// leafCertificatePEM returns the first certificate block from a PEM bundle.
+// Mongo tooling (eg mongofump) expects server.pem to contain a single cert
```
Comment (hpidcock) [inline mongo/mongo.go]: mongo**f**ump?? 😆

**Review by hpidcock — APPROVED** [review]
