### PR TITLE
fix(secretbackend): migration for secret in builtin CaaS backend

### LINKED ISSUE #21936: migration of secret on k8s doens't works for default backend
### Description

Migrating a model with a secret defined on the default backend doesn't works on k8s.

### Juju version

4.0

### Cloud

Kubernetes

### Expected behaviour

This model is migrated, the secret is still accessible after migration.

### Reproduce / Test

* juju_36 is a 3.6 version of juju
* microk8s is available

```sh
juju bootstrap tgt
juju_36 bootstrap microk8s src
juju add-model moveme
juju add-secret model-secret-1 key=val # add a secret to the model
juju migrate src:moveme tgt
```

We got a failure:

```sh
juju status --format yaml | yq '.model.["model-status"].message'                                                                                                                                              

Model "admin/moveit" is empty.
migrating: aborted, removing model from target controller: model data transfer failed, failed to import model into target controller: execute operation import secrets: cannot import secrets: saving secret "d6lfj37mp2500csb5spg": cannot get secret backend ID for "09a7abf8-6f53-4fed-8c12-293130bc9683": secret backend not found: "09a7abf8-6f53-4fed-8c12-293130bc9683" (secret backend not found)
```

### Notes & References

THis is due to the fact that the default backend for kubernetes in 3.6 isn't clearly defined

```sh
> juju secret-backends                                                                                                                                                                                          
Name          Type        Secrets  Message
internal      controller  0          
moveit-local  kubernetes  1     
```
However, looking into the model description, we can see the secret structure:

```yaml
secrets:
  secrets:
  - acl:
      model-09a7abf8-6f53-4fed-8c12-293130bc9683:
        role: manage
        scope: model-09a7abf8-6f53-4fed-8c12-293130bc9683
    create-time: "2026-03-06T15:58:04Z"
    description: ""
    id: d6lfj37mp2500csb5spg
    label: model-secret-1
    latest-revision-checksum: 2a9ff783586df8502df93ecc7a8dcb63109bc180b067e770f27d195fbc76f4eb
    owner: model-09a7abf8-6f53-4fed-8c12-293130bc9683
    revisions:
    - create-time: "2026-03-06T15:58:04Z"
      number: 1
      update-time: "2026-03-06T15:58:04Z"
      value-ref:
        backend-id: 09a7abf8-6f53-4fed-8c12-293130bc9683
        revision-id: d6lfj37mp2500csb5spg-1
    rotate-policy: never
    secret-version: 1
    update-time: "2026-03-06T15:58:04Z"
  version: 2
sequences:
```

The backend id is the model id. We should probably rely on it during migration to be able to properly fetch and reinsert the secret value.

### PR DESCRIPTION
**Pull request by gfouillet**
In a CaaS model from 3.6, secret which belongs to the built-in backend are not exported by value (as in IaaS model), but instead they use a reference to a backend with an ID equal to de modelUUID.

This patch take advantage of this situation to resolve the modelUUID for backendID into the builtIn kubernetes backend before importing. 

Since the builtin backend is the model namespace on the k8s cluster (which can hold secrets), this work without any extra work. This behavior mimics the import logiccode  from 3.6.

Fixes #21936

> [!NOTE]
> 
> Limits: It is unclear how this behaves on cross-cluster migration. This will work if the model namespace is migrated from cluster to cluster with all its resources through the provider substrate. The migration code in 3.6 suggests it is the case since no special work is done for those secrets.
> 
> If it is not the case, extra works will need to be done for the usecase of inter-cluster migration.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

Get the script:
[setup_secrets_k8s.sh](https://github.com/user-attachments/files/26121407/setup_secrets_k8s.sh)

```sh
sudo make go-install && sudo make microk8s-operator-update 
juju bootstrap microk8s c4 && juju_36 bootstrap microk8s c3 && bash setup_secrets_k8s.sh
# notice the secret url for app and unit secrets
juju migrate c3:moveme c4
juju switch c4:moveme
```

Checks
```sh
juju secrets # secrets should be shown
```
```sh
juju secret-backends # should have a moveme-local backend
```
```sh
juju exec --unit qa/0 -- secret-get <unit secret url> # should works
```
```sh
juju exec --unit qa/0 -- secret-get <app secret url> # should works
```

## Links

**Issue:** Fixes #21936.

**Jira card:** [JUJU-9293](https://warthogs.atlassian.net/browse/JUJU-9293)

[JUJU-9293]: https://warthogs.atlassian.net/browse/JUJU-9293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/secret/import_integration_test.go [hunk 1]
```diff
@@ -105,6 +106,7 @@ func (s *importSuite) prepareModel(c *tc.C) description.Model {
 
 	// Add a secret backend to handle secrets.
 	s.addSecretBackend(c, "internal", "controller")
+	s.addSecretBackend(c, kubernetes.BackendName, kubernetes.BackendType)
```
Comment (wallyworld) [inline domain/secret/import_integration_test.go]: Can we be consistent with params - literals or consts.
Literals have the advantage that the test breaks if something changes.

File: domain/secret/modelmigration/import.go [hunk 2]
```diff
@@ -142,6 +144,40 @@ func (i *importOperation) Execute(ctx context.Context, model description.Model)
...
+	if err != nil {
+		// This should never happen, since this backend is always present
+		return errors.Errorf("getting built-in CaaS backend ID: %w", err)
+	}
+	modelUUID := model.UUID()
+	i.migrateBackendID = func(backendID string) (string, error) {
+		// Set the backend ID to the built-in CaaS backend ID
+		// if it matches the model's UUID.
+		// - On IaaS models, exported secrets from the builtin backend are
+		//   by value (so we won't pass into this code).
```
Comment (wallyworld) [inline domain/secret/modelmigration/import.go:159]: Note: they are by value because that's exactly how the secret is stored in mongo.
And for k8s, they are by reference because it is indeed a reference to the value being stored external to the juju model db, in k8s itself.
So the distinction between value and reference is not related to whether it's a built in backend or not, but by the access patterns used to manage the content.

File: domain/secret/modelmigration/import.go [hunk 3]
```diff
@@ -142,6 +144,40 @@ func (i *importOperation) Execute(ctx context.Context, model description.Model)
...
+		// - On CaaS models, exported secrets from the builtin backend are
+		//   by reference, with a backend ID of the model's UUID. However,
+		//   those secrets are stored in the model namespace in k8s, so we just
+		//   need to change the backend ID to the built-in CaaS backend ID which
+		//   would store the secret in the model namespace.
+		if backendID == modelUUID {
+			return builtInCaaSBackendID, nil
+		}
+
+		// If the backend id is not the CaaS builtin, check it exists into the
```
Comment (wallyworld) [inline domain/secret/modelmigration/import.go]: typo: in

File: domain/secret/modelmigration/import.go [hunk 4]
```diff
@@ -142,6 +144,40 @@ func (i *importOperation) Execute(ctx context.Context, model description.Model)
 		return errors.Errorf("loading secret backend IDs: %w", err)
 	}
 	i.knownSecretBackends = set.NewStrings(backendIDs...)
+	i.seenBackendIds = set.NewStrings()
+	builtInCaaSBackendID, err := i.backendService.GetBuiltInKubernetesBackendID(ctx)
+	if err != nil {
+		// This should never happen, since this backend is always present
```
Comment (wallyworld) [inline domain/secret/modelmigration/import.go]: A db access error can occur for several reasons. I think you may be referring to if the error were "not found".

File: domain/secret/modelmigration/import_test.go [hunk 5]
```diff
@@ -201,8 +202,9 @@ secrets:
     - number: 1
       create-time: %[2]s
       update-time: %[2]s
-      content:
```
Comment (wallyworld) [inline domain/secret/modelmigration/import_test.go:204]: We could retain this content and add an additional external secret revision. That would give test coverage that we can import a secret with revisions in different backends (due to draining).
If we want better test coverage, we'd also have an external secret in a different backend to the built in k8s one, eg vault.
And we'd have both iaas and caas models - here we're just flipping iaas to caas.

File: domain/secret/modelmigration/import.go [hunk 6]
```diff
@@ -142,6 +144,40 @@ func (i *importOperation) Execute(ctx context.Context, model description.Model)
...
+		return errors.Errorf("getting built-in CaaS backend ID: %w", err)
+	}
+	modelUUID := model.UUID()
+	i.migrateBackendID = func(backendID string) (string, error) {
```
Comment (wallyworld) [inline domain/secret/modelmigration/import.go:155]: Is there a reason why we're making this writable? I can't see any test that stubs it out, unless I'm missing it. If no test needs to stub this out, we can just define it as a normal method in the importOperation

File: domain/secret/import_integration_test.go (hunk 1 above)
Comment (gfouillet) [reply domain/secret/import_integration_test.go]: I agree, I hesitated to be honest. I am happy to get insight.

File: domain/secret/modelmigration/import.go (hunk 4 above)
Comment (gfouillet) [reply domain/secret/modelmigration/import.go]: Sure, when i wrote "never happen", it was implicitly "never happen in happy path". I will explicit the comment though.

File: domain/secret/modelmigration/import.go (hunk 6 above)
Comment (gfouillet) [reply domain/secret/modelmigration/import.go:155]: No specific reason, mostly convenience (the function itself requires captured params like model.UUID).

I chose this form because it is something which will probably evolves when implementing secret export, and trying to import 4.x to x.x

Using a normal method would mix "backendID" params and implementation-specific (modelUUID) params into the input parameters.

The correct alternative would be to pass  the migrateBackendID method as a parameter into the importSecret function, but there is already a pattern using importer fields to handle context-related parameters.

To me this is the best compromise in term of readability and maintainability, even though a better solution may arise while implementing futur migration.

File: domain/secret/modelmigration/import_test.go (hunk 5 above)
Comment (gfouillet) [reply domain/secret/modelmigration/import_test.go:204]: We have already the case of different backend for the other secret, that's why I updated this one which doesn't grant any coverage (execpt having several secrets)

`domain/secret/modelmigration/import_test.go:162-171`

```yaml
    revisions:
    - number: 1
      create-time: %[2]s
      update-time: %[2]s
      value-ref:
        backend-id: backend-id
        revision-id: revision-id
      expire-time: %[4]s
    - number: 2
      create-time: %[2]s
      update-time: %[2]s
      content:
        foo: bar
```


I switched iaas to caas for consistency, but there is no impact, so I don't see any interest to double the unit test.
