### PR TITLE
fix(k8s): delete orphaned StatefulSets before recreating to avoid PVC mismatch

### LINKED ISSUE #21722: StatefulSet volume claim name mismatch after force-removing and redeploying an application
### Description

After force-removing a K8s application with `--destroy-storage` and redeploying it, the StatefulSet pod fails to create because the pod template references volume names using the new application UUID, while the `volumeClaimTemplates` still use the old UUID from the previous deployment. This causes a volume name mismatch, and the StatefulSet controller enters a `FailedCreate` loop with errors like:

```
create Pod postgresql-k8s-0 in StatefulSet postgresql-k8s failed error: Pod "postgresql-k8s-0" is invalid:
  [spec.containers[0].volumeMounts[8].name: Not found: "postgresql-k8s-archive-<NEW_UUID>",
   spec.containers[0].volumeMounts[9].name: Not found: "postgresql-k8s-data-<NEW_UUID>", ...]
```

Specifically, the containers' volume mounts reference volumes named with the **current** `app.juju.is/uuid` (e.g. `postgresql-k8s-data-abde389f`), but the `volumeClaimTemplates` on the StatefulSet still carry names from a **previous** deployment's UUID (e.g. `postgresql-k8s-data-30ab1e6d`). This prevents the pod from being created, as Kubernetes cannot find the referenced volumes.

This works correctly in Juju **3.6.12** — both the pod template volume mounts and the volume claim template names use the same UUID. The regression was introduced in **3.6.13** and is still present in **3.6.14**.

### Juju version

3.6.13, 3.6.14 (works correctly on 3.6.12)

### Cloud

Kubernetes

### Expected behaviour

After force-removing an application with `juju remove-application <app> --destroy-storage --force --no-prompt --no-wait` and redeploying it, the new StatefulSet should have consistent UUIDs between its pod template volume mounts and its `volumeClaimTemplates`. The pod should be created and start successfully, just as it does on Juju 3.6.12.

### Reproduce / Test

1. Bootstrap three controllers running Juju 3.6.12, 3.6.13, and 3.6.14 respectively (e.g. on MicroK8s):
   ```
   juju add-model --no-switch --controller micro3612 dev3612
   juju add-model --no-switch --controller micro3613 dev3613
   juju add-model --no-switch --controller micro3614 dev3614
   ```

2. Deploy the same charm on all three models:
   ```
   juju deploy postgresql-k8s --trust --channel 16/edge -m micro3612:dev3612 --revision 726
   juju deploy postgresql-k8s --trust --channel 16/edge -m micro3613:dev3613 --revision 726
   juju deploy postgresql-k8s --trust --channel 16/edge -m micro3614:dev3614 --revision 726
   ```

3. Wait until all three deployments reach `active/idle`.

4. Force-remove the application on all three models:
   ```
   juju remove-application postgresql-k8s --destroy-storage --force --no-prompt --no-wait -m micro3612:dev3612
   juju remove-application postgresql-k8s --destroy-storage --force --no-prompt --no-wait -m micro3613:dev3613
   juju remove-application postgresql-k8s --destroy-storage --force --no-prompt --no-wait -m micro3614:dev3614
   ```

5. Wait until all three models show no applications.

6. Redeploy the same charm:
   ```
   juju deploy postgresql-k8s --trust --channel 16/edge -m micro3612:dev3612 --revision 726
   juju deploy postgresql-k8s --trust --channel 16/edge -m micro3613:dev3613 --revision 726
   juju deploy postgresql-k8s --trust --channel 16/edge -m micro3614:dev3614 --revision 726
   ```

7. Observe results:
   - **Juju 3.6.12 (dev3612):** Pod starts successfully (1 Running).
   - **Juju 3.6.13 (dev3613):** Pod stuck at 0 Running with `FailedCreate` errors.
   - **Juju 3.6.14 (dev3614):** Pod stuck at 0 Running with `FailedCreate` errors.

8. Verify with `kubectl describe sts -n <namespace> postgresql-k8s` — the broken models show mismatched UUIDs between volume mounts and volume claim names.

[kubectl logs.txt](https://github.com/user-attachments/files/25075622/kubectl.logs.txt)

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by marceloneppel**
When an application is force-removed with `--force --no-wait`, the StatefulSet may not be fully cleaned up. On redeployment, Juju reuses the orphaned StatefulSet via the update path, but Kubernetes does not allow modifying `volumeClaimTemplates` on an existing StatefulSet. Since PR #20795 changed the `StorageUniqueID` source of truth from the StatefulSet annotation to the application document, a new unique ID is generated on redeploy, causing a mismatch between the volume mount names and the existing PVC names. This prevents pods from starting.

The fix detects orphaned StatefulSets by comparing the `app.juju.is/uuid` annotation against the expected `StorageUniqueID`. When a mismatch is found and the StatefulSet is confirmed to be owned by Juju (via `app.kubernetes.io/managed-by` label and `model.juju.is/id` annotation), it is deleted and recreated with the correct `volumeClaimTemplates`.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] Integration tests
- [ ] doc.go added or updated in changed packages

## QA steps

1. Bootstrap a k8s controller: `juju bootstrap microk8s micro`
2. Add a model: `juju add-model test`
3. Deploy: `juju deploy postgresql-k8s --trust --channel 16/edge --revision 726`
4. Wait for active, then force-remove: `juju remove-application postgresql-k8s --destroy-storage --force --no-prompt --no-wait`
5. Verify orphaned StatefulSet exists: `kubectl get statefulset -n test`
6. Redeploy: `juju deploy postgresql-k8s --trust --channel 16/edge --revision 726`
7. Without the fix, the app is stuck at "agent initialising". With the fix, the controller logs `deleting orphaned statefulset` and the app reaches active.

## Documentation changes

No user-facing workflow changes. The fix is transparent — orphaned StatefulSets are automatically cleaned up during redeployment.

## Links

**Issue:** Fixes #21722.

**Jira card:** [JUJU-9161](https://warthogs.atlassian.net/browse/JUJU-9161)

[JUJU-9161]: https://warthogs.atlassian.net/browse/JUJU-9161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: internal/provider/kubernetes/application/application.go [hunk 1]
```diff
@@ -277,13 +277,40 @@ func (a *app) Ensure(config caas.ApplicationConfig) (err error) {
...
+		// If the existing StatefulSet has a different storage unique ID,
+		// it is an orphan from a previous deployment. Kubernetes does not
+		// allow updating volumeClaimTemplates on an existing StatefulSet,
+		// so we must delete and recreate it to avoid a PVC name mismatch.
+		// See https://github.com/juju/juju/issues/21722.
+		if exists {
+			annKey := utils.AnnotationKeyApplicationUUID(a.labelVersion)
+			existingUID := existingSts.GetAnnotations()[annKey]
+			if existingUID != "" && config.StorageUniqueID != "" && existingUID != config.StorageUniqueID &&
+				a.isStatefulSetOwnedByJuju(existingSts) {
```
Comment (wallyworld) [inline internal/provider/kubernetes/application/application.go]: We can optimise/consolidate this logic a bit. The `isStatefulSetOwnedByJuju()` and storageUUID fetching both use the annotations, which we get twice. We can just have a method `shouldDeleteExistingStatefulSet()` which has the logic here folded into it. So here would be
```
if exists && shouldDeleteExistingStatefulSet(...) {
    logger.Infof("deleting orphaned statefulset %q (storage UID %q does not match expected %q)", a.name, existingUID, config.StorageUniqueID)
    ...
}
```

File: internal/provider/kubernetes/application/application_test.go [hunk 2]
```diff
@@ -606,6 +606,179 @@ func (s *applicationSuite) TestEnsureStateful(c *gc.C) {
...
+			},
+			Template: corev1.PodTemplateSpec{
+				ObjectMeta: metav1.ObjectMeta{
+					Labels: map[string]string{"app.kubernetes.io/name": s.appName},
+				},
+			},
+		},
+	}
+	_, err := s.client.AppsV1().StatefulSets(s.namespace).Create(
+		context.TODO(), orphanSts, metav1.CreateOptions{},
```
Comment (wallyworld) [inline internal/provider/kubernetes/application/application_test.go]: In tests use `context.Backhround()`

File: internal/provider/kubernetes/application/application.go [hunk 3]
```diff
@@ -277,13 +277,40 @@ func (a *app) Ensure(config caas.ApplicationConfig) (err error) {
...
+				logger.Infof("deleting orphaned statefulset %q (storage UID %q does not match expected %q)", a.name, existingUID, config.StorageUniqueID)
+				if delErr := existingSts.Delete(context.Background()); delErr != nil && !errors.IsNotFound(delErr) {
```
[the remark this answers is not in the document]
Comment (wallyworld) [reply internal/provider/kubernetes/application/application.go]: We also need to treat a not found error as a no op

Comment (wallyworld) [inline internal/provider/kubernetes/application/application.go]: Use context.TODO()

File: internal/provider/kubernetes/application/application.go [hunk 4]
```diff
@@ -860,6 +887,43 @@ func (a *app) getStatefulSet() (*resources.StatefulSet, error) {
...
+// is fully removed from Kubernetes. This is needed because foreground deletion
+// is async — the resource persists with a deletionTimestamp until all
+// dependents (pods) are terminated.
+func (a *app) waitForStatefulSetDeletion() error {
+	timeout := a.clock.After(2 * time.Minute)
+	for {
+		select {
+		case <-timeout:
+			return errors.Errorf("timed out waiting for orphaned statefulset %q to be deleted", a.name)
+		case <-a.clock.After(3 * time.Second):
```
Comment (wallyworld) [inline internal/provider/kubernetes/application/application.go]: Instead of polling, we could use a k8s event watcher, similar to
```
func (k *kubernetesClient) watchEvents(objName string, objKind string) (watcher.NotifyWatcher, error)
```
Not sure if we can configure the Informer to fire directly when the specified object is deleted. But would be cleaner and avoid the poll / lookup loop

**Review by wallyworld — COMMENTED** [review]
Thanks for submitting the patch, much appreciated.

I've suggested  a couple of tweaks.

File: internal/provider/kubernetes/application/application.go (hunk 1 above)
Comment (marceloneppel) [reply internal/provider/kubernetes/application/application.go]: Good catch. Updated on https://github.com/juju/juju/pull/21786/changes/c9f7f0305c7f4a70ef4644316c03997f8aea8e07.

File: internal/provider/kubernetes/application/application_test.go (hunk 2 above)
Comment (marceloneppel) [reply internal/provider/kubernetes/application/application_test.go]: Thanks for letting me know this. Updated on https://github.com/juju/juju/pull/21786/changes/c9f7f0305c7f4a70ef4644316c03997f8aea8e07.

File: internal/provider/kubernetes/application/application.go (hunk 3 above)
Comment (marceloneppel) [reply internal/provider/kubernetes/application/application.go]: Updated on https://github.com/juju/juju/pull/21786/changes/c9f7f0305c7f4a70ef4644316c03997f8aea8e07.

File: internal/provider/kubernetes/application/application.go (hunk 4 above)
Comment (marceloneppel) [reply internal/provider/kubernetes/application/application.go]: Great idea. Updated on https://github.com/juju/juju/pull/21786/changes/c9f7f0305c7f4a70ef4644316c03997f8aea8e07.

**Comment by marceloneppel** [comment]
Thanks for the review, @wallyworld! I've addressed all your comments in the latest push. Appreciate the suggestions!

File: internal/provider/kubernetes/application/application.go [hunk 5]
```diff
@@ -277,13 +277,35 @@ func (a *app) Ensure(config caas.ApplicationConfig) (err error) {
...
 		}
 
+		// If the existing StatefulSet has a different storage unique ID,
+		// it is an orphan from a previous deployment. Kubernetes does not
+		// allow updating volumeClaimTemplates on an existing StatefulSet,
+		// so we must delete and recreate it to avoid a PVC name mismatch.
+		// See https://github.com/juju/juju/issues/21722.
+		if exists && a.shouldDeleteExistingStatefulSet(existingSts, config.StorageUniqueID) {
+			logger.Infof("deleting orphaned statefulset %q", a.name)
+			if delErr := existingSts.Delete(context.TODO()); delErr != nil && !errors.IsNotFound(delErr) {
```
Comment (wallyworld) [inline internal/provider/kubernetes/application/application.go]: If we get a NotFound error, do we still need to call `waitForStatefulSetDeletion()`

File: internal/provider/kubernetes/application/application.go [hunk 6]
```diff
@@ -860,6 +882,87 @@ func (a *app) getStatefulSet() (*resources.StatefulSet, error) {
...
+	stsAnnotations := sts.GetAnnotations()
+	annKey := utils.AnnotationKeyApplicationUUID(a.labelVersion)
+	existingUID := stsAnnotations[annKey]
+	if existingUID == "" || existingUID == expectedStorageUID {
+		return false
+	}
+	// Only delete if the StatefulSet is managed by Juju and belongs to
+	// the current model, to avoid deleting resources we don't own.
+	stsLabels := sts.GetLabels()
+	if stsLabels[constants.LabelKubernetesAppManaged] != "juju" {
```
Comment (wallyworld) [inline internal/provider/kubernetes/application/application.go]: We have a const `resources.JujuFieldManager`

File: internal/provider/kubernetes/application/application.go [hunk 7]
```diff
@@ -860,6 +882,87 @@ func (a *app) getStatefulSet() (*resources.StatefulSet, error) {
...
+		return false
+	}
+	modelUUIDKey := utils.AnnotationModelUUIDKey(a.labelVersion)
+	if stsAnnotations[modelUUIDKey] != a.modelUUID {
+		return false
+	}
+	logger.Infof("detected orphaned statefulset %q: storage UID %q does not match expected %q",
```
Comment (wallyworld) [inline internal/provider/kubernetes/application/application.go]: Small nit: we tend to use `UUID`, would be good to be consistent

File: internal/provider/kubernetes/application/application.go (hunk 5 above)
Comment (marceloneppel) [reply internal/provider/kubernetes/application/application.go]: Good catch. Fixed in https://github.com/juju/juju/pull/21786/commits/01a9ebac8a — now only calls waitForStatefulSetDeletion() when the delete was actually issued.

File: internal/provider/kubernetes/application/application.go (hunk 6 above)
Comment (marceloneppel) [reply internal/provider/kubernetes/application/application.go]: Fixed in https://github.com/juju/juju/pull/21786/commits/01a9ebac8a.

File: internal/provider/kubernetes/application/application.go (hunk 7 above)
Comment (marceloneppel) [reply internal/provider/kubernetes/application/application.go]: Fixed in https://github.com/juju/juju/pull/21786/commits/01a9ebac8a.

**Review by adisazhar123 — APPROVED** [review]
Thank you for the fix. I have QAed it too and it looks good.
