### PR TITLE
fix: avoid creating duplicate default routes for vms with multiple nics

### LINKED ISSUE #20540: Juju Spaces default routes (miss-configuration?) randomly causing no WAN connectivity (with reachable LAN)
### Description

Hi,

**Issue**: randomly, PostgreSQL charm deployed with Juju Spaces is not able to install PostgreSQL snap => failing to deploy charm.

**STR**: [detailed internal manual](https://docs.google.com/document/d/1anRUSykOuTsExkz9-45RUbXNlV52P6ZA2VljK4LFdqM/edit), public STR:
```
sudo snap install juju --channel=3.6/stable
sudo snap install lxd --channel=5.21/edge # should be the same with 5.21/stable
sudo lxd init --auto
sudo lxc network set lxdbr0 ipv6.address none
sudo lxc network set lxdbr0 dns.mode none
sudo lxc network create lxdbr1 \
  				ipv4.address=192.168.100.1/24 \
  				ipv6.address=none \
				dns.mode=none

sudo lxc network create lxdbr2 \
  				ipv4.address=192.168.200.1/24 \
  				ipv6.address=none \
				dns.mode=none

juju bootstrap lxd test --bootstrap-constraints="virt-type=virtual-machine mem=4G"

juju add-model testspaces
juju add-space peers
juju move-to-space peers 192.168.100.0/24
juju add-space clients
juju move-to-space clients 192.168.200.0/24

for i in $(seq 1 15) ; do
juju deploy postgresql db${i} \
--channel 16/edge \
--constraints "spaces=clients,peers" \
--bind="database-peers=peers database=clients" ; done
```

**Actual results**: 1-10 of 15 deployment fails (specific to hardware).
**Error**: for the history only, as unrelated to the root cause, as it is pure networking issue:
```
  File "/var/lib/juju/agents/unit-db15-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 971, in get_snap_information
    return self._request("GET", "find", {"name": name})[0]  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
So, error says, cannot connect SnapStore to get metadata.

**Troubleshooting**: It is true, WAN is not reachable (but machine is reachable on LAN, and communicate with Juju controller):
```
> juju ssh db15/0 # failed installation
ubuntu@juju-b7bd28-15:~$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
^C
--- 1.1.1.1 ping statistics ---
20 packets transmitted, 0 received, 100% packet loss <<<<
```

The cloud-init.log also have WAN connectivity issues on this machine:
```
...
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['eatmydata', 'apt-get', '--option=Dpkg::Options::=--force-confold', '--option=Dpkg::options::=--force-unsafe-io', '--assume-yes', '--quiet', 'install', 'curl', 'tmux', 'cpu-checker']
Exit code: 100
...
2025-09-02 15:25:11,023 - handlers.py[DEBUG]: finish: modules-final: FAIL: running modules for final
```

The further investigation shown the following:
* all deployed machines have multiple default routes:
```
ubuntu@juju-b7bd28-15:~$ ip route show default
default via 192.168.200.1 dev eth2 proto dhcp src 192.168.200.133 metric 100 
default via 192.168.100.1 dev eth3 proto dhcp src 192.168.100.110 metric 100 
default via 10.175.141.1 dev eth0 proto dhcp src 10.175.141.144 metric 100 
default via 10.175.141.1 dev eth1 proto dhcp src 10.175.141.73 metric 100 
```
* IF expected default route eth0 is in first/second line => container has access to WAN
* IF default route eth0 is in third/forth line => container has access to LAN but NO access to WAN !

The further routing tests shown eth2/eth3 used only:
```
ubuntu@juju-b7bd28-15:~$ for i in $(seq 1 10); do ip route get 1.1.1.1; done
1.1.1.1 via 192.168.100.1 dev eth3 src 192.168.100.110 uid 1000 
    cache 
1.1.1.1 via 192.168.200.1 dev eth2 src 192.168.200.133 uid 1000 
    cache 
1.1.1.1 via 192.168.100.1 dev eth3 src 192.168.100.110 uid 1000 
    cache 
1.1.1.1 via 192.168.200.1 dev eth2 src 192.168.200.133 uid 1000 
    cache 
1.1.1.1 via 192.168.100.1 dev eth3 src 192.168.100.110 uid 1000 
    cache 
1.1.1.1 via 192.168.200.1 dev eth2 src 192.168.200.133 uid 1000 
    cache 
1.1.1.1 via 192.168.100.1 dev eth3 src 192.168.100.110 uid 1000 
    cache 
1.1.1.1 via 192.168.200.1 dev eth2 src 192.168.200.133 uid 1000 
    cache 
1.1.1.1 via 192.168.100.1 dev eth3 src 192.168.100.110 uid 1000 
    cache 
1.1.1.1 via 192.168.200.1 dev eth2 src 192.168.200.133 uid 1000 
    cache 
```

Which makes sense:
* Juju (LXD) uses competing routes (no ECMP)
* Linux collapsed eth0/eth1 (duplicate gateway 10.175.141.1) into a single candidate (net.ipv4.fib_multipath_hash_policy is `0`)
* L3-only hash happens to map src → dst=1.1.1.1 flows into just the buckets for eth2 and eth3 (eth0/eth1 never chosen)

All results to LAN reachable but no WAN.... and order of routes inserted by Juju into LXD is important... if eth0 is first/second all works well.

There are several ways to address this, but all depends on the final networking goals/configuration.

### Juju version

3.6.9

### Cloud

LXD

### Expected behaviour

`juju deploy postgresql` should work reliable with and without Juju Spaces used.

### Reproduce / Test

See above.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by wallyworld**
For vms with multiple nics, we generate a netplan like so:

```
cat /etc/netplan/99-juju.yaml 
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      dhcp4: true
    eth2:
      dhcp4: true
```

However, this causes a multiple default routes, one for for each nic
```
ip route
default via 10.68.49.1 dev enp7s0 proto dhcp src 10.68.49.242 metric 100 
default via 10.68.47.1 dev enp5s0 proto dhcp src 10.68.47.20 metric 100 
default via 10.68.48.1 dev enp6s0 proto dhcp src 10.68.48.194 metric 100 
```

If this happens, it can prevent network traffic egress.
We can adjust the metrics so that each route gets a different value.
Ideally there'd be a way to model what nic gets egress and/or configure the routes for each nic but the netplan we write for lxd is quite rigid. ie we just write a really simple netplan with dhcp4: true and don't provide a way to model/configure other aspects that I can see (apart from the matching algorithm we use on vms).

## QA steps

bootstrap on lxd with 3 networks
add 2 spaces
```
juju add-space sp1 <cidr1>
juju add-space sp2 <cidr2>
```
Add a vm machine
`juju add-machine --constraints "spaces=sp1,sp2 virt-type=virtual-machine"`

netplan will be
```
cat /etc/netplan/99-juju.yaml 
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
    eth1:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 110
    eth2:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 120
```

And now we have
```
ip route
default via 10.68.47.1 dev eth0 proto dhcp src 10.68.47.190 metric 100 
default via 10.68.48.1 dev eth2 proto dhcp src 10.68.48.15 metric 110 
default via 10.68.49.1 dev eth3 proto dhcp src 10.68.49.123 metric 120
```

## Links

**Issue:** Fixes #20540.

**Jira card:** [JUJU-8506](https://warthogs.atlassian.net/browse/JUJU-8506)

[JUJU-8506]: https://warthogs.atlassian.net/browse/JUJU-8506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: cloudconfig/cloudinit/network_ubuntu.go [hunk 1]
```diff
@@ -161,6 +162,14 @@ func GenerateNetplan(interfaces corenetwork.InterfaceInfos, matchHWAddr bool) (s
 		} else if info.ConfigType == corenetwork.ConfigDHCP {
 			t := true
 			iface.DHCP4 = &t
+			// We only want to allow a default DHCP route
+			// for the first DHCP enabled interface.
+			if numDHCPInterfaces > 0 && len(info.Routes) == 0 {
+				iface.DHCP4Overrides = &netplan.Overrides{
+					UseRoutes: false,
```
Comment (manadart) [inline cloudconfig/cloudinit/network_ubuntu.go]: For robustness, I think the override used should be the metric instead. So increment `numDHCPInterfaces` early, and multiply by 10 to get the metric.

So for the test below, this part:
```yaml
    any2:
      match:
        macaddress: aa:bb:cc:dd:ee:f2
      dhcp4: true
    any3:
      match:
        macaddress: aa:bb:cc:dd:ee:f3
      dhcp4: true
      dhcp4-overrides:
        use-routes: false
```
Becomes:
```yaml
    any2:
      match:
        macaddress: aa:bb:cc:dd:ee:f2
      dhcp4: true
      dhcp4-overrides:
        route-metric: 10
    any3:
      match:
        macaddress: aa:bb:cc:dd:ee:f3
      dhcp4: true
      dhcp4-overrides:
        route-metric: 20
```

Comment (wallyworld) [reply cloudconfig/cloudinit/network_ubuntu.go]: I started the metric values at 100 to be consistent with the current behaviour, so 100, 110, 120 etc.
Only DHCP interfaces without any route config at all get this metric applied.

**Comment by wallyworld** [comment]
> Prioritising with metric rather than turning off altogether is a better way.

Good idea.

File: cloudconfig/cloudinit/network_ubuntu.go [hunk 2]
```diff
@@ -150,6 +150,7 @@ func GenerateNetplan(interfaces corenetwork.InterfaceInfos, matchHWAddr bool) (s
 	var netPlan netplan.Netplan
 	netPlan.Network.Ethernets = make(map[string]netplan.Ethernet)
 	netPlan.Network.Version = 2
+	dhcpInterfaceRouteMetric := uint8(100)
```
Comment (SimonRichardson) [inline cloudconfig/cloudinit/network_ubuntu.go]: This will only allow 16 interfaces otherwise it'll cause a wrap around, which will cause strange behaviour. I'd suggest not using a uint8 and then if it goes over 255 set everything to disabled (like you had previously).

Comment (wallyworld) [reply cloudconfig/cloudinit/network_ubuntu.go]: 16 is a lot of interfaces, but fair point
I just changed it to an int. Better that we just be consistent in printing a metric for everything.
