### PR TITLE
fix(bundle): coerce numeric option type in BuildModelRepresentation

### LINKED ISSUE #21532: diff-bundle always reports integer config options as changed
### Description

When using `juju diff-bundle` integer config options are always reported as different between the model and bundle, regardless of whether they are different. I reproduced the issue on an LXD cloud but it's also been seen on a k8s cloud. Likely the cloud doesn't matter.

### Juju version

3.6.12

### Cloud

LXD

### Expected behaviour

If a config option is the same in a model and a bundle then diff-bundle should not include it.

### Reproduce / Test

A minimal reproducer can be done with any charm that has integer config options, e.g.,

```bash
juju add-model diff-bundle-issue
juju deploy apache2
juju diff-bundle <(juju export-bundle --include-charm-defaults --include-series)
```
We expect to receive `{}` but instead receive
```yaml
applications:
  apache2:
    options:
      lb_balancer_timeout:
        bundle: 60
        model: 60
      logrotate_count:
        bundle: 365
        model: 365
      mpm_maxclients:
        bundle: 2048
        model: 2048
      mpm_maxrequestsperchild:
        bundle: 0
        model: 0
      mpm_maxsparethreads:
        bundle: 75
        model: 75
      mpm_minsparethreads:
        bundle: 25
        model: 25
      mpm_serverlimit:
        bundle: 128
        model: 128
      mpm_startservers:
        bundle: 2
        model: 2
      mpm_threadlimit:
        bundle: 64
        model: 64
      mpm_threadsperchild:
        bundle: 64
        model: 64
````

### Notes & References

The issue arises because in the diffbundle code, the model representation has the options as floats while the bundle has parsed them as ints.

Concretely diff bundle calls [readModel](https://github.com/juju/juju/blob/cbb05654c7444dd6bee29e49aff16339f02c34f9/cmd/juju/application/diffbundle.go#L227) to fetch the model from the controller as json and by default the json codec unmarshals all numbers as float64s.

On the other hand when reading the bundle go-yaml interprets things that look integer-like as integers. Since `float64 != int64` we see the above behavior.

The simplest fix is probably to just use the type information for the options provided by the controller to cast to the appropriate type in [applicationConfigValue](https://github.com/juju/juju/blob/cbb05654c7444dd6bee29e49aff16339f02c34f9/cmd/juju/application/bundle/bundle.go#L234).

### PR DESCRIPTION
**Pull request by raineszm**
Json by default unmarshals all numeric types to floats.

As a result issues like #21532 arise, where identical values
compare as different between the bundle and model.

This change uses the known type information of application config to ensure
that integer options are are properly cast to int type.

Additionally, diff-bundle test slightly modified to reflect that json
unmarshalling of types as mentioned above.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

This code path is hit by `juju diff-bundle` and `juju deploy` when using a bundle a simple test, which exercises these and  verifies that #21532 is actually fixed is

```
juju add-model coerce-numeric-options
juju deploy apache2
juju export-bundle --include-charm-defaults --include-series > bundle.yaml
```

Then run
```
juju diff-bundle bundle.yaml
```
and ensure that the result is an empty map.

Change, some integer options in bundle.yaml to different values and ensure 
```
juju diff-bundle bundle.yaml
```
now reflects that.

Finally,
```
juju deploy ./bundle.yaml
````
and now
```
juju diff-bundle bundle.yaml
````
should again be an empty map.

## Links

**Issue:** Fixes #21532.

### CODE REVIEW

**Comment by raineszm** [comment]
It looks like the CI had some issues with fetching dependencies.

Beyond that, I ran the bundle deploy integration tests on my machine and everything passed.

File: cmd/juju/application/bundle/bundle_test.go [hunk 1]
```diff
@@ -136,8 +136,9 @@ func (s *buildModelRepSuite) TestBuildModelRepresentationApplicationsWithSubordi
 	obtainedWordpress, ok := obtainedModel.Applications["wordpress"]
 	c.Assert(ok, jc.IsTrue)
 	c.Assert(obtainedWordpress.Options, gc.HasLen, 1)
-	_, ok = obtainedWordpress.Options["skill-level"]
+	skill_level, ok := obtainedWordpress.Options["skill-level"]
```
Comment (SimonRichardson) [inline cmd/juju/application/bundle/bundle_test.go]:
```suggestion
	skillLevel, ok := obtainedWordpress.Options["skill-level"]
```

**Review by SimonRichardson — APPROVED** [review]
Thanks for the changes.

**Comment by SimonRichardson** [comment]
@raineszm if you can rebase against 3.6 that would be good.

File: cmd/juju/application/bundle/bundle_test.go (hunk 1 above)
Comment (raineszm) [reply cmd/juju/application/bundle/bundle_test.go]: Ack. Changed after rebasing onto 3.6.
