### PR TITLE
fix: set hostname in machine import

### LINKED ISSUE #18641: hostname not updated in machine status after juju migrate
### Description

Follow deployment steps on [Sunbeam Single-node quickstart](https://canonical.com/microstack/docs/single-node)

The step `sunbeam cluster bootstrap` will migrate the model admin/openstack-machines from local lxd based juju controller to k8s based juju controller. (At the migration point of time only the first machine or bootstrap node exists and gets mirgated.) 

juju status --format=yaml -> https://pastebin.canonical.com/p/3qBqt2mbfY/
`machine 0` which undergoes the `juju migration` process does not have `hostname` attribute where as the machines added after the migration `machine 1 and 2` have the hostname attribute.

### Juju version

3.6.1

### Cloud

Kubernetes, LXD

### Expected behaviour

`hostname` attribute should exist in juju status for each machine.

### Reproduce / Test

On a fresh jammy VM, run the following commands.
(Please see some manual steps required like updating IP in clouds.yaml)

```
cat <<EOF > clouds.yaml
clouds:
  sunbeam:
    type: manual
    endpoint: 10.40.76.66
    auth-types: [empty]
    regions:
      default: {}
EOF

cat <<EOF > credential.yaml
credentials:
  sunbeam:
    empty-creds:
      auth-type: empty
EOF

# Initialise LXD on non-default bridge
cat <<EOF | sudo lxd init --preseed
networks:
- config:
    ipv4.address: auto
    ipv6.address: none
  name: br0
  project: default
storage_pools:
- name: default
  driver: dir
profiles:
- devices:
    eth0:
      name: eth0
      network: br0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
EOF

# Juju + LXD and adding manual cloud and machine
sudo snap install juju --channel 3.6/stable
newgrp lxd
juju bootstrap localhost

### change endpoint in clouds.yaml to lxd juju controller ip
juju add-cloud -f clouds.yaml --client --controller localhost-localhost --force
juju add-credential sunbeam -f credential.yaml --client --controller localhost-localhost
juju add-model openstack-machines sunbeam --credential empty-creds
# IP should be the VM or machine IP
juju add-machine -m openstack-machines ssh:10.121.193.102

# Deploy microk8s on machine
juju deploy microk8s --channel legacy/stable --config channel=1.28-strict/stable --config addons="dns hostpath-storage metallb:10.121.193.210-10.121.193.220" --to 0
#sudo microk8s enable hostpath-storage
# Use metallb ip range that is accessible, in my case used free IPs from same network range as local ip
#sudo microk8s enable metallb:10.121.193.210-10.121.193.220

# Check juju status if machine has hostname attribute. In my tests hostname attribute exists
juju status --format=yaml

# Bootstrap juju controller on microk8s
sudo usermod -a -G snap_microk8s ubuntu
newgrp snap_microk8s
juju bootstrap --config controller-service-type=loadbalancer microk8s microk8s

# Modify clouds.yaml endpoint to point to microk8s juju controller
juju add-cloud -f clouds.yaml --controller microk8s --force
juju add-credential sunbeam -f credential.yaml --controller microk8s

juju switch localhost-localhost
juju migrate openstack-machines microk8s

juju switch microk8s
# Check juju status if machine has hostname attribute. In my tests i dont see hostname attribute
juju status -m admin/openstack-machines --format=yaml
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by adisazhar123**
This PR persists the machine hostname when we import a 3.6 model. 

Requires #22207 to test as it contains setting the hostname in the description machine struct.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [ ] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

#### Test Case 1 - Migrate machine

Outcome: migrate from 3.6 to 4.0.6 works. 4.0.6 sets the machine hostname.

Checkout this branch. Bootstrap 4.0 controller.

```
juju bootstrap localhost 406-dst --build-agent
```

Checkout #22207. Bootstrap source controller. Add model, deploy charm, add machine.

```
juju bootstrap localhost 3622-src --build-agent
juju add-model moveme
juju deploy ubuntu u1
juju add-machine
```

Wait to stabilize. 

```
# take note of the machine hostname
juju status --format json | jq '.machines | .[] | .hostname'

"juju-6fe27a-0"
"juju-6fe27a-0"

```

Migrate to destination

```
juju migrate moveme 406-dst
juju switch 406-dst:admin/moveme
```

```
Check hostname are carried over

juju status --format json | jq '.machines | .[] | .hostname'

"juju-6fe27a-0"
"juju-6fe27a-0"

```

#### Test Case 2 - Migrate machine hosting a container

Outcome: hostnames of host machine and its container are migrated. Unfortunately, an existing bug fails to import the layer link device #22224.

Apply this patch as a workaround to verify hostnames are set. It gives us enough time to query the records in DB.

```
diff --git a/domain/network/modelmigration/import_linklayerdevices.go b/domain/network/modelmigration/import_linklayerdevices.go
index 01330b6ddb..c789eb04c9 100644
--- a/domain/network/modelmigration/import_linklayerdevices.go
+++ b/domain/network/modelmigration/import_linklayerdevices.go
@@ -7,6 +7,7 @@ import (
 	"context"
 	"fmt"
 	"strings"
+	"time"
 
 	"github.com/juju/description/v12"
 
@@ -65,6 +66,10 @@ func (i *importOperation) Setup(scope modelmigration.Scope) error {
 
 // Execute the import of the link layer devices contained in the model.
 func (i *importOperation) Execute(ctx context.Context, model description.Model) error {
+	i.logger.Infof(ctx, "[linklayerimport] sleeping for 3 mins...")
+	<-time.After(3 * time.Minute)
+	i.logger.Infof(ctx, "[linklayerimport] woke up from sleep...")
+
 	if err := i.importLinkLayerDevices(ctx, model.LinkLayerDevices(), model.IPAddresses()); err != nil {
 		return errors.Capture(err)
 	}
```

Checkout this branch. Bootstrap 4.0 destination controller

```
juju bootstrap localhost 40-dst-new --build-agent
```

Checkout #22207. Bootstrap source controller. Add model and machines.

```
juju bootstrap localhost 36-src-new --debug
juju add-model moveme
juju add-machine
# create container on machine 0
juju add-machine lxd:0
```

Wait until machines are started... Check machine and container hostname. Note them down

```
juju status --format json \
| jq '.machines[]
      | (.hostname,
         .containers[]?.hostname)'

"juju-6fe27a-0"
"juju-6fe27a-0-lxd-0"
```

Then migrate

```
juju migrate moveme 40-dst-new
```

We have 3 minutes to check the records in DB before the next import operation is run. 

```
juju switch 40-dst-new
juju ssh -m controller controller/0

repl (controller)> .switch model-move

repl (model-move)> select name, hostname from machine
name	hostname		
0	juju-6fe27a-0		
0/lxd/0	juju-6fe27a-0-lxd-0	
```

Eventually migration fails with 

```
 migration model data transfer failed, failed to import model into target controller: execute operation import link layer devices: importing link layer devices: converting device "lxdbr0" on machine "0": converting address "10.136.55.1/24": no subnet found, nor created
```

However, this occurs in link layer devices import ([ref](https://github.com/juju/juju/blob/f3d234040cc8ad825373628d03e0b6d875a8bb28/domain/modelmigration/import.go#L83)) which is executed after machines import. So we know that the machine import was successful. 

Ideally, if the link layer device import succeeded, you should be able to juju status to see the hostnames set.

## Links

**Issue:** Fixes #18641.

**Jira card:** [JUJU-7682](https://warthogs.atlassian.net/browse/JUJU-7682)

[JUJU-7682]: https://warthogs.atlassian.net/browse/JUJU-7682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/machine/service/migration.go [hunk 1]
```diff
@@ -72,6 +72,7 @@ func NewMigrationService(
 // already exists.
 func (s *MigrationService) CreateMachine(
 	ctx context.Context,
+	hostname string,
```
Comment (wallyworld) [inline domain/machine/service/migration.go]: machineName is the primary param here.
Drop hostname down the list

File: domain/machine/state/migration.go [hunk 2]
```diff
@@ -118,6 +118,7 @@ func (st *State) InsertMigratingMachine(ctx context.Context, machineName string,
 			).Add(machineerrors.MachineAlreadyExists)
 		}
 		return CreateMachineWithName(ctx, tx, st, st.clock, machineName, CreateMachineArgs{
+			Hostname:    args.Hostname,
```
Comment (wallyworld) [inline domain/machine/state/migration.go]: Same here, i"d place it next to Nonce

File: domain/machine/state/types.go [hunk 3]
```diff
@@ -32,6 +32,9 @@ type CreateMachineArgs struct {
 	// HardwareCharacteristics contains the hardware characteristics for a
 	// manually provisioned machine.
 	HardwareCharacteristics instance.HardwareCharacteristics
+
+	// Hostname is the hostname of the machine.
+	Hostname string
```
Comment (wallyworld) [inline domain/machine/state/types.go]: Not sure this needs to be called out with its own comment. It's just a string, we can place it next to Platform above

File: domain/machine/types.go [hunk 4]
```diff
@@ -27,6 +27,9 @@ type ExportMachine struct {
 
 // CreateMachineArgs contains arguments for creating a machine.
 type CreateMachineArgs struct {
+	// Hostname is the hostname of the machine.
+	Hostname string
```
Comment (wallyworld) [inline domain/machine/types.go]: Move this down too

File: domain/machine/state/placement_test.go [hunk 5]
```diff
@@ -955,3 +961,20 @@ WHERE name = ?
 		c.Check(nonce.V, tc.Equals, *expected)
 	}
 }
+
+func (s *placementSuite) checkHostnameForMachine(c *tc.C, name machine.Name, expected string) {
+	var nonce sql.Null[string]
```
Comment (wallyworld) [inline domain/machine/state/placement_test.go]: typo

File: domain/machine/state/placement_test.go [hunk 6]
```diff
@@ -808,6 +811,7 @@ func (s *placementSuite) TestCreateMachineWithNameIndicatesUnmanagedMachine(c *t
 				MachineUUID: machineUUID.String(),
 				NetNodeUUID: netNodeUUID.String(),
 				InstanceID:  &instanceID,
+				Hostname:    "host-name-123",
```
Comment (wallyworld) [inline domain/machine/state/placement_test.go]: We don't really need this in this test. This test is about unmanaged machines.

We've coopted the TestCreateMachineWithName_PopulatesHardwareCharacteristics test to slide in a hostname check. But even there, that's not quite right.

Why not augment a test in migration_test.go, eg TestInsertMigratingMachine

**Review by wallyworld — COMMENTED** [review]
I don't think the state tests are in the right place

File: domain/machine/state/placement_test.go (hunk 5 above)
Comment (adisazhar123) [reply domain/machine/state/placement_test.go]: Thanks. It was a copy from existing helper

File: domain/machine/state/placement_test.go (hunk 6 above)
Comment (adisazhar123) [reply domain/machine/state/placement_test.go]: Makes sense to have it in migration_test. I was piggy-backing existing test but doesn't look to be in the right spot

**Review by wallyworld — APPROVED** [review]
Thank you

**Review by CodingCookieRookie — APPROVED** [review]
LGTM thanks adis!
