### PR TITLE
fix(cloud): cascade credential deletion when removing a cloud

### LINKED ISSUE #21791: Remove-cloud 3.6 -> 4.0 differences
### Remove cloud behaviour changed
The removal of k8s cloud is no longer automatically also cleaning up the credential. This breaks the Juju Terraform Provider when attempting to remove a k8s cloud it has just created, as the credential is implicitly created and not modelled in the plan.

This is because of this block: https://github.com/juju/juju/blob/cea469fd26b8c68d31ed625d8988d2d6be8cf1e4/domain/cloud/state/state.go#L651-L663

### Juju version

4.0

### Cloud

_No response_

### Expected behaviour

The cloud and it's implicitly created credential is removed.

### 3.6

In 3.6, the addition and removal of a k8s cloud worked as so:

1. Add k8s cloud
```bash
microk8s config | juju add-k8s alextest --controller 36
```

2. Cloud credential with same name as k8s cloud name created:
```bash
jj credentials                                         

Controller Credentials:
Cloud      Credentials
alextest   alextest
localhost  localhost
```

3. Remove the cloud
```bash
jj remove-cloud alextest                               
This operation can be applied to both a copy on this client and to the one on a controller.
Do you want to remove cloud alextest from:
    1. client only (--client)
    2. controller "36" only (--controller 36)
    3. both (--client --controller 36)
Enter your choice, or type Q|q to quit: 2
Removed details of cloud "alextest" from controller "36"
```

4. And it is successful, subsequently the credential is also removed:
```bash
jj credentials                                         

Controller Credentials:
Cloud      Credentials
localhost  localhost
```

### 4.0
In 4.0, if we attempt to remove the cloud, we receive the following:
```bash
jj remove-cloud alextest                               
This operation can be applied to both a copy on this client and to the one on a controller.
Do you want to remove cloud alextest from:
    1. client only (--client)
    2. controller "40" only (--controller 40)
    3. both (--client --controller 40)
Enter your choice, or type Q|q to quit: 2
ERROR deleting cloud "alextest": cannot delete cloud as it is still in use
```

### Notes & References

It appears intentional, but it does change the behaviour of removing clouds. It is fine if this is intentional, but I wanted to just confirm so I know if it should be fixed in Juju, or in the Terraform Provider (or both I guess given 4.0 is released already?)

### PR DESCRIPTION
**Pull request by nvinuesa**
DeleteCloud was blocking cloud removal when any cloud_credential existed, breaking the Terraform Provider for k8s clouds where credentials are implicitly created. This restores the 3.6 behaviour by cascading deletion of cloud_credential_attribute and cloud_credential rows, while guarding against removal of clouds referenced by models.

## QA steps

Bootstrap a controller, then add a cloud on it and then remove it (from the controller):
```
$ microk8s config | juju add-k8s alextest --controller c
$ juju remove-cloud alextest
This operation can be applied to both a copy on this client and to the one on a controller.
Do you want to remove cloud alextest from:
    1. client only (--client)
    2. controller "c" only (--controller c)
    3. both (--client --controller c)
Enter your choice, or type Q|q to quit: 2
Removed details of cloud "alextest" from controller "c"
```
Now, if you add a model referencing that cloud, then it's ok to prevent the removal:
```
$ juju add-model mm alextest
Added 'mm' model on alextest with credential 'alextest' for user 'admin'
To use "juju ssh", "juju scp" and "juju debug-hooks" ssh public keys need to be added to the model with "juju add-ssh-key"
$ juju remove-cloud alextest
This operation can be applied to both a copy on this client and to the one on a controller.
Do you want to remove cloud alextest from:
    1. client only (--client)
    2. controller "c" only (--controller c)
    3. both (--client --controller c)
Enter your choice, or type Q|q to quit: 2
ERROR deleting cloud "alextest": cannot delete cloud as it is still in use
```
## Links

**Issue:** Fixes #21791.

**Jira card:** [JUJU-9223](https://warthogs.atlassian.net/browse/JUJU-9223)

[JUJU-9223]: https://warthogs.atlassian.net/browse/JUJU-9223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/cloud/state/state.go [hunk 1]
```diff
@@ -700,7 +731,27 @@ WHERE  grant_on = $dbCloudName.name
...
 
 	return db.Txn(ctx, func(ctx context.Context, tx *sqlair.TX) error {
-		err := tx.Query(ctx, cloudRegionDeleteStmt, cloudName).Run()
+		// Check if any model references this cloud.
+		var count countResult
+		err := tx.Query(ctx, modelCountStmt, cloudName).Get(&count)
+		if err != nil {
+			return errors.Errorf("checking model references: %w", err)
+		}
+		if count.Count > 0 {
```
Comment (ale8k) [inline domain/cloud/state/state.go:749]: Isn't this business logic and should "technically" be called in the service layer?  Idm tbf though as it's a little count.

File: domain/cloud/state/state.go [hunk 2]
```diff
@@ -700,7 +731,27 @@ WHERE  grant_on = $dbCloudName.name
...
+			return errors.Errorf("cannot delete cloud as it is still in use")
+		}
+
+		// Cascade-delete credentials and their attributes.
```
Comment (ale8k) [inline domain/cloud/state/state.go:753]: There's no way we could know from the query it is a cascade delete?

File: domain/cloud/state/state.go [hunk 3]
```diff
@@ -641,21 +641,52 @@ func dbCloudFromCloud(ctx context.Context, tx *sqlair.TX, cloudUUID string, clou
 	return cld, nil
 }
 
-// DeleteCloud removes a cloud credential with the given name.
+// DeleteCloud removes a cloud and its associated credentials with the given
```
Comment (ale8k) [inline domain/cloud/state/state.go:644]: // DeleteCloud removes a cloud and **it's** associated credentials with the given

File: domain/cloud/state/state.go [hunk 4]
```diff
@@ -700,7 +731,27 @@ WHERE  grant_on = $dbCloudName.name
...
+		if count.Count > 0 {
+			return errors.Errorf("cannot delete cloud as it is still in use")
+		}
+
+		// Cascade-delete credentials and their attributes.
+		err = tx.Query(ctx, credAttrDeleteStmt, cloudName).Run()
+		if err != nil {
+			return errors.Errorf("deleting cloud credential attributes: %w", err)
+		}
+		err = tx.Query(ctx, credDeleteStmt, cloudName).Run()
```
Comment (ale8k) [inline domain/cloud/state/state.go:758]: Nit: I don't really like this being in DeleteCloud only because it's not immediately obvious why we're doing this if you aren't aware of how add-k8s works? Wouldn't it be better to have an explicit remove k8s credential call? Or at the minimum a godoc explaining that we also remove the cred of the same name as the cloud for k8s scenarios?

File: domain/cloud/state/state.go (hunk 1 above)
Comment (nvinuesa) [reply domain/cloud/state/state.go:749]: This is where the line gets blurrier. If we wanted to extract this count it'd mean having 2 transactions. Now, having two transactions in a Delete* is not problematic from a consistency point of view (in any case we are removing it - if it exists - on the second txn, and do nothing it if doesn't).
I personally prefer it here, but we can change if other people agree.

Comment (ale8k) [reply domain/cloud/state/state.go:749]: We could also have two methods and be super explicit? 

LIke DeleteK8SCloud and DeleteCloud? And then have a lil cloud type check in svc? That way when you follow the code it's another "hey k8s is actually different" scenario, rather than "hey why are we randomly deleting a cred of the same name" with no explanation next to it is all I meant.

I wasn't suggesting we remove the atomicity btw.

Comment (nvinuesa) [reply domain/cloud/state/state.go:749]: I'm confused then. The count there is done to check before removal on the same txn for atomicity. The fact that we remove cloud credentials as well is independent of k8s.

File: domain/cloud/state/state.go (hunk 2 above)
Comment (nvinuesa) [reply domain/cloud/state/state.go:753]: We avoid `ON DELETE CASCADE`s in favor of explicit ordered deletions.

File: domain/cloud/state/state.go (hunk 4 above)
Comment (nvinuesa) [reply domain/cloud/state/state.go:758]: Again, this is not k8s specific, it just removes cloud credentials independent of the provider. I might me missing something or misunderstanding the comment though.

File: domain/cloud/state/state.go (hunk 3 above)
Comment (nvinuesa) [reply domain/cloud/state/state.go:644]: I think `its` (possessive pr., i.e. cloud owned credentials) is correct .

Comment (ale8k) [reply domain/cloud/state/state.go:644]: Ah sorry misread it lol! Resolved

File: domain/cloud/state/state.go (hunk 1 above)
Comment (ale8k) [reply domain/cloud/state/state.go:749]: As discussed resolved!

File: domain/cloud/state/state.go (hunk 4 above)
Comment (ale8k) [reply domain/cloud/state/state.go:758]: As discussed resolved!

**Review by ale8k — APPROVED** [review]
Ty for this!

File: domain/cloud/state/state.go [hunk 5]
```diff
@@ -700,7 +740,27 @@ WHERE  grant_on = $dbCloudName.name
...
 	return db.Txn(ctx, func(ctx context.Context, tx *sqlair.TX) error {
-		err := tx.Query(ctx, cloudRegionDeleteStmt, cloudName).Run()
+		// Check if any model references this cloud.
+		var count countResult
+		err := tx.Query(ctx, modelCountStmt, cloudName).Get(&count)
+		if err != nil {
+			return errors.Errorf("checking model references: %w", err)
+		}
+		if count.Count > 0 {
+			return errors.Errorf("cannot delete cloud as it is still in use")
```
Comment (SimonRichardson) [inline domain/cloud/state/state.go]: Something like and then transform the error at the apiserver level.

```suggestion
			return errors.Errorf("deleting cloud").Add(clouderrors.CloudStillInUse)
```

Comment (nvinuesa) [reply domain/cloud/state/state.go]: Indeed, done!
