### PR TITLE
fix(modelmigration): create external users on model import

### LINKED ISSUE #22099: Importing credentials doesn't create external users
### Description

When importing a 3.6 model with an associated external user(s) we don't create the external users and so will fail to import the model.

We do create an external user when the user logs in (which is the work around), but that can't be done in production as each user would have to login to the destination controller to create the user, so that you can migrate the model.

This works if you already have the external user on the destination controller.

### Juju version

4.0-HEAD

### Cloud

_No response_

### Expected behaviour

Juju should migrate the model.

### Reproduce / Test

Setup a 3.6 controller and model:

```sh
$ /snap/bin/juju bootstrap localhost from --config identity-url=https://api.jujucharms.com/identity --config allow-model-access=true
$ /snap/bin/juju grant <your LP ID>@external superuser
$ /snap/bin/juju change-user-password admin
$ /snap/bin/juju logout
$ /snap/bin/juju login
$ /snap/bin/juju whoami
$ /snap/bin/juju update-credentials localhost localhost
$ /snap/bin/juju add-model foo
$ /snap/bin/juju deploy juju-qa-test
```

Now bootstrap a 4.0 controller:

```sh
$ juju bootstrap localhost to --config identity-url=https://api.jujucharms.com/identity --config allow-model-access=true
$ juju migrate from:foo to
```

This will fail with the following error:

```
juju show-status-log -m from:foo --type model
Time                   Type   Status     Message
27 Mar 2026 09:50:01Z  model  available
27 Mar 2026 09:50:59Z  model  busy       migrating: starting
27 Mar 2026 09:50:59Z  model  busy       migrating: performing source prechecks
27 Mar 2026 09:50:59Z  model  busy       migrating: performing target prechecks
27 Mar 2026 09:50:59Z  model  busy       migrating: quiescing, waiting for agents to report back
27 Mar 2026 09:50:59Z  model  busy       migrating: quiescing, all agents reported success
27 Mar 2026 09:50:59Z  model  busy       migrating: performing source prechecks
27 Mar 2026 09:50:59Z  model  busy       migrating: performing target prechecks
27 Mar 2026 09:50:59Z  model  busy       migrating: exporting model
27 Mar 2026 09:50:59Z  model  busy       migrating: importing model into target controller
27 Mar 2026 09:50:59Z  model  busy       migrating: model data transfer failed, failed to import model into target controller: execute operation import cloud credential: updating credential: getting user uuid for credential owner "simonrichardson@external": user not found when finding user uuid for name "simonrichardson@external"
27 Mar 2026 09:50:59Z  model  busy       migrating: aborted, removing model from target controller: model data transfer failed, failed to import model into target controller: execute operation import cloud credential: updating credential: getting user uuid for credential owner "simonrichardson@external": user not found when finding user uuid for name "simonrichardson@external"
27 Mar 2026 09:50:59Z  model  available  migrating: aborted, removing model from target controller: model data transfer failed, failed to import model into target controller: execute operation import cloud credential: updating credential: getting user uuid for credential owner "simonrichardson@external": user not found when finding user uuid for name "simonrichardson@external"
```

### Notes & References

The model d

```yaml
actions:
  actions: []
  version: 4
agent-version: ""
applications:
  applications:
  - charm-actions:
      actions:
        fortune:
          description: Returns a pithy phrase.
          execution-group: ""
          parallel: false
          parameters:
            description: Returns a pithy phrase.
            properties:
              fail:
                default: ""
                description: Fail with this message
                type: string
            title: fortune
            type: object
      version: 1
    charm-configs:
      configs:
        foo-file:
          default: false
          description: Get resource and set log contents of foo-file as Info.
          type: boolean
        skill:
          default: 0
          description: Skill level.
          type: int
        status:
          default: hello
          description: Temporary string for unit status
          type: string
        thing:
          default: "\U0001F381"
          description: A thing used by the charm.
          type: string
      version: 1
    charm-manifest:
      bases:
      - architectures:
        - amd64
        - arm64
        channel: 16.04/stable
        name: ubuntu
      - architectures:
        - amd64
        - arm64
        channel: 18.04/stable
        name: ubuntu
      - architectures:
        - amd64
        - arm64
        channel: 20.04/stable
        name: ubuntu
      - architectures:
        - amd64
        - arm64
        channel: 22.04/stable
        name: ubuntu
      version: 1
    charm-metadata:
      assumes: "null"
      description: |
        A container-based V2 metadata charm to use in testing juju.
        It has config, actions, resources, and a relation.
      lxd-profile: '{"config":{},"description":"","devices":{}}'
      min-juju-version: 0.0.0
      name: juju-qa-test
      requires:
        info:
          interface: juju-info
          limit: 0
          name: info
          optional: false
          role: requirer
          scope: container
      resources:
        foo-file:
          description: foo resource.
          name: foo-file
          path: foo.txt
          type: file
      summary: |
        A container-based V2 metadata charm to use in testing juju.
      version: 1
    charm-mod-version: 0
    charm-origin:
      channel: latest/stable
      hash: 5566ed1bd22c4bd87fd42d169abc1dfccde88205e6db079e3ec69ec218f6fc25
      id: Hw30RWzpUBnJLGtO71SX8VDWvd3WrjaJ
      platform: amd64/ubuntu/20.04
      revision: 25
      source: charm-hub
      version: 2
    charm-url: ch:amd64/juju-qa-test-25
    constraints:
      architecture: amd64
      version: 5
    cs-channel: ""
    endpoint-bindings:
      "": "0"
      info: "0"
    leadership-settings: {}
    name: juju-qa-test
    operator-status:
      status:
        neverset: false
        updated: "0001-01-01T00:00:00Z"
        value: ""
      version: 2
    resources:
      resources:
      - application-revision:
          description: foo resource.
          fingerprint: a93ba5aa9c3987a672fec9c977eaef5c54ba89519bdaf1b1f33be51a3145bc1369b91e1513fe944f33d7c25f5ed0ad9c
          origin: store
          path: foo.txt
          revision: 2
          size: 13
          type: file
        charmstore-revision:
          description: foo resource.
          fingerprint: a93ba5aa9c3987a672fec9c977eaef5c54ba89519bdaf1b1f33be51a3145bc1369b91e1513fe944f33d7c25f5ed0ad9c
          origin: store
          path: foo.txt
          revision: 2
          size: 13
          type: file
        name: foo-file
      version: 1
    settings: {}
    status:
      status:
        neverset: false
        updated: "2026-03-27T09:50:15.029400208Z"
        value: unset
      version: 2
    status-history:
      history:
      - neverset: false
        updated: "2026-03-27T09:50:15.029400208Z"
        value: unset
      version: 2
    type: iaas
    units:
      units:
      - agent-status:
          status:
            neverset: false
            updated: "2026-03-27T09:50:56.738464332Z"
            value: idle
          version: 2
        agent-status-history:
          history:
          - neverset: false
            updated: "2026-03-27T09:50:59.665449155Z"
            value: idle
          - message: running start hook
            neverset: false
            updated: "2026-03-27T09:50:56.369814065Z"
            value: executing
          - message: running config-changed hook
            neverset: false
            updated: "2026-03-27T09:50:56.045360258Z"
            value: executing
          - message: running leader-elected hook
            neverset: false
            updated: "2026-03-27T09:50:55.75659892Z"
            value: executing
          - message: running install hook
            neverset: false
            updated: "2026-03-27T09:50:55.137897952Z"
            value: executing
          - neverset: false
            updated: "2026-03-27T09:50:15.044763249Z"
            value: allocating
          version: 2
        constraints:
          architecture: amd64
          version: 5
        machine: "0"
        name: juju-qa-test/0
        password-hash: 4npK8yfQf5xvFRKNQHtPWwpS
        payloads:
          payloads: []
          version: 1
        resources:
          resources: []
          version: 1
        tools:
          sha256: ""
          size: 0
          tools-version: 3.6.20-ubuntu-amd64
          url: ""
          version: 2
        uniter-state: |
          leader: true
          started: true
          stopped: false
          installed: true
          removed: false
          status-set: true
          op: continue
          opstep: pending
          config-hash: 07a0277e88e42b1448033e399e1e30e7fe22796afdfbbc0d340d57d2bb7b37a8
          trust-hash: 41ace2e915732d81472608ff949197960dd04d590598e76a532a863f17f750f2
          addresses-hash: 25379e9600cc719cb419b63f233deeb19af757ef90a1b4cdcee336b1e6a7965a
        workload-status:
          status:
            message: hello
            neverset: false
            updated: "2026-03-27T09:50:56.127213822Z"
            value: active
          version: 2
        workload-status-history:
          history:
          - message: hello
            neverset: false
            updated: "2026-03-27T09:50:56.127213822Z"
            value: active
          - message: installing charm software
            neverset: false
            updated: "2026-03-27T09:50:55.131050178Z"
            value: maintenance
          - message: agent initialising
            neverset: false
            updated: "2026-03-27T09:50:53.984333638Z"
            value: waiting
          - message: installing agent
            neverset: false
            updated: "2026-03-27T09:50:53.887817066Z"
            value: waiting
          - message: waiting for machine
            neverset: false
            updated: "2026-03-27T09:50:15.044763249Z"
            value: waiting
          version: 2
        workload-version-history:
          history:
          - neverset: false
            updated: "2026-03-27T09:50:15.044763249Z"
            value: unknown
          version: 2
      version: 3
  version: 14
cloud: localhost
cloud-credential:
  attributes:
    client-cert: |
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    client-key: |
      -----BEGIN EC PRIVATE KEY-----
      -----END EC PRIVATE KEY-----
    server-cert: |
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
  auth-type: certificate
  cloud: localhost
  name: localhost
  owner: <lp user id>@external
  version: 2
cloud-image-metadata:
  cloudimagemetadata:
  - arch: amd64
    date-created: 1774605015874981141
    image-id: ami-013c7686735b77f96
    priority: 10
    region: eu-south-2
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874983967
    image-id: ami-01637463b2cbe7cb6
    priority: 10
    region: eu-north-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874984287
    image-id: ami-01775358d07d09cb0
    priority: 10
    region: mx-central-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874984498
    image-id: ami-01b9f61899f9bb1fa
    priority: 10
    region: ca-west-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874984788
    image-id: ami-02ab616bef07ac291
    priority: 10
    region: eu-west-3
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874985069
    image-id: ami-033d9c6fcfad7c42e
    priority: 10
    region: eu-central-2
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874985249
    image-id: ami-03ab230a152fe777b
    priority: 10
    region: ap-northeast-3
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874985440
    image-id: ami-0495a93f1f3b4a562
    priority: 10
    region: ca-central-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874985870
    image-id: ami-05e7ecda2dd8dcb7a
    priority: 10
    region: eu-south-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874986081
    image-id: ami-065c8be12b0c71019
    priority: 10
    region: ap-east-2
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874986261
    image-id: ami-065dc5b24996c2a07
    priority: 10
    region: ap-southeast-7
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874986451
    image-id: ami-066489b5435ba6817
    priority: 10
    region: sa-east-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874986662
    image-id: ami-06abd59faf3628aaf
    priority: 10
    region: me-central-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874986852
    image-id: ami-06cc5ebfb8571a147
    priority: 10
    region: ap-south-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874987043
    image-id: ami-06cd25c905a7e9a0f
    priority: 10
    region: ap-southeast-2
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874987223
    image-id: ami-076838d6a293cb49e
    priority: 10
    region: us-east-2
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874987413
    image-id: ami-07b99ebf9e44f72bc
    priority: 10
    region: ap-southeast-3
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874987624
    image-id: ami-0836e97b3d843dd82
    priority: 10
    region: ap-northeast-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874987824
    image-id: ami-08b138b7cf65145b1
    priority: 10
    region: ap-southeast-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874988014
    image-id: ami-08dc1096b47733f08
    priority: 10
    region: af-south-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874988205
    image-id: ami-08fe9bdd11670668e
    priority: 10
    region: us-west-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874988385
    image-id: ami-0910be1e1d214d762
    priority: 10
    region: eu-west-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874988575
    image-id: ami-0a15226b1f7f23580
    priority: 10
    region: us-west-2
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874988766
    image-id: ami-0afdf9b39792adf4f
    priority: 10
    region: ap-southeast-6
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874988946
    image-id: ami-0bcb89ed2c3d0e585
    priority: 10
    region: me-south-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874989137
    image-id: ami-0c021d3a56971d13a
    priority: 10
    region: ap-south-2
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874989357
    image-id: ami-0ce9159196fa630f0
    priority: 10
    region: ap-east-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874989547
    image-id: ami-0cebfb1f908092578
    priority: 10
    region: eu-central-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874989738
    image-id: ami-0cf5279adbb219ec9
    priority: 10
    region: ap-southeast-4
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874989918
    image-id: ami-0d31a417c2e969eb4
    priority: 10
    region: il-central-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874990108
    image-id: ami-0f321d890424a6390
    priority: 10
    region: eu-west-2
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874990299
    image-id: ami-0f8d552e06067b477
    priority: 10
    region: ap-northeast-2
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874990489
    image-id: ami-0fb0b230890ccd1e6
    priority: 10
    region: us-east-1
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  - arch: amd64
    date-created: 1774605015874990679
    image-id: ami-0fc5fa8f3d2860a8f
    priority: 10
    region: ap-southeast-5
    root-storage-type: ssd
    source: default ubuntu cloud images
    stream: released
    version: "20.04"
    virt-type: hvm
  version: 2
cloud-region: default
config:
  agent-metadata-url: ""
  agent-stream: released
  agent-version: 3.6.20
  apt-ftp-proxy: ""
  apt-http-proxy: ""
  apt-https-proxy: ""
  apt-mirror: ""
  apt-no-proxy: ""
  authorized-keys: ssh-rsa 
  automatically-retry-hooks: true
  backup-dir: ""
  charmhub-url: https://api.charmhub.io
  cloudinit-userdata: ""
  container-image-metadata-defaults-disabled: false
  container-image-metadata-url: ""
  container-image-stream: released
  container-inherit-properties: ""
  container-networking-method: local
  default-base: ""
  default-space: ""
  development: false
  disable-network-management: false
  disable-telemetry: false
  egress-subnets: ""
  enable-os-refresh-update: true
  enable-os-upgrade: true
  fan-config: ""
  firewall-mode: instance
  ftp-proxy: ""
  http-proxy: ""
  https-proxy: ""
  ignore-machine-addresses: false
  image-metadata-defaults-disabled: false
  image-metadata-url: ""
  image-stream: released
  juju-ftp-proxy: ""
  juju-http-proxy: ""
  juju-https-proxy: ""
  juju-no-proxy: 127.0.0.1,localhost,::1
  logforward-enabled: false
  logging-config: <root>=DEBUG;juju.apiserver=INFO;juju.mgo=INFO;juju.rpc=INFO;juju.worker.httpserver=INFO;juju.worker.peergrouper=INFO;juju.replicaset=INFO;juju.state.pool.txnwatcher=INFO;juju.worker.dependency=TRACE;juju.security=ERROR
  logging-output: ""
  lxd-snap-channel: 5.0/stable
  max-action-results-age: 336h
  max-action-results-size: 5G
  max-status-history-age: 336h
  max-status-history-size: 5G
  mode: requires-prompts
  name: foo
  net-bond-reconfigure-delay: 17
  no-proxy: 127.0.0.1,localhost,::1
  num-container-provision-workers: 4
  num-provision-workers: 16
  project: default
  provisioner-harvest-mode: destroyed
  proxy-ssh: false
  resource-tags: ""
  saas-ingress-allow: 0.0.0.0/0,::/0
  secret-backend: auto
  snap-http-proxy: ""
  snap-https-proxy: ""
  snap-store-assertions: ""
  snap-store-proxy: ""
  snap-store-proxy-url: ""
  ssh-allow: 0.0.0.0/0,::/0
  ssl-hostname-verification: true
  storage-default-filesystem-source: lxd
  test-mode: false
  transmit-vendor-metrics: true
  type: lxd
  update-status-hook-interval: 5m
  uuid: 45f51cad-4d34-400c-87ca-c7fdb56a1322
environ-version: 1
external-controllers:
  external-controllers: []
  version: 1
filesystems:
  filesystems: []
  version: 1
firewall-rules:
  firewall-rules: []
  version: 1
ip-addresses:
  ip-addresses:
  - config-method: static
    device-name: eth0
    dns-search-domains: []
    dns-servers: []
    gateway-address: 10.232.51.1
    is-default-gateway: false
    is-secondary: false
    is-shadow: false
    machine-id: "0"
    origin: machine
    provider-network-id: net-lxdbr0
    provider-subnet-id: subnet-lxdbr0-10.232.51.0/24
    subnet-cidr: 10.232.51.0/24
    value: 10.232.51.157
  - config-method: loopback
    device-name: lo
    dns-search-domains: []
    dns-servers: []
    gateway-address: ""
    is-default-gateway: false
    is-secondary: false
    is-shadow: false
    machine-id: "0"
    origin: machine
    subnet-cidr: 127.0.0.0/8
    value: 127.0.0.1
  - config-method: loopback
    device-name: lo
    dns-search-domains: []
    dns-servers: []
    gateway-address: ""
    is-default-gateway: false
    is-secondary: false
    is-shadow: false
    machine-id: "0"
    origin: machine
    subnet-cidr: ::1/128
    value: ::1
  version: 5
link-layer-devices:
  link-layer-devices:
  - is-autostart: true
    is-up: true
    mac-address: ""
    machine-id: "0"
    mtu: 65536
    name: lo
    parent-name: ""
    type: loopback
  - is-autostart: true
    is-up: true
    mac-address: 00:16:3e:94:a9:4e
    machine-id: "0"
    mtu: 1500
    name: eth0
    parent-name: ""
    provider-id: nic-00:16:3e:94:a9:4e
    type: ethernet
  version: 1
machines:
  machines:
  - base: ubuntu@20.04/stable
    block-devices:
      block-devices: []
      version: 2
    constraints:
      architecture: amd64
      version: 5
    containers: []
    id: "0"
    instance:
      architecture: amd64
      availability-zone: simon-work
      instance-id: juju-6a1322-0
      modification-status:
        status:
          neverset: false
          updated: "2026-03-27T09:50:59.597703678Z"
          value: applied
        version: 2
      status:
        status:
          message: Running
          neverset: false
          updated: "2026-03-27T09:50:19.066708357Z"
          value: running
        version: 2
      status-history:
        history:
        - message: Running
          neverset: false
          updated: "2026-03-27T09:50:19.066708357Z"
          value: running
        - message: Container started
          neverset: false
          updated: "2026-03-27T09:50:16.400423334Z"
          value: running
        - message: Creating container
          neverset: false
          updated: "2026-03-27T09:50:15.911395592Z"
          value: allocating
        - message: acquiring LXD image
          neverset: false
          updated: "2026-03-27T09:50:15.899820436Z"
          value: allocating
        - message: starting
          neverset: false
          updated: "2026-03-27T09:50:15.888222347Z"
          value: allocating
        - neverset: false
          updated: "2026-03-27T09:50:15.070292152Z"
          value: pending
        version: 2
      version: 6
      virt-type: container
    jobs:
    - host-units
    machine-addresses:
    - origin: machine
      scope: local-cloud
      type: ipv4
      value: 10.232.51.157
      version: 2
    - origin: machine
      scope: local-machine
      type: ipv4
      value: 127.0.0.1
      version: 2
    - origin: machine
      scope: local-machine
      type: ipv6
      value: ::1
      version: 2
    nonce: machine-0:eabb01b1-1b36-4f81-86b8-f4040eb53f98
    password-hash: FUjwqsn93clRVMNE5Zo375U1
    preferred-private-address:
      origin: provider
      scope: local-cloud
      spaceid: "0"
      type: ipv4
      value: 10.232.51.157
      version: 2
    preferred-public-address:
      origin: provider
      scope: local-cloud
      spaceid: "0"
      type: ipv4
      value: 10.232.51.157
      version: 2
    provider-addresses:
    - origin: provider
      scope: local-cloud
      spaceid: "0"
      type: ipv4
      value: 10.232.51.157
      version: 2
    status:
      status:
        neverset: false
        updated: "2026-03-27T09:50:53.938252583Z"
        value: started
      version: 2
    status-history:
      history:
      - neverset: false
        updated: "2026-03-27T09:50:59.587909353Z"
        value: started
      - neverset: false
        updated: "2026-03-27T09:50:15.070292152Z"
        value: pending
      version: 2
    supported-containers:
    - lxd
    tools:
      sha256: ""
      size: 0
      tools-version: 3.6.20-ubuntu-amd64
      url: ""
      version: 2
  version: 3
meter-status:
  code: ""
  info: ""
offer-connections:
  offer-connections: []
  version: 1
operations:
  operations: []
  version: 2
owner: <lp user id>@external
relation-networks:
  relation-networks: []
  version: 1
relations:
  relations: []
  version: 3
remote-applications:
  remote-applications: []
  version: 3
remote-entities:
  remote-entities: []
  version: 1
remote-secrets:
  remote-secrets: []
  version: 1
secrets:
  secrets: []
  version: 2
sequences:
  application-juju-qa-test: 1
  machine: 1
  modelmigration: 1
  subnet: 4
sla:
  credentials: ""
  level: unsupported
  owner: ""
spaces:
  spaces: []
  version: 2
ssh-host-keys:
  ssh-host-keys:
  - keys:
    - |
      
    machine-id: "0"
  version: 1
status:
  status:
    message: 'migrating: aborted, removing model from target controller: model data
      transfer failed, failed to import model into target controller: execute operation
      import cloud credential: updating credential: getting user uuid for credential
      owner "<lp user id>@external": user not found when finding user uuid for
      name "<lp user id>@external"'
    neverset: false
    updated: "2026-03-27T09:50:59.522929714Z"
    value: available
  version: 2
status-history:
  history:
  - message: 'migrating: aborted, removing model from target controller: model data
      transfer failed, failed to import model into target controller: execute operation
      import cloud credential: updating credential: getting user uuid for credential
      owner "<lp user id>@external": user not found when finding user uuid for
      name "<lp user id>@external"'
    neverset: false
    updated: "2026-03-27T09:50:59.522929714Z"
    value: available
  - message: 'migrating: aborted, removing model from target controller: model data
      transfer failed, failed to import model into target controller: execute operation
      import cloud credential: updating credential: getting user uuid for credential
      owner "<lp user id>@external": user not found when finding user uuid for
      name "<lp user id>@external"'
    neverset: false
    updated: "2026-03-27T09:50:59.504762151Z"
    value: busy
  - message: 'migrating: model data transfer failed, failed to import model into target
      controller: execute operation import cloud credential: updating credential:
      getting user uuid for credential owner "<lp user id>@external": user not
      found when finding user uuid for name "<lp user id>@external"'
    neverset: false
    updated: "2026-03-27T09:50:59.497564443Z"
    value: busy
  - message: 'migrating: importing model into target controller'
    neverset: false
    updated: "2026-03-27T09:50:59.471243509Z"
    value: busy
  - message: 'migrating: exporting model'
    neverset: false
    updated: "2026-03-27T09:50:59.442256115Z"
    value: busy
  - message: 'migrating: performing target prechecks'
    neverset: false
    updated: "2026-03-27T09:50:59.436054628Z"
    value: busy
  - message: 'migrating: performing source prechecks'
    neverset: false
    updated: "2026-03-27T09:50:59.399896047Z"
    value: busy
  - message: 'migrating: quiescing, all agents reported success'
    neverset: false
    updated: "2026-03-27T09:50:59.370320327Z"
    value: busy
  - message: 'migrating: quiescing, waiting for agents to report back'
    neverset: false
    updated: "2026-03-27T09:50:59.354296211Z"
    value: busy
  - message: 'migrating: performing target prechecks'
    neverset: false
    updated: "2026-03-27T09:50:59.330864099Z"
    value: busy
  - message: 'migrating: performing source prechecks'
    neverset: false
    updated: "2026-03-27T09:50:59.318355033Z"
    value: busy
  - message: 'migrating: starting'
    neverset: false
    updated: "2026-03-27T09:50:59.265140428Z"
    value: busy
  - neverset: false
    updated: "2026-03-27T09:50:01.002416443Z"
    value: available
  version: 2
storage-pools:
  pools:
  - attributes:
      driver: btrfs
      lxd-pool: juju-btrfs
    name: lxd-btrfs
    provider: lxd
  - attributes:
      driver: zfs
      lxd-pool: juju-zfs
      zfs.pool_name: juju-lxd
    name: lxd-zfs
    provider: lxd
  version: 1
storages:
  storages: []
  version: 3
subnets:
  subnets:
  - availability-zones:
    - simon-work
    cidr: 10.232.51.0/24
    is-public: false
    provider-id: subnet-lxdbr0-10.232.51.0/24
    provider-network-id: net-lxdbr0
    space-id: "0"
    space-name: ""
    subnet-id: "0"
    vlan-tag: 0
  - availability-zones:
    - simon-work
    cidr: 172.18.0.0/16
    is-public: false
    provider-id: subnet-br-b6d5223e1224-172.18.0.0/16
    provider-network-id: net-br-b6d5223e1224
    space-id: "0"
    space-name: ""
    subnet-id: "1"
    vlan-tag: 0
  - availability-zones:
    - simon-work
    cidr: 172.19.0.0/16
    is-public: false
    provider-id: subnet-br-c4c8dcf391f5-172.19.0.0/16
    provider-network-id: net-br-c4c8dcf391f5
    space-id: "0"
    space-name: ""
    subnet-id: "2"
    vlan-tag: 0
  - availability-zones:
    - simon-work
    cidr: 172.17.0.0/16
    is-public: false
    provider-id: subnet-docker0-172.17.0.0/16
    provider-network-id: net-docker0
    space-id: "0"
    space-name: ""
    subnet-id: "3"
    vlan-tag: 0
  version: 6
type: iaas
users:
  users:
  - access: admin
    created-by: <lp user id>@external
    date-created: "2026-03-27T09:50:01Z"
    display-name: <lp user id>
    name: <lp user id>@external
  version: 1
version: 12
virtual-host-keys:
  version: 1
  virtual-host-keys:
  - host-key: 
    id: machine-0-hostkey
volumes:
  version: 1
  volumes: []
```

### PR DESCRIPTION
**Pull request by gfouillet**
When migrating a model from a 3.6 controller to a 4.0 controller, external
users (e.g. `<your LP user>@external`) that had been granted access to the model
were not created on the target controller. This caused the migration to fail
with `user not found` when trying to grant model permissions.

This change fixes the issue by introducing a dedicated migration operation
that creates missing external users on the target controller early in the
import pipeline — before credential import — since an external user may be
the model owner referenced during credential import. Each external user is
created with `everyone@external` as creator (consistent with how external
users are materialised on first authentication), preserving their original
display name and creation date. If the user already exists it is silently
skipped.

**Changes:**
- `domain/access/modelmigration/import.go`: New `importExternalUsersOperation`
  registered via `RegisterExternalUsersImport`; handles only external user
  creation. The existing `importOperation` (permissions + last-login) is
  unchanged in purpose but no longer manages user creation.
- `domain/modelmigration/import.go`: `RegisterExternalUsersImport` is
  registered between `externalcontroller.RegisterImport` and
  `credential.RegisterImport` to guarantee external users exist before
  credentials are imported.
- `domain/access/service/import.go`: New `UserService.ImportExternalUsers`
  method — looks up `everyone@external` UUID, creates each external user with
  `AddUserWithCreatedAt`, silently skips users that already exist.
- `domain/access/state/user.go`: New `AddUserWithCreatedAt` state method that
  preserves the caller-supplied creation timestamp.
- `domain/access/internal/types.go`: New `ExternalUserImport` struct carrying
  the data needed to recreate an external user.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [x] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

> Reproduces the scenario from [issue #22099](https://github.com/juju/juju/issues/22099).

1. Bootstrap a 3.6 controller, grant an external user access to a model, then
   migrate to a 4.0 controller built from this branch.

```sh
juju_36 bootstrap localhost src36
juju_36 grant <your LP user>@external superuser
juju_36 change-user-password admin
juju_36 logout
juju_36 login # will login with your ldap user
juju_36 add-model moveme # will create a model owned by you
juju bootstrap lxd dst40   # built from this branch
juju migrate src36:moveme dst40
```

2. Verify the migration succeeds and the external user has the expected
   permission on the target controller.

```sh
juju users -m dst40:moveme
```

3. Check migration status

```sh
juju show-status-log -m src36:moveme --type mode
juju switch dst40
juju models --all
```

## Documentation changes

None — this is a bug fix with no user-visible API or CLI changes.

## Links

**Issue:** Fixes #22099.

**Jira card:** [JUJU-9513](https://warthogs.atlassian.net/browse/JUJU-9513)

[JUJU-9513]: https://warthogs.atlassian.net/browse/JUJU-9513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/access/service/import.go [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+		)
+	}
+
+	for _, u := range users {
+		userUUID, err := user.NewUUID()
+		if err != nil {
+			return errors.Errorf("generating UUID for user %q: %w", u.Name, err)
+		}
+
+		err = s.st.AddUserWithCreatedAt(
```
Comment (hmlanigan) [inline domain/access/service/import.go:47]: question: Why can't we add them all at once? Rather than one at a time?

File: domain/access/modelmigration/import.go [hunk 2]
```diff
@@ -87,42 +93,84 @@ func (i *importOperation) Setup(scope modelmigration.Scope) error {
...
-	for _, u := range model.Users() {
+// userImport holds the common data needed to create permissions and record
+// the last model login for any user (local or external) during import.
+type userImport struct {
+	Name           user.Name
+	Access         corepermission.Access
+	LastConnection time.Time
+}
+
+func (i *importOperation) fetchUsers(
```
Comment (SimonRichardson) [inline domain/access/modelmigration/import.go]:
```suggestion
func (i *importOperation) collectUsers(
```

nit: I think fetch implies getting something from the database.

**Comment by nvinuesa** [comment]
I think there is a problem (still investigating if it's related to your changes). When I do a full QA (not the one you displayed, but one with login providers and actual logged in external users I get this error:
```
machine-0: 09:30:55 ERROR juju.apiserver import failed: execute operation import cloud credential: updating credential: getting user uuid for credential owner "nvinuesa@external": user not found when finding user uuid for name "nvinuesa@external"
```

**Comment by nvinuesa** [comment]
@gfouillet this is the QA I ran:
```
$ juju_36 bootstrap lxd c36 --config identity-url=https://api.jujucharms.com/identity
$ juju_36 change-user-password admin
$ juju_36 grant nvinuesa@external superuser -c c36
$ juju_36 logout
$ juju_36 update-credential localhost localhost
$ juju_36 login -u nvinuesa@external   
$ juju_36 add-model m             
$ juju_36 deploy ubuntu
# then on this branch:
$ juju bootstrap lxd dst40 --config identity-url=https://api.jujucharms.com/identity --build-agent
$ juju migrate c36:m dst40
```

**Comment by nvinuesa** [comment]
The issue is in the ordering of imports, credentials need the user to be there:
https://github.com/juju/juju/blob/918d102a1941ac139a4ebf580bf625dd810cd3a8/domain/credential/state/state.go#L335

(I hope this isn't a chicken and egg issue)

**Comment by gfouillet** [comment]
> @gfouillet this is the QA I ran:
> 
> ```
> $ juju_36 bootstrap lxd c36 --config identity-url=https://api.jujucharms.com/identity
> $ juju_36 change-user-password admin
> $ juju_36 grant nvinuesa@external superuser -c c36
> $ juju_36 logout
> $ juju_36 update-credential localhost localhost
> $ juju_36 login -u nvinuesa@external   
> $ juju_36 add-model m             
> $ juju_36 deploy ubuntu
> # then on this branch:
> $ juju bootstrap lxd dst40 --config identity-url=https://api.jujucharms.com/identity --build-agent
> $ juju migrate c36:m dst40
> ```

@nvinuesa 
Looks strange because the only difference is update credentials step. In my simpler QA step i just removed it since what we want is that the external user is the owner, and yes, external user are created before any cred import.

I will dig a bit. Are you sure you use the right fresh build from the branch when you were QAing ?

**Comment by gfouillet** [comment]
@nvinuesa Actually this is on me:
image

Thanks for your vigilance.

File: domain/access/service/import.go (hunk 1 above)
Comment (gfouillet) [reply domain/access/service/import.go:47]: I think we could, but I just use existing AddUser code to do it and it was not designed as batch. Adding a user requires insert in several table (user and user_authentication), and I don't think we should diverge too much path to insert users. 

This would requires a refactoring.
