### PR TITLE
fix: missing availability zones for lxd machines

### LINKED ISSUE #20150: Machine AZ column on juju status is empty on LXD cluster models
### Description

As per title, when Juju is adding machines to LXD model, if in LXD cluster, then the machines are added to different LXD nodes. Juju is treating each node as a zone. However, this information is not present in the juju status. Instead the relevant field is empty.

### Juju version

3.6.7

### Cloud

LXD

### Expected behaviour

`AZ` column is filled with the proper zone: e.g., `hp-1`

### Reproduce / Test

```
juju add model maas
juju add-machine --constraints="virt-type=virtual-machine" --base=ubuntu@24.04 -n 6
juju status
...
Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.240.246.4  juju-e8664b-0  ubuntu@24.04      Running
1        started  10.240.246.5  juju-e8664b-1  ubuntu@24.04      Running
2        started  10.240.246.6  juju-e8664b-2  ubuntu@24.04      Running
3        started  10.240.246.7  juju-e8664b-3  ubuntu@24.04      Running
4        started  10.240.246.8  juju-e8664b-4  ubuntu@24.04      Running
6        started  10.240.246.9  juju-e8664b-6  ubuntu@22.04      Running
```

### Notes & References

Information is known to Juju as it is revealed in the debug logs, when Juju is provisioning machines:

```bash
controller-0: 14:19:07 INFO juju.worker.provisioner provisioning in zones: [hp-1 hp-2 hp-3]
controller-0: 14:19:13 INFO juju.worker.provisioner trying machine 6 StartInstance in availability zone hp-2
```

### PR DESCRIPTION
**Pull request by adisazhar123**
We missed setting `AvailabilityZone` field in `HardwareCharacteristics` struct. As a result we were getting empty string for availability zones. While the user reported it using LXD clustering, this was also apparent in non-clustered mode.

Missing values in `az` column:

```text
(base) ➜  juju-upstream git:(3.6) ✗ juju status
Model       Controller  Cloud/Region         Version  SLA          Timestamp
controller  az-test-3   localhost/localhost  3.6.9.4  unsupported  13:47:01+07:00

App         Version  Status  Scale  Charm            Channel     Rev  Exposed  Message
controller           active      1  juju-controller  3.6/stable  116  yes      

Unit           Workload  Agent  Machine  Public address  Ports      Message
controller/0*  active    idle   0        10.120.73.16    17022/tcp  

Machine  State    Address                                 Inst id        Base          AZ  Message
0        started  10.120.73.16                            juju-74fa3f-0  ubuntu@22.04      Running
1        started  10.120.73.44                            juju-74fa3f-1  ubuntu@24.04      Running
2        started  fd42:31c4:f1f6:447d:216:3eff:fef8:a05e  juju-74fa3f-2  ubuntu@24.04      Running
```

## Checklist

- ~~[ ] Code style: imports ordered, good names, simple structure, etc~~
- ~~[ ] Comments saying why design decisions were made~~
- [x] Go unit tests, with comments saying what you're testing
- ~~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~~
- ~~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~~

## QA steps

1. Bootstrap a controller to LXD.
2. Add a model: `juju add-model model1`
3. Deploy some machines:  `juju add-machine --constraints="virt-type=virtual-machine" --base=ubuntu@24.04 -n 3`
4. See `az` column populated

Non clustered LXD

```text
(base) ➜  juju-upstream git:(3.6) ✗ juju status
Model   Controller  Cloud/Region         Version  SLA          Timestamp
model1  az-test-3   localhost/localhost  3.6.9.1  unsupported  14:05:46+07:00

Machine  State    Address                                 Inst id        Base          AZ       Message
4        started  fd42:31c4:f1f6:447d:216:3eff:fec1:e807  juju-ceddda-4  ubuntu@24.04  K6501ZM  Running
5        started  fd42:31c4:f1f6:447d:216:3eff:fe1f:317c  juju-ceddda-5  ubuntu@24.04  K6501ZM  Running
6        started  fd42:31c4:f1f6:447d:216:3eff:fe08:d85e  juju-ceddda-6  ubuntu@24.04  K6501ZM  Running
```

Clustered LXD with 3 members in a cluster. Machines are started in az `adis-1` and `adis-3`.

```text
root@adis-3:~# juju status
Model   Controller  Cloud/Region         Version  SLA          Timestamp
model1  az-test     localhost/localhost  3.6.9.1  unsupported  01:21:24Z

Machine  State    Address       Inst id        Base          AZ      Message
0        started  240.5.0.65    juju-ea2d07-0  ubuntu@22.04  adis-3  Running
1        started  240.140.0.60  juju-ea2d07-1  ubuntu@22.04  adis-1  Running
```

## Documentation changes

N/A.

## Links

**Issue:** Fixes #20150.

**Jira card:** [JUJU-8243](https://warthogs.atlassian.net/browse/JUJU-8243)

[JUJU-8243]: https://warthogs.atlassian.net/browse/JUJU-8243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by adisazhar123** [comment]
Still testing the fix on an LXD cluster. Setting it up is a bit more involved. In the meantime, the PR can be reviewed.
Edit: QA result posted in the PR description.

File: provider/lxd/environ_broker.go [hunk 1]
```diff
@@ -408,10 +408,11 @@ func (env *environ) getHardwareCharacteristics(
...
 	return &instance.HardwareCharacteristics{
-		Arch:     &archStr,
-		CpuCores: &cores,
-		Mem:      &mem,
-		VirtType: &container.Type,
+		Arch:             &archStr,
+		CpuCores:         &cores,
+		Mem:              &mem,
+		VirtType:         &container.Type,
+		AvailabilityZone: &args.AvailabilityZone,
```
Comment (wallyworld) [inline provider/lxd/environ_broker.go]: This should come from the inst returned from the cloud, for openstack we do
https://github.com/juju/juju/blob/8155fb3d45aae1d36fc225903fe423624246153e/provider/openstack/provider.go#L458

Comment (adisazhar123) [reply provider/lxd/environ_broker.go]: @wallyworld Thanks Ian. I've made the relevant changes to grab it from inst. One thing to note is that for non-cluster mode, the `location` value from LXD is `none`, in that case we fallback to the value from the args to make it human friendly.
Otherwise `az` will show as `none` in `juju status`. 

Wdyt?

File: provider/lxd/environ_broker.go [hunk 2]
```diff
@@ -407,11 +407,18 @@ func (env *environ) getHardwareCharacteristics(
 	}
 	cores := uint64(container.CPUs())
 	mem := uint64(container.Mem())
+	location := container.Location
```
Comment (wallyworld) [inline provider/lxd/environ_broker.go:410]: For non clustered, we use the inst name, see
https://github.com/juju/juju/blob/a1fa57c25d7ae44540f5b33bdda98b946a551cec/provider/lxd/environ.go#L334

File: provider/lxd/environ_broker.go (hunk 1 above)
Comment (wallyworld) [reply provider/lxd/environ_broker.go]: For non clustered, we use inst Name for AZ
https://github.com/juju/juju/blob/a1fa57c25d7ae44540f5b33bdda98b946a551cec/provider/lxd/environ.go#L334

File: provider/lxd/environ_broker.go (hunk 2 above)
Comment (adisazhar123) [reply provider/lxd/environ_broker.go:410]: Addressed. Thanks.

**Comment by adisazhar123** [comment]
There's an existing flaky test that is failing. Gonna re-trigger the merge.
Created card JUJU-8338 to track the issue.
