### PR TITLE
fix: use new apt mirror spec with cloud init

### LINKED ISSUE #21461: Juju incorrectly injects top-level apt_mirror key into user-data
### Description

When Juju is bootstrapped on a MAAS cloud, the controller automatically injects an apt_mirror key into the root level of the generated cloud-config for every unit.

Cloud-init enforces strict schema validation. The apt_mirror top-level key is deprecated/invalid, causing Cloud-init to crash with Schema validation errors during the init-local or init stage.

This injection occurs even if:
- enable-os-refresh-update is set to false.
- enable-os-upgrade is set to false.
- The user provides no apt configuration in cloudinit-userdata.
- The apt-mirror model config is explicitly unset or reset.

from  cloud-init schema --system:
```
Error: Cloud config schema errors: apt_mirror: Additional properties are not allowed ('apt_mirror' was unexpected)
```

### Juju version

3.6.9

### Cloud

MAAS

### Expected behaviour

The cloud-config.txt should generate valid yaml that complies with the Cloud-init schema for the target OS. It should not contain deprecated keys like apt_mirror

### Reproduce / Test

- Bootstrap a Juju controller on MAAS
- Deploy a basic charm 
- Inspect the generated user-data on the machine: cat /var/lib/cloud/instances/<instance-id>/cloud-config.txt

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by wallyworld**
Replace the use of the deprecated and now unsupported cloud init apt_mirror attribute.

The use of `apt_mirror` with cloud init was deprecated back in 2018 and is now removed (deprecated in 22.1 and removed in 27.1). Creating a cloud init configuration with this attribute causes the parsing to fail and cloud init to not complete properly.

Current ubuntu images from bionic onwards have the recent cloud init versions. Only bionic originally shipped with a cloud init version that was old. But current images are good and 3.6 ostensibly doesn't support bionic anyway.

This PR uses the new syntax
```
apt:
  primary:
    - arches: [default]
      search:
        - http://archive.ubuntu.com
```
We can still only support a single mirror because other juju logic and upstream would require a more extensive change. This PR simply retains the current functionality of a single mirror in model config.

## QA steps

bootstrap
add a model
set apt mirror config:
`juju model-config apt-mirror=http://us.archive.ubuntu.com/ubuntu`

`juju add-machine --base ubuntu@18.04`
`juju add-machine`

ssh into the machines
```
$ cloud-init status --long
status: done
boot_status_code: enabled-by-generator
last_update: Fri, 19 Dec 2025 03:19:40 +0000
detail:
DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud-net][dsmode=net]
```
previously this would show a parsing error

On noble
```
$ cat /etc/apt/sources.list.d/ubuntu.sources
...
Types: deb
URIs: http://us.archive.ubuntu.com/ubuntu
Suites: noble noble-updates noble-backports
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

## Ubuntu security updates. Aside from URIs and Suites,
## this should mirror your choices in the previous section.
Types: deb
URIs: http://us.archive.ubuntu.com/ubuntu
Suites: noble-security
Components: main universe restricted multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```

On bionic
```
$ cat /etc/apt/sources.list
...
deb http://us.archive.ubuntu.com/ubuntu bionic-security main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu bionic-security main restricted
deb http://us.archive.ubuntu.com/ubuntu bionic-security universe
# deb-src http://us.archive.ubuntu.com/ubuntu bionic-security universe
deb http://us.archive.ubuntu.com/ubuntu bionic-security multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu bionic-security multiverse

```

## Links

**Issue:** Fixes #21461.
**Jira card:** [JUJU-8977](https://warthogs.atlassian.net/browse/JUJU-8977)

[JUJU-8977]: https://warthogs.atlassian.net/browse/JUJU-8977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: cloudconfig/cloudinit/cloudinit.go [hunk 1]
```diff
@@ -56,7 +56,6 @@ type cloudConfig struct {
 	//
 	// used only for Ubuntu but implemented as runcmds on CentOS:
 	// apt_proxy			string
-	// apt_mirror			string/bool
```
Comment (adisazhar123) [inline cloudconfig/cloudinit/cloudinit.go:59]: Should we add `apt map[string][]map[string][]string` in the comment doc?

Comment (wallyworld) [reply cloudconfig/cloudinit/cloudinit.go:59]: sure

File: cloudconfig/cloudinit/cloudinit_ubuntu.go [hunk 2]
```diff
@@ -43,20 +43,54 @@ func (cfg *ubuntuCloudConfig) PackageProxy() string {
...
+	mirrorInfo, ok := cfg.attrs["apt"].(map[string][]AptMirrorInfo)
+	if !ok {
+		return ""
+	}
+	primary, ok := mirrorInfo["primary"]
+	if !ok || len(primary) < 1 {
+		return ""
+	}
+	search, ok := primary[0]["search"]
+	if !ok || len(primary) < 1 {
```
Comment (CodingCookieRookie) [inline cloudconfig/cloudinit/cloudinit_ubuntu.go]: do you mean len(search) here in this condition?

**Review by CodingCookieRookie — COMMENTED** [review]
LGTM but just a change in condition check to prevent panics before approval

File: cloudconfig/cloudinit/cloudinit_ubuntu.go (hunk 2 above)
Comment (wallyworld) [reply cloudconfig/cloudinit/cloudinit_ubuntu.go]: good pickup, thank you
