### PR TITLE
fix: gracefully handle missing storage backing status

### LINKED ISSUE #22101: Intermittent "filesystem for storage instance "database/0" not found" when running `juju status` immediately after deploy
### Description

With Juju 2 we used to experience lots of errors like these in our integration tests:

https://github.com/canonical/mysql-operators/actions/runs/23640145219/job/68870000190#step:6:2108

```
Mar 27 11:17:07 INFO     jubilant:_juju.py:308 cli: juju deploy --model testing ./mysql_ubuntu@24.04-amd64.charm mysql --base ubuntu@24.04 --config profile=testing --num-units 3
Mar 27 11:17:13 INFO     jubilant:_juju.py:308 cli: juju deploy --model testing mysql-test-app mysql-test-app --base ubuntu@24.04 --channel latest/edge --config sleep_interval=500
Mar 27 11:17:15 INFO     jubilant:_juju.py:308 cli: juju integrate --model testing mysql:database mysql-test-app:database
Mar 27 11:17:15 INFO     root:test_self_healing_network_cut.py:65 Wait for applications to become active
=========================== short test summary info ============================
FAILED tests/integration/integration/high_availability/test_self_healing_network_cut.py::test_deploy_highly_available_cluster - jubilant._juju.CLIError: Command '['juju', 'status', '--model', 'testing', '--format', 'json']' returned non-zero exit status 1.
Stdout:
{}

Stderr:
ERROR cannot process storage instances: cannot convert storage details for storage-database-0: filesystem for storage instance "database/0" not found (not found)
```

We patched those by adding `sleep()` in selective places, and moved on. This was only needed on Juju 2.

However, in the last Juju 3.6.20 version we're seeing these errors suddenly pop up in our upcoming branch, which dropped support for Juju 2 and removed the `sleep()` workarounds.

### Juju version

3.6.20

### Cloud

LXD

### Expected behaviour

`juju status` is more robust against transient storage issues that resolve themselves seconds later.

### Reproduce / Test

I've been trying to reproduce this locally, with a tight loop running the commands above, with no luck so far. Looks like it only happens on CI.

### Notes & References

Controller logs are here https://github.com/canonical/mysql-operators/actions/runs/23640145219/job/68870000227#step:13:912

### PR DESCRIPTION
**Pull request by adisazhar123**
The creation of a storage instance and its storage backing (either a filesystem or volume) may not happen in a single transaction. For example, when deploying an app, a unit and storage instance is created. However, its storage backing is eventually created once the unit is assigned to a machine.

Running juju status returns an error due to failing to find the corresponding storage backing for a storage instance.

We fix this by gracefully catching the storage backing NotFound error and translating this to a pending status when the unit is not assigned. This means that the storage backing creation hasn't kicked in yet, so it's safe to translate the error into a pending status.

On the other hand, if a storage backing NotFound error is returned AND a unit is already assigned to a machine, then this indicates a real error that should be surfaced, hence, we don't translate to any status. Taking a look at assignToMachineOps ([ref](https://github.com/juju/juju/blob/4dfc3a84e914611530b7f90b134f4a53b9fe1608/state/unit.go#L1714)) it builds the list of operations to assign a unit to a machine and build the storage backing. It happens in the same transaction. Therefore, it's an anomaly if the storage backing isn't found despite unit having a machine, so it makes sense to propagate the error.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

#### Test Case 1: Show pending status when storage backing is not created yet

1. Apply patch to delay storage backing creation

```
diff --git a/state/storage.go b/state/storage.go
index b9debaa831..b18451b45e 100644
--- a/state/storage.go
+++ b/state/storage.go
@@ -2302,6 +2302,10 @@ func (sb *storageBackend) hostStorageOps(
 		attachOnly      = true
 	)
 
+	logger.Infof("[hostStorageOps] hostId: %q waiting 30 seconds", hostId)
+	<-time.After(30 * time.Second)
+	logger.Infof("[hostStorageOps] hostId: %q proceed creating storage backing", hostId)
+
 	// Create filesystems and filesystem attachments.
 	for _, f := range args.filesystems {
 		ops, filesystemTag, volumeTag, err := sb.addFilesystemOps(f.Filesystem, hostId)

```

2. bootstrap, add model, and deploy app

```
juju bootstrap localhost juju-9520-testing-1 --build-agent --debug
juju add-model m1
juju deploy postgresql --channel 14/stable --trust
```

3. storage shows pending status because unit isn't yet assigned to a machine and storage backing is missing

```
juju storage
Unit          Storage ID  Type        Size  Status   Message
postgresql/0  pgdata/0    filesystem        pending  waiting for filesystem to be provisioned

```

```
juju status --storage          
                                                           
Model  Controller           Cloud/Region         Version   SLA          Timestamp
m4     juju-9520-testing-2  localhost/localhost  3.6.21.5  unsupported  23:15:04+07:00

App         Version  Status   Scale  Charm       Channel     Rev  Exposed  Message
postgresql           waiting    0/1  postgresql  14/stable  1045  no       waiting for machine

Unit          Workload  Agent       Machine  Public address  Ports  Message
postgresql/0  waiting   allocating                                  waiting for machine

Storage Unit  Storage ID  Type        Mountpoint  Size  Status   Message
postgresql/0  pgdata/0    filesystem                    pending  waiting for filesystem to be provisioned

```

4. after app is deployed storage status should show attached because the storage backing is created after a unit is assigned to a machine

```
juju storage

Unit          Storage ID  Type        Pool    Size    Status    Message
postgresql/0  pgdata/0    filesystem  rootfs  74 GiB  attached  
```

```
juju status --storage

Model  Controller           Cloud/Region         Version   SLA          Timestamp
m4     juju-9520-testing-2  localhost/localhost  3.6.21.5  unsupported  23:19:05+07:00

App         Version  Status   Scale  Charm       Channel     Rev  Exposed  Message
postgresql           waiting      1  postgresql  14/stable  1045  no       agent initialising

Unit           Workload  Agent      Machine  Public address  Ports  Message
postgresql/0*  waiting   executing  0        10.45.171.166          agent initialising

Machine  State    Address        Inst id        Base          AZ     Message
0        started  10.45.171.166  juju-376d28-0  ubuntu@22.04  ZBook  Running

Storage Unit  Storage ID  Type        Pool    Mountpoint                           Size    Status    Message
postgresql/0  pgdata/0    filesystem  rootfs  /var/snap/charmed-postgresql/common  74 GiB  attached  
```

#### Test Case 2: return error when storage backing is missing despite the unit is assigned to a machine

1. Undo the patch from test case 1.

2. Apply patch to prevent creating storage backing.

```
diff --git a/state/storage.go b/state/storage.go
index b9debaa831..21dc901c0e 100644
--- a/state/storage.go
+++ b/state/storage.go
@@ -2293,67 +2293,7 @@ func combineStorageParams(lhs, rhs *storageParams) *storageParams {
 func (sb *storageBackend) hostStorageOps(
 	hostId string, args *storageParams,
 ) ([]txn.Op, []volumeAttachmentTemplate, []filesystemAttachmentTemplate, error) {
-	var filesystemOps, volumeOps []txn.Op
-	var fsAttachments []filesystemAttachmentTemplate
-	var volumeAttachments []volumeAttachmentTemplate
-
-	const (
-		createAndAttach = false
-		attachOnly      = true
-	)
-
-	// Create filesystems and filesystem attachments.
-	for _, f := range args.filesystems {
-		ops, filesystemTag, volumeTag, err := sb.addFilesystemOps(f.Filesystem, hostId)
-		if err != nil {
-			return nil, nil, nil, errors.Trace(err)
-		}
-		filesystemOps = append(filesystemOps, ops...)
-		fsAttachments = append(fsAttachments, filesystemAttachmentTemplate{
-			filesystemTag, f.Filesystem.storage, f.Attachment, createAndAttach,
-		})
-		if volumeTag != (names.VolumeTag{}) {
-			// The filesystem requires a volume, so create a volume attachment too.
-			volumeAttachments = append(volumeAttachments, volumeAttachmentTemplate{
-				volumeTag, VolumeAttachmentParams{}, createAndAttach,
-			})
-		}
-	}
-	for tag, filesystemAttachment := range args.filesystemAttachments {
-		fsAttachments = append(fsAttachments, filesystemAttachmentTemplate{
-			tag, names.StorageTag{}, filesystemAttachment, attachOnly,
-		})
-	}
-
-	// Create volumes and volume attachments.
-	for _, v := range args.volumes {
-		ops, tag, err := sb.addVolumeOps(v.Volume, hostId)
-		if err != nil {
-			return nil, nil, nil, errors.Trace(err)
-		}
-		volumeOps = append(volumeOps, ops...)
-		volumeAttachments = append(volumeAttachments, volumeAttachmentTemplate{
-			tag, v.Attachment, createAndAttach,
-		})
-	}
-	for tag, volumeAttachment := range args.volumeAttachments {
-		volumeAttachments = append(volumeAttachments, volumeAttachmentTemplate{
-			tag, volumeAttachment, attachOnly,
-		})
-	}
-
-	ops := make([]txn.Op, 0, len(filesystemOps)+len(volumeOps)+len(fsAttachments)+len(volumeAttachments))
-	if len(fsAttachments) > 0 {
-		attachmentOps := createMachineFilesystemAttachmentsOps(hostId, fsAttachments)
-		ops = append(ops, filesystemOps...)
-		ops = append(ops, attachmentOps...)
-	}
-	if len(volumeAttachments) > 0 {
-		attachmentOps := createMachineVolumeAttachmentsOps(hostId, volumeAttachments)
-		ops = append(ops, volumeOps...)
-		ops = append(ops, attachmentOps...)
-	}
-	return ops, volumeAttachments, fsAttachments, nil
+	return []txn.Op{}, []volumeAttachmentTemplate{}, []filesystemAttachmentTemplate{}, nil
 }
 
 // addMachineStorageAttachmentsOps returns txn.Ops for adding the IDs of

```

3. bootstrap, add model, and deploy app

```
juju bootstrap localhost juju-9520-testing-2 --build-agent --debug
juju add-model m1
juju deploy postgresql --channel 14/stable --trust
```

4. check juju status periodically until unit is assigned to a machine

5. check storage, it should return error that filesystem isn't found. this is expected because the unit is already assigned a machine but the storage backing is missing. 

```
juju storage  


Unit   Storage ID  Type        Size  Status  Message
db1/0  pgdata/0    filesystem        error   filesystem for storage instance "pgdata/0" not found
```

```
juju status --storage   

Model  Controller           Cloud/Region         Version   SLA          Timestamp
m2     juju-9520-testing-4  localhost/localhost  3.6.21.3  unsupported  12:16:15+07:00

App  Version  Status   Scale  Charm       Channel     Rev  Exposed  Message
db1           waiting    0/1  postgresql  14/stable  1045  no       waiting for machine

Unit   Workload  Agent       Machine  Public address  Ports  Message
db1/0  waiting   allocating  0        10.45.171.222          waiting for machine

Machine  State    Address        Inst id        Base          AZ     Message
0        pending  10.45.171.222  juju-13d38c-0  ubuntu@22.04  ZBook  Running

Storage Unit  Storage ID  Type        Mountpoint  Size  Status  Message
db1/0         pgdata/0    filesystem                    error   filesystem for storage instance "pgdata/0" not found
```

## Documentation changes

N/A

## Links

**Issue:** Fixes #22101.

**Jira card:** [JUJU-9520](https://warthogs.atlassian.net/browse/JUJU-9520)

[JUJU-9520]: https://warthogs.atlassian.net/browse/JUJU-9520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apiserver/common/storagecommon/storagedetails_test.go
Comment (adisazhar123) [inline apiserver/common/storagecommon/storagedetails_test.go:1]: The test cases for volume and filesystem are symmetrical to each other so they may appear duplicated. I have added them for completeness

File: apiserver/common/storagecommon/storagedetails.go [hunk 1]
```diff
@@ -34,36 +36,63 @@ func StorageDetails(
...
 		// here too.
-		filesystem, err := sb.StorageInstanceFilesystem(si.StorageTag())
-		if err != nil {
-			return nil, errors.Trace(err)
+		filesystem, fsErr := sb.StorageInstanceFilesystem(si.StorageTag())
+		if errors.Is(fsErr, errors.NotFound) {
+			var err error
+			aStatus, err = missingBackingStorageStatus(
+				storageAttachments, unitToMachine, fsErr,
+				"waiting for filesystem to be provisioned", since,
```
Comment (wallyworld) [inline apiserver/common/storagecommon/storagedetails.go:64]: Do we see this message anywhere prior to these changes? I'm guessing this is a new message because we'd previously just almost immediately transition to "attaching"?

**Review by wallyworld — COMMENTED** [review]
Thank you for the fix.
RE:
```
juju status --storage   

ERROR cannot process storage instances: cannot convert storage details for storage-pgdata-0: filesystem for storage instance "pgdata/0" not found (not found)
```

This would be existing behaviour, but I'm wondering if we can confine the blast radius to just the particular storage details so that status works and just that storage is shown as in an error state.

File: apiserver/common/storagecommon/storagedetails.go (hunk 1 above)
Comment (adisazhar123) [reply apiserver/common/storagecommon/storagedetails.go:64]: Yes, this is a new message. 

>  I'm guessing this is a new message because we'd previously just almost immediately transition to "attaching"?

Yup. This `pending` is a transient state which then transition to `attaching` once the filesystem/volume doc is created.

**Comment by adisazhar123** [comment]
> This would be existing behaviour, but I'm wondering if we can confine the blast radius to just the particular storage details so that status works and just that storage is shown as in an error state.

Good idea as this will keep the status command usable. Will look into this thanks.

**Comment by adisazhar123** [comment]
@wallyworld changes pushed. Error message for test case 2 is now shown in storage message rather than error-ing status.

```
juju status --storage

Model  Controller           Cloud/Region         Version   SLA          Timestamp
m2     juju-9520-testing-4  localhost/localhost  3.6.21.3  unsupported  12:16:15+07:00

App  Version  Status   Scale  Charm       Channel     Rev  Exposed  Message
db1           waiting    0/1  postgresql  14/stable  1045  no       waiting for machine

Unit   Workload  Agent       Machine  Public address  Ports  Message
db1/0  waiting   allocating  0        10.45.171.222          waiting for machine

Machine  State    Address        Inst id        Base          AZ     Message
0        pending  10.45.171.222  juju-13d38c-0  ubuntu@22.04  ZBook  Running

Storage Unit  Storage ID  Type        Mountpoint  Size  Status  Message
db1/0         pgdata/0    filesystem                    error   filesystem for storage instance "pgdata/0" not found

```

```
juju storage

Unit   Storage ID  Type        Size  Status  Message
db1/0  pgdata/0    filesystem        error   filesystem for storage instance "pgdata/0" not found

```

File: apiserver/common/storagecommon/storagedetails.go [hunk 2]
```diff
@@ -120,3 +149,59 @@ func storageAttachmentInfo(
...
+		return status.StatusInfo{
+			Status: status.Detached,
+			Since:  &since,
+		}, nil
+	}
+	assigned, err := allAttachedUnitsAssigned(attachments, unitToMachine)
+	if err != nil {
+		return status.StatusInfo{}, err
+	}
+	// When a unit is assigned to a machine, the machine assignment
```
Comment (CodingCookieRookie) [inline apiserver/common/storagecommon/storagedetails.go]: hi adis, just wanted to clarify on this. If this statement is true, that 

```
when a unit is attached to machine, the machine assignment transaction [AssignToMachine] func guarantees that the backing volume/filesystem document is created
```

CMIIW but
shouldn't the storage backing for the storage instance be created as long as we have any of the units depending on this storage instance be assigned to a machine? Following which, we would have this assigned predicate logic to be based on anyAttachedUnitsAssigned instead of allAttachedUnitsAssigned

if assigned {
		return status.StatusInfo{
			Status:  status.Error,
			Message: notFoundErr.Error(),
			Since:   &since,
		}, nil
	}

**Comment by CodingCookieRookie** [comment]
QA tc 1 works for me, just a clarification point which relates to tc2.

File: apiserver/common/storagecommon/storagedetails.go (hunk 2 above)
Comment (CodingCookieRookie) [reply apiserver/common/storagecommon/storagedetails.go]: Just a follow-up if this comment makes sense, perhaps we could expand the tc2 to having two units that would be attached to the same storage, but only one of them is assigned to a machine to test this. not sure if this is doable though, feel free to ignore this follow-up comment if it's too difficult to test this

File: apiserver/common/storagecommon/storagedetails.go [hunk 3]
```diff
@@ -120,3 +149,59 @@ func storageAttachmentInfo(
...
+	notFoundErr error,
+	message string,
+	since time.Time,
+) (status.StatusInfo, error) {
+	if len(attachments) == 0 {
+		return status.StatusInfo{
+			Status: status.Detached,
+			Since:  &since,
+		}, nil
+	}
```
Comment (wallyworld) [inline apiserver/common/storagecommon/storagedetails.go]: This is new behaviour it seems? Can you explain why this is necessary as it seems unrelated to the change we want, which is to simply set status to Pending if the storage filesystem/volume is not yet created in the model due to the unit not having a host machine yet.

File: state/storage.go [hunk 4]
```diff
@@ -489,6 +489,10 @@ func (sb *storageBackend) destroyStorageInstanceOps(
 	return ops, nil
 }
 
+func (sb *storageBackend) Unit(tag names.UnitTag) (*Unit, error) {
+	return sb.unit(tag.Id())
+}
```
Comment (wallyworld) [inline state/storage.go]: Delete this - see other comments.

File: apiserver/common/storagecommon/storagedetails.go [hunk 5]
```diff
@@ -14,13 +16,14 @@ import (
...
 
-// DetailsBacked is used by StorageDetails, VolumeDetails and FilesystemDetails to access
+// DetailsBackend is used by StorageDetails, VolumeDetails and FilesystemDetails to access
 // state for collecting all the required information to send back over the wire.
 type DetailsBackend interface {
 	StorageAccess
 	VolumeAccess
 	FilesystemAccess
 	StorageAttachments(names.StorageTag) ([]state.StorageAttachment, error)
+	Unit(tag names.UnitTag) (*state.Unit, error)
```
Comment (wallyworld) [inline apiserver/common/storagecommon/storagedetails.go]: This won't compile.
Don't add Unit() here.
We have a state object we can weave through. We get the si owner, see it's a unit tag, and then call st.Unit() to get the unit.

**Comment by adisazhar123** [comment]
@wallyworld @CodingCookieRookie new changes pushed. Prior to this, I was traversing the storage instance -> attachment -> unit to get the owner of the storage instance. 

The change now grabs the owner directly from storage instance which returns the unit tag. From there, we can fetch the unit by name and determine whether this unit is assigned to a machine.

Re-tested and works.

File: apiserver/common/storagecommon/storagedetails.go (hunk 2 above)
Comment (adisazhar123) [reply apiserver/common/storagecommon/storagedetails.go]: I've pushed a new change to determine the machine a unit is assigned to. We don't iterate the slice of attachments anymore. See comment below.

File: apiserver/common/storagecommon/storagedetails.go (hunk 3 above)
Comment (adisazhar123) [reply apiserver/common/storagecommon/storagedetails.go]: Removed. New changes pushed, see comment below.

File: apiserver/common/storagecommon/storagedetails.go (hunk 5 above)
Comment (adisazhar123) [reply apiserver/common/storagecommon/storagedetails.go]: Thanks. That was partial work which I pushed too early. I have made the changes following your suggestion.

File: apiserver/common/storagecommon/storagedetails.go [hunk 6]
```diff
@@ -23,47 +25,87 @@ type DetailsBackend interface {
...
 
+// GetUnitFunc is a function type that retrieves a Unit by its name
+type GetUnitFunc func(name string) (Unit, error)
+
 // StorageDetails returns the storage instance as a params StorageDetails.
 func StorageDetails(
 	sb DetailsBackend,
 	unitToMachine UnitAssignedMachineFunc,
 	si state.StorageInstance,
+	getUnit GetUnitFunc,
```
Comment (wallyworld) [inline apiserver/common/storagecommon/storagedetails.go:48]: nit: move this so it is next to the other Func parameter above

Maybe:
```
	sb DetailsBackend,
	si state.StorageInstance,
	unitToMachine UnitAssignedMachineFunc,
	getUnit GetUnitFunc,
```

File: apiserver/common/storagecommon/storagedetails.go [hunk 7]
```diff
@@ -120,3 +162,69 @@ func storageAttachmentInfo(
 	}
 	return machineTag, info.Location, nil
 }
+
+// missingBackingStorageStatus classifies storage status when the backing
+// volume/filesystem record is missing.
+func missingBackingStorageStatus(
+	si state.StorageInstance,
+	getUnit GetUnitFunc,
+	notFoundErr error,
```
Comment (wallyworld) [inline apiserver/common/storagecommon/storagedetails.go]: nit: call this "originalErr"
we don't want to assume what it was, just that it was the error we got originally

File: apiserver/facades/client/client/status.go [hunk 8]
```diff
@@ -679,6 +680,7 @@ type statusContext struct {
 	providerType string
 	model        *state.Model
 	status       *state.ModelStatus
+	state        *state.State
```
Comment (wallyworld) [inline apiserver/facades/client/client/status.go]: Don't need this. You can just use `context.model.State()`

File: apiserver/facades/client/client/status.go [hunk 9]
```diff
@@ -308,6 +308,7 @@ func (c *Client) FullStatus(args params.StatusParams) (params.FullStatus, error)
 		return noStatus, errors.Annotate(err, "could not fetch controller timestamp")
 	}
 	context.branches = fetchBranches(c.modelCache)
+	context.state = c.state()
```
Comment (wallyworld) [inline apiserver/facades/client/client/status.go]: delete me - see other comment

File: apiserver/common/storagecommon/storagedetails_test.go [hunk 10]
```diff
@@ -0,0 +1,400 @@
...
+	c.Assert(err, jc.ErrorIsNil)
+	c.Assert(details.Status.Status, gc.Equals, corestatus.Attached)
+	c.Assert(details.Status.Info, gc.Equals, "volume attached")
+	c.Assert(details.Persistent, gc.Equals, true)
+	c.Assert(details.Attachments, gc.IsNil)
+}
+
+// TestFilesystemWithBackingEntityUsesStatus verifies the happy path where the
+// backing filesystem exists and its status is returned.
+func (s *StorageDetailsSuite) TestFilesystemWithBackingEntityUsesStatus(c *gc.C) {
```
Comment (wallyworld) [inline apiserver/common/storagecommon/storagedetails_test.go]: Is this test name AI generated? It's a bit meh.
It should be something like `TestStorageDetailsFilesystemAttached` or something.

Please audit the other test names and revise as necessary.

File: apiserver/common/storagecommon/storagedetails_test.go [hunk 11]
```diff
@@ -0,0 +1,400 @@
...
+	c.Assert(details.Status.Status, gc.Equals, corestatus.Pending)
+	c.Assert(details.Status.Info, gc.Equals, "waiting for volume to be provisioned")
+	c.Assert(details.Attachments, gc.HasLen, 1)
+	c.Assert(details.Attachments[s.unitTag.String()].MachineTag, gc.Equals, "")
+}
+
+// TestFilesystemNotFoundWithNotAssignedUnitsReturnsPending verifies status is surfaced
+// as pending when the backing filesystem is not found due to the unit not being assigned
+// to a machine yet.
+func (s *StorageDetailsSuite) TestFilesystemNotFoundWithNotAssignedUnitsReturnsPending(c *gc.C) {
```
Comment (wallyworld) [inline apiserver/common/storagecommon/storagedetails_test.go]: I can't see a test for the case where ShouldBeAssigned() = false
Maybe I missed it

**Review by wallyworld — APPROVED** [review]
Thank you, a few small fixes

File: apiserver/common/storagecommon/storagedetails_test.go (hunk 11 above)
Comment (adisazhar123) [reply apiserver/common/storagecommon/storagedetails_test.go]: We have two: TestVolumeNotFoundPropagatesErrorWhenUnitShouldNotBeAssigned and TestFilesystemNotFoundPropagatesErrorWhenUnitShouldNotBeAssigned.

File: apiserver/common/storagecommon/storagedetails_test.go (hunk 10 above)
Comment (adisazhar123) [reply apiserver/common/storagecommon/storagedetails_test.go]: A bit of help from copilot's /doc command. Sure.

File: apiserver/common/storagecommon/storagedetails.go [hunk 12]
```diff
@@ -120,3 +162,69 @@ func storageAttachmentInfo(
...
+		}, nil
+	}
+	unitTag, err := names.ParseUnitTag(owner.String())
+	if err != nil {
+		return status.StatusInfo{}, err
+	}
+
+	unit, err := getUnit(unitTag.Id())
+	if err != nil {
+		return status.StatusInfo{}, err
```
Comment (CodingCookieRookie) [inline apiserver/common/storagecommon/storagedetails.go:190]: hi adis just wondering if we it would be better to propagate the error for unit not found as statusInfo as well since we could technically remove unit concurrently?

**Review by CodingCookieRookie — APPROVED** [review]
LGTM, QA TC2 works too. Just a small suggestion/comment, thanks adis!

**Comment by adisazhar123** [comment]
Upgrade Smoke (localhost) repeatedly fails with

```
05:10:09 DEBUG juju.environs.tools build.go:379 forcing version to 3.6.22.1
05:10:09 DEBUG juju.environs.tools build.go:50 adding entry: &tar.Header{Typeflag:0x30, Name:"FORCE-VERSION", Linkname:"", Size:8, Mode:436, Uid:0, Gid:0, Uname:"ubuntu", Gname:"ubuntu", ModTime:time.Date(2026, time.April, 20, 5, 10, 9, 635108822, time.Local), AccessTime:time.Date(2026, time.April, 20, 5, 10, 9, 635108822, time.Local), ChangeTime:time.Date(2026, time.April, 20, 5, 10, 9, 635108822, time.Local), Devmajor:0, Devminor:0, Xattrs:map[string]string(nil), PAXRecords:map[string]string(nil), Format:0}
05:10:09 DEBUG juju.environs.tools build.go:50 adding entry: &tar.Header{Typeflag:0x30, Name:"jujud", Linkname:"", Size:223471328, Mode:509, Uid:0, Gid:0, Uname:"ubuntu", Gname:"ubuntu", ModTime:time.Date(2026, time.April, 20, 5, 10, 9, 600108823, time.Local), AccessTime:time.Date(2026, time.April, 20, 5, 10, 9, 600108823, time.Local), ChangeTime:time.Date(2026, time.April, 20, 5, 10, 9, 600108823, time.Local), Devmajor:0, Devminor:0, Xattrs:map[string]string(nil), PAXRecords:map[string]string(nil), Format:0}
05:10:15 INFO  juju.environs.sync sync.go:337 using agent binary 3.6.22-ubuntu-amd64 aliased to 3.6.22.1 (56438kB)
05:10:15 INFO  juju.cmd.juju.commands upgradecontroller.go:242 uploading agent binary 3.6.22.1 (56438kB) to Juju controller
no prepackaged agent binaries available, using local agent binary 3.6.22.1 (built from source)
05:10:16 DEBUG juju.rpc server.go:356 error closing codec: websocket: close sent
write tcp [fd42:dfa2:8c5c:aade::1]:50394->[fd42:dfa2:8c5c:aade:216:3eff:fee7:d32e]:17070: write: broken pipe
05:10:16 DEBUG juju.rpc server.go:356 error closing codec: websocket: close sent
write tcp 10.55.187.1:49004->10.55.187.140:17070: write: broken pipe
05:10:16 DEBUG juju.cmd.juju.commands upgradecontroller.go:330 upgradeController failed connection is shutdown before send: connection is shut down
ERROR connection is shutdown before send: connection is shut down
05:10:16 DEBUG cmd supercommand.go:571 error stack: 
github.com/juju/juju/rpc.init:17: connection is shut down
github.com/juju/juju/rpc.(*Conn).send:91: connection is shutdown before send
github.com/juju/juju/api.(*state).APICall:1404: 
github.com/juju/juju/api/client/modelupgrader.(*Client).UpgradeModel:67: '
```

https://github.com/juju/juju/actions/runs/24551038656/job/72068100121?pr=22159
