### PR TITLE
fix(bundle): treat compare integral float values as ints

### LINKED ISSUE #22058: diff-bundle reports float config options without a fractional/decimal part as always changed
### Description

When using `juju diff-bundle` float config options are always reported as different between the model and bundle if the are "equal" to an integer, regardless of whether they are actually different, e.g. `10!=10` but `10.1=10.1`. This is the same class of bug as #21532 which was fixed in #21557 (which is included in 3.6.19). 

### Juju version

3.6.19

### Cloud

_No response_

### Expected behaviour

If a config option is the same in a model and a bundle then diff-bundle should not include it.

### Reproduce / Test

A minimal reproducer can be done with any charm that has integer config options, e.g.,

```bash
juju add-model diff-bundle-issue
juju deploy postgresql
juju diff-bundle <(juju export-bundle --include-charm-defaults --include-series)
```
We expect to receive `{}` but instead receive
```yaml
applications:
  postgresql:
    options:
      optimizer_geqo_seed:
        bundle: 0
        model: 0
      optimizer_geqo_selection_bias:
        bundle: 2
        model: 2
      optimizer_jit_above_cost:
        bundle: 100000
        model: 100000
      optimizer_jit_inline_above_cost:
        bundle: 500000
        model: 500000
      optimizer_jit_optimize_above_cost:
        bundle: 500000
        model: 500000
      optimizer_parallel_setup_cost:
        bundle: 1000
        model: 1000
      storage_bgwriter_lru_multiplier:
        bundle: 2
        model: 2
      vacuum_autovacuum_vacuum_cost_delay:
        bundle: 2
        model: 2
      vacuum_vacuum_cost_delay:
        bundle: 0
        model: 0
````

### Notes & References

It's unclear why #21557 wasn't enough to resolve this. I haven't had time to dive in yet, but my guess is that we are being bitten by the opposite problem where the yaml parser sees e.g. `1000` instead of `1000.0` and assumes its an int while when receiving the value from the controller we now correctly convert to a float. This problem exists in `3.6.14` and so was not caused by #21557. I'll take a deeper look and update as I learn more.

### PR DESCRIPTION
**Pull request by raineszm**
This is another fix for the differing unmarshaling strategies of yaml and json. A config option that is a float can take integral values, and yaml will parse it as an int. This leads to a situation where a value is not equal to itself in diff-bundle since one side of the comparison is loaded from json and the other from yaml, i.e. we get `10.0!=10`.

This patch treats float option values that "look like integers" as integers for the purpose of comparing with bundle yaml.

This change is a fix for #22058.  In principle this is somewhat redundant with the fix #21557, but the two don't conflict and provide somewhat of a belt and suspenders solution.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [x] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
~- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

This can be verified in a manner very similar to #21557.

```
juju add-model coerce-numeric-options
juju deploy apache2
juju deploy postgresql
juju export-bundle --include-charm-defaults --include-series > bundle.yaml
```

Then run
```
juju diff-bundle bundle.yaml
```
and ensure that the result is an empty map.

Change, some integer options in bundle.yaml to different values and ensure 
```
juju diff-bundle bundle.yaml
```
now reflects that.

Finally,
```
juju deploy ./bundle.yaml
````
and now
```
juju diff-bundle bundle.yaml
````
should again be an empty map.

## Links

**Related Issue:** #21532
**Related PR:** #21557

**Issue:** Fixes #22058.

### CODE REVIEW

File: core/bundle/changes/diff_test.go [hunk 1]
```diff
@@ -755,6 +755,61 @@ func (s *diffSuite) TestApplicationOptions(c *gc.C) {
...
+                charm: ch:prometheus
+                revision: 7
+                series: xenial
+                channel: stable
+                num_units: 1
+                options:
+                    travis: 5
+                    clint: 6
+                    ellen: 11.0
+                    jane: 2
```
Comment (jameinel) [inline core/bundle/changes/diff_test.go:771]: It would be good to have one of these start with "2.1" or something similar. You have float values in the model below, but nothing that isn't possibly an int here.

File: tests/suites/cli/diff_bundle.sh [hunk 2]
```diff
@@ -0,0 +1,29 @@
+run_diff_bundle_reflexive() {
+	echo
+
+	file="${TEST_DIR}/test-cli-diff-bundle-reflexive.log"
+
+	ensure "test-cli-diff-bundle-reflexive" "${file}"
+
+	juju deploy apache2
+	juju deploy postgresql
```
Comment (jameinel) [inline tests/suites/cli/diff_bundle.sh:14]: Does this work because these specifically have both possible floats and int config?
There is always a question of whether you want to have test case charms or you use official charms. I do think postgresql will get a lot of maintenance, but that does mean they could push something that breaks us.

I *think* this is the right approach, but I would at least raise this as a potential thing that we might want to tweak. (eg, we could go with a juju-qa-float-int-config-charm).

File: core/bundle/changes/diff_test.go [hunk 3]
```diff
@@ -755,6 +755,61 @@ func (s *diffSuite) TestApplicationOptions(c *gc.C) {
...
+                to: [0]
+        machines:
+            0:
+            `
+	model := &bundlechanges.Model{
```
Comment (jameinel) [inline core/bundle/changes/diff_test.go:777]: Test fails without the patch, passes with it, so that part is good.

File: core/bundle/changes/diff.go [hunk 4]
```diff
@@ -337,6 +337,41 @@ func (d *differ) diffOptions(bundle, model map[string]interface{}) map[string]Op
 	return result
 }
 
+// AsInt checks whether a value is semantically an integer and of so
```
Comment (jameinel) [inline core/bundle/changes/diff.go]:
```suggestion
// AsInt checks whether a value is semantically an integer and if so
```

File: core/bundle/changes/diff.go [hunk 5]
```diff
@@ -337,6 +337,41 @@ func (d *differ) diffOptions(bundle, model map[string]interface{}) map[string]Op
...
+// return it as int with the second return value true.
+// Otherwise the second return value wil be false.
```
Comment (jameinel) [inline core/bundle/changes/diff.go]:
```suggestion
// Otherwise, the second return value will be false.
```

File: core/bundle/changes/diff.go [hunk 6]
```diff
@@ -337,6 +337,41 @@ func (d *differ) diffOptions(bundle, model map[string]interface{}) map[string]Op
...
+func asInt(x reflect.Value) (int, bool) {
```
Comment (jameinel) [inline core/bundle/changes/diff.go]: I would probably rename this "maybeAsInt" or some other way of signifying that we aren't sure if this is a valid int.

I'm not positive we want to go to reflect.Value here. I suppose this handles "int8" as well as "int" as well as "uint32".
If we know that everything from JSON is going to be a float, could we just simplify some of this to a type coercion?
eg:
```
func asInt(x any) (int, bool) {
  i, ok := x.(int)
  if ok {
    return i, true
  }
  f, ok := x.(float64)
  if ok {
    i := int(f)
    return i, f == float64(i)
  }
  return 0, false
```

The one fatality here are large ints (a 64 bit integer can't be stored 100% in a 64 bit float), but I think that we've already lost once we've round-tripped to JSON anyway.

The above feels cleaner than a bunch of reflect.Values (and that also has a minor impact on runtime performance as well).

File: core/bundle/changes/diff.go [hunk 7]
```diff
@@ -337,6 +337,41 @@ func (d *differ) diffOptions(bundle, model map[string]interface{}) map[string]Op
...
+	if x.CanInt() {
+		return int(x.Int()), true
+	}
+
+	if x.CanFloat() {
+		f := x.Float()
+		i := int(f)
+		return i, f == float64(i)
```
Comment (jameinel) [inline core/bundle/changes/diff.go]: given than this might be 'false' do we actually want to return 'i', or would it be better to return '0, false' here?
That way nobody thinks that it is safe to use the value.

File: core/bundle/changes/diff_test.go (hunk 1 above)
Comment (raineszm) [reply core/bundle/changes/diff_test.go:771]: ack

File: tests/suites/cli/diff_bundle.sh (hunk 2 above)
Comment (raineszm) [reply tests/suites/cli/diff_bundle.sh:14]: Right. Apache has int options and postgres has float options set to integer values by defualt.

File: core/bundle/changes/diff.go (hunk 4 above)
Comment (raineszm) [reply core/bundle/changes/diff.go]: Good catch.

File: core/bundle/changes/diff.go (hunk 6 above)
Comment (raineszm) [reply core/bundle/changes/diff.go]: That's a fair point. Under the covers the code is already falling back to reflect.Value since it's using `reflect.DeepEqual`, but the above feels more readable.

File: core/bundle/changes/diff.go (hunk 7 above)
Comment (raineszm) [reply core/bundle/changes/diff.go]: Agreed.

**Comment by raineszm** [comment]
Related to our discussion, another option would  be to enrich the model representation to also include type information about the config options since that is available when the model representation is created. The down side is that compared to this fix which is fairly local, a larger area would be affected. It is also an option though.

File: core/bundle/changes/diff_test.go [hunk 8]
```diff
@@ -755,6 +755,63 @@ func (s *diffSuite) TestApplicationOptions(c *gc.C) {
...
+                revision: 7
+                series: xenial
+                channel: stable
+                num_units: 1
+                options:
+                    travis: 5
+                    clint: 6
+                    ellen: 11.0
+                    jane: 2
+                    john: 13.37
```
Comment (jameinel) [inline core/bundle/changes/diff_test.go:772]: I see how it is. You leave a suggestion and you're name gets put into the data :)
