### PR TITLE
fix(cmr): find-offers failing for external users

### LINKED ISSUE #21932: Regression in offer consumption for external users
### Description

https://github.com/juju/juju/pull/21763 introduced a regression for offers owned by external users.

When we added a call to `state.User`. it introduced into the flow, a `NotFound` error for external users.

### Juju version

3.6 HEAD

### Cloud

LXD

### Expected behaviour

`find-offers` and `consume` should work for offers owned by external users.

### Reproduce / Test

- `juju bootstrap lxd lxd-36 --config identity-url=https://api.jujucharms.com/identity --config allow-model-access=true`
- `juju grant <your launchpad user>@external superuser`
- `juju change-user-password`
- `juju logout`
- `juju login -u <your launchpad user>@external`
- `juju add-model work36 --credential lxd`
- `juju deploy juju-qa-dummy-source && juju offer dummy-source:sink`
- `juju find-offers` (this fails, but works on the current release)
- `juju switch <some other model or controller>`
- `juju consume lxd-36:<your launchpad user>@external/work36.dummy-source` (also fails, but works on prior)

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by iyiguncevik**
**Root cause:** The commit removed the userDisplayName helper which gracefully handled
NotFound errors for external users (e.g., foo@external). It replaced it with a direct
backend.User(user) call that propagates the NotFound error. External users don't have
local user documents in the controller state, so backend.User() returns NotFound,
causing applicationOffersFromModel to fail for any external user — breaking both juju
find-offers and juju consume.

**Fix:** Restored the NotFound handling inline: if backend.User() returns NotFound, the
display name is left empty (empty string) instead of returning an error, matching the
original safe behavior.

Added bash tests to avoid regressions.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [x] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Setup:
```
❯ juju bootstrap lxd lxd-36 --config identity-url=https://api.jujucharms.com/identity --config allow-model-access=true
❯ juju grant iyiguncevik@external superuser
❯ juju change-user-password
❯ juju logout
❯ juju login -u iyiguncevik@external
❯ juju add-model work36 --credential lxd
❯ juju deploy juju-qa-dummy-source && juju offer dummy-source:sink

```

Check:
```
❯ juju find-offers 
Store   URL                                       Access  Interfaces
lxd-36  iyiguncevik@external/work36.dummy-source  admin   dummy-token:sink

❯ juju switch local-lxd-3 #any existing controller
❯ juju consume lxd-36:iyiguncevik@external/work36.dummy-source
Added lxd-36:iyiguncevik@external/work36.dummy-source as dummy-source
```

## Links

**Issue:** Fixes #21932

**Jira card:** [JUJU-9291](https://warthogs.atlassian.net/browse/JUJU-9291)

[JUJU-9291]: https://warthogs.atlassian.net/browse/JUJU-9291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: tests/tools/test-identity-provider/main.go
Comment (hpidcock) [inline tests/tools/test-identity-provider/main.go:1]: This should be moved into tools

File: tests/tools/test-identity-provider/main.go [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+	"os"
+	"os/signal"
+	"syscall"
+
+	"github.com/go-macaroon-bakery/macaroon-bakery/v3/bakery/checkers"
+	"github.com/go-macaroon-bakery/macaroon-bakery/v3/bakerytest"
+	"github.com/go-macaroon-bakery/macaroon-bakery/v3/httpbakery"
+)
+
+// test-identity-provider is a minimal bakery-based identity provider for use
```
Comment (wallyworld) [inline tests/tools/test-identity-provider/main.go:19]: This seems useful enough and probably relevant to other tests using external users that it could be located elsewhere as a generic helper, not just tied to the cmr suite.

File: tests/suites/cmr/offer_consume.sh [hunk 2]
```diff
@@ -139,6 +139,133 @@ run_offer_consume_cross_controller() {
...
+	echo "Check find-offers output as external user"
+	JUJU_MODEL="ctrl-extuser-idp:admin/model-offer-ext" JUJU_DATA=/tmp/extuser \
+		juju find-offers --format=json |
+		jq -r 'has("ctrl-extuser-idp:admin/model-offer-ext.dummy-offer")' |
+		check true
+
+	echo "Clean up"
+	kill "${IDP_PID}" 2>/dev/null || true
+	rm -rf /tmp/extuser "${TEST_IDP_TMPDIR}"
+	destroy_controller "ctrl-extuser-idp"
```
Comment (hpidcock) [inline tests/suites/cmr/offer_consume.sh:267]: @wallyworld when this is merged into the release branch we'll need to change it to
```sh
	echo

	# Start the discharger in the background; wait for it to write its two
	# output lines (URL then public key).
	IDP_OUTPUT="${TEST_DIR}/idp-output.txt"
	go run github.com/juju/juju/tools/test-identity-provider --username testextuser >"${IDP_OUTPUT}" 2>&1 &
	track_daemon_pid $!

	IDP_URL=""
	IDP_PUBKEY=""
	for i in $(seq 1 20); do
		if [[ $(wc -l <"${IDP_OUTPUT}" 2>/dev/null) -ge 2 ]]; then
			IDP_URL=$(sed -n '1p' "${IDP_OUTPUT}")
			IDP_PUBKEY=$(sed -n '2p' "${IDP_OUTPUT}")
			break
		fi
		sleep $i
	done

	if [[ -z ${IDP_URL} || -z ${IDP_PUBKEY} ]]; then
		echo "ERROR: test identity provider failed to start"
		exit 1
	fi
	echo "Identity provider running at ${IDP_URL}"

	# Bootstrap a dedicated controller that uses the test identity provider.
	# BOOTSTRAP_ADDITIONAL_ARGS is extended here; pre_bootstrap will append
	# --agent-version etc., and post_bootstrap will unset it afterwards.
	export BOOTSTRAP_ADDITIONAL_ARGS="${BOOTSTRAP_ADDITIONAL_ARGS:-} \
		--config identity-url=${IDP_URL} \
		--config identity-public-key=${IDP_PUBKEY} \
		--config allow-model-access=true"

	file="${TEST_DIR}/test-offer-find-external.log"
	juju_bootstrap "${BOOTSTRAP_CLOUD:-localhost}" "ctrl-extuser-idp" "model-offer-ext" "${file}"

	# Grant the external user controller-level access so they can query offers.
	juju grant testextuser@external superuser

	echo "Deploy application and create the offer as admin"
	juju deploy juju-qa-dummy-source --series jammy
	juju offer dummy-source:sink dummy-offer

	wait_for "dummy-source" "$(idle_condition "dummy-source")"

	# Retrieve one of the API endpoints for the external-user login step.
	CTRL_ENDPOINT=$(juju show-controller ctrl-extuser-idp --format=json |
		yq -r '."ctrl-extuser-idp".details."api-endpoints"[0]')

	echo "Login as testextuser@external (auto-approved by test identity provider)"
	TEST_EXTUSER_DIR="$(mktemp -d)"
	
	# --no-prompt suppresses all interactive input including the CA cert trust
	# prompt; --trust auto-approves the self-signed controller certificate.
	# The bakery discharger auto-approves the login, so no browser is needed.
	JUJU_DATA="${TEST_EXTUSER_DIR}" juju login "${CTRL_ENDPOINT}" \
		-c ctrl-extuser-idp --no-prompt --trust

	echo "Check find-offers output as external user"
	JUJU_MODEL="ctrl-extuser-idp:admin/model-offer-ext" JUJU_DATA="${TEST_EXTUSER_DIR}" \
		juju find-offers --format=json |
		yq -r 'has("ctrl-extuser-idp:admin/model-offer-ext.dummy-offer")' |
		check true

	echo "Clean up"
	rm -rf "${TEST_EXTUSER_DIR}"
	destroy_controller "ctrl-extuser-idp"
```

File: tests/suites/cmr/task.sh [hunk 3]
```diff
@@ -7,13 +7,23 @@ test_cmr() {
...
 
 	echo "==> Checking for dependencies"
-	check_dependencies juju
+	check_dependencies juju go
 
-	file="${TEST_DIR}/test-cmr.log"
+	# Only bootstrap the shared controller when at least one test that uses it
+	# will run. This avoids an unnecessary bootstrap/destroy cycle when only
+	# test_offer_find_external_user is selected (it manages its own controller).
+	if [ -z "$(skip 'test_offer_consume')" ] || [ -z "$(skip 'test_offer_find_non_admin')" ]; then
```
Comment (hpidcock) [inline tests/suites/cmr/task.sh]: @wallyworld this should become when merged into the release branch.

```suggestion
	if [ -z "$(skip 'test_offer_consume' 'test_offer_find_non_admin')" ]; then
```

File: apiserver/facades/client/applicationoffers/base.go [hunk 4]
```diff
@@ -103,9 +103,12 @@ func (api *BaseAPI) applicationOffersFromModel(
...
 	}
 
+	var apiUserDisplayName string
 	u, err := backend.User(user)
-	if err != nil {
+	if err != nil && !errors.Is(err, errors.NotFound) {
 		return nil, errors.Trace(err)
+	} else if err == nil {
+		apiUserDisplayName = u.DisplayName()
 	}
```
Comment (hpidcock) [inline apiserver/facades/client/applicationoffers/base.go:112]: Be explicit with a log or comment.
```go
var apiUserDisplayName string
u, err := backend.User(user)
if errors.Is(err, errors.NotFound) {
	logger.Tracef("something something, external user connected no display name")
} else if err != nil {
	return nil, errors.Trace(err)
} else {
	apiUserDisplayName = u.DisplayName()
}
```

Better yet, make a method to resolve this:
```go
// resolveUserDisplayName resolves the display name of a user and because of external users ...
func (api *BaseAPI) resolveUserDisplayName(user names.UserTag, ...) (string, error) {
	u, err := backend.User(user)
	if errors.Is(err, errors.NotFound) {
		logger.Tracef("something something, external user connected no display name")
		return "", nil
	} else if err != nil {
		return "", errors.Trace(err)
	}
	return u.DisplayName(), nil
}
```

**Review by hpidcock — APPROVED** [review]

File: tests/suites/cmr/offer_consume.sh [hunk 5]
```diff
@@ -139,6 +139,133 @@ run_offer_consume_cross_controller() {
...
+# to use that discharger as its identity-url, and then logs in with a fresh
+# JUJU_DATA (simulating the external-user experience) to confirm find-offers
+# returns the expected offer.
+run_offer_find_external_user() {
+	echo
+
+	# Build the test identity provider binary (CWD is repo root via "cd ..").
+	TEST_IDP_TMPDIR=$(mktemp -d)
+	TEST_IDP_BIN="${TEST_IDP_TMPDIR}/test-identity-provider"
+	go build -o "${TEST_IDP_BIN}" ./tests/suites/cmr/test-identity-provider/
```
Comment (wallyworld) [inline tests/suites/cmr/offer_consume.sh]: We can't hard code the location. It needs to be relative to the executing script.

File: tests/tools/test-identity-provider/main.go
Comment (wallyworld) [reply tests/tools/test-identity-provider/main.go:1]: Yep. Moved to `tests/tools`

File: tests/tools/test-identity-provider/main.go (hunk 1 above)
Comment (wallyworld) [reply tests/tools/test-identity-provider/main.go:19]: Moved to `tests/tools`

File: tests/suites/cmr/offer_consume.sh (hunk 5 above)
Comment (wallyworld) [reply tests/suites/cmr/offer_consume.sh]: I've pushed a fix
