### PR TITLE
fix: cleanup LXD profile when a model is deleted

### LINKED ISSUE #20149: Juju destroy model on LXD does not delete the LXD profile of the model in the LXD project
### Description

When adding a Juju model that is targeting a LXD project, Juju automatically creates a LXD profile in that project. Upon Juju model deletion, this profile is not deleted.

### Juju version

3.6.7

### Cloud

LXD

### Expected behaviour

The LXD profile of the Juju model is deleted when the model is destroyed

### Reproduce / Test

```
juju add-model test --config project=test
juju destroy-model test
2025/07/08 11:40:45.920954 cmd_run.go:1285: WARNING: cannot start document portal: dial unix /run/user/0/bus: connect: permission denied
WARNING This command will destroy the "test" model and affect the following resources. It cannot be stopped.

 - 4 machines will be destroyed
  - machine list: "0 (juju-4029d3-0)" "1 ()" "2 (juju-4029d3-2)" "3 (juju-4029d3-3)"
 - 0 application will be removed
 - 0 filesystem and 0 volume will be destroyed

To continue, enter the name of the model to be unregistered: test
Destroying model
Waiting for model to be removed, 1 error(s), 4 machine(s)...
Waiting for model to be removed, 4 machine(s)........
Waiting for model to be removed, 2 machine(s)....
Waiting for model to be removed...
Model destroyed.

lxc profile list microcloud: --project test
+-----------+--------------------------------------+---------+
|   NAME    |             DESCRIPTION              | USED BY |
+-----------+--------------------------------------+---------+
| default   | Default LXD profile for project test | 0       |
+-----------+--------------------------------------+---------+
| juju-test |                                      | 0       |
+-----------+--------------------------------------+---------+
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by adisazhar123**
Some preliminary background:

- An LXD profile is created for a model under the name of `juju-<model>`
- Other LXD profiles specific for a charm is also created if that charm has an `lxd-profile.yaml` defined, they follow the naming scheme `juju-<model>-<app>-<rev>`
- Unfortunately, when a model is destroyed or a machine is removed, the relevant profiles aren't destroyed, which leads to orphaned profiles

As part of this PR:

- We delete the model profile and charm profiles when a model is destroyed
- We add an upgrade step to create a model profile and charm profiles using the new naming scheme.
   - As part of the upgrade step, we also attempt to delete the old profiles. We can't be sure of the ownership, hence, if that profile is attached to some instance, this deletion will fail (and we treat this failure as a safe one, that is we don't crash the worker).

To support the deletion use case, we must ensure that the profile names are unique. We shouldn't mistakenly delete a profile that is used by another model with the same name on a different controller. Hence, we have updated the naming scheme to include the short model UUID. The new naming schemes are:

-  `juju-<model>-<shortid>`
- `juju-<model>-<shortid>-<app>-<rev>`

**Note:** don't include the upgrade step in 4.0

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- ~~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~~
- ~~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~~

#### Prelim

Pack a local machine charm named `machinecharm` with `lxd-profile.yaml` file. This is so that a charm profile gets created.

```
description: "custom profile for charm made by adis"
config:
  user.name: "adis-custom"
  user.year: "2025"
```

Pack it by running
```charmcract pack```.

This will output a `machinecharm_amd64.charm` file.

Convention I am using: 
- `/snap/bin/juju` is the 3.6.8 binary
-  `juju` is the 3.6.9 binary.

#### Test Case 1: profiles in old version are upgraded

version 3.6.8 before upgrade

Deploy a total of 50 apps.

Bootstrap to LXD

```
/snap/bin/juju bootstrap localhost adiscontroller
```

```
// 20 apps
/snap/bin/juju add-model model1 
for i in {1..20}; do /snap/bin/juju deploy ./machinecharm_amd64.charm watermelon$i; done
```

```
// 20 apps
/snap/bin/juju add-model model2
for i in {1..20}; do /snap/bin/juju deploy ./machinecharm_amd64.charm avocado$i; done
```

```
// 10 apps
/snap/bin/juju add-model model3
for i in {1..10}; do /snap/bin/juju deploy ./machinecharm_amd64.charm strawberry$i; done
```

Check profiles. 
You'll see 3 model profiles. They are: `juju-model1`, `juju-model2`, and `juju-model3`.
You'll see 1 controller profile. They are `juju-controller`.

You'll see 50 charm profiles. Some examples are (non-exhaustive): `juju-model3-strawberry1-0`, `juju-model2-avocado14-14 `, and `juju-model1-watermelon17-16`.

Configure logs
```
/snap/bin/juju model-config -m controller logging-config="juju.provider.lxd=DEBUG"
```

After the upgrade
Now upgrade it with the changes in this PR. The upgrade step will run to create the profiles for each instance. 
```
make go-install
juju upgrade-controller --build-agent
```

Check the logs for `finishing create profile step for model <uuid>`.

```
juju debug-log -m controller --replay --include-module juju.provider.lxd
```

e.g.
```
ubuntu@ip-172-31-47-202:~/.local/share/juju/ssh$ juju debug-log -m controller --replay | grep "running create profile step for model"
machine-0: 06:24:41 DEBUG juju.provider.lxd running create profile step for model "15183c62-5d11-44e0-8f67-8ce82dcc2cb9"
machine-0: 06:24:41 DEBUG juju.provider.lxd running create profile step for model "36fb271b-49ff-4279-8486-219430e47f91"
machine-0: 06:24:57 DEBUG juju.provider.lxd running create profile step for model "59dad47c-5f12-4239-8abb-917a2a1c86a7"
machine-0: 06:25:12 DEBUG juju.provider.lxd running create profile step for model "4ad64f2a-33b0-4e5e-8496-f78a17f504aa"
ubuntu@ip-172-31-47-202:~/.local/share/juju/ssh$ juju debug-log -m controller --replay | grep "finishing create profile step for model"
machine-0: 06:25:28 DEBUG juju.provider.lxd finishing create profile step for model "4ad64f2a-33b0-4e5e-8496-f78a17f504aa"
machine-0: 06:25:58 DEBUG juju.provider.lxd finishing create profile step for model "59dad47c-5f12-4239-8abb-917a2a1c86a7"
machine-0: 06:26:02 DEBUG juju.provider.lxd finishing create profile step for model "15183c62-5d11-44e0-8f67-8ce82dcc2cb9"
machine-0: 06:26:02 DEBUG juju.provider.lxd finishing create profile step for model "36fb271b-49ff-4279-8486-219430e47f91"
```

Check the profiles. There should be 3 new model profiles  `juju-model1-<shortid>`, `juju-model2-<shortid>`, and `juju-model3-<shortid>`. 
The controller profile should be `juju-controller-<shortid>`.
And 50 new charm profiles with the model shortid as well. The old profiles may be kept and this is okay because another instance may be attached to it. We can't be 100% sure they're safe to delete. We attempt a best effort delete, we skip the error if it fails so the worker doesn't crash.

Examples of the profile charms (non-exhaustive):

```
lxc profile list
```

```
juju-model3-59dad4-strawberry1-0
juju-model2-15183c-avocado14-14
juju-model1-36fb27-watermelon17-16
```

Now if we destroy a model, the model profile and charms profile in that model are destroyed too.

These are the profiles in model3 before destroyed.
```
| juju-model3-59dad4                 |                                       | 10      |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry1-0   | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry2-1   | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry3-2   | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry4-3   | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry5-4   | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry6-5   | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry7-6   | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry8-7   | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry9-8   | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
| juju-model3-59dad4-strawberry10-9  | custom profile for charm made by adis | 1       |
+------------------------------------+---------------------------------------+---------+
```

Let's destroy it...

```
juju destroy-model model3
```

Check that the profiles in model3 are gone :>
```
lxc profile list
```

#### Test Case 2: profiles created in new the version using the new naming scheme... and deleted when the model is destroyed

Add a model and deploy a charm.
```
juju add-model model4
juju deploy ./machinecharm_amd64.charm dragonfruit
```

Check the profiles have shortid.

```
lxc profile list
```

Destroy the model and check the profiles are gone afterwards.
```
juju destroy-model model4
lxc profile list
```

## Documentation changes

N/A

## Links
**Issue:** Fixes #20149.

**Jira card:** [JUJU-8242](https://warthogs.atlassian.net/browse/JUJU-8242)

[JUJU-8242]: https://warthogs.atlassian.net/browse/JUJU-8242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: provider/lxd/environ.go [hunk 1]
```diff
@@ -31,6 +32,7 @@ import (
 var _ environs.HardwareCharacteristicsDetector = (*environ)(nil)
 
 const bootstrapMessage = `To configure your system to better support LXD containers, please see: https://documentation.ubuntu.com/lxd/en/latest/explanation/performance_tuning/`
+const shortModelIdLength = 6
```
Comment (CodingCookieRookie) [inline provider/lxd/environ.go]: nit: perhaps can group the const here

File: provider/lxd/environ.go [hunk 2]
```diff
@@ -133,8 +135,12 @@ func (env *environ) initProfile() error {
 	return err
 }
 
+func (env *environ) shortModelUUID() string {
+	return env.uuid[:shortModelIdLength]
```
Comment (CodingCookieRookie) [inline provider/lxd/environ.go]: hi adis, perhaps we can do a len check here?

File: provider/lxd/environ.go [hunk 3]
```diff
@@ -276,6 +283,20 @@ func (env *environ) destroyHostedModelResources(controllerUUID string) error {
...
 
+func (env *environ) destroyProfile(ctx context.ProviderCallContext) error {
+	server := env.server()
+	hasProfile, err := server.HasProfile(env.profileName())
+	if err != nil {
+		common.HandleCredentialError(IsAuthorisationFailure, err, ctx)
+		return errors.Trace(err)
+	}
+	if hasProfile {
+		return errors.Trace(server.DeleteProfile(env.profileName()))
```
Comment (CodingCookieRookie) [inline provider/lxd/environ.go]: suggestion (optional): might be a personal opinion but perhaps for better clarity we could refactor server.DeleteProfile(env.profileName()) instead of putting them in one line together, or we could invert the hasProfile condition and return server.DeleteProfile(env.profileName()) at the end

File: provider/lxd/environ.go [hunk 4]
```diff
@@ -133,8 +135,12 @@ func (env *environ) initProfile() error {
 	return err
 }
 
+func (env *environ) shortModelUUID() string {
+	return env.uuid[:shortModelIdLength]
+}
+
 func (env *environ) profileName() string {
```
Comment (CodingCookieRookie) [inline provider/lxd/environ.go]: discussion:
hi adis, just curious about a detail regarding this implementation. Destroy() seems to be used in the client side as well in the kill controller command when we kill a controller. If users were to upgrade their client and does a kill-controller command on old controller, the profile wouldn't be deleted right? Not sure in this case do we have to handle possible users' expectations that the profile would be deleted in kill-controller once the client is upgraded? Perhaps ian could weigh in on this as well.

File: provider/lxd/environ.go [hunk 5]
```diff
@@ -133,8 +135,12 @@ func (env *environ) initProfile() error {
 	return err
 }
 
+func (env *environ) shortModelUUID() string {
```
Comment (hmlanigan) [inline provider/lxd/environ.go]: This is a duplicate method. The short model uuid is also used an the lxd instance names, thus calculated somewhere already.

File: provider/lxd/environ.go (hunk 3 above)
Comment (hmlanigan) [inline provider/lxd/environ.go]: todo: log the error if `server.DeleteProfile` rather than fail. It's not critical enough to fail model destruction.

**Review by hmlanigan — CHANGES_REQUESTED** [review]
Thank you for attempting this. LXD profiles in juju are very complicated, so a few things need to be resolved. 

The change conflicts with lxd profiles created by charms and how they are handled. Handling involves the model profile as well. 

LXD Profiles are written to machines as a group. Each write replaces the previous list of profiles on the machine. 

The profile name specific to the model is recreated in the code for charm's lxd profiles.

Any machine with a charm lxd profile will have a `juju-modelname`, `juju-modelname-sha`, `juju-modelname-appname-#`

QA
```
| juju-controller                                                |                                                   | 2       |
| juju-controller-7b0768                                         |                                                   | 0       |

# The profile is created, but not used by the controller machine.

$ lxc profile show juju-controller
...
used_by:
- /1.0/instances/juju-a54e1a-0
- /1.0/instances/juju-f626dc-0

$ juju status -m controller
...
Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.74.147.110  juju-f626dc-0  ubuntu@24.04      Running 
```

an example of the charm lxd profile problem:
```
$ juju add-model adis
$ juju deploy ./testcharms/charms/lxd-profile
$ lxc profile list | grep adis
| juju-adis-7c593c                                               |                                                   | 1       |
| juju-adis-lxd-profile-0                                        | lxd profile for testing                           | 1       |
$ juju status
...
Machine  State  Address       Inst id        Base          AZ  Message
0        error  10.74.147.14  juju-dc7a5d-0  ubuntu@24.04      cannot upgrade machine's lxd profile: failed to update "juju-dc7a5d-0" with profiles: Profile not found
```

# from debug-log:

controller-0: 22:38:19 INFO juju.worker.instancemutater.environ machine-0 (juju-dc7a5d-0) assign lxd profiles ["default" "juju-adis" "juju-adis-lxd-profile-0"], []lxdprofile.ProfilePost{lxdprofile.ProfilePost{Name:"juju-adis-lxd-profile-0", Profile:(*lxdprofile.Profile)(0xc002724300)}}
controller-0: 22:38:19 ERROR juju.worker.instancemutater.environ failure to assign lxd profiles [default juju-adis juju-adis-lxd-profile-0] to machine-0: failed to update "juju-dc7a5d-0" with profiles: Profile not found
```


Note: the model name is only included in profiles written on juju machines with an lxd substrate, not lxd containers on a machine.

File: provider/lxd/environ.go (hunk 2 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: I resorted to using `names.NewModelTag()`

File: provider/lxd/environ.go (hunk 4 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: This is a good point. IMO it's okay to delete the profile when we issue a `juju kill-controller` command because that destroys the model too. We wouldn't want any profiles lying around if the models are gone.

When a new environ is opened, the profiles are then created there.

File: provider/lxd/environ.go (hunk 1 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: This is removed because I've resorted to using `names.NewModelTag()`

File: provider/lxd/environ.go (hunk 3 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: Updated. Thanks.

File: provider/lxd/environ.go (hunk 5 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: I resorted to using `names.NewModelTag()`.
I see the instance name is using the last 6 digits of the model UUID, however, `names.NewModelTag().ShortId()` takes the first 6 digits. 

Which convention should I follow?

**Comment by adisazhar123** [comment]
@hmlanigan thanks Heather for educating me. I wasn't aware that we create profiles for charms. Based on my investigation, the error was due to `GetRequiredLXDProfiles()` returning a profile using the old name. LXD couldn't find that profile because it doesn't exist since I had changed the profile to use a new naming format. The fix was to pass in the new format to `GetRequiredLXDProfiles()`.

There were several updates I've made such as deleting the charm profiles when an instance is removed and deleting the model profile when a model is destroyed. PR description and QA steps updated.

I might be missing something but I wasn't able to see profiles for `juju-modelname-sha`. Would you be able to point me to this?

File: provider/lxd/environ.go (hunk 4 above)
Comment (CodingCookieRookie) [reply provider/lxd/environ.go]: Thanks Adis, agreed on deleting the profile when kill-controller is run. My concern is more about the mixed-version case: if a user runs a new client against an older controller, the profile wouldn’t be deleted. Not sure if we need to handle that to meet user expectations, or is it okay to leave the profile behind in that case?

File: provider/lxd/environ.go [hunk 6]
```diff
@@ -276,6 +279,18 @@ func (env *environ) destroyHostedModelResources(controllerUUID string) error {
 	return errors.Trace(env.server().RemoveContainers(names))
 }
 
+func (env *environ) destroyModelProfile() error {
+	server := env.server()
+	profile := env.profileName()
+	err := server.DeleteProfile(profile)
+	logger.Debugf("deleted profile %q", profile)
```
Comment (CodingCookieRookie) [inline provider/lxd/environ.go]: nit: hi adis, perhaps this log should be after the err check?

File: provider/lxd/environ_broker.go [hunk 7]
```diff
@@ -447,9 +447,40 @@ func (env *environ) StopInstances(ctx context.ProviderCallContext, instances ...
...
 	err := env.server().RemoveContainers(names)
 	if err != nil {
 		common.HandleCredentialError(IsAuthorisationFailure, err, ctx)
+		return errors.Trace(err)
 	}
-	return errors.Trace(err)
+
+	for _, profile := range profilesToDelete {
+		err = env.server().DeleteProfile(profile)
+		logger.Debugf("deleted profile %q", profile)
```
Comment (CodingCookieRookie) [inline provider/lxd/environ_broker.go]: nit: same for this as well

File: provider/lxd/environ.go [hunk 8]
```diff
@@ -276,6 +279,18 @@ func (env *environ) destroyHostedModelResources(controllerUUID string) error {
...
+	if err != nil {
+		logger.Debugf("failed to delete profile %q due to %s, it may need to be deleted manually through the provider", profile, err.Error())
```
Comment (CodingCookieRookie) [inline provider/lxd/environ.go]: hi adis should this be an error log?

**Review by CodingCookieRookie — COMMENTED** [review]
Hi adis, thanks for the changes! Made a reply on the discussion, hope it makes sense,  and happy to discuss further as well! :D

File: apiserver/facades/agent/instancemutater/shim.go [hunk 9]
```diff
@@ -24,6 +24,14 @@ func (s *instanceMutaterStateShim) ModelName() (string, error) {
 	return m.Name(), err
 }
 
+func (s *instanceMutaterStateShim) ModelUUID() (string, error) {
```
Comment (wallyworld) [inline apiserver/facades/agent/instancemutater/shim.go]: Don't need this - `state.State` has a `ModelUUID()` method

File: apiserver/facades/agent/instancemutater/instancemutater.go [hunk 10]
```diff
@@ -372,9 +374,14 @@ func (api *InstanceMutaterAPI) machineLXDProfileInfo(m Machine) (lxdProfileInfo,
 	if err != nil {
 		return empty, errors.Trace(err)
 	}
+	modelUUID, err := api.st.ModelUUID()
```
Comment (wallyworld) [inline apiserver/facades/agent/instancemutater/instancemutater.go]: Just use the direct method without the shim
```
// ModelUUID returns the model UUID for the model
// controlled by this state instance.
func (st *State) ModelUUID() string {
	return st.modelTag.Id()
}
```

File: apiserver/facades/agent/instancemutater/instancemutater.go [hunk 11]
```diff
@@ -102,6 +102,7 @@ func (api *InstanceMutaterAPI) CharmProfilingInfo(arg params.Entity) (params.Cha
 	// result
 	result.InstanceId = lxdProfileInfo.InstanceId
 	result.ModelName = lxdProfileInfo.ModelName
+	result.ModelUUID = lxdProfileInfo.ModelUUID
```
Comment (wallyworld) [inline apiserver/facades/agent/instancemutater/instancemutater.go:128]: This needs a facade version bump.
That allows older workers to get the same results as before and avoid the not found issue.

**Comment by adisazhar123** [comment]
Moved back to draft because there is ongoing work to be done when handling existing profiles after discussion with @wallyworld

File: apiserver/facades/agent/instancemutater/instancemutater.go (hunk 10 above)
Comment (adisazhar123) [reply apiserver/facades/agent/instancemutater/instancemutater.go]: Sorry, I'm not understanding this correctly. `api.st` is a reference to the shim. I don't think it holds reference to `State`. Did you get this mixed up (or perhaps I did)?

File: apiserver/facades/agent/instancemutater/shim.go (hunk 9 above)
Comment (adisazhar123) [reply apiserver/facades/agent/instancemutater/shim.go]: Related to my comment below

File: provider/lxd/environ.go (hunk 8 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: Yup, thanks!

File: provider/lxd/environ.go (hunk 6 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: Good catch :)

File: provider/lxd/environ_broker.go (hunk 7 above)
Comment (adisazhar123) [reply provider/lxd/environ_broker.go]: Good catch :)

File: apiserver/facades/agent/instancemutater/register.go [hunk 12]
```diff
@@ -14,6 +14,10 @@ func Register(registry facade.FacadeRegistry) {
 	registry.MustRegister("InstanceMutater", 3, func(ctx facade.Context) (facade.Facade, error) {
 		return newFacadeV3(ctx)
 	}, reflect.TypeOf((*InstanceMutaterAPI)(nil)))
+	// Bumped to version 4 to include modelUUID in the response struct.
+	registry.MustRegister("InstanceMutater", 4, func(ctx facade.Context) (facade.Facade, error) {
+		return newFacadeV3(ctx)
+	}, reflect.TypeOf((*InstanceMutaterAPI)(nil)))
```
Comment (adisazhar123) [inline apiserver/facades/agent/instancemutater/register.go]: @wallyworld I'm following an existing version bump. Is this the correct way?

File: api/facadeversions.go [hunk 13]
```diff
@@ -71,7 +71,7 @@ var facadeVersions = facades.FacadeVersions{
 	"HostKeyReporter":              {1},
 	"ImageMetadata":                {3},
 	"ImageMetadataManager":         {1},
-	"InstanceMutater":              {3},
+	"InstanceMutater":              {3, 4},
 	"InstancePoller":               {4},
```
Comment (adisazhar123) [inline api/facadeversions.go:75]: @wallyworld I'm following an existing version bump. Is this the correct way?

File: api/facadeversions.go [hunk 14]
```diff
@@ -71,7 +71,7 @@ var facadeVersions = facades.FacadeVersions{
 	"HostKeyReporter":              {1},
 	"ImageMetadata":                {3},
 	"ImageMetadataManager":         {1},
-	"InstanceMutater":              {3},
+	"InstanceMutater":              {3, 4},
```
Comment (adisazhar123) [inline api/facadeversions.go:74]: @wallyworld I'm following an existing version bump. Is this the correct way?

File: apiserver/facades/agent-schema.json [hunk 15]
```diff
@@ -3367,7 +3367,7 @@
     {
         "Name": "InstanceMutater",
         "Description": "",
-        "Version": 3,
+        "Version": 4,
```
Comment (adisazhar123) [inline apiserver/facades/agent-schema.json:3370]: @wallyworld I'm following an existing version bump. Is this the correct way?

File: provider/lxd/environ.go (hunk 4 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: @CodingCookieRookie yup, that's completely fine to delete the old profile if they are running a new client targeting an old controller.

The expectation is that profile creation using the new naming scheme (`juju-model-<shortid>-....`) and profile deletion targeting the new naming scheme is done on the new controller version. The user has to upgrade their Juju controller for the new behavior to take into effect.

I hope that clears things up :)

File: provider/lxd/upgrades.go [hunk 16]
```diff
@@ -54,3 +61,152 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+	logger.Debugf("running create profile step for model %q", c.env.uuid)
+
+	// Create a model profile.
+	if exists, err := server.HasProfile(c.env.profileName()); err != nil {
+		return errors.Annotatef(err, "check for existing profile %q", c.env.profileName())
+	} else if !exists {
+		if err := server.CreateProfileWithConfig(c.env.profileName(), c.env.profileCfg()); err != nil {
+			return errors.Annotatef(err, "create profile %q with config %+v", c.env.provider, c.env.profileCfg())
+		}
+		logger.Debugf("created new profile %q for model %q", c.env.profileName(), c.env.uuid)
```
Comment (adisazhar123) [inline provider/lxd/upgrades.go]: We only create a new profile if it doesn't exist. We could run into a scenario where a previous upgrade step was run and successfully created a profile but crashed afterwards. 

We make it idempotent here.

File: provider/lxd/upgrades.go [hunk 17]
```diff
@@ -54,3 +61,152 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+				return err
+			} else if !exists {
+				if err = server.CreateProfile(lxdapi.ProfilesPost{
+					ProfilePut: lxdapi.ProfilePut{
+						Config:      profile.Config,
+						Description: profile.Description,
+						Devices:     profile.Devices,
+					},
+					Name: newProfileName,
+				}); err != nil {
```
Comment (adisazhar123) [inline provider/lxd/upgrades.go]: Same here. Only create the charm profile if it doesn't exist. Might have created it in the previous upgrade run but crashed afterwards.

File: apiserver/facades/agent/instancemutater/instancemutater.go (hunk 11 above)
Comment (adisazhar123) [reply apiserver/facades/agent/instancemutater/instancemutater.go:128]: I've left some questions on the files changed regarding version bump. Wanted to get your confirmation if that's the correct way of doing it.

File: apiserver/facades/controller/undertaker/state.go [hunk 18]
```diff
@@ -79,4 +79,9 @@ type Model interface {
 
 	// Watch returns a watcher watching the model.
 	Watch() state.NotifyWatcher
+
+	// Tag returns a name identifying the model.
+	Tag() names.Tag
+
+	ModelTag() names.ModelTag
```
Comment (manadart) [inline apiserver/facades/controller/undertaker/state.go]: What's the difference between `Tag` and (uncommented) `ModelTag`?

File: provider/lxd/environ.go [hunk 19]
```diff
@@ -5,6 +5,8 @@ package lxd
 
 import (
 	stdcontext "context"
+	"fmt"
+	"log"
```
Comment (manadart) [inline provider/lxd/environ.go]: Don't use this log.

File: apiserver/facades/controller/undertaker/state.go (hunk 18 above)
Comment (adisazhar123) [reply apiserver/facades/controller/undertaker/state.go]: Ah they're similar. I was using `Tag()` to get the cloudspec by tag and `ModelTag()` to get the model's short ID. `Tag()` invokes `ModelTag()` under the hood.

I will remove `Tag()` in favor of `ModelTag()`. Thanks Joe.

File: provider/lxd/environ.go (hunk 19 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: Yep good catch. Forgot to remove it while debugging.

**Comment by hmlanigan** [comment]
Running thru QA:

* The `juju-controller` profile is still created at bootstrap, but not used. I deleted all juju named profiles before starting.:
```
$ lxc profile list | grep juju
| juju-controller            |                             | 0       |
| juju-controller-7f622f     |                             | 1       |
```
Interestingly, once bootstrap is complete, this changes to:
```
$ lxc profile list | grep juju
| juju-controller            |                             | 1       |
| juju-controller-7f622f     |                             | 0       |
```

* The `juju-<model-name>` profile is created when `juju add-model` is called:
```
| juju-testing               |                             | 0       |
```

* A charm profile is created without the model short sha
```
$ lxc profile list | grep juju
| juju-testing               |                             | 1       |
| juju-testing-lxd-profile-0 | lxd profile for testing     | 1       |
```

The machine does deploy successfully.

File: api/facadeversions.go (hunk 14 above)
Comment (hmlanigan) [reply api/facadeversions.go:74]: This is correct.

File: apiserver/facades/agent/instancemutater/instancemutater.go (hunk 11 above)
Comment (hmlanigan) [reply apiserver/facades/agent/instancemutater/instancemutater.go:128]: You need two versions of `CharmProfilingInfo`, one with the old behavior and one with the new. The result struct needs a new version as well. The old version of the method can call the new version, rather than fully replicating the code.

File: apiserver/facades/agent/instancemutater/instancemutater.go (hunk 10 above)
Comment (hmlanigan) [reply apiserver/facades/agent/instancemutater/instancemutater.go]: InstanceMutaterState is an interface, you can't call the direct method via `api.st`. The shim implementation is different from what is shown.

**Comment by adisazhar123** [comment]
@hmlanigan the issue you're facing is due to the server side agent using `3.6.9` from the new release while the client was using `3.6.9` from my changes. Could you pull the latest changes? This branch has been rebased on top of `3.6`. If you do a `make go-install` and bootstrap it should work as intended now.

I have also added changes to upgrade the facades by exposing a v3 and v4. The v4 API has its own struct with a `ModelUUID` field.

File: api/agent/instancemutater/machine_test.go [hunk 20]
```diff
@@ -169,7 +169,7 @@ func (s *instanceMutaterMachineSuite) TestCharmProfilingInfoSuccessChangesWithNo
 	defer s.setup(c).Finish()
 
 	args := params.Entity{Tag: s.tag.String()}
-	results := params.CharmProfilingInfoResult{
+	results := params.CharmProfilingInfoResultV4{
```
Comment (wallyworld) [inline api/agent/instancemutater/machine_test.go:172]: The caller needs to be aware of what version is being used on the controller and make the necessary logic changes to adapt. Use `m.facade.BestAPIVersion()`

File: internal/worker/instancemutater/mutater.go [hunk 21]
```diff
@@ -230,7 +230,8 @@ func (m MutaterMachine) processMachineProfileChanges(info *instancemutater.UnitP
 		return report(errors.Annotatef(err, "%s", m.id))
 	}
 
-	expectedProfiles := m.context.getRequiredLXDProfiles(info.ModelName)
+	modelProfileName := fmt.Sprintf("%s-%s", info.ModelName, names.NewModelTag(info.ModelUUID).ShortId())
```
Comment (wallyworld) [inline internal/worker/instancemutater/mutater.go:233]: So here, info may or may not contain the model uuid, depending on what version of the facade we were talking to. The caller needs to make a decision as to whether the old or new naming is used depending on the facade version.

**Review by wallyworld — COMMENTED** [review]
A couple of discussion points to cha about initially.

File: api/agent/instancemutater/machine_test.go (hunk 20 above)
Comment (wallyworld) [reply api/agent/instancemutater/machine_test.go:172]: I was wrong here. The comment only applies to cli uses, not workers.

File: api/controller/undertaker/undertaker.go [hunk 22]
```diff
@@ -66,6 +66,10 @@ func (c *Client) RemoveModelSecrets() error {
 	return c.entityFacadeCall("RemoveModelSecrets", nil)
 }
 
+func (c *Client) RemoveModelProfile() error {
```
Comment (wallyworld) [inline api/controller/undertaker/undertaker.go]: Comment me

File: apiserver/facades/agent-schema.json (hunk 15 above)
Comment (wallyworld) [reply apiserver/facades/agent-schema.json:3370]: This json file is generated via `make rebuild-schema`

File: apiserver/facades/agent/instancemutater/instancemutater.go [hunk 23]
```diff
@@ -41,6 +41,19 @@ type InstanceMutaterAPI struct {
 	getAuthFunc common.GetAuthFunc
 }
 
+type InstanceMutaterAPIV4 struct {
```
Comment (wallyworld) [inline apiserver/facades/agent/instancemutater/instancemutater.go]: This should be the other way around
```
type InstanceMutaterAPI struct {
    *InstanceMutaterV4
}
```
I would rename the current InstanceMutator to InstanceMutatorV3 as well to avoid confusion.

File: apiserver/facades/agent/instancemutater/shim.go (hunk 9 above)
Comment (wallyworld) [reply apiserver/facades/agent/instancemutater/shim.go]: You can delete this method entirely.
Change the `InstanceMutaterState` interface to have `ModelUUID() string` and not `ModelUUID() (string, error)`
and it all works.

File: apiserver/facades/controller/undertaker/undertaker.go [hunk 24]
```diff
@@ -118,6 +122,35 @@ func (u *UndertakerAPI) RemoveModelSecrets() error {
 	return nil
 }
 
+func (u *UndertakerAPI) RemoveModelProfile() error {
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/undertaker.go]: Comment me

File: apiserver/facades/controller/undertaker/undertaker.go [hunk 25]
```diff
@@ -118,6 +122,35 @@ func (u *UndertakerAPI) RemoveModelSecrets() error {
...
+	param := params.Entities{Entities: []params.Entity{{Tag: model.ModelTag().String()}}}
+	cloudSpecResults, err := u.CloudSpec(param)
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if len(cloudSpecResults.Results) != 1 {
+		return fmt.Errorf("expected cloud spec results to return 1 entity, got %d", len(cloudSpecResults.Results))
+	}
+
+	cloudSpec := cloudSpecResults.Results[0]
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/undertaker.go]: Don't need this. Get the cloud type from the model config

File: apiserver/facades/controller/undertaker/undertaker.go [hunk 26]
```diff
@@ -13,14 +15,16 @@ import (
...
 	"github.com/juju/juju/rpc/params"
 	"github.com/juju/juju/secrets/provider"
 	"github.com/juju/juju/state/watcher"
 )
 
 // For testing.
 var (
-	GetProvider = provider.Provider
+	GetProvider    = provider.Provider
+	GetEnvProvider = environs.Provider
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/undertaker.go]: GetEnvironProvider

File: apiserver/facades/controller/undertaker/undertaker.go [hunk 27]
```diff
@@ -118,6 +122,35 @@ func (u *UndertakerAPI) RemoveModelSecrets() error {
...
+	cloudSpecResults, err := u.CloudSpec(param)
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if len(cloudSpecResults.Results) != 1 {
+		return fmt.Errorf("expected cloud spec results to return 1 entity, got %d", len(cloudSpecResults.Results))
+	}
+
+	cloudSpec := cloudSpecResults.Results[0]
+	env, err := GetEnvProvider(cloudSpec.Result.Type)
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/undertaker.go]: s/env/provider

env has a meaning which is Environ

File: provider/lxd/environ.go [hunk 28]
```diff
@@ -96,6 +98,13 @@ func newEnviron(
 	return env, nil
 }
 
+func (env *environ) profileCfg() map[string]string {
+	return map[string]string{
+		"boot.autostart":   "true",
+		"security.nesting": "true",
+	}
+}
+
```
Comment (wallyworld) [inline provider/lxd/environ.go]: Why this change? The profile config does not need an env receiver

File: provider/lxd/environ_broker.go [hunk 29]
```diff
@@ -454,9 +454,42 @@ func (env *environ) StopInstances(ctx context.ProviderCallContext, instances ...
...
+		containerProfiles, err := env.server().GetContainerProfiles(name)
+		if err != nil {
+			common.HandleCredentialError(IsAuthorisationFailure, err, ctx)
+		}
+		profiles = append(profiles, containerProfiles...)
+	}
+
+	var profilesToDelete []string
+	for _, profile := range profiles {
+		// Delete the profiles for the charms assigned to this machine.
```
Comment (wallyworld) [inline provider/lxd/environ_broker.go]: Remind me, why are we doing this?
Just because one machine is removed, there will likely be other machines running units of the app and we need the profile for those. I don't understand how this bit is in the scope of the fix, which is to clean up profiles when a model is deleted.

File: provider/lxd/upgrades.go [hunk 30]
```diff
@@ -54,3 +61,152 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
 		credAttrClientKey:  clientKey,
 	}), nil
 }
+
+func (env *environ) UpgradeOperations(context.ProviderCallContext, environs.UpgradeOperationsParams) []environs.UpgradeOperation {
```
Comment (wallyworld) [inline provider/lxd/upgrades.go]: Comment me

File: provider/lxd/upgrades.go [hunk 31]
```diff
@@ -54,3 +61,152 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+	server := c.env.server()
+
+	logger.Debugf("running create profile step for model %q", c.env.uuid)
+
+	// Create a model profile.
+	if exists, err := server.HasProfile(c.env.profileName()); err != nil {
+		return errors.Annotatef(err, "check for existing profile %q", c.env.profileName())
+	} else if !exists {
+		if err := server.CreateProfileWithConfig(c.env.profileName(), c.env.profileCfg()); err != nil {
+			return errors.Annotatef(err, "create profile %q with config %+v", c.env.provider, c.env.profileCfg())
```
Comment (wallyworld) [inline provider/lxd/upgrades.go]: Can't we just call `env.initProfile()` ?

File: provider/lxd/upgrades.go [hunk 32]
```diff
@@ -54,3 +61,152 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+
+		// Add the model profile.
+		newProfiles = append(newProfiles, c.env.profileName())
+		profilesToAttach = append(profilesToAttach, profileAndInstance{
+			profiles: newProfiles,
+			instance: instanceID,
+		})
+	}
+
+	// Attach new profiles and delete old profiles.
```
Comment (wallyworld) [inline provider/lxd/upgrades.go]: We can't delete the old ones though right?
Cause the whole point of this work is to remove the disambiguation. And so there could be other models still using the old named ones.

Comment (adisazhar123) [reply provider/lxd/upgrades.go]: Initially we didn't want to delete the old profiles because we can't guarantee profile ownership. However, during our discussion with Harry, we decided that it would be okay to attempt at deleting it. Deleting a profile is successful if that profile is unused (not attached to any LXD instance), and error otherwise.

Since as part of the upgrade we attach profiles with the new naming scheme and a `default` profile, the old profiles are unassigned from the current instance. If that was the only instance using the old profile, then deleting it is successful. On the other hand, if there appears to be another instance using that profile, the delete will fail. We treat this as a safe error and continue the upgrade, so that we don't crash the worker.

I hope that clear things up. Happy to discuss if you think otherwise.

File: provider/lxd/environ_broker.go (hunk 29 above)
Comment (adisazhar123) [reply provider/lxd/environ_broker.go]: As discussed this will be moved to the undertaker. The undertaker will invoke a remove model profiles through a facade.

File: provider/lxd/upgrades.go (hunk 31 above)
Comment (adisazhar123) [reply provider/lxd/upgrades.go]: I can indeed do that. Thank you.

File: apiserver/facades/agent/instancemutater/shim.go (hunk 9 above)
Comment (adisazhar123) [reply apiserver/facades/agent/instancemutater/shim.go]: Beautiful.

File: provider/lxd/environ.go (hunk 28 above)
Comment (adisazhar123) [reply provider/lxd/environ.go]: Reverted.

**Comment by adisazhar123** [comment]
@wallyworld the changes are pushed based on your feedback. When you're back could you please take another look? Thank you.

File: provider/lxd/upgrades.go [hunk 33]
```diff
@@ -54,3 +61,151 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+			if oldProfile != "default" && strings.HasPrefix(oldProfile, prefix) {
+				logger.Debugf("deleting profile %q in model %q", oldProfile, c.env.uuid)
+				// In reality, it's difficult to prove the ownership of the profile because the old
+				// naming scheme isn't unique. We attempt to delete it here. If it's used by another instance
+				// then it will fail, and we are okay with this (it'll be kept).
+				err := server.DeleteProfile(oldProfile)
+				if err != nil {
+					logger.Errorf("failed to delete old profile %q due to %q, not a fatal error", oldProfile, err.Error())
+				}
+			}
```
Comment (hpidcock) [inline provider/lxd/upgrades.go]: When possible, try to invert logic in order to exit/branch early.
Long functions are OK, but deep nested logic is difficult to comprehend.

```suggestion
			if oldProfile == "default" {
				continue
			}
			if !strings.HasPrefix(oldProfile, prefix) {
				continue
			}
			
			logger.Debugf("deleting profile %q in model %q", oldProfile, c.env.uuid)
			// In reality, it's difficult to prove the ownership of the profile because the old
			// naming scheme isn't unique. We attempt to delete it here. If it's used by another instance
			// then it will fail, and we are okay with this (it'll be kept).
			err := server.DeleteProfile(oldProfile)
			if err != nil {
				logger.Errorf("failed to delete old profile %q due to %q, not a fatal error", oldProfile, err.Error())
			}
```

File: provider/lxd/upgrades.go [hunk 34]
```diff
@@ -54,3 +61,151 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+		// It's safe for the API to re-attach profiles that are already attached.
+		// So there is no need to exclude profiles that are already attached.
+		err = server.UpdateContainerProfiles(attach.instance, toAttach)
+		if err != nil {
+			return errors.Annotatef(err, "updating instance %q with profiles %+v", attach.instance, toAttach)
+		}
+		logger.Debugf("attached profiles %v to instance %q in model %q", toAttach, attach.instance, c.env.uuid)
+
+		// Delete old profiles except "default".
+		profilesToDelete := currentProfilesSet.Difference(toAttachSet)
```
Comment (hpidcock) [inline provider/lxd/upgrades.go]: We need to move the deletion of profiles to outside of the `for _, attach := range profilesToAttach {` loop.

I suggest doing this set difference and adding them to a outer profiles to delete set. Then iterate that set after. This way you are only attempting to delete each profile once.

File: provider/lxd/upgrades.go [hunk 35]
```diff
@@ -54,3 +61,151 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+
+		currentProfilesSet := set.NewStrings(currentProfiles...)
+		toAttachSet := set.NewStrings(attach.profiles...)
+
+		// This may happen if on a previous run, the upgrade step has attached the new profiles
+		// but crashed and retries. It is safe to skip it.
+		if toAttachSet.IsEmpty() {
+			continue
+		}
+		toAttachSet.Add("default")
```
Comment (hpidcock) [inline provider/lxd/upgrades.go]: You have the `currentProfilesSet`, just check if this instance has the `default` profile first before forcing it on it.

File: provider/lxd/upgrades.go (hunk 32 above)
Comment (hpidcock) [reply provider/lxd/upgrades.go]: Yeah, it appears safe to try to delete a profile that is in use (it won't let you until the profile is unused). If another controller wants to use that profile, it can recreate it or error. It will never affect existing instances.

File: provider/lxd/upgrades.go [hunk 36]
```diff
@@ -54,3 +61,151 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+}
+
+// Description returns a brief explanation what the upgrade step performs.
+func (c createProfilesStep) Description() string {
+	return "Create and assign LXD profiles to instances."
+}
+
+// Run executes the upgrade logic to create profiles with the new naming scheme.
+func (c createProfilesStep) Run(ctx context.ProviderCallContext) error {
+	prefix := fmt.Sprintf("juju-%s", c.env.name)
```
Comment (hpidcock) [inline provider/lxd/upgrades.go]:
```suggestion
	prefix := fmt.Sprintf("juju-%s-", c.env.name)
```

File: provider/lxd/upgrades.go [hunk 37]
```diff
@@ -54,3 +61,151 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+			if !isCharmProfile {
+				continue
+			}
+
+			profile, _, err := server.GetProfile(profileName)
+			if err != nil {
+				return errors.Annotatef(err, "get profile %q", profileName)
+			}
+
+			appAndRevName := profileName[len(prefix)+1:]
```
Comment (hpidcock) [inline provider/lxd/upgrades.go]:
```suggestion
			appAndRevName := profileName[len(prefix):]
```

File: provider/lxd/environ.go [hunk 38]
```diff
@@ -276,6 +279,27 @@ func (env *environ) destroyHostedModelResources(controllerUUID string) error {
...
+	for _, profile := range profiles {
+		if strings.HasPrefix(profile, env.profileName()) {
+			err := server.DeleteProfile(profile)
+			if err != nil {
+				logger.Errorf("failed to delete profile %q due to %s, it may need to be deleted manually through the provider", profile, err.Error())
+			}
+
+			logger.Infof("deleted profile %q", profile)
+		}
```
Comment (hpidcock) [inline provider/lxd/environ.go]:
```suggestion
		if !strings.HasPrefix(profile, env.profileName()) {
			continue
		}
		
		err := server.DeleteProfile(profile)
		if err != nil {
			logger.Errorf("failed to delete profile %q due to %s, it may need to be deleted manually through the provider", profile, err.Error())
			continue
		}

		logger.Infof("deleted profile %q", profile)
```

File: provider/lxd/upgrades.go (hunk 35 above)
Comment (adisazhar123) [reply provider/lxd/upgrades.go]: Unfortunately, we'll always need to have `default` profile inside `toAttachSet` because the call to:

```go
server.UpdateContainerProfiles(attach.instance, toAttach)
```

overwrites the existing profiles that are assigned to the LXD instance. Without `default` in `toAttachSet`, the API complains about:

```
Invalid root disk device: No root device could be found
```

which by default is configured in `default` profile.

**Comment by adisazhar123** [comment]
@hpidcock Thanks Harry. I have made the changes to invert the logic. I need your help to review again.

File: apiserver/facades/agent/instancemutater/instancemutater.go [hunk 39]
```diff
@@ -50,19 +63,33 @@ type instanceMutatorWatcher struct {
...
+	api, err := NewInstanceMutaterAPIV4(st, watcher, resources, authorizer)
+	if err != nil {
+		return nil, err
+	}
+	return &InstanceMutaterAPIV3{
+		api,
+	}, nil
+}
+
+func NewInstanceMutaterAPIV4(st InstanceMutaterState,
```
Comment (wallyworld) [inline apiserver/facades/agent/instancemutater/instancemutater.go:79]: comment me

File: apiserver/facades/agent/instancemutater/instancemutater.go [hunk 40]
```diff
@@ -41,6 +41,19 @@ type InstanceMutaterAPI struct {
 	getAuthFunc common.GetAuthFunc
 }
 
+type InstanceMutaterAPIV3 struct {
+	*InstanceMutaterAPIV4
+}
+
+type charmProfilingData struct {
```
Comment (wallyworld) [inline apiserver/facades/agent/instancemutater/instancemutater.go]: No need for this new struct.  The V3 method just calls the V4 method and thunks the result into the old struct minus the model uuid.

File: apiserver/facades/agent/instancemutater/instancemutater.go [hunk 41]
```diff
@@ -41,6 +41,19 @@ type InstanceMutaterAPI struct {
 	getAuthFunc common.GetAuthFunc
 }
 
+type InstanceMutaterAPIV3 struct {
```
Comment (wallyworld) [inline apiserver/facades/agent/instancemutater/instancemutater.go:48]: Existing issue, but these should be commented.

File: apiserver/facades/agent/instancemutater/instancemutater.go [hunk 42]
```diff
@@ -72,44 +99,76 @@ func NewInstanceMutaterAPI(st InstanceMutaterState,
 	}, nil
 }
 
-// CharmProfilingInfo returns info to update lxd profiles on the machine. If
-// the machine is not provisioned, no profile change info will be returned,
-// nor will an error.
-func (api *InstanceMutaterAPI) CharmProfilingInfo(arg params.Entity) (params.CharmProfilingInfoResult, error) {
-	result := params.CharmProfilingInfoResult{
+func (api *InstanceMutaterAPIV4) gatherCharmProfilingData(arg params.Entity) (charmProfilingData, error) {
```
Comment (wallyworld) [inline apiserver/facades/agent/instancemutater/instancemutater.go]: Make this the V4 implementation returning the V4 struct. Call it from the V3 method.

File: apiserver/facades/client/client/status.go [hunk 43]
```diff
@@ -975,7 +975,7 @@ func fetchAllApplicationsAndUnits(st Backend, model *state.Model, spaceInfos net
 		if err != nil {
 			continue
 		}
-		chName := lxdprofile.Name(model.Name(), app.Name(), ch.Revision())
+		chName := lxdprofile.Name(model.Name(), model.ModelTag().ShortId(), app.Name(), ch.Revision())
```
Comment (wallyworld) [inline apiserver/facades/client/client/status.go]: chName should be charmProfileName right?

File: apiserver/facades/controller/undertaker/mock_test.go [hunk 44]
```diff
@@ -200,3 +210,67 @@ func (m *mockSecrets) CleanupModel(cfg *provider.ModelBackendConfig) error {
...
+type mockProfileDestroyer struct {
+	destroyedProfiles bool
+}
+
+func (m *mockProfileDestroyer) DestroyProfiles() error {
+	m.destroyedProfiles = true
+	return nil
+}
+
+func (m *mockProfileDestroyer) Validate(cfg, old *config.Config) (valid *config.Config, _ error) {
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/mock_test.go]: Don't need all these methods. Just embed the EnvironProvider interface in the mock struct and implement the one DestroyProfiles method we care about.
Or use a go mock.

File: apiserver/facades/controller/undertaker/undertaker_test.go [hunk 45]
```diff
@@ -25,6 +27,7 @@ import (
 type undertakerSuite struct {
 	coretesting.BaseSuite
 	secrets *mockSecrets
+	profile *mockProfileDestroyer
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/undertaker_test.go]: The attr should be called profileDestroyer

File: apiserver/facades/controller/undertaker/undertaker.go [hunk 46]
```diff
@@ -118,6 +120,31 @@ func (u *UndertakerAPI) RemoveModelSecrets() error {
...
+	if err != nil {
+		return errors.Trace(err)
+	}
+
+	modelConfig, err := model.ModelConfig()
+	if err != nil {
+		return err
+	}
+
+	environ, err := GetEnvironProvider(modelConfig.Type())
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/undertaker.go]: Model type is invariant. We have the model when the undertaker api is constructed, We can just set the model type as an attr and avoid the 10 lines above. In fact, we should be getting the environ provider in the register method as well (nb the environ var above should be provider). The undertaker api struct would have a profileDestroyer attr of type ModelProfileDestroyer. Passing in this dependency is a better IOC approach and will make porting the work to 4.0 easier.

File: apiserver/facades/controller/undertaker/undertaker_test.go [hunk 47]
```diff
@@ -57,18 +67,23 @@ func (s *undertakerSuite) setupStateAndAPI(c *gc.C, isSystem bool, modelName str
 			},
 		}, secretsConfigError
 	}
-	api, err := undertaker.NewUndertaker(st, nil, authorizer, secretBackendConfigGetter, nil)
+
+	mockCloudSpecer := mockCloudSpec{}
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/undertaker_test.go]: I can't see where this is used.

File: apiserver/facades/controller/undertaker/undertaker_test.go [hunk 48]
```diff
@@ -40,9 +43,16 @@ func (s *undertakerSuite) setupStateAndAPI(c *gc.C, isSystem bool, modelName str
...
 	}
 
-	st := newMockState(names.NewUserTag("admin"), modelName, isSystem)
+	modelCfg, err := config.New(config.NoDefaults, coretesting.FakeConfig())
+	c.Assert(err, gc.IsNil)
+	st := newMockState(names.NewUserTag("admin"), modelName, isSystem, *modelCfg)
 	s.secrets = &mockSecrets{}
+	s.profile = &mockProfileDestroyer{}
 	s.PatchValue(&undertaker.GetProvider, func(string) (provider.SecretBackendProvider, error) { return s.secrets, nil })
+	s.PatchValue(&undertaker.GetEnvironProvider, func(providerType string) (environs.EnvironProvider, error) {
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/undertaker_test.go]: We won't need this is we fix the IOC approach.

File: provider/lxd/environ.go [hunk 49]
```diff
@@ -276,6 +279,29 @@ func (env *environ) destroyHostedModelResources(controllerUUID string) error {
 	return errors.Trace(env.server().RemoveContainers(names))
 }
 
+func (env *environ) DestroyProfiles() error {
```
Comment (wallyworld) [inline provider/lxd/environ.go]: comment me

File: provider/lxd/environ.go [hunk 50]
```diff
@@ -231,7 +233,8 @@ func (env *environ) Destroy(ctx context.ProviderCallContext) error {
 			return errors.Annotate(err, "destroying LXD filesystems for model")
 		}
 	}
-	return nil
+
+	return env.DestroyProfiles()
```
Comment (wallyworld) [inline provider/lxd/environ.go]: Actually, if this is being done here, we don't need to explicitly call it again in the undertaker worker. Given the undertaker worker calls Destroy(), that's all we need to do, otherwise we're doing it twice.. So we can drop the RemoveModelProfiles() from the controller facade.

File: provider/lxd/environ.go [hunk 51]
```diff
@@ -276,6 +279,29 @@ func (env *environ) destroyHostedModelResources(controllerUUID string) error {
...
+		return errors.Annotate(err, "get profiles")
+	}
+
+	for _, profile := range profiles {
+		if !strings.HasPrefix(profile, env.profileName()) {
+			continue
+		}
+
+		err := server.DeleteProfile(profile)
+		if err != nil {
```
Comment (wallyworld) [inline provider/lxd/environ.go]: We should check for a not found error and ignore it

File: apiserver/facades/agent/instancemutater/instancemutater.go (hunk 39 above)
Comment (adisazhar123) [reply apiserver/facades/agent/instancemutater/instancemutater.go:79]: Done

File: apiserver/facades/agent/instancemutater/instancemutater.go (hunk 40 above)
Comment (adisazhar123) [reply apiserver/facades/agent/instancemutater/instancemutater.go]: Much cleaner. Thanks.

File: apiserver/facades/agent/instancemutater/instancemutater.go (hunk 41 above)
Comment (adisazhar123) [reply apiserver/facades/agent/instancemutater/instancemutater.go:48]: Done

File: apiserver/facades/agent/instancemutater/instancemutater.go (hunk 42 above)
Comment (adisazhar123) [reply apiserver/facades/agent/instancemutater/instancemutater.go]: Much cleaner. Thanks.

File: apiserver/facades/client/client/status.go (hunk 43 above)
Comment (adisazhar123) [reply apiserver/facades/client/client/status.go]: Done.

File: apiserver/facades/controller/undertaker/mock_test.go (hunk 44 above)
Comment (adisazhar123) [reply apiserver/facades/controller/undertaker/mock_test.go]: Removed. This is not needed anymore since we are deleting the profiles in the environ's Destroy method which gets called in the undertaker.

File: apiserver/facades/controller/undertaker/undertaker_test.go (hunk 45 above)
Comment (adisazhar123) [reply apiserver/facades/controller/undertaker/undertaker_test.go]: Removed. This is not needed anymore since we are deleting the profiles in the environ's Destroy method which gets called in the undertaker.

File: apiserver/facades/controller/undertaker/undertaker.go (hunk 46 above)
Comment (adisazhar123) [reply apiserver/facades/controller/undertaker/undertaker.go]: Removed. This is not needed anymore since we are deleting the profiles in the environ's Destroy method which gets called in the undertaker.

File: apiserver/facades/controller/undertaker/undertaker_test.go (hunk 47 above)
Comment (adisazhar123) [reply apiserver/facades/controller/undertaker/undertaker_test.go]: Removed. This is not needed anymore since we are deleting the profiles in the environ's Destroy method which gets called in the undertaker.

File: apiserver/facades/controller/undertaker/undertaker_test.go (hunk 48 above)
Comment (adisazhar123) [reply apiserver/facades/controller/undertaker/undertaker_test.go]: Removed. This is not needed anymore since we are deleting the profiles in the environ's Destroy method which gets called in the undertaker.

File: apiserver/facades/controller/undertaker/mock_test.go [hunk 52]
```diff
@@ -147,6 +149,10 @@ func (m *mockModel) Tag() names.Tag {
 	return names.NewModelTag(m.uuid)
 }
 
+func (m *mockModel) ModelTag() names.ModelTag {
```
Comment (wallyworld) [inline apiserver/facades/controller/undertaker/mock_test.go]: Given we already use Tag() - see above - let's stick with that instead of having both Tag() and ModelTag()

File: provider/lxd/environ.go [hunk 53]
```diff
@@ -231,7 +236,8 @@ func (env *environ) Destroy(ctx context.ProviderCallContext) error {
 			return errors.Annotate(err, "destroying LXD filesystems for model")
 		}
 	}
-	return nil
+
+	return env.DestroyProfiles()
```
Comment (wallyworld) [inline provider/lxd/environ.go]: Could we get the error and annotate , eg above we annotate with  "destroying LXD filesystems for model"

File: provider/lxd/environ.go [hunk 54]
```diff
@@ -30,7 +32,10 @@ import (
 
 var _ environs.HardwareCharacteristicsDetector = (*environ)(nil)
 
-const bootstrapMessage = `To configure your system to better support LXD containers, please see: https://documentation.ubuntu.com/lxd/en/latest/explanation/performance_tuning/`
+const (
+	bootstrapMessage = `To configure your system to better support LXD containers, please see: https://documentation.ubuntu.com/lxd/en/latest/explanation/performance_tuning/`
+	profileNotFound  = "Profile not found"
```
Comment (wallyworld) [inline provider/lxd/environ.go]: Let's comment this to explain we need it because lxd api doesn't give us typed errors

File: provider/lxd/environ.go [hunk 55]
```diff
@@ -276,6 +282,36 @@ func (env *environ) destroyHostedModelResources(controllerUUID string) error {
...
+	}
+
+	for _, profile := range profiles {
+		if !strings.HasPrefix(profile, env.profileName()) {
+			continue
+		}
+
+		err := server.DeleteProfile(profile)
+		if err != nil {
+			if !strings.Contains(err.Error(), profileNotFound) {
```
Comment (wallyworld) [inline provider/lxd/environ.go]: Let's invert this
```
if strings.Contains(err.Error(), profileNotFound) {
    continue
}
...
```

File: provider/lxd/environ_broker_test.go [hunk 56]
```diff
@@ -700,7 +700,7 @@ func (s *environBrokerSuite) TestStopInstances(c *gc.C) {
 	defer ctrl.Finish()
 	svr := lxd.NewMockServer(ctrl)
 
-	svr.EXPECT().RemoveContainers([]string{"juju-f75cba-1", "juju-f75cba-2"})
+	svr.EXPECT().RemoveContainers([]string{"juju-f75cba-1", "juju-f75cba-2"}).Return(nil)
```
Comment (wallyworld) [inline provider/lxd/environ_broker_test.go]: Don't need the return(nil)

File: provider/lxd/upgrades.go [hunk 57]
```diff
@@ -54,3 +62,160 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+	}
+
+	var profilesToAttach []profileAndInstance
+
+	prefix := fmt.Sprintf("juju-%s", c.env.name)
+	prefixTrailingHyphen := fmt.Sprintf("%s-", prefix)
+	// Create charm profiles for each instance.
+	for _, inst := range instances {
+		instanceID := string(inst.Id())
+		log.Println("instanceID is", instanceID)
```
Comment (wallyworld) [inline provider/lxd/upgrades.go]: delete me

File: provider/lxd/upgrades.go [hunk 58]
```diff
@@ -54,3 +62,160 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+		profiles, err := server.GetContainerProfiles(instanceID)
+		if err != nil {
+			return errors.Annotatef(err, "get container profiles for instance %q", instanceID)
+		}
+		log.Println("profiles are", profiles)
```
Comment (wallyworld) [inline provider/lxd/upgrades.go]: delete me

File: provider/lxd/upgrades.go [hunk 59]
```diff
@@ -54,3 +62,160 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+
+			profile, _, err := server.GetProfile(profileName)
+			if err != nil {
+				return errors.Annotatef(err, "get profile %q", profileName)
+			}
+
+			appAndRevName := profileName[len(prefixTrailingHyphen):]
+			newProfileName := fmt.Sprintf("%s-%s", c.env.profileName(), appAndRevName)
+			if exists, err := server.HasProfile(newProfileName); err != nil {
+				return err
```
Comment (wallyworld) [inline provider/lxd/upgrades.go]: errors.Trace(err)

File: provider/lxd/upgrades.go [hunk 60]
```diff
@@ -54,3 +62,160 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+			} else if !exists {
+				if err = server.CreateProfile(lxdapi.ProfilesPost{
+					ProfilePut: lxdapi.ProfilePut{
+						Config:      profile.Config,
+						Description: profile.Description,
+						Devices:     profile.Devices,
+					},
+					Name: newProfileName,
+				}); err != nil {
+					return errors.Annotatef(err, "create a new profile %q", newProfileName)
```
Comment (wallyworld) [inline provider/lxd/upgrades.go]: start error messages with a gerrand, eg "creating nre profile %q"

File: provider/lxd/upgrades.go [hunk 61]
```diff
@@ -54,3 +62,160 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+		if !strings.HasPrefix(oldProfile, prefix) {
+			continue
+		}
+
+		logger.Debugf("deleting profile %q in model %q", oldProfile, c.env.uuid)
+		// In reality, it's difficult to prove the ownership of the profile because the old
+		// naming scheme isn't unique. We attempt to delete it here. If it's used by another instance
+		// then it will fail, and we are okay with this (it'll be kept).
+		err := server.DeleteProfile(oldProfile)
+		if err != nil {
```
Comment (wallyworld) [inline provider/lxd/upgrades.go]: Can we check the error to see if it's an "in use" error and log accordingly

File: provider/lxd/upgrades.go [hunk 62]
```diff
@@ -54,3 +62,160 @@ func ReadLegacyCloudCredentials(readFile func(string) ([]byte, error)) (cloud.Cr
...
+			logger.Errorf("failed to delete old profile %q due to %q, not a fatal error", oldProfile, err.Error())
+		}
+	}
+
+	logger.Debugf("finishing create profile step for model %q", c.env.uuid)
```
Comment (wallyworld) [inline provider/lxd/upgrades.go]: Maybe `s/create/rename`

File: container/lxd/manager.go [hunk 63]
```diff
@@ -456,8 +456,9 @@ func (m *containerManager) AssignLXDProfiles(
 	if err := m.server.UpdateContainerProfiles(instID, profilesNames); err != nil {
 		return report(errors.Trace(err))
 	}
-
+	logger.Debugf("profiles to delete %+v", deleteProfiles)
 	for _, name := range deleteProfiles {
+		logger.Debugf("deleting profile %q", name)
```
Comment (hpidcock) [inline container/lxd/manager.go]: One log is enough. Drop one of these.

**Review by wallyworld — APPROVED** [review]
Thanks for getting this done. It's good to see it fixed.
A few small fixes.
We'll need to double check QA after all the changes.

File: provider/lxd/environ.go [hunk 64]
```diff
@@ -489,7 +525,9 @@ func (env *environ) AssignLXDProfiles(instID string, profilesNames []string, pro
 		return report(errors.Trace(err))
 	}
 
+	logger.Debugf("profiles to delete  %+v", deleteProfiles)
 	for _, name := range deleteProfiles {
+		logger.Debugf("deleting profile %q", name)
```
Comment (hpidcock) [inline provider/lxd/environ.go]: One log is enough.

File: provider/lxd/upgrades.go (hunk 35 above)
Comment (hpidcock) [reply provider/lxd/upgrades.go]: Sorry, what I meant here is that the default profile is just the default. It can be removed from an instance.

We need to respect that the existing instance may not have a default profile attached. In this case, we should not add it.

The logic here should be, for any profile that is already attached to the instance that is not prefixed with `juju-` should be left in the list.

**Comment by adisazhar123** [comment]
@hpidcock @wallyworld thanks both for your feedback. I've pushed new changes to address them.

**Comment by adisazhar123** [comment]
The new changes are tested following the QA steps in the description. It behaves as intended.

**Comment by adisazhar123** [comment]
@hmlanigan I'll go ahead and merge the PR. Please feel free to share any comments later if you have them.
