### PR TITLE
fix: filter ports by server

### LINKED ISSUE #20763: Scale-In of a single unit removes Network Interfaces from each machine in the model.
### Bug Description

After deploying on OpenStack with 3 ubuntu units, scaling-in (juju remove-unit) each instance has its network interfaces removed. 

From an OpenStack point of view , the VMs have lost their network connectivity i.e. they no longer have Neutron ports attached to them.) 

### Environment

juju with OpenStack provider.  Specifically creating a "catch-all" space called `juju` where the subnet-cidr is defined is a REQUIREMENT.  Without this specific binding on the application, the model will not fail this way. 

### Relevant log output

```shell
juju debug-log -m controller --include-module juju.provider.openstack --tail | tee kill-ubunutu.log

machine-0: 19:58:50 TRACE juju.provider.openstack 3/3 live servers found
machine-0: 19:58:53 DEBUG juju.provider.openstack finding subnets in networks: b1af4bf8-da54-436e-b9b2-3d2d4ae6f536, 658bff1a-f1dd-46a0-8102-4062e3b0eda5
machine-0: 19:58:53 TRACE juju.provider.openstack ignoring subnet "1b053424-1977-481e-8bd7-bac10804ee11", part of network "b062de39-5d7b-42bb-b29f-2b92dfae613a"
machine-0: 19:58:53 TRACE juju.provider.openstack ignoring subnet "a5dc2d88-0939-4a0e-9f98-a91b8b74e982", part of network "80d598d2-cd65-4678-8ad9-757618a332bb"
machine-0: 19:58:53 TRACE juju.provider.openstack ignoring subnet "c5c5a4e7-d570-48f4-9850-fce3c3f964e3", part of network "3a776ec9-8527-410b-9220-5391c06ab1c8"
machine-0: 19:58:53 TRACE juju.provider.openstack subnet "1b053424-1977-481e-8bd7-bac10804ee11" not in [], skipping
machine-0: 19:58:53 TRACE juju.provider.openstack subnet "a5dc2d88-0939-4a0e-9f98-a91b8b74e982" not in [], skipping
machine-0: 19:58:53 TRACE juju.provider.openstack subnet "c5c5a4e7-d570-48f4-9850-fce3c3f964e3" not in [], skipping
machine-0: 19:58:53 TRACE juju.provider.openstack found subnet with info network.SubnetInfo{ID:"", CIDR:"91.189.89.16/28", parsedCIDRNetwork:(*net.IPNet)(nil), ProviderId:"ce6513c5-60be-4906-9cae-e3ebe95f08ac", ProviderSpaceId:"", ProviderNetworkId:"658bff1a-f1dd-46a0-8102-4062e3b0eda5", VLANTag:0, AvailabilityZones:[]string{}, SpaceID:"", SpaceName:"", FanInfo:(*network.FanCIDRs)(nil), IsPublic:false, Life:""}
machine-0: 19:58:53 TRACE juju.provider.openstack found subnet with info network.SubnetInfo{ID:"", CIDR:"192.168.0.0/24", parsedCIDRNetwork:(*net.IPNet)(nil), ProviderId:"eeb3ea31-127e-42a4-b5f2-8eea31c37a43", ProviderSpaceId:"", ProviderNetworkId:"b1af4bf8-da54-436e-b9b2-3d2d4ae6f536", VLANTag:0, AvailabilityZones:[]string{}, SpaceID:"", SpaceName:"", FanInfo:(*network.FanCIDRs)(nil), IsPublic:false, Life:""}
machine-1: 19:58:39 TRACE juju.provider.openstack 1/1 live servers found
machine-1: 19:58:44 INFO juju.provider.openstack opened ports in security group 5e9344b5-5274-48ff-86d1-2c42e2e695c1-4: [6443/tcp from 0.0.0.0/0,::/0]
machine-1: 19:58:47 TRACE juju.provider.openstack 1/1 live servers found
machine-1: 19:58:47 INFO juju.provider.openstack opened ports in security group 5e9344b5-5274-48ff-86d1-2c42e2e695c1-6: [6443/tcp from 0.0.0.0/0,::/0]
machine-1: 19:58:47 TRACE juju.provider.openstack 1/1 live servers found
machine-1: 19:58:48 INFO juju.provider.openstack opened ports in security group 5e9344b5-5274-48ff-86d1-2c42e2e695c1-5: [6443/tcp from 0.0.0.0/0,::/0]
machine-2: 19:58:48 TRACE juju.provider.openstack 4/4 live servers found
machine-2: 19:58:50 DEBUG juju.provider.openstack finding subnets in networks: b1af4bf8-da54-436e-b9b2-3d2d4ae6f536, 658bff1a-f1dd-46a0-8102-4062e3b0eda5
machine-2: 19:58:50 TRACE juju.provider.openstack ignoring subnet "1b053424-1977-481e-8bd7-bac10804ee11", part of network "b062de39-5d7b-42bb-b29f-2b92dfae613a"
machine-2: 19:58:50 TRACE juju.provider.openstack ignoring subnet "a5dc2d88-0939-4a0e-9f98-a91b8b74e982", part of network "80d598d2-cd65-4678-8ad9-757618a332bb"
machine-2: 19:58:50 TRACE juju.provider.openstack ignoring subnet "c5c5a4e7-d570-48f4-9850-fce3c3f964e3", part of network "3a776ec9-8527-410b-9220-5391c06ab1c8"
machine-2: 19:58:50 TRACE juju.provider.openstack subnet "1b053424-1977-481e-8bd7-bac10804ee11" not in [], skipping
machine-2: 19:58:50 TRACE juju.provider.openstack subnet "a5dc2d88-0939-4a0e-9f98-a91b8b74e982" not in [], skipping
machine-2: 19:58:50 TRACE juju.provider.openstack subnet "c5c5a4e7-d570-48f4-9850-fce3c3f964e3" not in [], skipping
machine-2: 19:58:50 TRACE juju.provider.openstack found subnet with info network.SubnetInfo{ID:"", CIDR:"91.189.89.16/28", parsedCIDRNetwork:(*net.IPNet)(nil), ProviderId:"ce6513c5-60be-4906-9cae-e3ebe95f08ac", ProviderSpaceId:"", ProviderNetworkId:"658bff1a-f1dd-46a0-8102-4062e3b0eda5", VLANTag:0, AvailabilityZones:[]string{}, SpaceID:"", SpaceName:"", FanInfo:(*network.FanCIDRs)(nil), IsPublic:false, Life:""}
machine-2: 19:58:50 TRACE juju.provider.openstack found subnet with info network.SubnetInfo{ID:"", CIDR:"192.168.0.0/24", parsedCIDRNetwork:(*net.IPNet)(nil), ProviderId:"eeb3ea31-127e-42a4-b5f2-8eea31c37a43", ProviderSpaceId:"", ProviderNetworkId:"b1af4bf8-da54-436e-b9b2-3d2d4ae6f536", VLANTag:0, AvailabilityZones:[]string{}, SpaceID:"", SpaceName:"", FanInfo:(*network.FanCIDRs)(nil), IsPublic:false, Life:""}
machine-1: 20:00:46 TRACE juju.provider.openstack 1/1 live servers found
machine-1: 20:00:48 DEBUG juju.provider.openstack terminating instances [985914e6-cf13-4030-9aab-e8f2d00daf72]
machine-1: 20:00:49 TRACE juju.provider.openstack 1/1 live servers found
machine-1: 20:00:50 INFO juju.provider.openstack closed ports in security group 5e9344b5-5274-48ff-86d1-2c42e2e695c1-4: [6443/tcp from 0.0.0.0/0,::/0]
```

### Additional context

One thing to note is that when deployed this way, juju does CREATE a security-group for each machine instance and it does create a global model security-group -- neither of which are attached to the port supporting the instance.  Instead a "default" SG is attached to each port. 

By changing the bundle to not have the endpoint bindings, scale-in works fine:

ex) leave these off
```yaml
    # bindings:
    #  "": juju
```

### Juju version

3.6.9

### Cloud

OpenStack

### Expected behaviour

I'd expect that when removing one of the ubuntu units -- only that unit would drop.  It doesn't matter if the application is ubuntu or kubernetes or postgres.  Whatever the machine workload is -- the same effect is seen.

### Reproduce / Test

Deploy a cluster using the provided script, then scale down the ubuntu nodes using `juju remove-unit ubuntu/X`

create  `simple.sh `

```sh
#!/bin/bash
set -euxo pipefail

JUJU_MODEL=u-prod
CLOUD=openstack-*****

# Ensure openstack provider logging
juju model-config -m controller logging-config='<root>=INFO;juju.provider.openstack=TRACE'

# Check if model exists, create if not
if ! juju models --format json | jq -e ".models[].name | select(. == \"admin/$JUJU_MODEL\")" >/dev/null; then
    juju add-model "$JUJU_MODEL" "$CLOUD"
fi

# Clear fan-config if needed
juju model-config -m "$JUJU_MODEL" fan-config=""

# Add a `juju` space if it doesn't exist
if ! juju spaces -m "$JUJU_MODEL" --format json | jq -e ".spaces[] | select(.name == \"juju\")" >/dev/null; then
    juju add-space -m "$JUJU_MODEL" juju 192.168.0.0/24
fi

# Create a temporary bundle file in the current directory
TMPDIR="./tmp_bundle_$$"
mkdir -p "$TMPDIR"
trap 'rm -rf "$TMPDIR"' EXIT  # cleanup temp dir on exit
BUNDLE="$TMPDIR/ubuntu.yaml"

cat > "$BUNDLE" <<'EOF'
applications:
  ubuntu:
    charm: ch:ubuntu
    base: ubuntu@24.04
    exposed: true
    num_units: 3
    bindings:
      "": juju
EOF

# Deploy the bundle using relative path
juju deploy -m "$JUJU_MODEL" "$BUNDLE"
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nicolasbock**
When terminating instance ports, the ports need to be filtered by the device_id (the server ID). Using only the port name is too broad and will result in the deletion of ports that are unrelated to the termination.

## Checklist

- [ ] Code style: imports ordered, good names, simple structure, etc
- [ ] Comments saying why design decisions were made
- [ ] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

A reproducer would do something like the following:

```console
$ juju bootstrap --config network=net1 --config network=net2
$ juju add-model ports
$ juju add-space beta net1/cidr
$ juju add-space gamma net2/cidr
$ juju deploy --num-units 2 --bind beta ubuntu server-beta
$ juju deploy --num-units 2 --bind gamma ubuntu server-gamma
$ openstack port list --column Name --column "MAC Address" --format value | grep juju-
juju-7fdb0ac2-9a6b-4743-80f2-f644ee7a9a5a-y9degn8b fa:16:3e:52:2e:06
juju-7fdb0ac2-9a6b-4743-80f2-f644ee7a9a5a-9l06zsug fa:16:3e:35:2b:14
```

Juju will create 2 named ports attached to the machines in space beta
(server-beta application). The ports in space alpha do not have a name.

When the server-beta deployment is scaled down, juju will remove all
ports:

```console
$ juju remove-unit server-beta/1
$ openstack server list --name test-2 --column Name --column Networks --format value
juju-9aead6-test-2 {}
```

## Links

**Issue:** Fixes #20763.

**Jira card:** JUJU-

### CODE REVIEW

File: internal/provider/openstack/provider.go [hunk 1]
```diff
@@ -2242,7 +2242,9 @@ func (e *Environ) terminateInstanceNetworkPorts(id instance.Id) error {
 	}
 
 	client := e.neutron()
-	ports, err := client.ListPortsV2()
+	filter := neutron.NewFilter()
+	filter.Set("device_id", string(id))
+	ports, err := client.ListPortsV2(filter)
```
Comment (SimonRichardson) [inline internal/provider/openstack/provider.go:2247]: Can we get a test for this.

Is the device_id always guaranteed to be the instance id?

File: internal/provider/openstack/provider.go
Comment (SimonRichardson) [inline internal/provider/openstack/provider.go:2271]: I also feel like it would be good to tag ports with additional information, so that it makes it easier to filter. Though, that seems like a larger change.

https://github.com/go-goose/goose/blob/6428799c7cac05d7106fdfa7bb17a7bea0f8655e/neutron/neutron.go#L268

**Review by SimonRichardson — COMMENTED** [review]
This seems legitimate.

**Review by nicolasbock — COMMENTED** [review]
I am working on a reproducer and a test for this patch.

File: internal/provider/openstack/provider.go (hunk 1 above)
Comment (nicolasbock) [reply internal/provider/openstack/provider.go:2247]: According to the upstream [API documentation](https://docs.openstack.org/api-ref/network/v2/#list-ports), the `device_id` is the whatever uses the port, including the server ID.

File: internal/provider/openstack/provider.go
Comment (nicolasbock) [reply internal/provider/openstack/provider.go:2271]: I agree, that would be helpful. I can propose such a change in a follow-on PR. What do you think?

Comment (SimonRichardson) [reply internal/provider/openstack/provider.go:2271]: >  I can propose such a change in a follow-on PR.

Yeah, 100%.

File: internal/provider/openstack/provider.go [hunk 2]
```diff
@@ -2275,6 +2277,7 @@ func (e *Environ) terminateInstanceNetworkPorts(id instance.Id) error {
 	for _, change := range changes.SortedValues() {
 		// Delete a port. If we encounter an error add it to the list of errors
 		// and continue until we've exhausted all the ports to delete.
+		logger.Tracef("Deleting port %s", change)
```
Comment (nicolasbock) [inline internal/provider/openstack/provider.go:2280]: @addyess

**Review by wallyworld — COMMENTED** [review]
Change looks ok,thank you.
We'd need a unit test, and QA steps in the PR description.

**Comment by nicolasbock** [comment]
Thanks @wallyworld 

I am working on the unit test right now. I will update the description to add reproducer steps.

File: internal/provider/openstack/provider_test.go [hunk 3]
```diff
@@ -1189,3 +1190,50 @@ func envWithNetworking(net Networking, netCfg string) *Environ {
...
+
+	testInterfaces := []nova.OSInterface{
+		{PortID: "server-1-port-1"},
+		{PortID: "server-1-port-2"},
+		{PortID: ""},
+	}
+
+	mockNeutron := NewMockNetworkingNeutron(ctrl)
+
+	mockNeutron.EXPECT().ListPortsV2(gomock.Any()).Return([]neutron.PortV2{
```
Comment (jameinel) [inline internal/provider/openstack/provider_test.go]: Is this the right test? 
I thought the explicit change that we were trying to make is that we are passing ListPortsV2 the device_id. But by using "gomock.Any()" here, I thought we allow for it to be empty.

eg, I think this should be:

```suggestion
	mockNeutron.EXPECT().ListPortsV2("test-instance-1").Return([]neutron.PortV2{
```

I supposed it can't be exactly that because you actually have a `Filter{}` object. However, the concrete fix that we are making is that we need to be passing the device_id, so we need a small tweak here.
Otherwise the rest is pretty much a tautology because it would have passed with the previous version of the code.

**Review by jameinel — COMMENTED** [review]
The framing is good here, I think the test infrastructure is in the right place, but we need to make sure that we uncover the fix, probably with a commented line about why it is important that we have it.

File: internal/provider/openstack/provider_test.go [hunk 4]
```diff
@@ -1189,3 +1190,59 @@ func envWithNetworking(net Networking, netCfg string) *Environ {
...
+
+	testInterfaces := []nova.OSInterface{
+		{PortID: "server-1-port-1"},
+		{PortID: "server-1-port-2"},
+		{PortID: ""},
+	}
+
+	mockNeutron := NewMockNetworkingNeutron(ctrl)
+
+	filter := neutron.NewFilter()
```
Comment (jameinel) [inline internal/provider/openstack/provider_test.go]:
```suggestion
    // We need to ensure that the query against Openstack ListPortsV2 is passing in a device_id filter
    // so that we know it isn't getting all ports that openstack knows about.
	filter := neutron.NewFilter()
```

**Review by jameinel — APPROVED** [review]
I've tested that the test does ensure that we are passing in a filter vs not passing in a filter. It has hard-to-understand failure modes, but that is because of gomock, not because of something that we can control.
I have *not* done full QA against a live Openstack model, but I did ensure that the unit-test covers the change and the constraint that we need.

File: internal/provider/openstack/provider_test.go [hunk 5]
```diff
@@ -1189,3 +1190,60 @@ func envWithNetworking(net Networking, netCfg string) *Environ {
 		networking: net,
 	}
 }
+
+func (s *providerUnitTests) TestTerminateInstanceNetworkPorts(c *gc.C) {
```
Comment (wallyworld) [inline internal/provider/openstack/provider_test.go]: This isn't how we want to test this part. The go-goose upstream has test service which the nova and neutron clients can use directly without needing to stub any api calls.
The test would be added to `local_test.go`. 
I'll do the changes and push them up.

**Review by wallyworld — APPROVED** [review]
