### PR TITLE
fix(secret): support filtering secrets by label

### LINKED ISSUE #21296: In Juju 4.0.0 show-secret returns all secrets when a name is used
### Description

In Juju 4.0.0, `juju show-secret <secret-name>` returns all secrets, not just the named one:

```
$ juju secrets
ID                    Name  Owner    Rotation  Revision  Last updated
d4fq08fmp25c797lul70  sec2  <model>  never            3  12 minutes ago  
d4fq017mp25c797lul6g  sec1  <model>  never            2  3 minutes ago   
$ juju show-secret sec1
d4fq08fmp25c797lul70:
  revision: 3
  rotation: never
  owner: <model>
  description: foo2
  name: sec2
  created: 2025-11-20T23:11:29.999052694Z
  updated: 2025-11-20T23:12:51.4728684Z
d4fq017mp25c797lul6g:
  revision: 2
  rotation: never
  owner: <model>
  description: foo
  name: sec1
  created: 2025-11-20T23:11:00.851255111Z
  updated: 2025-11-20T23:21:40.609024785Z
```

### Juju version

4.0.0

### Cloud

Kubernetes

### Expected behaviour

Only the secret that was named in the command should be returned.

### Reproduce / Test

Setup:

```
$ juju add-secret sec1 username=usr password=hunter2 --info=foo
secret:d4fq017mp25c797lul6g
$ juju add-secret sec2 username=usr2 password=hunter3 --info=foo2
secret:d4fq08fmp25c797lul70
$ juju update-secret sec2 username=usr3 password=hunter4
$ juju update-secret sec2 username=usr3 password=hunter5
```

Specifying `--revision=1` and specifically the `sec2` secret, I get both secrets, the only revision for `sec1` (which should not be there) and something called "revision 3" but with the revision 1 content for `sec2`:

```
$ juju show-secret sec2 --reveal --format=json --revision=1 | jq
{
  "d4fq017mp25c797lul6g": {
    "revision": 1,
    "checksum": "4366a963cebe2366852129cf7a06d0e3fbad0d3a7843e088545baef77db0153e",
    "rotation": "never",
    "owner": "<model>",
    "description": "foo",
    "name": "sec1",
    "created": "2025-11-20T23:11:00.851255111Z",
    "updated": "2025-11-20T23:11:00.851255111Z",
    "content": {
      "Data": {
        "password": "hunter2",
        "username": "usr"
      }
    }
  },
  "d4fq08fmp25c797lul70": {
    "revision": 3,
    "checksum": "c8039eb0bc48ef38b39a0e7cda0020741d5d93d73c0cfae22a83a58dd9b571c1",
    "rotation": "never",
    "owner": "<model>",
    "description": "foo2",
    "name": "sec2",
    "created": "2025-11-20T23:11:29.999052694Z",
    "updated": "2025-11-20T23:12:51.4728684Z",
    "content": {
      "Data": {
        "password": "hunter3",
        "username": "usr2"
      }
    }
  }
}
```

If I ask for another revision, I get an error:

```
$ juju show-secret sec2 --reveal --format=json --revision=2
{}
ERROR secret revision 2 for  not found (secret revision not found)
```

But this is because it's trying to get revision 2 of `sec1`. If I add one, it works:

```
$ juju update-secret sec1 username=secret1user password=hunter0
$ juju show-secret sec2 --reveal --format=json --revision=2 | jq
{
  "d4fq017mp25c797lul6g": {
    "revision": 2,
    "checksum": "7591d04ecf361cedfde22f53b9084b5af9904f9bf375541ab3b0b9c57fc9c945",
    "rotation": "never",
    "owner": "<model>",
    "description": "foo",
    "name": "sec1",
    "created": "2025-11-20T23:11:00.851255111Z",
    "updated": "2025-11-20T23:21:40.609024785Z",
    "content": {
      "Data": {
        "password": "hunter0",
        "username": "secret1user"
      }
    }
  },
  "d4fq08fmp25c797lul70": {
    "revision": 3,
    "checksum": "c8039eb0bc48ef38b39a0e7cda0020741d5d93d73c0cfae22a83a58dd9b571c1",
    "rotation": "never",
    "owner": "<model>",
    "description": "foo2",
    "name": "sec2",
    "created": "2025-11-20T23:11:29.999052694Z",
    "updated": "2025-11-20T23:12:51.4728684Z",
    "content": {
      "Data": {
        "password": "hunter4",
        "username": "usr3"
      }
    }
  }
}
```

Using the ID rather than the name works fine:

```
$ juju show-secret d4fq08fmp25c797lul70 --reveal --format=json --revision=2 | jq
{
  "d4fq08fmp25c797lul70": {
    "revision": 3,
    "checksum": "c8039eb0bc48ef38b39a0e7cda0020741d5d93d73c0cfae22a83a58dd9b571c1",
    "rotation": "never",
    "owner": "<model>",
    "description": "foo2",
    "name": "sec2",
    "created": "2025-11-20T23:11:29.999052694Z",
    "updated": "2025-11-20T23:12:51.4728684Z",
    "content": {
      "Data": {
        "password": "hunter4",
        "username": "usr3"
      }
    }
  }
}
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by gfouillet**
This patch introduces new methods `GetSecretByURI`, `GetSecretsByLabels`, and `ListAllSecrets` in
`domain/secret/state/state.go` to replace the jack-of-all-trades `ListSecrets`. This significantly
improves clarity and modularity when querying secrets and fixes https://github.com/juju/juju/issues/21296

The changes include:
- Adding `GetSecretByURI` to retrieve a single secret by its URI.
- Adding `GetSecretsByLabels` to fetch secrets based on labels.
- Adding `ListAllSecrets` to retrieve all secrets.
- Refactoring `fetchSecrets` and related helper methods for improved query flexibility.
- Updating the test suite in `state_test.go` to align with the newly introduced methods and
  removing references to the old implementation.
- Enhancing mock support in `service/package_mock_test.go` for the newly added methods.

> ![NOTE]
>
> I believe SQL query can be a bit refactored too, through introducing a view for secret. 
> It implies a significant refactoring, s I focused this PR on fixing bug. I let a todo to keep that in mind.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Bootstrap and add a model

then create two secrets:
```sh
juju add-secret foo bar=42 # secret-1
juju add-secret <id of secret-1> baz=42  # secret-2
```

Verify following:
```sh
juju secrets # return all secrets
juju show-secret foo # return  secret-1
juju show-secret <id of secret-1> # return  secret-1, even if it is technically the label of secret-2
juju show-secret <id of secret-2> # return  secret-2
juju show-secret secret:<id of secret-1> # return  secret-1
juju show-secret secret:<id of secret-2> # return  secret-2
```

## Documentation changes

This doesn't affect the documentation, it is a deviation from behavior of 3.6

## Links
**Issue:** Fixes #21296.

**Jira card:** [JUJU-8823](https://warthogs.atlassian.net/browse/JUJU-8823)

[JUJU-8823]: https://warthogs.atlassian.net/browse/JUJU-8823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/secret/state/state.go [hunk 1]
```diff
@@ -1170,13 +1169,20 @@ func (st State) ListSecrets(ctx context.Context, uri *coresecrets.URI,
 			"secret revision %d for %s not found", *revision, uri).Add(secreterrors.SecretRevisionNotFound)
 	}
 
+	var label *string
+	if len(labels) > 1 {
```
Comment (wallyworld) [inline domain/secret/state/state.go]: The method as written takes multiple labels as a possible filter term and so we can't just arbitrarily decide to impose different semantics here. We either need to honour the contract and compose a query with an IN clause, or change the method. The facade caller currently only deals with a single label so we could change the method here to take a single label as a filter term. It was intended that we might support multiple labels in the filter term, but we don't have that at the moment - the cli and facade just pass in a single label.

We should probably have 2 state methods
`GetSecretByURI(ctx context.Context, uri *coresecrets.URI, revision *int) (*coresecrets.SecretMetadata, []*coresecrets.SecretRevisionMetadata, error)`

If we want to support multiple labels:

`GetSecretsForLabels(ctx context.Context, labels domainsecret.Labels, revision *int) ([]*coresecrets.SecretMetadata, [][]*coresecrets.SecretRevisionMetadata, error)`

But we could agree to just filter on a single label and rework later if needed, so it would be
`GetSecretsByLabel(ctx context.Context, label string, revision *int) (*coresecrets.SecretMetadata, []*coresecrets.SecretRevisionMetadata, error)`

File: domain/secret/state/state.go [hunk 2]
```diff
@@ -1409,36 +1429,35 @@ SELECT sm.secret_id AS &secretInfo.secret_id,
...
-          FROM   secret_application_owner so
-          JOIN   application
-          WHERE  application.uuid = so.application_uuid
-          UNION
-          SELECT $ownerKind.unit_owner_kind AS owner_kind, unit.name AS owner_id, label, secret_id
-          FROM   secret_unit_owner so
-          JOIN   unit
-          WHERE  unit.uuid = so.unit_uuid
-       ) so ON so.secret_id = sm.secret_id`
+JOIN secret_revision AS sr ON sm.secret_id = sr.secret_id
```
Comment (wallyworld) [inline domain/secret/state/state.go]: What's our standard syntax to use? Some places use `AS` and others don't Have we settled on an agreed approach?

File: domain/secret/state/state.go [hunk 3]
```diff
@@ -1409,36 +1429,35 @@ SELECT sm.secret_id AS &secretInfo.secret_id,
...
+LEFT JOIN secret_owner AS so ON so.secret_id = sm.secret_id
+`
 
 	queryTypes := []any{
 		secretInfo{},
 		secretOwner{},
 		ownerKindParam,
 	}
 	queryParams := []any{ownerKindParam}
+	if uri != nil && label != nil {
```
Comment (wallyworld) [inline domain/secret/state/state.go]: This is input validation which we can do in the service layer.

File: domain/secret/state/state.go [hunk 4]
```diff
@@ -1409,36 +1429,35 @@ SELECT sm.secret_id AS &secretInfo.secret_id,
...
 		queryTypes = append(queryTypes, secretID{})
 		query = query + "\nWHERE sm.secret_id = $secretID.id"
 		queryParams = append(queryParams, secretID{ID: uri.ID})
 	}
+	type secretLabelOrId struct {
+		Value string `db:"value"`
+	}
+	if label != nil {
+		queryTypes = append(queryTypes, secretLabelOrId{})
+		query = query + "\nWHERE so.label = $secretLabelOrId.value OR sm.secret_id = $secretLabelOrId.value"
```
Comment (wallyworld) [inline domain/secret/state/state.go]: This isn't right - a label is not a secret id. The label and id (secret uri) attributes are distinct and different from each other. The label filter term is just used to march a secret label.

The caller will pass in either a secret URI (id) or a label with an optional revision. The URI or label is used to find a single matching secret. This `listSecretsAnyOwner()` method really needs to be changed to a method that returns only a single secret.

File: domain/secret/state/state.go [hunk 5]
```diff
@@ -1409,36 +1429,35 @@ SELECT sm.secret_id AS &secretInfo.secret_id,
...
 	queryParams := []any{ownerKindParam}
+	if uri != nil && label != nil {
+		return nil, errors.New("cannot specify both URI and label")
+	}
 	if uri != nil {
 		queryTypes = append(queryTypes, secretID{})
 		query = query + "\nWHERE sm.secret_id = $secretID.id"
 		queryParams = append(queryParams, secretID{ID: uri.ID})
 	}
+	type secretLabelOrId struct {
```
Comment (wallyworld) [inline domain/secret/state/state.go]: We should keep all the types together in types.go

File: domain/secret/state/state.go [hunk 6]
```diff
@@ -1454,6 +1473,30 @@ FROM   secret_metadata sm
 	if err != nil && !errors.Is(err, sqlair.ErrNoRows) {
 		return nil, errors.Capture(err)
 	}
+
+	// if any secret match by its secret ID, discard any secret that matches by label
```
Comment (wallyworld) [inline domain/secret/state/state.go]: ????
Secret labels are unique, as are secret ids. They are distinct attributes and should never be compared for equality.

Comment (gfouillet) [reply domain/secret/state/state.go]: Yes. but:

```sh
❯ juju show-secret -h
Usage: juju show-secret [options] <ID>|<name>
```

At this point, we can use an ID or a name as first arg.

In practice, it can be a secret URI (secret:ID) a plain ID, a plain name ("label").

URI case can be decided early (through parsing), but ID vs label can't.

So I tested in 3.6. And apparently, if we have a secret with a label which is the ID of another secret, and we try get this ID, the "ID" type take precedence over the label.

See my QA step for more insight.

This is the main reason of this ugliness.

File: domain/secret/state/state.go (hunk 2 above)
Comment (gfouillet) [reply domain/secret/state/state.go]: Yes, to me we want to be sqlfluff compliance with the requirements we use for validating the DDL.

So AS is required (as you can see if you try to define a view in DDL and don't follow the pattern.

However this is not enforced by any linter for now.

File: domain/secret/state/state.go (hunk 1 above)
Comment (gfouillet) [reply domain/secret/state/state.go]: Yes I definitely want to do that (and actually started to do it). But it leads to several question and more refactoring.

see my other comment about `juju show-secret <ID>|<name>` which is an example of those.

I decided to go to the smallest change that fixes the bug (show-secret list ALL secrets), then do more refactoring afterward (at least remove the possibility to have several labels down in the service).

We need to be careful, though, because the facade has only one function `ListSecrets` with filters which either return a list `juju secrets` or a single secret `juju show-secret`.

File: domain/secret/state/state.go (hunk 4 above)
Comment (gfouillet) [reply domain/secret/state/state.go]: I am aware of that intent... But behavior don't respect exactly that (see QA). the ID can come in a form which is not an URI.

**Comment by gfouillet** [comment]
@wallyworld I am reviewing the whole code base to understand what are label and what are names, because this is confusing.

I assume that most of the misunderstanding we got is due to the signification between URI, ID, name or label terminology. Here is my understanding that leads to my change:

* URI: is a string composed of the prefix `secret:` and the ID of the secret
* ID: is a unique random string generated when the secret is added
* name: in CLI, it refers to the "label" of the secret.
* label: it is the "name" of the secret in the DDL.

Those assumption about label where based on the following code (in show-secret command):

https://github.com/juju/juju/blob/23ab1d4abd3d80929ecf1a38c85bf56384b11c8a/cmd/juju/secrets/show.go#L138-L140

And also:

https://github.com/juju/juju/blob/d75d187adbfe916c6fc56488f41ee8127c1a57ee/cmd/juju/secrets/list.go#L204-L226

But this is indeed confusing, i don't get why we would have different labels depending on the owner...

image


Insight would be appreciate on this point.

**Comment by gfouillet** [comment]
This one is related with semantics:
https://github.com/juju/juju/issues/21344#event-21222789661

**Comment by wallyworld** [comment]
All secrets have a unique ID which is an [XID identifier](https://github.com/rs/xid)
This ID can be used to form a secret URI of the form `secret:<xid>`
When referring to a secret by ID, either the stand alone `<xid>` can be used as a shortcut, or the full URI can be used.
Thus
`juju show-secret secret:9m4e2mr0ui3e8a215n4g`
and
`juju show-secret 9m4e2mr0ui3e8a215n4g`
are equivalent.

Secrets also have a label. Labels must be unique for a given owner. For user created secrets, the model is considered the owner. For charm created secrets, either the app or the unit is the owner.

For `juju show-secret`, if the supplied positional arg cannot be parsed as a valid XID, it is considered a label (aka secret name). Thus either a single URI or label is used, not both. The determination of whether a URI or label is use dis done in the CLI; by the time the request gets to the facade, the filter with either URI or label is already filled in.

For model owned secrets, the label will return a unique secret. For app or unit owned secrets, the label could return multiple secrets (two different apps could create a secret with the same label) and I realise my comment saying that filtering on label only returns one secret was wrong. Sorry about that, don't know what I was thinking.

File: domain/secret/state/state.go (hunk 6 above)
Comment (wallyworld) [reply domain/secret/state/state.go]: I was wrong here - labels are NOT universally unique; they are just unique for user created secrets, since the owner is always the model. But different apps and units can create secrets with the same label.

File: domain/secret/state/state.go (hunk 1 above)
Comment (wallyworld) [reply domain/secret/state/state.go]: I was wrong about labels always being unique, so 
`GetSecretsByLabel(ctx context.Context, label string, revision *int) (*coresecrets.SecretMetadata, []*coresecrets.SecretRevisionMetadata, error)`

Is not valid. Ignore that bit.

**Comment by gfouillet** [comment]
> For `juju show-secret`, if the supplied positional arg cannot be parsed as a valid XID, it is considered a label (aka secret name). Thus either a single URI or label is used, not both. The determination of whether a URI or label is use dis done in the CLI; by the time the request gets to the facade, the filter with either URI or label is already filled in.

Gotcha, this was what I missed, thanks.

File: domain/secret/service/interface.go [hunk 7]
```diff
@@ -56,9 +56,11 @@ type State interface {
 	GetLatestRevision(ctx context.Context, uri *secrets.URI) (int, error)
 	GetLatestRevisions(ctx context.Context, uris []*secrets.URI) (map[string]int, error)
 	GetSecretValue(ctx context.Context, uri *secrets.URI, revision int) (secrets.SecretData, *secrets.ValueRef, error)
-	ListSecrets(ctx context.Context, uri *secrets.URI,
-		revision *int, labels domainsecret.Labels,
-	) ([]*secrets.SecretMetadata, [][]*secrets.SecretRevisionMetadata, error)
+	GetSecretByURI(ctx context.Context, uri secrets.URI, revision *int) (*secrets.SecretMetadata,
+		[]*secrets.SecretRevisionMetadata, error)
+	GetSecretsByLabels(ctx context.Context, labels domainsecret.Labels, revision *int) ([]*secrets.SecretMetadata,
```
Comment (wallyworld) [inline domain/secret/service/interface.go]: I guess this should be `ListSecretsByLabels`
When I suggested the api change, I should have suggested List for this one

File: domain/secret/service/service.go [hunk 8]
```diff
@@ -639,16 +638,43 @@ func (s *SecretService) updateSecret(ctx domain.AtomicContext, uri *secrets.URI,
...
+		metadataList, revisionsList, err := s.secretState.GetSecretsByLabels(ctx, labels, revision)
+		if err != nil {
+			return nil, nil, errors.Errorf("getting secrets by labels: %w", err)
+		}
+		return metadataList, revisionsList, nil
+	}
+
+	if revision != nil {
+		return nil, nil, errors.Errorf("cannot specify revision without URI or labels")
+	}
```
Comment (wallyworld) [inline domain/secret/service/service.go:674]: Let's do all the arg validation checks together at the start of the method.

File: domain/secret/state/state.go [hunk 9]
```diff
@@ -1152,54 +1152,128 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
 }
 
-// ListSecrets returns the secrets matching the specified criteria.
-// If all terms are empty, then all secrets are returned.
-func (st State) ListSecrets(ctx context.Context, uri *coresecrets.URI,
-	revision *int,
-	// TODO(secrets) - use all filter terms
-	labels domainsecret.Labels,
-) ([]*coresecrets.SecretMetadata, [][]*coresecrets.SecretRevisionMetadata, error) {
+func (st State) GetSecretByURI(ctx context.Context, uri coresecrets.URI, revision *int) (*coresecrets.SecretMetadata,
```
Comment (wallyworld) [inline domain/secret/state/state.go:1156]: Comment me

File: domain/secret/state/state.go [hunk 10]
```diff
@@ -1152,54 +1152,128 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
+	}
+	if revision != nil && len(revisions[0]) == 0 {
+		return nil, nil, errors.Errorf("secret revision %d for %s not found", *revision, uri).
+			Add(secreterrors.SecretRevisionNotFound)
 	}
 
+	return secret, revisions[0], nil
+}
+
+func (st State) GetSecretsByLabels(ctx context.Context, labels domainsecret.Labels, revision *int) ([]*coresecrets.SecretMetadata,
```
Comment (wallyworld) [inline domain/secret/state/state.go]: Comment me

File: domain/secret/state/state.go [hunk 11]
```diff
@@ -1152,54 +1152,128 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
 
-	var revisionNotFoundErr error
-	if revision != nil {
-		revisionNotFoundErr = errors.Errorf(
-			"secret revision %d for %s not found", *revision, uri).Add(secreterrors.SecretRevisionNotFound)
+	if len(revisions) != 1 {
+		return nil, nil, errors.Errorf("programming error: expected 1 revision, got %d", len(revisions))
+	}
+	if revision != nil && len(revisions[0]) == 0 {
+		return nil, nil, errors.Errorf("secret revision %d for %s not found", *revision, uri).
```
Comment (wallyworld) [inline domain/secret/state/state.go:1191]: Is there a reason to drop the creation of the `revisionNotFoundErr`
We get a consistent error message for here and line 1177

File: domain/secret/state/state.go [hunk 12]
```diff
@@ -1152,54 +1152,128 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
+			if rev != nil {
+				filteredSecrets = append(filteredSecrets, secrets[i])
+				filteredRevisions = append(filteredRevisions, rev)
+			}
+		}
+		secrets, revisions = filteredSecrets, filteredRevisions
+	}
+	return secrets, revisions, nil
+}
+func (st State) ListAllSecrets(ctx context.Context) ([]*coresecrets.SecretMetadata, [][]*coresecrets.SecretRevisionMetadata, error) {
```
Comment (wallyworld) [inline domain/secret/state/state.go:1245]: Comment me

File: domain/secret/state/state.go [hunk 13]
```diff
@@ -1152,54 +1152,128 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
+		}
+		return nil
+	}); err != nil {
+		return nil, nil, errors.Capture(err)
+	}
+
+	return secrets, revisions, nil
+}
+
+func (st State) listSecretsRevisions(ctx context.Context, tx *sqlair.TX, secrets []*coresecrets.SecretMetadata,
```
Comment (wallyworld) [inline domain/secret/state/state.go:1272]: We could just pass in the list of secret URIs here. I guess doing it this way means we don't need to take a slice of secret metadata from the list secrets result and create another slice with just the URIs

File: domain/secret/state/state.go [hunk 14]
```diff
@@ -1389,11 +1459,68 @@ WHERE  sm.secret_id = $secretID.id`, secretID{}, secretInfo{})
...
-func (st State) listSecretsAnyOwner(
-	ctx context.Context, tx *sqlair.TX, uri *coresecrets.URI,
+func (st State) listAllSecrets(ctx context.Context, tx *sqlair.TX) ([]*coresecrets.SecretMetadata, error) {
+	return st.fetchSecrets(ctx, tx)
+}
+
+func (st State) getSecretBySecretID(
+	ctx context.Context, tx *sqlair.TX, uri coresecrets.URI,
+) (*coresecrets.SecretMetadata, error) {
+	// select by secret_id
```
Comment (wallyworld) [inline domain/secret/state/state.go]: Start comments with a capital letter and end with a "."

File: domain/secret/state/state.go [hunk 15]
```diff
@@ -1389,11 +1459,68 @@ WHERE  sm.secret_id = $secretID.id`, secretID{}, secretInfo{})
...
+			append(params, labelList(labels))
+	}
+	return st.fetchSecrets(ctx, tx, selectByLabels)
+}
 
+type queryModifier func(query string, types, params []any) (newQuery string, newTypes, newParams []any)
+
+func (st State) fetchSecrets(ctx context.Context,
+	tx *sqlair.TX,
+	updateQuery ...queryModifier,
```
Comment (wallyworld) [inline domain/secret/state/state.go]: This method could do with a comment - the initial instinct is to think `updateQuery` is a query which performs updates.

`queryModifier` above should probably be `queryModifierFunc`
(which is consistent with other places)

Could we call the param `queryModifierFuncs`

File: domain/secret/state/state.go [hunk 16]
```diff
@@ -1389,11 +1459,68 @@ WHERE  sm.secret_id = $secretID.id`, secretID{}, secretInfo{})
...
+	if len(secrets) == 0 {
+		return nil, errors.Errorf("secret %q not found", uri).Add(secreterrors.SecretNotFound)
+	}
+	if len(secrets) > 1 {
+		return nil, errors.Errorf("multiple secrets found for %q", uri)
+	}
+	return secrets[0], nil
+}
+
+func (st State) listSecretsBySecretLabels(
```
Comment (wallyworld) [inline domain/secret/state/state.go:1496]: Comment me

File: domain/secret/state/state.go [hunk 17]
```diff
@@ -1408,53 +1535,43 @@ SELECT sm.secret_id AS &secretInfo.secret_id,
...
-          JOIN   application
-          WHERE  application.uuid = so.application_uuid
-          UNION
-          SELECT $ownerKind.unit_owner_kind AS owner_kind, unit.name AS owner_id, label, secret_id
-          FROM   secret_unit_owner so
-          JOIN   unit
-          WHERE  unit.uuid = so.unit_uuid
-       ) so ON so.secret_id = sm.secret_id`
+FROM   secret_metadata AS sm
+JOIN secret_revision AS sr ON sm.secret_id = sr.secret_id
```
Comment (wallyworld) [inline domain/secret/state/state.go]: Fix indenting

File: domain/secret/state/state.go [hunk 18]
```diff
@@ -1408,53 +1535,43 @@ SELECT sm.secret_id AS &secretInfo.secret_id,
...
+		dbSecrets      secretInfos
+		dbSecretOwners []secretOwner
+	)
+
+	for _, update := range updateQuery {
+		// Apply modifier to the query
+		query, queryTypes, queryParams = update(query, queryTypes, queryParams)
 	}
+
+	// finish by a GROUP BY clause to make the MAX(sr.revision) work
```
Comment (wallyworld) [inline domain/secret/state/state.go]: As with other comment - start with capital, end with ".". Same for line 1558 etc

**Review by wallyworld — APPROVED** [review]
Thanks for fixing.

File: domain/secret/service/interface.go (hunk 7 above)
Comment (gfouillet) [reply domain/secret/service/interface.go]: Indeed, I had the false idea that most of our codebase didn't use ListThings but GetThings, but in reality there is only a `GetOperations` and the other are ListXXX.

Will fix, thanks to point it to me.

File: domain/secret/service/service.go (hunk 8 above)
Comment (gfouillet) [reply domain/secret/service/service.go:674]: It would break the logic. Added a comment to explain why this check is there and not above.

File: domain/secret/state/state.go (hunk 13 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1272]: Yes it is pure refactoring where in every code path we got a secret metadata. Since the method is unexposed, it is not relevant to make it more generic (though passing only the URI), we want it to be leaner over the codepath (so no copy of URI for just passing args)

File: domain/secret/state/state.go (hunk 11 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1191]: To me, the pattern:

```go
var revisionNotFoundError error // Oh, we may have a revision thus it may be not found 

if revision != nil { // Oh, we have a revision, so we *may* have a revision no found 
   revisionNotFoundError = errors.Errorf(/*...*/) // Since we know, let's init it !
}

// Do various stuff
err := somethingThatConcernRevision(ctx, /* args */, revision)
If err != nil { // Oh we have an error that may concern revision
   return revisionNotFoundError
}
```

Is very volubile for nothing (ok, maybe not nothing, very local consistency). 

I know I have a very talkative internal code reader, but noises when reading code is very error prone. 
I think there is no need to neither declare nor init a variable we *may* not use, so in this case, copy paste of the error message is better.

Moreover, I really wonder if the error handling is correct there. I choose to not change it because I am bug fixing and not refactoring, but to me, this method should return either a SecretNotFound (if the URI is not found) or a SecretRevisionNotFound (if no revisions are found, or even just an empty list), and it should be the service layer that handle the translation to SecretNotFound in any case.
The service layer has all information required to produce the right error message (with both URI and optional revision) and to decide what to do. I can do it as a follow-up in this PR are another if it make sense to you.

File: domain/secret/service/exportimport.go [hunk 19]
```diff
@@ -21,7 +21,7 @@ func (s *SecretService) GetSecretsForExport(ctx context.Context) (*SecretExport,
 	ctx, span := trace.Start(ctx, trace.NameFromFunc())
 	defer span.End()
 
-	secrets, secretRevisions, err := s.secretState.ListSecrets(ctx, nil, nil, secret.NilLabels)
+	secrets, secretRevisions, err := s.secretState.ListAllSecrets(ctx)
```
Comment (manadart) [inline domain/secret/service/exportimport.go:24]: I mentioned this some time ago. What is the difference between _Listing_ and _Getting_? If there is none, we should keep convention, because the differentiation implies that there _is_ a difference.

File: domain/secret/state/state.go [hunk 20]
```diff
@@ -1389,72 +1467,120 @@ WHERE  sm.secret_id = $secretID.id`, secretID{}, secretInfo{})
...
+
+func (st State) getSecretBySecretID(
+	ctx context.Context, tx *sqlair.TX, uri coresecrets.URI,
+) (*coresecrets.SecretMetadata, error) {
+	selectBySecretID := func(query string, types, params []any) (newQuery string, newTypes, newParams []any) {
+		return query + "\nWHERE sm.secret_id = $secretID.id",
+			append(types, secretID{}),
+			append(params, secretID{ID: uri.ID})
+	}
+	secrets, err := st.fetchSecrets(ctx, tx, selectBySecretID)
```
Comment (hpidcock) [inline domain/secret/state/state.go:1480]: We need to stop doing this. The sooner we start the better.

File: domain/secret/state/state.go [hunk 21]
```diff
@@ -1389,72 +1467,120 @@ WHERE  sm.secret_id = $secretID.id`, secretID{}, secretInfo{})
...
+
+type queryModifierFunc func(query string, types, params []any) (newQuery string, newTypes, newParams []any)
 
+func (st State) fetchSecrets(ctx context.Context,
+	tx *sqlair.TX,
+	queryModifierFuncs ...queryModifierFunc,
+) ([]*coresecrets.SecretMetadata, error) {
+	// TODO(gfouillet): we should introduce a view for this one. It should be done in
+	//    a specific PR since it is not trivial (we need to probably introduce an enum
+	//    table for owner type, and refine the associated code in state)
```
Comment (hpidcock) [inline domain/secret/state/state.go:1516]: Why are we making this worse? Copy the SQL statement.

File: domain/secret/state/state.go [hunk 22]
```diff
@@ -1152,54 +1152,136 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
+	if err := db.Txn(ctx, func(ctx context.Context, tx *sqlair.TX) error {
+		var err error
+		secret, err = st.getSecretBySecretID(ctx, tx, uri)
+		if err != nil {
+			// If a specific revision was requested and the secret doesn't exist,
+			// surface a SecretRevisionNotFound error instead of SecretNotFound.
+			if revision != nil && errors.Is(err, secreterrors.SecretNotFound) {
+				return errors.Errorf("secret revision %d for %s not found", *revision, uri).
+					Add(secreterrors.SecretRevisionNotFound)
+			}
```
Comment (hpidcock) [inline domain/secret/state/state.go:1175]: This is business logic.

File: domain/secret/state/state.go [hunk 23]
```diff
@@ -1152,54 +1152,136 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
-// If all terms are empty, then all secrets are returned.
-func (st State) ListSecrets(ctx context.Context, uri *coresecrets.URI,
-	revision *int,
-	// TODO(secrets) - use all filter terms
-	labels domainsecret.Labels,
-) ([]*coresecrets.SecretMetadata, [][]*coresecrets.SecretRevisionMetadata, error) {
+// GetSecretByURI retrieves metadata and revisions of a secret by its URI and
+// optional revision.
+// Returns the secret metadata, a list of its revisions, or an error if the operation fails.
+func (st State) GetSecretByURI(ctx context.Context, uri coresecrets.URI, revision *int) (*coresecrets.SecretMetadata,
```
Comment (hpidcock) [inline domain/secret/state/state.go:1156]: This is doing way too much.

These are the methods we should be using:
```go
GetSecretMetadataByURI(ctx context.Context, uri coresecrets.URI) (coresecrets.SecretMetadata, error)
GetAllSecretRevisionMetadataByURI(ctx context.Context, uri coresecrets.URI) ([]coresecrets.SecretRevisionMetadata, error)
GetSecretRevisionMetadata(ctx context.Context, uri coresecrets.URI, revision int) (coresecrets.SecretRevisionMetadata, error)
```

or the absurd:
```go
GetSecretMetadataWithAllSecretRevisionMetadataByURI(ctx context.Context, uri coresecrets.URI) (coresecrets.SecretMetadata, []coresecrets.SecretRevisionMetadata, error)
GetSecretMetadataByURIWithSecretRevisionMetadataByNumber(ctx context.Context, uri coresecrets.URI, revision int) (coresecrets.SecretRevisionMetadata, error)
```

File: domain/secret/state/state.go [hunk 24]
```diff
@@ -1152,54 +1152,136 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
+		return nil, nil, errors.Errorf("secret revision %d for %s not found", *revision, uri).
+			Add(secreterrors.SecretRevisionNotFound)
 	}
 
+	return secret, revisions[0], nil
+}
+
+// ListSecretsByLabels retrieves secrets and their revisions filtered by
+// specified labels and an optional revision.
+func (st State) ListSecretsByLabels(ctx context.Context, labels domainsecret.Labels, revision *int) ([]*coresecrets.SecretMetadata,
```
Comment (hpidcock) [inline domain/secret/state/state.go:1200]: Same as above, we are doing way too much here, decompose the problem into getting the secret metadata and then getting the revision metadata (singular and all).

File: domain/secret/state/state.go [hunk 25]
```diff
@@ -1152,54 +1152,136 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
+			}
+		}
+		secrets, revisions = filteredSecrets, filteredRevisions
+	}
+	return secrets, revisions, nil
+}
+
+// ListAllSecrets retrieves a list of all secrets and their associated revisions
+// from the database in a single operation.
+func (st State) ListAllSecrets(ctx context.Context) ([]*coresecrets.SecretMetadata, [][]*coresecrets.SecretRevisionMetadata, error) {
```
Comment (hpidcock) [inline domain/secret/state/state.go:1245]: This is fine, should just be called something like `GetAllSecretsWithRevisions`.

File: domain/secret/state/state.go [hunk 26]
```diff
@@ -1152,54 +1152,136 @@ WHERE  sao.application_uuid IN ($ApplicationOwners[:]) OR suo.unit_uuid IN ($Uni
...
+	if err := db.Txn(ctx, func(ctx context.Context, tx *sqlair.TX) error {
+		var err error
+		secrets, err = st.listAllSecrets(ctx, tx)
+		if err != nil {
+			return errors.Errorf("querying secrets: %w", err)
+		}
+		revisions, err = st.listSecretsRevisions(ctx, tx, secrets, nil)
+		if err != nil {
+			return errors.Errorf("querying secret revisions: %w", err)
+		}
```
Comment (hpidcock) [inline domain/secret/state/state.go:1263]: Implement a bespoke `getAllRevisions` state method that does not take a list of secrets.

**Review by hpidcock — DISMISSED** [review]
I think this needs work, we need to move secrets in a better direction. Not asking to do it all here.

File: domain/secret/service/exportimport.go (hunk 19 above)
Comment (gfouillet) [reply domain/secret/service/exportimport.go:24]: Actual code use mostly Listing (with one exception) when the interface method return a slice.

So it is not a semantic difference, just an existing pattern: as the code is written enforcing consistency implies "singular => get", "plural => list".

I have a personal preference to use get everywhere (because no semantic differences), but actual methods use list for plural.

File: domain/secret/state/state.go (hunk 20 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1480]: Yes. This should be done as follow up, with a view. 

This is a bug fix, so I won't engage in a large refactoring unless it is required.

This pattern was already there (conditionally append stuff to a very huge query), but it is too early to cut it, as mentioned in the TODO i added to cover this point.

File: domain/secret/state/state.go (hunk 21 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1516]: I disagree with that assertion. I will be far easier to introduce a SQL view and remove fetch secret as a whole and patch the callers than make surgery over each copy pasted version of the big SQL statement... Especially if things get wild and late and for some reason the DDL shift before we can do the change (even if it is not something I want)

File: domain/secret/state/state.go (hunk 22 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1175]: I agree, as expressed there: https://github.com/juju/juju/pull/21327#discussion_r2576229867

Can do, even if it is not direct part of the bug fix.

File: domain/secret/state/state.go (hunk 23 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1156]: This is a bug fix, so we shouldn't trade transactional behavior (get secret+revision) against non transactional (get secrets then revision) in this PR, since it is unrelated to the bug.

File: domain/secret/state/state.go (hunk 25 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1245]: This oppose directly a comment from @wallyworld about List vs Get.

File: domain/secret/state/state.go (hunk 26 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1263]: out of scope.

**Comment by gfouillet** [comment]
> I think this needs work, we need to move secrets in a better direction. Not asking to do it all here.

Thank you for your feedback, yet I don't see in your comments what justify a blocking change request, even though you show good direction for a follow up PR.

Please let me know what is mandatory from your point of view, to help me assess tomorrow if I should discard your review.

File: domain/secret/state/state.go (hunk 21 above)
Comment (hpidcock) [reply domain/secret/state/state.go:1516]: It is worse, you are now generating SQL statements. Copy the SQL statement, make it singular for your new use case to get a single secret.

File: domain/secret/state/state.go (hunk 23 above)
Comment (hpidcock) [reply domain/secret/state/state.go:1156]: Then copy it, make two state methods. One that deals with a singular secret and a revision, the other that deals with a singular secret and all its revisions.

File: domain/secret/state/state.go (hunk 26 above)
Comment (hpidcock) [reply domain/secret/state/state.go:1263]: 100% in scope, this has horrible perforce implications without doing it.

**Comment by hpidcock** [comment]
> > I think this needs work, we need to move secrets in a better direction. Not asking to do it all here.
> 
> Thank you for your feedback, yet I don't see in your comments what justify a blocking change request, even though you show good direction for a follow up PR.
> 
> Please let me know what is mandatory from your point of view, to help me assess tomorrow if I should discard your review.

All of it is required.

File: domain/secret/state/state.go (hunk 25 above)
Comment (SimonRichardson) [reply domain/secret/state/state.go:1245]: As @manadart and @hpidcock have said, this should stick to conventions - rename to `GetAllSecretsWithRevisions`

**Comment by SimonRichardson** [comment]
@gfouillet I think concrete next steps on how we're going to remove a lot of concerns that @hpidcock has voiced is going to be required. I understand that you're trying to fix just one bug, but it's clear that there are deficiencies with in this domain, esp. around over generalization of existing methods.

File: domain/secret/state/state.go (hunk 25 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1245]: I don't want to push it but, this naming is not some hallucination of mine. The actual codebase is consistently using List<plural>:

- Cloud (`domain/cloud/service`): `Service.ListAll(ctx)` returns all clouds; `State.ListClouds(ctx)`; `Service.Cloud(ctx, name)`.
- Model (`domain/model/service`): `ListModelUUIDs`, `ListModelUUIDsForUser`, `ListAllModels`, `ListModelsForUser`.
- Application (`domain/application/service`): `ListCharmLocators`, `ListCharmLocatorsByNames`.
- Agent binary (`domain/agentbinary/service`): `ListAgentBinaries`, `GetAgentBinary` (singular), plus `GetExternalAgentBinary`.
- Resource (`domain/resource/service`): `ListResources(...)`.
- Secret backend (`domain/secretbackend/service`): `ListBackendIDs`.
- Secrets (`domain/secret/service`): Current state-level methods include `ListSecrets`, `ListCharmSecrets`, `ListGrantedSecretsForBackend`, `ListCharmSecretsToDrain`, `ListUserSecretsToDrain`.
- Key manager (`domain/keymanager/service`):  `ListPublicKeysForUser`.
- Object store (`domain/objectstore/service`): `ListMetadata`.

Actually the only exception is:

- Operation (`domain/operation/service`) `GetOperations(ctx, params operation.QueryArgs) (operation.QueryResult, error)` returns a multi-item query result; `GetOperationByID` for singular.

However, since there is a consensus on the fact that the actual norm is wrong, I will do the change here. Maybe the refactoring is a good task for copilot (boring and easy)

File: domain/secret/state/state.go (hunk 21 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1516]: > It is worse, **you are now** generating SQL statements. Copy the SQL statement, make it singular for your new use case to get a single secret.

It was the case *before*, I just made it *obvious* and add a **todo** at one place to get ride of it (through a view) in a follow up PR.

File: domain/secret/state/state.go (hunk 23 above)
Comment (gfouillet) [reply domain/secret/state/state.go:1156]: That make sense.

**Comment by gfouillet** [comment]
@hpidcock @manadart @SimonRichardson 

As discussed in EMEA team, I take the responsibility of moving forward on the technical debt on secret domain.

I still don't think that this PR is the right place to fix every concern from Harry, because the implications are larger than what should be addressed in a bug fix PR.

The concerns are legitimate, here it is a plan to address them:

---- 

Main concerns:
* Get<Plural> or List<Plural>
* crafted SQL
* Jack-of-all-trades function (fetch a specific revision or all of them)
* Business logic around SecretAlreadyExist buried in state

How to get Ride of those concern
* Get<Plural> or List<Plural> should be addressed in a specific PR (or train of PR), over the whole domain, since it is a common pattern (see https://github.com/juju/juju/pull/21327#discussion_r2581443473)
* Crafted SQL and Jack-of-all-trades function can be addressed at once, as well of the SecretAlreadyExist logic through:
	* Introducing a view for secret metadata
	* Introducing a view for secret revision
	* Introduce specific function with or without revision in state
		* `GetSecretByURIWithAllRevision(ctx, uri)` return a secret with all its revision
		* `GetSecretByURI(ctx, uri, revision)` return a secret with a specific revision
		* `ListSecretsByLabelsWithAllRevision(ctx, labels)` return all secrets matching any label with all their revisions
		* `ListSecretsByLabels(ctx, labels, revision)` return all secrets matching any label and with a specific revision
		* `ListAllSecrets(ctx)` need to be refactored and simplified with the views, fetching all secrets and all revision in two query, then reconciliate both lists.

This refactoring is better to be done in another PR, since introducing the view will require various update (for instance around the [Owner enum](https://github.com/juju/juju/blob/5485660d915788b712bda7cdd4017789f9fe1d9c/domain/secret/types.go#L28-L33) that should be moved in the DDL and used in the view), and can be used as an opportunity to fix some very ugly pattern (like this return signature : `[]*secrets.SecretMetadata, [][]*secrets.SecretRevisionMetadata` which is totally wrong, with overuse of pointer and expectation that both slice will have the same size, or the general use of non-primary type in state layer interface.)

Refactor it without introducing the view would cause duplication of not-so-trivial select (like this [one](https://github.com/juju/juju/blob/1b670df434dc8310023a01ea952dab4299c318d6/domain/secret/state/state.go#L1517-L1551) ), which I is wrong, even for the sake of "not crafting statement" policy. I can go with the fact that we still craft statement until we introduce a view for those query.

--- 

Unless there is a strong reason to not merge this PR, I will dismiss Harry review tomorrow and merge, letting those changes to a follow up PR.

However, feedback on above plan are welcomed.

File: domain/secret/service/exportimport.go (hunk 19 above)
Comment (manadart) [reply domain/secret/service/exportimport.go:24]: GetLatestRevisions, GetSecretGrants, GetRelationEndpoints, GetOwnedSecretIDs, GetApplicationUUIDsForNames, GetRevisionIDsForObsolete, GetUnitUUIDsForNames, GetObsoleteUserSecretRevisionsReadyToPrune.

Comment (gfouillet) [reply domain/secret/service/exportimport.go:24]: Oh sorry, indeed: in secrets both wording exists (ListCharmSecrets, ListCharmSecretsToDrain, ListGrantedSecretsForBackend, ListSecrets, ListUserSecretsToDrain). 

We should definitely normalize it, this is a mess. Will do in a follow up PR, as planned.
