### PR TITLE
fix(offer): use charm reference_name instead of metadata name in v_offer_detail view

### LINKED ISSUE #21765: status shows incorrect charm name
### Description

When deploying and offerring juju-qa-dummy-source, status shows the application name and not the charm name.

In 3.6:

```sh
Model  Controller  Cloud/Region       Version  Timestamp
dud    dst         localhost/default  3.6.14   13:05:37Z

App           Version  Status       Scale  Charm                 Channel        Rev  Exposed  Message
dummy-source           maintenance      1  juju-qa-dummy-source  latest/stable    6  no       Started

Unit             Workload     Agent  Machine  Public address  Ports  Message
dummy-source/0*  maintenance  idle   0        10.232.51.237          Started

Machine  State    Address        Inst id        Base          AZ          Message
0        started  10.232.51.237  juju-59af4e-0  ubuntu@20.04  simon-work  Running

Offer         Application   Charm                 Rev  Connected  Endpoint  Interface    Role
dummy-source  dummy-source  juju-qa-dummy-source  6    0/0        sink      dummy-token  requirer
```

In 4.0-HEAD

```sh
Model  Controller  Cloud/Region  Version  Timestamp
offer  src         lxd/default   4.0.2.1  13:06:03Z

App           Version  Status       Scale  Charm                 Channel        Rev  Exposed  Message
dummy-source           maintenance      1  juju-qa-dummy-source  latest/stable    6  no       Started

Unit             Workload     Agent  Machine  Public address  Ports  Message
dummy-source/0*  maintenance  idle   0        10.232.51.99           Started

Machine  State    Address       Inst id        Base          AZ          Message
0        started  10.232.51.99  juju-b5f24d-0  ubuntu@20.04  simon-work  Running

Offer         Application   Charm         Rev  Connected  Endpoint  Interface    Role
dummy-source  dummy-source  dummy-source  6    0/0        sink      dummy-token  requirer
```

### Juju version

4.0-HEAD

### Cloud

_No response_

### Expected behaviour

Should show `juju-qa-dummy-source` not `dummy-source`.

### Reproduce / Test

```sh
$ juju bootstrap lxd src
$ juju add-model m && juju deploy juju-qa-dummy-source && juju offer dummy-source:sink
$ juju status
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
The v_offer_detail SQL view was selecting charm_metadata.name (the internal metadata name from metadata.yaml) instead of charm.reference_name (the canonical charm name). 

This caused `juju status` to show the application name in the Offer "Charm" column rather than the actual charm name (e.g. "dummy-source" instead of "juju-qa-dummy-source").

Fix by patching the (already patched) view.

__Note: There already was a patch on that exact same view, introduced in https://github.com/juju/juju/pull/21542. But since that patch corresponds to a relased version (4.0.1) we cannot reuse it.__

## QA steps

QA steps exactly as in the GH issue:
```
$ juju bootstrap lxd src
$ juju add-model m && juju deploy juju-qa-dummy-source && juju offer dummy-source:sink
$ juju status
```
Correct status:
```
Model  Controller  Cloud/Region         Version  Timestamp
m      c           localhost/localhost  4.0.2.1  13:19:43+01:00

App           Version  Status   Scale  Charm                 Channel        Rev  Exposed  Message
dummy-source           waiting    0/1  juju-qa-dummy-source  latest/stable    6  no       waiting for machine

Unit            Workload  Agent       Machine  Public address  Ports  Message
dummy-source/0  waiting   allocating  0                               waiting for machine

Machine  State    Address  Inst id  Base          AZ  Message
0        pending           pending  ubuntu@20.04

Offer         Application   Charm                 Rev  Connected  Endpoint  Interface    Role
dummy-source  dummy-source  juju-qa-dummy-source  6    0/0        sink      dummy-token  requirer
```

## Links

**Issue:** Fixes #21765.

**Jira card:** [JUJU-9190](https://warthogs.atlassian.net/browse/JUJU-9190)

[JUJU-9190]: https://warthogs.atlassian.net/browse/JUJU-9190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/crossmodelrelation/state/model/offer_test.go [hunk 1]
```diff
@@ -579,10 +582,13 @@ func (s *modelOfferSuite) setupForGetOfferDetails(c *tc.C) []*crossmodelrelation
 	}
 }
 
-// setupForGetOfferDetails
+// setupOfferWithInterface
```
Comment (SimonRichardson) [inline domain/crossmodelrelation/state/model/offer_test.go]: Just delete this comment.

File: domain/schema/model/sql/0032-offer.sql [hunk 2]
```diff
@@ -36,7 +36,7 @@ SELECT
     o.name AS offer_name,
     a.name AS application_name,
     cm.description AS application_description,
-    cm.name AS charm_name,
+    c.reference_name AS charm_name,
```
Comment (jack-w-shaw) [inline domain/schema/model/sql/0032-offer.sql]: No, this file can't change

**Review by jack-w-shaw — CHANGES_REQUESTED** [review]

File: domain/crossmodelrelation/state/model/offer_test.go (hunk 1 above)
Comment (jack-w-shaw) [inline domain/crossmodelrelation/state/model/offer_test.go]: Either write a doc string or delete this imo

**Comment by jack-w-shaw** [comment]
Other than the ddl change, LGTM

Remember to do a merge forward and resolve the PATCH once this is merged!

File: domain/schema/model/sql/0032-offer.sql (hunk 2 above)
Comment (nvinuesa) [reply domain/schema/model/sql/0032-offer.sql]: Sure, I had forgotten to revert this change (from when I was still debugging). Done now.

File: domain/crossmodelrelation/state/model/offer_test.go (hunk 1 above)
Comment (nvinuesa) [reply domain/crossmodelrelation/state/model/offer_test.go]: I just removed this one and another one like this in the file, not very useful.

**Review by jack-w-shaw — APPROVED** [review]

File: domain/schema/model/sql/0048-offer.PATCH.sql [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+    cm.description AS application_description,
+    c.reference_name AS charm_name,
+    c.revision AS charm_revision,
+    cs.name AS charm_source,
+    c.architecture_id AS charm_architecture,
+    cr.name AS endpoint_name,
+    crr.name AS endpoint_role,
+    cr.interface AS endpoint_interface,
+    cr.capacity AS endpoint_limit,
+    (SELECT COUNT(*) FROM conn AS c WHERE o.uuid = c.offer_uuid) AS total_connections,
```
Comment (manadart) [inline domain/schema/model/sql/0048-offer.PATCH.sql]: Pre-aggregate these. Don't repeat the count per row:
```sql
CREATE VIEW v_offer_detail AS
  WITH total_conn AS (
      SELECT
          offer_uuid,
          COUNT(*) AS total_connections
      FROM offer_connection
      GROUP BY offer_uuid
  ),
  active_conn AS (
      SELECT
          oc.offer_uuid,
          COUNT(*) AS total_active_connections
      FROM offer_connection AS oc
      JOIN relation_status AS rs
        ON rs.relation_uuid = oc.remote_relation_uuid
       AND rs.relation_status_type_id = 1
      GROUP BY oc.offer_uuid
  )
  SELECT
      o.uuid AS offer_uuid,
      o.name AS offer_name,
      a.name AS application_name,
      cm.description AS application_description,
      c.reference_name AS charm_name,
      c.revision AS charm_revision,
      cs.name AS charm_source,
      c.architecture_id AS charm_architecture,
      cr.name AS endpoint_name,
      crr.name AS endpoint_role,
      cr.interface AS endpoint_interface,
      cr.capacity AS endpoint_limit,
      COALESCE(tc.total_connections, 0) AS total_connections,
      COALESCE(ac.total_active_connections, 0) AS total_active_connections
  FROM offer AS o
  JOIN offer_endpoint AS oe ON o.uuid = oe.offer_uuid
  JOIN application_endpoint AS ae ON oe.endpoint_uuid = ae.uuid
  JOIN application AS a ON ae.application_uuid = a.uuid
  JOIN charm_relation AS cr ON ae.charm_relation_uuid = cr.uuid
  JOIN charm_relation_role AS crr ON cr.role_id = crr.id
  JOIN charm AS c ON a.charm_uuid = c.uuid
  JOIN charm_source AS cs ON c.source_id = cs.id
  JOIN charm_metadata AS cm ON c.uuid = cm.charm_uuid
  LEFT JOIN total_conn AS tc ON tc.offer_uuid = o.uuid
  LEFT JOIN active_conn AS ac ON ac.offer_uuid = o.uuid;
```

You are also missing all the indexes that this needs to be fast.

These on `offer_connection`:
```sql
  CREATE INDEX idx_offer_connection_offer_uuid
      ON offer_connection (offer_uuid);

  CREATE INDEX idx_offer_connection_remote_relation_offer
      ON offer_connection (remote_relation_uuid, offer_uuid);
```

And this one on `relation_status`:
```sql
  CREATE INDEX idx_relation_status_type_relation
      ON relation_status (relation_status_type_id, relation_uuid);
```

Comment (nvinuesa) [reply domain/schema/model/sql/0048-offer.PATCH.sql]: Yes, way better. Done and created the indexes as well. See 16e2fdaf6fc75d2f9e80a3980d77225d17d0d83b

**Review by manadart — APPROVED** [review]
Thanks; looks good.
