### PR TITLE
fix: MAAS storage provisioning

### LINKED ISSUE #21375: [juju4] failed to acquire node: No available machine
### Description

`juju deploy --force --channel 16/edge  -n 3 postgresql`

```
$ juju status
Model  Controller       Cloud/Region        Version  Timestamp
test   juju-controller  maas_cloud/default  4.0.0    18:39:09Z

App         Version  Status   Scale  Charm       Channel  Rev  Exposed  Message
postgresql           waiting    0/3  postgresql  16/edge  969  no       waiting for machine

Unit          Workload  Agent       Machine  Public address  Ports  Message
postgresql/0  waiting   allocating  0                               waiting for machine
postgresql/1  waiting   allocating  1                               waiting for machine
postgresql/2  waiting   allocating  2                               waiting for machine

Machine  State  Address  Inst id  Base          AZ  Message
0        error           pending  ubuntu@24.04      No available machine matches constraints: [('agent_name', ['fbad9de2-7d76-4408-898e-9bb2b903da53']), ('arch', ['amd64...
1        error           pending  ubuntu@24.04      No available machine matches constraints: [('agent_name', ['fbad9de2-7d76-4408-898e-9bb2b903da53']), ('arch', ['amd64...
2        error           pending  ubuntu@24.04      No available machine matches constraints: [('agent_name', ['fbad9de2-7d76-4408-898e-9bb2b903da53']), ('arch', ['amd64...
```

```
    machine-status: 
      current: allocating
      message: 'failed to start machine 1 (failed to acquire node: No available machine
        matches constraints: [(''agent_name'', [''fbad9de2-7d76-4408-898e-9bb2b903da53'']),
        (''arch'', [''amd64'']), (''storage'', [''root:0,4:1,5:1,6:1,7:1'']), (''zone'',
        [''default''])] (resolved to "arch=amd64/generic storage=root:0,4:1,5:1,6:1,7:1
        zone=default")), retrying in 10s (3 more attempts)'
      since: 01 Dec 2025 18:29:33Z
      life: alive
```

Exactly the same works fine on juju 3

### Juju version

4.0

### Cloud

MAAS

### Expected behaviour

three machines are deployed

### Reproduce / Test

sudo snap install juju --channel=4.0/stable

cat <<EOF > mycloud.yaml
clouds:
  maas_cloud:
    type: maas
    auth-types: [oauth1]
    endpoint: http://172.16.1.2:5240/MAAS
    regions:
      default:
        endpoint: http://172.16.1.2:5240/MAAS
EOF

cat <<EOF > credentials.yaml
credentials:
  maas_cloud:
    maas_cloud_credentials:
      auth-type: oauth1
      maas-oauth: $(cat ~/api.key)
EOF

cat <<EOF > model_defaults.yaml
cloudinit-userdata: "write_files:\n  - content: |\n      kernel.keys.maxkeys = 2000\n\
  \    owner: \"root:root\"\n    path: /etc/sysctl.d/10-maxkeys.conf\n    permissions:\
  \ \"0644\"\npostruncmd:\n  - sysctl --system\n"
juju-no-proxy: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,127.0.0.1,localhost
logging-config: <root>=DEBUG
EOF

juju add-cloud maas_cloud mycloud.yaml --client
juju add-credential maas_cloud -f credentials.yaml --client
juju bootstrap --bootstrap-constraints "arch=amd64 tags=juju-controller" --config caas-image-repo=ghcr.io/juju --config bootstrap-timeout=1800 --model-default model_defaults.yaml maas_cloud juju-controller
juju add-model test
juju deploy --force --channel 16/edge  -n 3 postgresql

### Notes & References

@anvial knows context and why --force is used
Anyhow, exactly that works fine in 3.6.12

### PR DESCRIPTION
**Pull request by tlm**
This PR is about fixing the issues identified in #21375 where Juju deployments to a MAAS environ were failing with an error message that a machine was not able to be acquired matching the constraints that had been provided by the Juju machine provisioner. 

# Background
How this bug came to be was due to two changes specifically made to 4.0 in PR #20445 and #20463 where I removed the concept from the controller that storage in a model can be provisioned by either a provider or a storage pool.

The change was done for good reason as prior to this whenever a user communicated with the controller that they would like storage provisioned by `x` a check would be done to try and infer if the user meant the storage pool `x` or the provider `x`. If both existed in the model by the same name then the one that got chosen was not idempotent due to this check being performed in many places. On top of this provisioning storage with provider `y` today may result in bugs further down the line as upgrades are performed. Particularly when having to reconcile storage in a provider. The logic the provider has today may not be the same in n versions time. Storage pools represent a snap shot of intent and a reference in time of how storage comes into existent.

To fix this each of the environs implement a storage pool registry where they convey the storage providers that they support. Each storage provider is then able to offer up a set of default storage pools to the model that are using well know UUIDs. A storage registry is then also able to recommend a storage pool to use for provisioning a class of storage in the model (`filesystems` & `blockdevices`). These recommendations aim to support figuring out what storage pool to use when the user has provided no preferences.

The other reason for performing the above change is now model migration is able to move the model's complete storage configuration to a new controller every time instead of possibly relying on a difference of implementation in the new controller. This makes a model more deterministic as it is migrated over a life time.

# Bug Explanation
As identified by @manadart & @nvinuesa when deploying a charm to a model that is using the MAAS environ the charm was failing to deploy as all of the storage for the charm was trying to be provisioned by the MAAS storage provisioner. The MAAS storage provisioner does not support provisioning of storage for charms and can only be used as of today for provisioning root disks for new machines in the model.

This arose because of the change in implementation where the MAAS environ's storage registry was recommending the MAAS storage pool to be used for filesystem and block devices. When it came to provisioning new machines for the units of a deployment the MAAS environ was also trying to provision the storage of the unit along with the root disk on the new machine. MAAS was subsequently failing as it couldn't honour the storage requirements requested.

In versions prior to Juju 4.0 this situation was resolved by the unit's storage being provisioned against either the `rootfs` provider or the `loop` provider depending on the kind of storage requested. Both of these storage provisioners operate on the machine itself once it has been started to provision their respective storage.

The bug came about due to a sweeping change to the storage registry interface across all providers. The interface change was done without considering each of the storage providers in the environ and if they can always be used for provisioning unit/charm storage.

# Fix
The fix for this bug is quite simple and requires the MAAS environ storage registry to stop recommending the MAAS storage provider for any kind of storage kind. This way it will never be used as the default storage pool when fulfilling storage on behalf of a unit.

We will still make and use a default MAAS storage pool in a model when MAAS is the provider. This is because machine constraints support creating the root disk on the provider. On top of this it is still valid to have a MAAS storage pool via a custom name defined in the model. The reason a user might want to do this is to have a set of custom tags applied to root disk volumes provisioned in MAAS for each machine. This is done by setting the `tags` attribute on a MAAS storage pool.

To bolster this fix with some more rigour I have made the `Supports` func on the MAAS storage provider always return false for any storage kind now. When evaluating root disk constraints of a new machine we currently don't consult the storage provider to ask if it can be used to provision a given kind of storage. We probably should have some check around this and possibly a new storage kind for root disks long term but until we do it is safest for the storage provider to always return false when asked if it supports a storage kind. This determination is done to support deployment of applications in a model. Without this change it would be theoretically possible for a user to deploy application `foo` using storage pool `MAAS`. As prior to this change the storage provider would indicate that it supported block devices. This would result in a deployment that could never be realised as the provider is incapable of actually provisioning the storage.

By not supporting any storage kind it should mean that if a user does deploy an application using a MAAS storage pool the deployment code will fail early and reject the deployment instead of letting it get into a committed state that is unrecoverable.

# Other Fixes
I found two other bugs/miss implementations in the MAAS provider while doing this fix that I took the time to resolve as part of this fix as they are all tightly linked.

## Bug 1 Tags
The MAAS storage provider supports a `tags` attribute to define a set of tags that get applied to a root disk when it is provisioned. The schema for this supports either a set of tags via comma separated string or via a slice of string values. Tags parsed by the provider are trimmed of leading and trailing white space and are considered invalid if the tag contains white space within the bounds of the tag. The following problems existed:

- The tags validator was considering the type of the slice value as `[]string` where the schema package will always provided the coerced values as `[]any`. It means that we could never support tags defined via a slice.
- Tags that were defined by the slice mechanism (assuming they worked) were never applied to the same validation logic that string tags were. This meant it was valid to supply an invalid tag via the slice mechanism which contained white space inside of the tag bounds. No white space stripping was being performed as well. Tags of all shapes and sized are now parsed with the same modification and validation logic.

## Bug 2 Provisioning Storage For Any Provider
This bug will still exist in 3.6 but would be almost impossible to see in reality at present. When the provisioner worker asks the environ to start a new instance it supplies the environ with the set of volumes in the model that should be provisioned by the environ as part of starting a new instance. These volumes are supplied if they are not provisioned already and have an attachment on to the machine. The volume must also be provisioned from the environ in the model and not on the machine itself.

It is possible that this set of volumes can have different storage providers requiring provisioning from a provider that is not the MAAS storage provider. The code that existed assumed it was always singular, with the modeling we have it is possible to have many volumes on different providers. It just can't be achieved today because of composition.

The fix was to have the MAAS start instance func only attempt to provision volumes that are using the MAAS storage provider. In reality this cannot be anything besides the root disk of the machine. Any other volumes will now be ignored by the environ and left up to the storage provisioner.

# Testing
I have added regression testing for each of the issues above with explanation as to why they exist and what they are tracking long term should this ever be accidentality broken in the future.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps
I don't have access to a MAAS cluster at the moment and will setup a virtual one if @manadart and @nvinuesa cannot help with running the QA steps.

## QA 1
Assert the initial bug is fixed.

1. Bootstrap a new controller to a MAAS cloud and create a new test model.
2. Deploy postgres `juju deploy --force --channel 16/edge  -n 3 postgresql` and confirm that each unit of the application comes up happy. We don't want to see a bad machine status when running `juju status`.
3. Confirm in the DB that the charm storage was provisioned with the `rootfs` provider.
```
juju ssh -m controller 0
juju_db_repl
.switch model-test
select * from storage_instance;
select * from storage_pool;
```

If this test succeeds then the bug has been fixed.

## QA 2
Confirm that the MAAS storage pool cannot be used for charm storage.

1. Bootstrap a new controller to a MAAS cloud and create a new test model.
2. Deploy postgres using the `maas` pool for `pgdata` `juju deploy --force --channel 16/edge --storage=pgdata=maas`

The hope here is that the deployment fails with an error message. The error message might be a bit terse as the application facade isn't handling the full scope of domain errors at the moment.

## QA 3
Confirm creating a MAAS storage pool with tags. This will required PR #21449 to be rebased on to.

1. `juju create-storage-pool test maas tags=tag1,tag2`

## QA 4
Confirm creating a MAAS storage pool with bad tags.

1. `juju create-storage-pool test maas "tags=tag1,has space, tag2"`

## Documentation changes

N/A

## Links

**Issue:** Fixes #21375 

**Jira card:** [JUJU-8897](https://warthogs.atlassian.net/browse/JUJU-8897)

[JUJU-8897]: https://warthogs.atlassian.net/browse/JUJU-8897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: internal/provider/maas/maas_environ_whitebox_test.go [hunk 1]
```diff
@@ -599,6 +601,71 @@ func (suite *maasEnvironSuite) TestAcquireNodeStorage(c *tc.C) {
...
+					Label: "root",
+					Size:  0,
+				},
+				{
+					Label: "1",
+					Size:  1,
+				},
+			})
+		},
+		allocateMachine: newFakeMachine("Bruce Sterling", arch.HostArch(), ""),
```
Comment (manadart) [inline internal/provider/maas/maas_environ_whitebox_test.go:624]: Schismatrix is an old favourite.

File: internal/provider/maas/maasstorageprovider_test.go [hunk 2]
```diff
@@ -0,0 +1,362 @@
...
+
+	"github.com/juju/tc"
+
+	coreerrors "github.com/juju/juju/core/errors"
+	internalstorage "github.com/juju/juju/internal/storage"
+)
+
+// maasStorageProviderSuite provides a suite of tests for asserting the
+// contracts and behaviour of the [maasStorageProvider].
+type maasStorageProviderSuite struct{}
```
Comment (manadart) [inline internal/provider/maas/maasstorageprovider_test.go:17]: Thanks for this coverage increase.

**Review by manadart — APPROVED** [review]
Thanks for sorting this.

File: internal/provider/maas/volumes.go [hunk 3]
```diff
@@ -34,35 +43,56 @@ const (
...
+			tagsAttribute: schema.OneOf(
+				schema.List(schema.String()),
+				schema.String(),
+			),
+		},
+		schema.Defaults{
+			tagsAttribute: schema.Omit,
+		},
+	)
+}
```
Comment (SimonRichardson) [inline internal/provider/maas/volumes.go:60]: nit: this could just be a `var providerConfigChecker = schema.FieldMap...`

There isn't a reason to create it over and over again.

File: internal/provider/maas/volumes.go [hunk 4]
```diff
@@ -72,105 +102,190 @@ func (*maasEnviron) StorageProvider(t storage.ProviderType) (storage.Provider, e
...
+//
+// [maasStorageProvider] always returns false for all [storage.StorageKind]
+// values. This is because the provider can only provision root disks for newly
+// created machines in MAAS.
+//
+// This current implementation should be considered a quirk of the storage
+// provider interface as it only supports asking broad provisioning questions
+// and not specifics about the context the provisioning is occurring. We
+// understand that this is safe to do for the moment as the provisioning of
+// machines doesn't interrogate the capabilities of the storage provider.
```
Comment (SimonRichardson) [inline internal/provider/maas/volumes.go:205]: It seems the wrong question to ask. It feels like it should return the storage kinds it does support.

File: internal/provider/maas/volumes.go [hunk 5]
```diff
@@ -72,105 +102,190 @@ func (*maasEnviron) StorageProvider(t storage.ProviderType) (storage.Provider, e
...
+//
+// It should be noted that while a default pool is offered, it is never
+// recommended. See [maasEnviron.RecommendedPoolForKind].
 //
 // Implements [storage.Provider] interface.
 func (maasStorageProvider) DefaultPools() []*storage.Config {
+	// The error for constructing a new storage pool config is disgarded as the
+	// [storage.Provider] interface does not support a error return. Because
+	// the configuration is static in nature we assume that unit testing will
+	// suffice.
```
Comment (SimonRichardson) [inline internal/provider/maas/volumes.go:251]: We should change this in the future, and just make `DefaultPools` to return an error. Azure, EC2, LXD etc do all the same thing.

Something to follow up on though. Not a blocker.

File: internal/provider/maas/maasstorageprovider_test.go [hunk 6]
```diff
@@ -0,0 +1,362 @@
...
+// that contain either leading or trailing whitespace, the whitespace is removed
+// from the output result.
+func (maasStorageProviderSuite) TestTagsFromAttributesStringSliceTrimsWhitespace(c *tc.C) {
+	provider := &maasStorageProvider{}
+	input := map[string]any{
+		"tags": []string{"tag1", " spaceprefix", "tabsuffix	"},
+	}
+
+	output, err := provider.TagsFromAttributes(input)
+	c.Check(err, tc.ErrorIsNil)
```
Comment (nvinuesa) [inline internal/provider/maas/maasstorageprovider_test.go:64]: These are `c.Assert()`

File: internal/provider/maas/volumes.go (hunk 3 above)
Comment (tlm) [reply internal/provider/maas/volumes.go:60]: Reason was to avoid the common temptation of altering the value in tests. Force a const that cannot be changed. Little funky yes but hard testing requirements and temptation avoidance.

File: internal/provider/maas/volumes.go (hunk 5 above)
Comment (tlm) [reply internal/provider/maas/volumes.go:251]: Agreed

File: internal/provider/maas/maasstorageprovider_test.go (hunk 6 above)
Comment (tlm) [reply internal/provider/maas/maasstorageprovider_test.go:64]: I don't think there is a reason to stop this test here if it is wrong. Can let it flow and get more signal.

**Comment by tlm** [comment]
Appreciate the help getting this landed @SimonRichardson, @manadart & @nvinuesa
