### PR TITLE
fix(resources): allows empty resources

### LINKED ISSUE #21213: [juju 4] 0-byte sized file-resources are rejected
### Description

When deploying a bundle with a local file and local file-resource for a charm is a 0-byte file, the deploy fails.

```
Executing changes:
- upload charm /home/ubuntu/git/canonical/k8s-operator/k8s_ubuntu@24.04-amd64.charm for base ubuntu@24.04/stable with architecture=amd64
- deploy application k8s on ubuntu@24.04/stable
ERROR cannot deploy bundle: resource "snap-installation": Put https://10.246.154.218:17070/model/b0656aff-a930-482d-800d-c8d8eb301b9f/applications/k8s/resources/snap-installation?pendingid=2e94e217-57c4-4d43-883b-f1f8a9a0a5bc: storing resource snap-installation of application k8s: putting resource "snap-installation" in store: validating resource size: size is 0
```

It's required in juju 3.x to provide a file resource for every local charm deployed.  Oddly -- juju 4 did not REQUIRE me to deploy with a resource (which may also seem like a bug??)

### Juju version

4.0-rc1

### Cloud

vSphere

### Expected behaviour

expected that a 0-byte file resource is accepted so long as its a valid file.  This was acceptable in juju 3

### Reproduce / Test

1) this is the original issue:, deploy with an empty resource
```sh
juju add-model test
touch empty.gz
juju deploy ./k8s_ubuntu@24.04-amd64.charm  --resource snap-installation=./empty.gz
```

error
```
ERROR resource "snap-installation": Put https://10.246.154.218:17070/model/d0d7e26a-2686-4bb1-8cda-ed67230f4c31/applications/k8s/resources/snap-installation?pendingid=67dee111-bd16-4e1e-844d-065aa2bf3da2: storing resource snap-installation of application k8s: putting resource "snap-installation" in store: validating resource size: size is 0
```

2) this is odd --- this charm has a file resource that's required
```sh
juju add-model test
juju deploy ./k8s_ubuntu@24.04-amd64.charm 
```

but the application deploys

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by gfouillet**
This patch removes the check against having an empty file as a resource.

It updates the tests accordingly and adds a CI test to enforce the behavior.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- [X] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

```sh
juju bootstrap lxd
juju add-model m
juju deploy juju-qa-test qa
touch test.txt # generate an empty file
juju attach-resource qa foo-file=./test.txt
```

This should works without any error message.

## Links

**Issue:** Fixes #21213.

**Jira card:** [JUJU-8755](https://warthogs.atlassian.net/browse/JUJU-8755)

[JUJU-8755]: https://warthogs.atlassian.net/browse/JUJU-8755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: internal/resource/store/fileresourcestore_test.go [hunk 1]
```diff
@@ -33,13 +33,15 @@ func TestFileResourceStoreSuite(t *testing.T) {
...
+}
+
+func (s *fileResourceStoreSuite) initResourceData(c *tc.C, data string) {
 	size := int64(len(data))
 	sha384hash := sha512.New384()
 	sha384hash.Write([]byte(data))
 	fp := fmt.Sprintf("%x", sha384hash.Sum(nil))
-	fingerprint, err := charmresource.ParseFingerprint(fp)
-	c.Assert(err, tc.ErrorIsNil)
+	fingerprint := tc.Must1_1(c, charmresource.ParseFingerprint, fp)
```
Comment (nvinuesa) [inline internal/resource/store/fileresourcestore_test.go:44]: 💯

File: tests/suites/resources/empty.sh [hunk 2]
```diff
@@ -0,0 +1,30 @@
+run_empty_resource_fileobjectstore() {
+	echo
+	name="empty-resource-fileobjectstore"
+
+	file="${TEST_DIR}/test-${name}.log"
+
+	ensure "test-${name}" "${file}"
+
+    touch empty-file.txt
```
Comment (nvinuesa) [inline tests/suites/resources/empty.sh]:
```suggestion
    touch "${TEST_DIR}/empty-file.txt"
```

**Review by SimonRichardson — APPROVED** [review]

File: tests/suites/resources/empty.sh [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+	name="empty-resource-fileobjectstore"
+
+	file="${TEST_DIR}/test-${name}.log"
+
+	ensure "test-${name}" "${file}"
+
+	touch "${TEST_DIR}/empty-file.txt"
+	juju deploy juju-qa-test qa
+	wait_for "qa" "$(idle_condition "qa")"
+	juju attach-resource qa foo-file=empty-file.txt
```
Comment (nvinuesa) [inline tests/suites/resources/empty.sh]: You probably have to update the path here as well, when I run the test I get:
```
    | ERROR failed to upload resource "foo-file": open empty-file.txt: no such file or directory
```

Comment (nvinuesa) [inline tests/suites/resources/empty.sh]: just do 
```suggestion
	juju attach-resource qa foo-file="${TEST_DIR}/empty-file.txt"
```

Comment (gfouillet) [reply tests/suites/resources/empty.sh]: :thinking: I remembered QAed it... But you have right. I must have forgot to commit something, sorry
