### PR TITLE
fix: block device provenance

### LINKED ISSUE #22218: storage block devices end up in race condition with storage provisioning
### Description

This was an issue that I noticed while testing some other storage work. Essentially what we are seeing is the provisioning of a volume attachment through AWS for which we are told a possible mount point location for the block device by AWS. In this example AWS tells us our block device can be found at /dev/xvda

We update the block device table in the database with this information but it is only partial. It isn't until the block device manager starts running on the machine that we get a full picture of what is available.

The storage provisioner on the machine has a good chance of starting before the block device manager and so attempts to provision a filesystem on partial block device information which isn't yet correct.

This is just a case of racing on information that isn't yet fully complete.

### Juju version

4.0.6

### Cloud

AWS

### Expected behaviour

The storage provisioner should only be attempting to partition block devices for which it can see.

### Reproduce / Test

It is hard to repo as it needs specific timing. But the status output for the storage looks as follow:

```
Unit          Storage ID  Type        Size  Status   Message
postgresql/0  pgdata/0    filesystem        pending  sgdisk failed: Problem opening /dev/xvdf for reading! Error is 2.
The specified file does not exist!
Problem opening '' for writing! Program will now terminate.
Warning! MBR not overwritten! Error is 2!: exit status 2
```

@hpidcock is confident of the work to be done.

### Notes & References

Talking with @hpidcock we believe the best path forward for this would be to:

- Record on the block device info the source of the information. i.e block device manager, provider etc
- Let the storage provisioner make decisions based on the source and test it's assumptions about the world before proceeding.

### PR DESCRIPTION
**Pull request by hpidcock**
This change fixes a race condition that allowed a block device to be consumed before
the machine diskmanager worker had reported it. This is due to 4.0 having partial
block devices stored in state (to preserve RI).

This adds a provenance field to the block device table and passes it around as such.
It leaves the storageprovisioner to make the call on if the block device is ready to
consume.

## QA steps

1. Bootstrap AWS.
2. Deploy app that needs storage with 10+ units.
3. Check for sgdisk in debug-log (should not be there).

## Links

**Issue:** Fixes #22218.
**Jira card:** [JUJU-9645](https://warthogs.atlassian.net/browse/JUJU-9645)

[JUJU-9645]: https://warthogs.atlassian.net/browse/JUJU-9645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: api/agent/diskmanager/diskmanager.go [hunk 1]
```diff
@@ -73,6 +73,13 @@ func blockDevicesToParams(in []blockdevice.BlockDevice) []params.BlockDevice {
 			MountPoint:     d.MountPoint,
 			SerialId:       d.SerialId,
 		}
+		switch d.Provenance {
+		case blockdevice.ProviderProvenance:
+			bd.Provenance = params.BlockDeviceProvenanceProvider
+		case blockdevice.MachineProvenance:
+			bd.Provenance = params.BlockDeviceProvenanceMachine
+		}
```
Comment (SimonRichardson) [inline api/agent/diskmanager/diskmanager.go:81]: Can we get a test for this?

File: apiserver/facades/agent/diskmanager/diskmanager_test.go [hunk 2]
```diff
@@ -149,3 +153,88 @@ func (s *DiskManagerSuite) TestSetMachineBlockDevicesMachineNotFound(c *tc.C) {
...
+	s.blockDeviceService.EXPECT().UpdateBlockDevicesForMachine(
+		gomock.Any(), machineUUID, expectedDevices).Return(nil)
+
+	results, err := s.api.SetMachineBlockDevices(
+		c.Context(),
+		params.SetMachineBlockDevices{
+			MachineBlockDevices: []params.MachineBlockDevices{{
+				Machine: "machine-0",
+				// Devices arrive with ProviderProvenance; V2 must
+				// replace it with MachineProv before forwarding.
```
Comment (SimonRichardson) [inline apiserver/facades/agent/diskmanager/diskmanager_test.go]:
```suggestion
				// Devices arrive with ProviderProvenance; V2 must
				// replace it with MachineProvenance before forwarding.
```

File: apiserver/facades/agent/storageprovisioner/register.go [hunk 3]
```diff
@@ -70,26 +77,26 @@ func newFacadeV6(stdCtx context.Context, ctx facade.ModelContext) (*StorageProvi
...
-		domainServices.Application(),
-		domainServices.Removal(),
-		ctx.Auth(),
-		domainServices.Status(),
-		domainServices.StorageProvisioning(),
-		ctx.Logger().Child("storageprovisioner"),
-		ctx.ModelUUID(),
-		ctx.ControllerUUID(),
-	)
-	return &StorageProvisionerAPIv5{storageProvisionerAPI}, err
```
Comment (SimonRichardson) [inline apiserver/facades/agent/storageprovisioner/register.go:92]: Thanks

File: apiserver/facades/agent/storageprovisioner/storageprovisioner.go [hunk 4]
```diff
@@ -1365,6 +1371,12 @@ func (s *StorageProvisionerAPI) VolumeBlockDevices(ctx context.Context, args par
 			MountPoint:     bd.MountPoint,
 			SerialId:       bd.SerialId,
 		}
+		switch bd.Provenance {
+		case blockdevice.ProviderProvenance:
+			result.Provenance = params.BlockDeviceProvenanceProvider
+		case blockdevice.MachineProvenance:
```
Comment (SimonRichardson) [inline apiserver/facades/agent/storageprovisioner/storageprovisioner.go:1377]: Should this be default?

File: apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go [hunk 5]
```diff
@@ -600,6 +604,82 @@ func (s *provisionerSuite) TestVolumeBlockDevices(c *tc.C) {
 		},
 	})
 	c.Assert(err, tc.ErrorIsNil)
+	c.Assert(result, tc.DeepEquals, params.BlockDeviceResults{
```
Comment (SimonRichardson) [inline apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go]:
```suggestion
	c.Check(result, tc.DeepEquals, params.BlockDeviceResults{
```

File: apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go [hunk 6]
```diff
@@ -600,6 +604,82 @@ func (s *provisionerSuite) TestVolumeBlockDevices(c *tc.C) {
...
+	result, err := api.VolumeBlockDevices(c.Context(), params.MachineStorageIds{
+		Ids: []params.MachineStorageId{
+			{
+				MachineTag:    names.NewMachineTag(s.machineName.String()).String(),
+				AttachmentTag: tag.String(),
+			},
+		},
+	})
+	c.Assert(err, tc.ErrorIsNil)
 	c.Assert(result, tc.DeepEquals, params.BlockDeviceResults{
```
Comment (SimonRichardson) [inline apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go]:
```suggestion
	c.Check(result, tc.DeepEquals, params.BlockDeviceResults{
```

File: domain/schema/model.go [hunk 7]
```diff
@@ -13,7 +13,7 @@ import (
 	"github.com/juju/juju/domain/schema/model/triggers"
 )
 
-//go:generate go run ./../../generate/triggergen -db=model -destination=./model/triggers/blockdevice-triggers.gen.go -package=triggers -tables=block_device
+//disabled go:generate go run ./../../generate/triggergen -db=model -destination=./model/triggers/blockdevice-triggers.gen.go -package=triggers -tables=block_device
```
Comment (SimonRichardson) [inline domain/schema/model.go:18]: Might be worth adding a // Merge comment above.

**Review by SimonRichardson — APPROVED** [review]

File: domain/blockdevice/modelmigration/import_test.go [hunk 8]
```diff
@@ -168,9 +169,80 @@ func (s *importSuite) TestImportVolumeAttachmentPlan(c *tc.C) {
...
+		HostMachine: "666",
+		DeviceLink:  "/dev/disk/by-id/d-link",
+		DeviceName:  "baz",
+	})
+
+	// Arrange: expected mock call. Where a block device is found in all
+	// three locations, the order of preference is: the machine's block
+	// device, the volume attachment plan's block device, lastly the
+	// volume attachment's block device.
+	expectedBlockDevices := []blockdevice.BlockDevice{{
```
Comment (gfouillet) [inline domain/blockdevice/modelmigration/import_test.go:228]: **nitpick:** It take me few second to understand this comment refers a general rule or explain the actual test. Because the priority order refers to three categorie and we have only two there.

I wonder if it wouldn't be better to have a test with each of the three categories represented. Also, using meaningful name for deviceLinks could hemp (instance o x-link, use machine, attachement plan, and attachement for instance)

File: internal/worker/storageprovisioner/blockdevices.go [hunk 9]
```diff
@@ -166,38 +166,43 @@ func refreshVolumeBlockDevices(ctx context.Context, deps *dependencies, volumeTa
...
-			// Neither of these errors is fatal; we just wait for
-			// the block device watcher to notify us again.
-		} else {
+		if result.Error != nil && params.IsCodeNotProvisioned(result.Error) {
+			// The volume (attachment) isn't provisioned, just wait for the
+			// block device watcher to notify us again.
+			continue
+		} else if result.Error != nil && params.IsCodeNotFound(result.Error) {
+			// The volume or attachment or block device is not found yet, just
+			// wait for the block device watcher to notify us again.
```
Comment (gfouillet) [inline internal/worker/storageprovisioner/blockdevices.go:175]: **issue:** There is a missing continue (and probably a missing test)

**Review by gfouillet — COMMENTED** [review]
QA works perfectly, but I found something that might be an issue.

File: domain/blockdevice/modelmigration/import_test.go (hunk 8 above)
Comment (hpidcock) [reply domain/blockdevice/modelmigration/import_test.go:228]: This is a copy of the test above to handle a missing use case, it specifically tests Volume Attachments, the above tests Volume Attachment Plans.

File: domain/schema/model.go (hunk 7 above)
Comment (hpidcock) [reply domain/schema/model.go:18]: I referenced it in the PATCH file, but I can do this too.

File: internal/worker/storageprovisioner/blockdevices.go (hunk 9 above)
Comment (hpidcock) [reply internal/worker/storageprovisioner/blockdevices.go:175]: Good catch.

Comment (hpidcock) [reply internal/worker/storageprovisioner/blockdevices.go:175]: Missing tests throughout this whole worker unfortunately.

File: apiserver/facades/agent/storageprovisioner/storageprovisioner.go (hunk 4 above)
Comment (hpidcock) [reply apiserver/facades/agent/storageprovisioner/storageprovisioner.go:1377]: There is only two possible values here, default should be an error, I'll add.

**Review by gfouillet — APPROVED** [review]
Thank you
