### PR TITLE
fix: prevent config and resource operations on synthetic applications

### LINKED ISSUE #21124: Setting config on SAAS application returns incorrect error
### Description

Attempting to set the config on a SAAS application returns the wrong error message. It's supposed to return application not found, instead it's returning `invalid application config...`.

### Juju version

4.0.0-beta8

### Cloud

_No response_

### Expected behaviour

`juju config <application name> token=foo` should return application not found.

### Reproduce / Test

```
$ juju bootstrap lxd test
$ juju add-model offer && juju deploy juju-qa-dummy-source && juju offer dummy-source:sink
$ juju add-model consume && juju deploy juju-qa-dummy-sink
$ juju consume admin/offer.dummy-source && juju relate dummy-source dummy-sink 
$ juju config dummy-source token=foo
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
Synthetic applications (e.g., SAAS) are now rejected for resource
listing, addition, and upload, returning "application not found" errors.
This prevents resource operations on applications that do not support
them.

Also, add check to prevent setting, unsetting, or retrieving config for
synthetic (SAAS in this case) applications. Return not found error for
these cases as well.

This is done in both places thanks to the new `GetApplicationDetailsByName`
method in the application domain. We can replace calls to `GetApplicationUUIDByName` 
and directly check if it's synthetic.

__Note: `GetApplicationUUIDByName` has been marked as deprecated in favor of `GetApplicationDetailsByName`.__

_Note: this patch is another approach off https://github.com/juju/juju/pull/21288._
## QA steps

Setting up a SAAS and trying to set the config should return app not found:
```
$ juju add-model offer && juju deploy juju-qa-dummy-source && juju offer dummy-source:sink
$ juju add-model consume && juju deploy juju-qa-dummy-sink
$ juju consume admin/offer.dummy-source && juju relate dummy-source dummy-sink 
$ juju config dummy-source token=foo
ERROR application "dummy-source" not found
```
Getting all config, one specific config and resetting should also return app not found:
```
$ juju config dummy-source
{}
ERROR application dummy-source not found (not found)
$ juju config dummy-source token
{}
ERROR application dummy-source not found (not found)
$ juju config dummy-source --reset token
{}
ERROR application dummy-source not found
```

Listing (or adding) resources should return an (app not found) error, while it should not fail on the non-synthetic app:
```
$  juju resources dummy-sink
No resources to display.
$ juju resources dummy-source
ERROR application dummy-source not found
$  juju attach-resource dummy-source foo=bar
ERROR application dummy-source not found
```
## Links

**Issue:** Fixes #21124.

**Jira card:** [JUJU-8769](https://warthogs.atlassian.net/browse/JUJU-8769)

[JUJU-8769]: https://warthogs.atlassian.net/browse/JUJU-8769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apiserver/facades/client/application/application.go [hunk 1]
```diff
@@ -1704,11 +1704,29 @@ func (api *APIBase) SetConfigs(ctx context.Context, args params.ConfigSetArgs) (
...
+// SAAS applications are not allowed to have their config set, unset, or retrieved.
+// If the application is synthetic, it returns an error as if the application was not found.
+func (api *APIBase) checkNotSyntheticApplication(ctx context.Context, appName string) error {
+	isSynthetic, err := api.crossModelRelationService.IsApplicationSynthetic(ctx, appName)
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if isSynthetic {
+		return errors.NotFoundf("application %s", appName)
+	}
```
Comment (jack-w-shaw) [inline apiserver/facades/client/application/application.go]: nit: this feels a little misleading to be included in this method

This may just be a styling difference, but i would include the erroring behavior on `isSynthetic == true` in the callers

Feel free to ignore though

**Review by jack-w-shaw — APPROVED** [review]

File: apiserver/facades/client/application/application.go [hunk 2]
```diff
@@ -1704,11 +1704,29 @@ func (api *APIBase) SetConfigs(ctx context.Context, args params.ConfigSetArgs) (
...
 func (api *APIBase) setConfig(ctx context.Context, arg params.ConfigSet) params.ErrorResult {
 	if arg.ConfigYAML != "" {
 		return params.ErrorResult{Error: apiservererrors.ServerError(errors.NotImplementedf("config yaml not supported"))}
 	}
 
+	if err := api.checkNotSyntheticApplication(ctx, arg.ApplicationName); err != nil {
+		return params.ErrorResult{Error: apiservererrors.ServerError(err)}
+	}
+
 	appID, err := api.applicationService.GetApplicationUUIDByName(ctx, arg.ApplicationName)
```
Comment (SimonRichardson) [inline apiserver/facades/client/application/application.go]: We shouldn't do two calls, when one call will do. Just add a new method called `GetApplicationDetailsByName` and deprecate `GetApplicationUUIDByName`

The details will contain both the UUID, and if it is synthetic - and potentially life if it's required.

**Review by SimonRichardson — CHANGES_REQUESTED** [review]

File: apiserver/facades/client/application/application.go (hunk 2 above)
Comment (jack-w-shaw) [reply apiserver/facades/client/application/application.go]: This seems like a bit of a potato to me, I reckon in the majority of cases where we call `GetApplicationUUIDByName` we only want the uuid to then later make a write call or something similar. 

We won't need to know it's life or if it's synthetic, so we'll end up pulling data we don't need from the db

Comment (nvinuesa) [reply apiserver/facades/client/application/application.go]: > and deprecate `GetApplicationUUIDByName`

Ah you're right, this is the correct direction. There's something bothering me with this method that I wanted to break in the previous patch, but deprecating it is the way to go.

**Review by SimonRichardson — APPROVED** [review]
Much better.

File: apiserver/facades/client/application/application.go (hunk 2 above)
Comment (SimonRichardson) [reply apiserver/facades/client/application/application.go]: > We won't need to know it's life or if it's synthetic, so we'll end up pulling data we don't need from the db

This would be correct if we had 1-1 mapping of facade calls to service calls. We don't, so we do end up spilling some additional service calls to the facade. The lack of 1-1 mapping also means that we're over generalising the calls in the facades, which means we *do* want to expose if it's a synthetic application at the facade level. 

Lastly, we don't want 1-1 mapping of all facade calls to service calls, because that means we our calls are too specialised. This is fine in the outliers (deploy would be a good case for this), but not in the large.
