### PR TITLE
fix(resources): prevent resource upload when model is not importing

### LINKED ISSUE #21341: Implement missing resource migration checks.
### Description

The resource migration handler has a TODO for performing more auth checks and making sure the model in question is migrating. See [here](https://github.com/juju/juju/blob/1a8d84ec114c2e4f9921e30081e5a5549f7cbfc4/apiserver/internal/handlers/resources/resourcemigration.go#L61).

This comment needs to be removed and the checks added back in. The handler is already authorized at a controller admin level.

### Juju version

4.0

### Cloud

_No response_

### Expected behaviour

TODO remove and checks implemented.

### Reproduce / Test

N/A

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by gfouillet**
Before this patch, the migration resource upload handler wasn't checking that the model it interacts
with was actually importing.
After this patch, the handler verifies it on post request.

As a fly-by small refactoring around fetching the domain services from request, to make it easier
to fetch the common domain services, or services dedicated to migration.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Bootstrap 3.6 and deploy a model containing an app with a resource.

```sh
juju_36 bootstrap lxd qa36
juju_36 add-model src
juju_36 deploy juju-qa-test qa --resource foo-file=./test.txt
```

Bootstrap a fresh version of juju

```sh
juju bootstrap lxd tgt
```

Migrate model from 3.6 to 4.0.x

```sh
juju switch qa36
juju_36 migrate src tgt
```

Then check everything is ok

## Documentation changes

RAS

## Links

**Issue:** Fixes #21341.

**Jira card:** [JUJU-8881](https://warthogs.atlassian.net/browse/JUJU-8881)

[JUJU-8881]: https://warthogs.atlassian.net/browse/JUJU-8881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apiserver/internal/handlers/resources/service.go [hunk 1]
```diff
@@ -83,6 +83,9 @@ type ApplicationService interface {
 	// application name. This includes the UUID, life status, name, and whether
 	// the application is synthetic.
 	GetApplicationDetailsByName(ctx context.Context, name string) (application.ApplicationDetails, error)
+
+	// IsImportingModel returns true if this model is being imported.
+	IsImportingModel(ctx context.Context) (bool, error)
```
Comment (nvinuesa) [inline apiserver/internal/handlers/resources/service.go]: I wonder if we want to expose this as part of the application service, or better as part of the model service.

Comment (gfouillet) [reply apiserver/internal/handlers/resources/service.go]: I had the same thought.

My assumption was that the model service is a controller service, it stands outside the model, when the application service is inside the model. In the case of importing resources, it make sense to use application service since it is resources linked to an application.

Comment (nvinuesa) [reply apiserver/internal/handlers/resources/service.go]: Yes that's right, and also we already had it on the state layer of application so it's just a matter of exposing it. :+1:

File: apiserver/internal/handlers/resources/resourcemigration.go [hunk 2]
```diff
@@ -58,10 +61,16 @@ func (h *resourcesMigrationUploadHandler) ServeHTTP(w http.ResponseWriter, r *ht
...
-	//  `importing` state.
+	applicationService, err := h.applicationServiceGetter.Application(r)
+	if err != nil {
+		return internalerrors.Capture(err)
+	}
+
+	if isImporting, err := applicationService.IsImportingModel(r.Context()); err != nil {
+		return internalerrors.Capture(err)
+	} else if !isImporting {
+		return errors.BadRequestf("cannot upload resources during migration: model is not importing")
```
Comment (nvinuesa) [inline apiserver/internal/handlers/resources/resourcemigration.go]: The error message is wrong, I suggest:
```suggestion
		return errors.BadRequestf("resource upload is only only allowed during model import")
```
Or something like that.

File: apiserver/internal/handlers/resources/service.go (hunk 1 above)
Comment (hmlanigan) [reply apiserver/internal/handlers/resources/service.go]: issue: this method does not belong in the application service. The model service has both controller and model db methods. CreateImportingModel adds a row to the `model_migrating` table in the model state. It can hold the IsImportingModel service/state methods.

File: apiserver/internal/handlers/resources/resourcemigration.go (hunk 2 above)
Comment (hmlanigan) [reply apiserver/internal/handlers/resources/resourcemigration.go]: todo: "resource upload is only only allowed during model import" is misleading when taken out of context as a user can upload resources to a non importing model via a different handler.

**Comment by gfouillet** [comment]
@hmlanigan updated the error message and move the IsModelImporting to ModelInfo interface from model domain.
