### PR TITLE
fix(modelconfig): coerce provider-specific config attributes from DB

### LINKED ISSUE #21214: [juju 4] vSphere cloud doesn't start machines
### Description

while bootstrapping to vpshere results in a controller model and unit successfully created, making new machines in that model doesn't work:

Nice it looks like the controller tries to get things going -- but it never results in a machine starting.
```
Model  Controller     Cloud/Region    Version  Timestamp
test   addyess-juju4  vsphere/Boston  4.0-rc1  21:03:11Z

App     Version  Status   Scale  Charm   Channel        Rev  Exposed  Message
ubuntu           waiting    0/1  ubuntu  latest/stable   26  no       waiting for machine

Unit      Workload  Agent       Machine  Public address  Ports  Message
ubuntu/0  waiting   allocating  0                               waiting for machine

Machine  State    Address  Inst id  Base          AZ  Message
0        pending           pending  ubuntu@24.04      starting
```

### Juju version

4.0-rc1

### Cloud

vSphere

### Expected behaviour

a machine with an ubuntu charm running would be started

### Reproduce / Test

```sh
juju add-model test-me
juju deploy ubuntu --base=ubuntu@24.04
watch juju status
```

some logs but nothing that seems like the culprit that i can tell

```
machine-0: 21:04:47 ERROR juju.worker.firewaller Machine not yet provisioned: machine 0 not provisioned
machine-0: 21:04:48 DEBUG juju.worker.modelstorageprovisioner volume attachments alive: [], dying: [], dead: []
machine-0: 21:04:48 DEBUG juju.worker.modelstorageprovisioner filesystems alive: [], dying: [], dead: []
machine-0: 21:04:48 INFO juju.worker.provisioner provisioning in zones: [Development Development/Test1 Development/Test2]
machine-0: 21:04:48 INFO juju.worker.provisioner found machine pending provisioning id:0, details:0
machine-0: 21:04:48 DEBUG juju.worker.provisioner pending: [0], dead: []
machine-0: 21:04:54 INFO juju.worker.apicaller [d0d7e2] "machine-0" successfully connected to "wss://localhost:17070"
machine-0: 21:04:54 INFO juju.worker.logger initial log config: "<root>=INFO"
machine-0: 21:04:54 INFO juju.worker.logger logger worker started
machine-0: 21:04:54 INFO juju.worker.providertracker start "d0d7e26a-2686-4bb1-8cda-ed67230f4c31"
machine-0: 21:04:54 INFO juju.worker.removal got removal job changes: []
machine-0: 21:04:54 INFO juju.worker.logger reconfiguring logging from "<root>=INFO" to "<root>=DEBUG;juju.provider.vsphere=TRACE"
machine-0: 21:04:54 DEBUG juju.worker.operationpruner config updated: max-age=336h0m0s, max-size-mb=5120
machine-0: 21:04:54 DEBUG juju.worker.providertracker "d0d7e26a-2686-4bb1-8cda-ed67230f4c31" started
machine-0: 21:05:00 INFO juju.worker.apicaller [d0d7e2] "machine-0" successfully connected to "wss://localhost:17070"
machine-0: 21:05:00 INFO juju.worker.logger initial log config: "<root>=INFO"
machine-0: 21:05:00 INFO juju.worker.logger logger worker started
machine-0: 21:05:00 INFO juju.worker.removal got removal job changes: []
machine-0: 21:05:00 INFO juju.worker.providertracker start "d0d7e26a-2686-4bb1-8cda-ed67230f4c31"
machine-0: 21:05:00 INFO juju.worker.logger reconfiguring logging from "<root>=INFO" to "<root>=DEBUG;juju.provider.vsphere=TRACE"
machine-0: 21:05:00 DEBUG juju.worker.operationpruner config updated: max-age=336h0m0s, max-size-mb=5120
machine-0: 21:05:00 DEBUG juju.worker.providertracker "d0d7e26a-2686-4bb1-8cda-ed67230f4c31" started
machine-0: 21:05:00 WARNING juju.worker.providertracker cloud type vsphere doesn't support dynamic changing of cloud spec
machine-0: 21:05:00 DEBUG juju.worker.operationpruner jittered prune interval: 19h31m32.842s
machine-0: 21:05:00 DEBUG juju.worker.firewaller started watching opened port ranges for the model
machine-0: 21:05:00 DEBUG juju.worker.modelstorageprovisioner volumes alive: [], dying: [], dead: []
machine-0: 21:05:00 INFO juju.worker.provisioner entering provisioner task loop; using provisioner pool with 16 workers
machine-0: 21:05:00 DEBUG juju.worker.provisioner processing machines [0]
machine-0: 21:05:00 DEBUG juju.worker.firewaller started watching "ubuntu/0"
machine-0: 21:05:00 DEBUG juju.worker.firewaller flush instance ports for 0: to open [], to close []
machine-0: 21:05:00 DEBUG juju.worker.firewaller started watching "0"
machine-0: 21:05:00 ERROR juju.worker.firewaller Machine not yet provisioned: machine 0 not provisioned
machine-0: 21:05:07 INFO juju.worker.apicaller [d0d7e2] "machine-0" successfully connected to "wss://localhost:17070"
machine-0: 21:05:07 INFO juju.worker.logger initial log config: "<root>=INFO"
machine-0: 21:05:07 INFO juju.worker.logger logger worker started
machine-0: 21:05:07 INFO juju.worker.providertracker start "d0d7e26a-2686-4bb1-8cda-ed67230f4c31"
machine-0: 21:05:07 INFO juju.worker.removal got removal job changes: []
machine-0: 21:05:07 INFO juju.worker.logger reconfiguring logging from "<root>=INFO" to "<root>=DEBUG;juju.provider.vsphere=TRACE"
machine-0: 21:05:07 DEBUG juju.worker.providertracker "d0d7e26a-2686-4bb1-8cda-ed67230f4c31" started
machine-0: 21:05:07 WARNING juju.worker.providertracker cloud type vsphere doesn't support dynamic changing of cloud spec
machine-0: 21:05:07 DEBUG juju.worker.firewaller started watching opened port ranges for the model
machine-0: 21:05:08 DEBUG juju.worker.operationpruner jittered prune interval: 26h21m41.75s
machine-0: 21:05:08 DEBUG juju.worker.modelstorageprovisioner volumes alive: [], dying: [], dead: []
machine-0: 21:05:08 DEBUG juju.worker.modelstorageprovisioner filesystems alive: [], dying: [], dead: []
machine-0: 21:05:08 INFO juju.worker.provisioner entering provisioner task loop; using provisioner pool with 16 workers
machine-0: 21:05:08 DEBUG juju.worker.provisioner processing machines [0]
machine-0: 21:05:08 DEBUG juju.worker.firewaller started watching "ubuntu/0"
machine-0: 21:05:08 DEBUG juju.worker.firewaller flush instance ports for 0: to open [], to close []
machine-0: 21:05:08 DEBUG juju.worker.firewaller started watching "0"
machine-0: 21:05:08 ERROR juju.worker.firewaller Machine not yet provisioned: machine 0 not provisioned
machine-0: 21:05:14 INFO juju.worker.apicaller [d0d7e2] "machine-0" successfully connected to "wss://localhost:17070"
machine-0: 21:05:14 INFO juju.worker.logger initial log config: "<root>=INFO"
machine-0: 21:05:14 INFO juju.worker.logger logger worker started
machine-0: 21:05:14 INFO juju.worker.providertracker start "d0d7e26a-2686-4bb1-8cda-ed67230f4c31"
machine-0: 21:05:14 INFO juju.worker.removal got removal job changes: []
machine-0: 21:05:14 INFO juju.worker.logger reconfiguring logging from "<root>=INFO" to "<root>=DEBUG;juju.provider.vsphere=TRACE"
machine-0: 21:05:14 DEBUG juju.worker.operationpruner config updated: max-age=336h0m0s, max-size-mb=5120
machine-0: 21:05:14 DEBUG juju.worker.operationpruner jittered prune interval: 25h0m13.804s
machine-0: 21:05:14 DEBUG juju.worker.operationpruner config updated: max-age=336h0m0s, max-size-mb=5120
machine-0: 21:05:14 DEBUG juju.worker.providertracker "d0d7e26a-2686-4bb1-8cda-ed67230f4c31" started
machine-0: 21:05:14 WARNING juju.worker.providertracker cloud type vsphere doesn't support dynamic changing of cloud spec
machine-0: 21:05:14 DEBUG juju.worker.operationpruner jittered prune interval: 21h29m10.507s
machine-0: 21:05:14 DEBUG juju.worker.firewaller started watching opened port ranges for the model
machine-0: 21:05:14 DEBUG juju.worker.modelstorageprovisioner volumes alive: [], dying: [], dead: []
machine-0: 21:05:14 DEBUG juju.worker.modelstorageprovisioner filesystems alive: [], dying: [], dead: []
machine-0: 21:05:14 INFO juju.worker.provisioner entering provisioner task loop; using provisioner pool with 16 workers
machine-0: 21:05:14 DEBUG juju.worker.provisioner processing machines [0]
machine-0: 21:05:14 DEBUG juju.worker.firewaller started watching "ubuntu/0"
machine-0: 21:05:14 DEBUG juju.worker.firewaller flush instance ports for 0: to open [], to close []
machine-0: 21:05:14 DEBUG juju.worker.firewaller started watching "0"
machine-0: 21:05:14 ERROR juju.worker.firewaller Machine not yet provisioned: machine 0 not provisioned
machine-0: 21:05:15 INFO juju.worker.provisioner provisioning in zones: [Development Development/Test1 Development/Test2]
machine-0: 21:05:15 INFO juju.worker.provisioner found machine pending provisioning id:0, details:0
machine-0: 21:05:15 DEBUG juju.worker.provisioner pending: [0], dead: []
machine-0: 21:05:15 WARNING juju.worker.providertracker cloud type vsphere doesn't support dynamic changing of cloud spec
machine-0: 21:05:15 DEBUG juju.worker.provisioner obtained provisioning info: params.ProvisioningInfoResults{Results:[]params.ProvisioningInfoResult{params.ProvisioningInfoResult{Result:(*params.ProvisioningInfo)(0xc003403ce0), Error:<nil>}}}
machine-0: 21:05:15 DEBUG juju.worker.provisioner worker 0: processing task "start-instance 0"
machine-0: 21:05:15 INFO juju.services.status.status-history kind:machine,logger-tags:status-history,message:starting,namespace_id:0,since:2025-11-13T21:05:15Z,status:allocating,category:status-history,data:null status-history (status: "allocating", status-message: "starting")
machine-0: 21:05:15 INFO juju.worker.provisioner trying machine 0 StartInstance in availability zone Development
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
This fix addresses a bug where starting instances in vsphere would hang because of a panic in https://github.com/juju/juju/blob/393ffaddbea56bd25d340c39c1055f67fe2c1b8b/internal/provider/vsphere/config.go#L135 because the value in the config is a string and not a bool. 

Provider-specific model config attributes (e.g., vsphere's enable-disk-uuid) are stored as strings in SQLite but provider code expects typed values (bool, int, etc.). 

Solution: Pass modeldefaults.ProviderModelConfigGetter() to modelconfig services, which use the provider's ConfigSchema() to coerce string values to proper types when reading from the database. This was taken from controller config.

Changes:
- Move ModelConfigProviderFunc type to domain/modeldefaults/types.go to avoid circular imports between modelconfig and modeldefaults services
- Update modelconfig Service and ProviderService to accept the getter function and call it in deserializeMap() to coerce provider attributes
- Pass ProviderModelConfigGetter() in both ModelServices.Config() and ProviderServices.Config()

The coercion happens once at the domain persistence boundary, ensuring all consumers receive properly typed config values.

## QA steps

QA is simply to bootstrap on Vsphere, add a model and deploy ubuntu. 
We should get an active machine and unit in idle status.

## Links

**Issue:** Fixes #21214.

**Jira card:** [JUJU-8753](https://warthogs.atlassian.net/browse/JUJU-8753)

[JUJU-8753]: https://warthogs.atlassian.net/browse/JUJU-8753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/modelconfig/service/service.go [hunk 1]
```diff
@@ -125,6 +132,59 @@ func (s *Service) ModelConfig(ctx context.Context) (*config.Config, error) {
...
 }
 
+// deserializeMap converts a map[string]string to map[string]any and coerces
+// any provider-specific values that are found in the provider's schema.
+func (s *Service) deserializeMap(m map[string]string) (map[string]any, error) {
+	result := make(map[string]any, len(m))
+
+	// If we don't have a model config provider getter, just do basic string->any conversion
+	if s.modelConfigProviderGetterFunc == nil {
+		return transform.Map(m, func(k, v string) (string, any) { return k, v }), nil
```
Comment (SimonRichardson) [inline domain/modelconfig/service/service.go]: You could move each of these maps to a function, so we're not repeating all the time.

File: domain/modelconfig/service/service.go [hunk 2]
```diff
@@ -125,6 +132,59 @@ func (s *Service) ModelConfig(ctx context.Context) (*config.Config, error) {
...
+	provider, err := s.modelConfigProviderGetterFunc(cloudType)
+	if err != nil {
+		// Provider not found or doesn't support schema - graceful degradation
+		return transform.Map(m, func(k, v string) (string, any) { return k, v }), nil
+	}
+
+	if provider == nil {
+		// No provider available - just convert without coercion
+		return transform.Map(m, func(k, v string) (string, any) { return k, v }), nil
+	}
```
Comment (SimonRichardson) [inline domain/modelconfig/service/service.go]:
```suggestion
	provider, err := s.modelConfigProviderGetterFunc(cloudType)
	if err != nil && !errors.Is(err, errors.NotSupported) {
		return nil, errors.Capture(err)
	} else if provider == nil {
		// Provider not found or doesn't support schema - graceful degradation
		return transform.Map(m, func(k, v string) (string, any) { return k, v }), nil
	}
```

File: domain/modelconfig/service/service.go [hunk 3]
```diff
@@ -125,6 +132,59 @@ func (s *Service) ModelConfig(ctx context.Context) (*config.Config, error) {
...
+
+	// Get the schema from the provider
+	fields := provider.ConfigSchema()
+	if fields == nil {
+		// No schema available - just convert without coercion
+		return transform.Map(m, func(k, v string) (string, any) { return k, v }), nil
+	}
```
Comment (SimonRichardson) [inline domain/modelconfig/service/service.go]: I think we should just go through the coercion.

File: domain/modelconfig/service/service.go [hunk 4]
```diff
@@ -81,21 +81,24 @@ type WatcherFactory interface {
...
+	modelValidator                config.Validator
+	modelConfigProviderGetterFunc modeldefaults.ModelConfigProviderFunc
+	st                            State
 }
 
 // NewService creates a new ModelConfig service.
 func NewService(
 	defaultsProvider ModelDefaultsProvider,
 	modelValidator config.Validator,
+	modelConfigProviderGetterFunc modeldefaults.ModelConfigProviderFunc,
```
Comment (SimonRichardson) [inline domain/modelconfig/service/service.go]: We should have our own ModelConfigProviderFunc, not steal the one from modeldefaults.

File: domain/modelconfig/service/service.go (hunk 3 above)
Comment (nvinuesa) [reply domain/modelconfig/service/service.go]: Should we fail if we don't have any fields or if we're missing any field? should we continue without that key but log it?
Returning the string felt as a reasonable fallback.

File: domain/modelconfig/service/service.go (hunk 4 above)
Comment (nvinuesa) [reply domain/modelconfig/service/service.go]: Sure, done, I copied it in modelconfig.

File: domain/modelconfig/service/service.go (hunk 3 above)
Comment (nvinuesa) [reply domain/modelconfig/service/service.go]: In controllerconfig we simply ignore the keys that cannot be coerced https://github.com/juju/juju/blob/cbb05654c7444dd6bee29e49aff16339f02c34f9/domain/controllerconfig/service/service.go#L187-L196 for example.

File: domain/modelconfig/service/service.go (hunk 2 above)
Comment (nvinuesa) [reply domain/modelconfig/service/service.go]: Done

File: domain/modelconfig/service/service.go (hunk 1 above)
Comment (nvinuesa) [reply domain/modelconfig/service/service.go]: Sure, done

File: domain/modelconfig/service/service.go (hunk 3 above)
Comment (nvinuesa) [reply domain/modelconfig/service/service.go]: Ok, I ended up removing it like you suggest, in any case we'll fallback to the string when iterating through the map if we don't have any fields.

File: domain/modelconfig/service/providerservice.go [hunk 5]
```diff
@@ -56,8 +66,68 @@ func (s *ProviderService) ModelConfig(ctx context.Context) (*config.Config, erro
...
+		// No provider available - just convert without coercion
+		return transform.Map(m, func(k, v string) (string, any) { return k, v }), nil
+	}
+
+	// Get the schema from the provider
+	fields := provider.ConfigSchema()
+	if fields == nil {
+		// No schema available - just convert without coercion
+		return transform.Map(m, func(k, v string) (string, any) { return k, v }), nil
+	}
```
Comment (jack-w-shaw) [inline domain/modelconfig/service/providerservice.go]: These feel like they should be error cases to me

File: domain/modelconfig/service/service.go [hunk 6]
```diff
@@ -125,6 +141,56 @@ func (s *Service) ModelConfig(ctx context.Context) (*config.Config, error) {
 	return config.New(config.NoDefaults, altConfig)
 }
 
+// deserializeMap converts a map[string]string to map[string]any and coerces
+// any provider-specific values that are found in the provider's schema.
+func (s *Service) deserializeMap(m map[string]string) (map[string]any, error) {
```
Comment (jack-w-shaw) [inline domain/modelconfig/service/service.go:148]: Maybe `deserialiseMap` should be in another package and exported?

File: domain/modelconfig/service/providerservice.go (hunk 5 above)
Comment (nvinuesa) [reply domain/modelconfig/service/providerservice.go]: Not really, we don't want to break model config retrieval just because we weren't able to get the config schema for a given provider IMHO. Falling back to returning just the map string->string (casted as any) should be good.

File: domain/modelconfig/service/service.go (hunk 6 above)
Comment (nvinuesa) [reply domain/modelconfig/service/service.go:148]: Why? I do need to access the provider getter from the `*Service`.

Comment (jack-w-shaw) [reply domain/modelconfig/service/service.go:148]: Because it's duplicated across files. You only use the `modelConfigProiderGetter` from the service, it could just be passed in as a param to a func

**Review by jack-w-shaw — APPROVED** [review]

File: domain/modelconfig/service/service.go (hunk 6 above)
Comment (jack-w-shaw) [reply domain/modelconfig/service/service.go:148]: However I don't mind enough to block merging

File: domain/modelconfig/service/providerservice.go (hunk 5 above)
Comment (SimonRichardson) [reply domain/modelconfig/service/providerservice.go]: > Not really, we don't want to break model config retrieval just because we weren't able to get the config schema for a given provider IMHO.

If we can't get the provider I think there is something really wrong.

So I think there should be some that we do error out with. I'd rather error out on line 87, 101 and 106. The rest I can see either way.

File: domain/modelconfig/service/service.go [hunk 7]
```diff
@@ -418,19 +484,43 @@ type WatchableService struct {
...
 		},
 		watcherFactory: watcherFactory,
 	}
 }
 
+// ProviderModelConfigGetter returns a ModelConfigProviderFunc that can be used
+// to get a ModelConfigProvider for a given cloud type.
+func ProviderModelConfigGetter() ModelConfigProviderFunc {
+	return func(cloudType string) (environs.ModelConfigProvider, error) {
+		envProvider, err := environs.GlobalProviderRegistry().Provider(cloudType)
```
Comment (SimonRichardson) [inline domain/modelconfig/service/service.go:538]: I really hate that we're getting a global provider registry out of the ether. I'd rather we passed the registry through the services so it can get at it. That way we're at liberty to change the backing of it without messing about with global variablies.
 
----

Also, why are we doing it this way, why can't we use a normal provider? As in when will a model have a different cloud type. It feels like we're jumping through hoops for no reason. I think we can do better here.

File: domain/modelconfig/service/providerservice.go (hunk 5 above)
Comment (nvinuesa) [reply domain/modelconfig/service/providerservice.go]: Sure, updated the returned errors.

File: domain/modelconfig/bootstrap/bootstrap.go [hunk 8]
```diff
@@ -53,7 +53,7 @@ func SetModelConfig(
 		}
 
 		attrs[config.UUIDKey] = m.UUID
-		attrs[config.TypeKey] = m.ModelType
```
Comment (SimonRichardson) [inline domain/modelconfig/bootstrap/bootstrap.go:56]: We need to 100% verify this. But if this is true, it will require a migration step in the database to fix all existing models.

File: domain/modelconfig/service/providerservice.go [hunk 9]
```diff
@@ -56,8 +65,56 @@ func (s *ProviderService) ModelConfig(ctx context.Context) (*config.Config, erro
...
+
+	return config.New(config.NoDefaults, coerced)
+}
+
+// deserializeMap converts a map[string]string from the database to map[string]any
+// and coerces any provider-specific values that are found in the provider's schema.
+// This is necessary because the database stores all config as strings, but provider
+// code expects typed values (e.g., bool, int) for provider-specific attributes.
+func (s *ProviderService) deserializeMap(m map[string]string) (map[string]any, error) {
+	result := make(map[string]any, len(m))
```
Comment (SimonRichardson) [inline domain/modelconfig/service/providerservice.go]: Move this line to the bottom of the method, above the for loop.

File: domain/modelconfig/bootstrap/bootstrap.go (hunk 8 above)
Comment (SimonRichardson) [reply domain/modelconfig/bootstrap/bootstrap.go:56]: The schema implies that it is actually the cloud type and not the model type:

https://github.com/juju/juju/blob/cbb05654c7444dd6bee29e49aff16339f02c34f9/environs/config/schema.go#L483-L489

File: domain/modelconfig/bootstrap/bootstrap_test.go [hunk 10]
```diff
@@ -121,13 +121,6 @@ func (s *bootstrapSuite) TestSetModelConfig(c *tc.C) {
 		}, nil
 	}
 
-	//cfg, err := config.New(config.NoDefaults, map[string]any{
-	//	"name": "wallyworld",
-	//	"uuid": "a677bdfd-3c96-46b2-912f-38e25faceaf7",
-	//	"type": "sometype",
-	//})
-	//c.Assert(err, tc.ErrorIsNil)
```
Comment (SimonRichardson) [inline domain/modelconfig/bootstrap/bootstrap_test.go:128]: Delete me or keep me.

File: domain/modelconfig/service/service.go [hunk 11]
```diff
@@ -26,6 +28,13 @@ type ModelDefaultsProvider interface {
 	ModelDefaults(context.Context) (modeldefaults.Defaults, error)
 }
 
+// ModelConfigProviderFunc describes a type that is able to return a
+// [environs.ModelConfigProvider] for the specified cloud type. If the no
+// model config provider exists for the supplied cloud type then a
+// [coreerrors.NotFound] error is returned. If the cloud type provider does not
+// support model config then a [coreerrors.NotSupported] error is returned.
+type ModelConfigProviderFunc func(string) (environs.ModelConfigProvider, error)
```
Comment (SimonRichardson) [inline domain/modelconfig/service/service.go]: It's a shame that `func(string)` isn't typed, otherwise we wouldn't have gotten ModelType and CloudType mixed up.

**Review by SimonRichardson — COMMENTED** [review]
We need an upgrade step to undo the models if we're storing the model type in model config and it should be replaced with cloud type.

Also, I want another set of eyes on this to confirm it.

Otherwise thanks for keep pushing on this one.

File: domain/modelconfig/bootstrap/bootstrap.go (hunk 8 above)
Comment (nvinuesa) [reply domain/modelconfig/bootstrap/bootstrap.go:56]: Yeah I agree, this little change has the power to do a lot of damage. @tlm wanna check this out?

File: domain/modelconfig/bootstrap/bootstrap_test.go (hunk 10 above)
Comment (nvinuesa) [reply domain/modelconfig/bootstrap/bootstrap_test.go:128]: I don't follow. I just deleted that commented lines (the defaults are being passed from line 116).

Comment (tlm) [reply domain/modelconfig/bootstrap/bootstrap_test.go:128]: Thank you

File: domain/modelconfig/service/providerservice.go [hunk 12]
```diff
@@ -56,8 +65,55 @@ func (s *ProviderService) ModelConfig(ctx context.Context) (*config.Config, erro
...
+
+	return config.New(config.NoDefaults, coerced)
+}
+
+// deserializeMap converts a map[string]string from the database to map[string]any
+// and coerces any provider-specific values that are found in the provider's schema.
+// This is necessary because the database stores all config as strings, but provider
+// code expects typed values (e.g., bool, int) for provider-specific attributes.
+func (s *ProviderService) deserializeMap(m map[string]string) (map[string]any, error) {
+	if s.modelConfigProviderGetterFunc == nil {
```
Comment (tlm) [inline domain/modelconfig/service/providerservice.go:82]: Place holder comment as I might find a better answer in the rest of the PR.

I don't think we should be making the contract of `ProviderService` support pass a nil dependency. It should always be required and if we have a use case where it won't be then provide a noop implementation.

File: domain/modelconfig/service/providerservice.go [hunk 13]
```diff
@@ -56,8 +65,55 @@ func (s *ProviderService) ModelConfig(ctx context.Context) (*config.Config, erro
...
+		return nil, errors.New("no model config provider getter")
+	}
+
+	cloudType, ok := m[config.TypeKey]
+	if !ok || cloudType == "" {
+		// No cloud type - just convert without coercion.
+		return stringMapToAny(m), nil
+	}
+
+	provider, err := s.modelConfigProviderGetterFunc(cloudType)
```
Comment (tlm) [inline domain/modelconfig/service/providerservice.go]: I would change this part in push the dependencies down a little further. Essentially my proposal would be to make `modelConfigProviderGetterFunc` always return the config provider for this model. i.e the function knows what model it is connected to and can get the cloud type for itself.

My reasons for this are:
- It disallows model scoped code from moving sideways into areas where it should not always be allowed to go. This is purely just defensive aspect and keeps to our strict internal modelling of always being scoped to a model and the model's resources.
- The func internally can load the value once and then store for the it's lifetime. i.e we don't incur a significant database penality every time.
- It allows us to get off of the read only model config keys that tell us model metadata. They are a lot of work to maintain and are a constant source of bugs. Quicker we can stamp them out the happy our bug queue will be.

File: domain/modelconfig/service/service.go (hunk 11 above)
Comment (tlm) [reply domain/modelconfig/service/service.go]: I would propose a name change here only because provider is very overload and is a big scope. Maybe something like `ModelProviderConfigSchemaFunc`.

File: domain/modelconfig/service/service.go [hunk 14]
```diff
@@ -125,6 +141,51 @@ func (s *Service) ModelConfig(ctx context.Context) (*config.Config, error) {
...
+	provider, err := s.modelConfigProviderGetterFunc(cloudType)
+	if err != nil && !errors.Is(err, coreerrors.NotSupported) {
+		return nil, errors.Capture(err)
+	} else if provider == nil {
+		// Provider not found or doesn't support config schema.
+		return nil, errors.New("provider not found or doesn't support config schema")
+	}
+
+	fields := provider.ConfigSchema()
+	for key, strVal := range m {
```
Comment (tlm) [inline domain/modelconfig/service/service.go]: I believe you can use a schema.FieldMap from the fields to coerce the whole lot as one.

Up to you just and FYI if you didn't know.

File: domain/modelconfig/service/service.go [hunk 15]
```diff
@@ -418,19 +479,43 @@ type WatchableService struct {
...
+			modelConfigProviderGetterFunc: modelConfigProviderGetterFunc,
+			st:                            st,
 		},
 		watcherFactory: watcherFactory,
 	}
 }
 
+// ProviderModelConfigGetter returns a ModelConfigProviderFunc that can be used
+// to get a ModelConfigProvider for a given cloud type.
+func ProviderModelConfigGetter() ModelConfigProviderFunc {
```
Comment (tlm) [inline domain/modelconfig/service/service.go]: Same comments as above re name change and capturing the model's metadata within this.

File: domain/modelconfig/service/service.go [hunk 16]
```diff
@@ -418,19 +479,43 @@ type WatchableService struct {
...
+	return func(cloudType string) (environs.ModelConfigProvider, error) {
+		envProvider, err := environs.GlobalProviderRegistry().Provider(cloudType)
+		if errors.Is(err, coreerrors.NotFound) {
+			return nil, errors.Errorf(
+				"no model config provider exists for cloud type %q", cloudType,
+			).Add(coreerrors.NotFound)
+		}
+
+		modelConfigProvider, supports := envProvider.(environs.ModelConfigProvider)
```
Comment (tlm) [inline domain/modelconfig/service/service.go:548]: I don't think we should be returning a not supported error for this. If the provider does not implement this interface then it just doesn't have an opinion about model config. In this case I would just return an empty set of fields.

No reason to propagate an error as it is an optional interface that a provider may choose to implement.

File: domain/modelconfig/bootstrap/bootstrap.go (hunk 8 above)
Comment (tlm) [reply domain/modelconfig/bootstrap/bootstrap.go:56]: We are so close to just being able to delete this key all together. Hopefully soon. Thank you for doing this but we should also be actively removing use of this value in the last few places we have.

**Review by tlm — APPROVED** [review]
Thanks for your work @nvinuesa, I think this is stella.

I don't have access to vsphere to test this in anger so hoping to rely on your testing.

My comments mainly are around design and pushing down dependencies into the func a bit more.

Happy to chat about any parts if you need.

**Review by SimonRichardson — APPROVED** [review]

File: domain/modelconfig/service/service.go (hunk 16 above)
Comment (nvinuesa) [reply domain/modelconfig/service/service.go:548]: It's already handled here https://github.com/juju/juju/pull/21469/changes#diff-778e13107f5a3aa8e9b57278e5e52ad368483893d8e5012b6d9118855657d70fR160 so not resurfaced.

File: domain/modelconfig/service/service.go (hunk 14 above)
Comment (nvinuesa) [reply domain/modelconfig/service/service.go]: Sure, done in 570871446f2.

File: domain/modelconfig/service/providerservice.go (hunk 13 above)
Comment (nvinuesa) [reply domain/modelconfig/service/providerservice.go]: Yeah good suggestion, see 570871446f2.

Comment (nvinuesa) [reply domain/modelconfig/service/providerservice.go]: Done in that commit.
