### PR TITLE
fix(removal): reschedule application child removals on retries

### LINKED ISSUE #21257: Wedged Kubernetes Application cannot be removed
### Description

When an application has been deployed to a Kubernetes model and it isn't considered healthy there is no way to remove the application after the fact with --force.

For example starting with `juju remove-application vault-k8s` will sit and spin for ever because the single unit for the application is not in a healthy state. If you then run `juju remove-application --force vault-k8s` no new removal job is made for the application with force set.

If you then try and unwedge the removal by removing the unit with `juju remove-unit --num-units 1 vault-k8s --force` you get back `ERROR changing scaling state for "vault-k8s": scale change invalid: cannot remove more units than currently exist`. This is because the unit has been set to dying but isn't considered in the remove workflow.

### Juju version

4.0.0

### Cloud

Kubernetes

### Expected behaviour

We should be able to remove the application again with force and have that cascade and or we should be able to force remove the unit stopping the removal.

### Reproduce / Test

Deploy vault-k8s as this will fail due to a storage bug and then attempt to remove the application. The storage bug is documented in #21254.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
__Note: this is the second patch that fixes the (re-)schedule of removal jobs on child entities when retried. Prev. one was https://github.com/juju/juju/pull/21973.__

## Problem

While analyzing https://github.com/juju/juju/issues/21257 I discovered that we have an issue when removing applications after a first attempt failed. 
The actual problem was that when we run remove-application with --force *after* it had been run without it, and a unit removal job hangs, then the application is blocked for removal.
The reason for this can be found in `EnsureApplicationNotAliveCascade()` in the state layer:
https://github.com/juju/juju/blob/78529496d3f72768f173b51286421c0eed0b393a/domain/removal/state/model/application.go#L142-L146
In this case, we only select units that are alive and update them to dying, then return their UUIDs. But what happens if the unit had previously been updated already?: It's not returned.
And therefore we don't re-schedule any job for it: https://github.com/juju/juju/blob/7c5e8de23c37e0ce9061454fcaac818c53c2e7db/domain/removal/service/model.go#L226
This is of course problematic since the second run of `juju destroy-model --force` should be effective and "supersede" the previously scheduled/running removal jobs for that entity.

If we look at an example (subset) hierarchy of model destroy:
```
                   Model
                     |
                 Application
                     |
       ----------------------------
       |                          |
      Unit <-fails             Relation
       |
    Machine
```

A common operator flow is to escalate removal intent over multiple commands:

   juju remove-application ubuntu
   juju remove-application ubuntu --force --wait=60s
   juju remove-application ubuntu --force --wait=0s   # highest priority request

Before this fix, the previous executions would be hang because the unit job would not finish and so the application cannot be removed.

## The fix

Before this change, remove-application only re-collected children that were still alive.
If a previous removal attempt had already moved units, relations, machines, or storage
to dying, a retry (including --force) would not reschedule those child jobs. That made
retry escalation ineffective and could leave app removal wedged.

Now application removal returns all non-dead cascaded children on each retry and
reschedules their jobs with the latest intent (including no-force -> force escalation),
while still keeping life transitions monotonic (alive -> dying only).

## Fly-by

As a flyby, an unseen bug was fixed in the container removal path (we were selecting based on the life of the parent and not the machine):
https://github.com/juju/juju/pull/22008/changes#diff-84670fef638b2c8dbf568c3029af0906c2f2661d129020b20ac8bd1a8f8e5fe8R96

## QA steps
The scenario is basically to deploy an app on a model, and then stop the jujud service on the machine to simulate a broken state that will block graceful removal. Then destroy again with --force and check that it actually goes away.
```
$ juju add-model m
$ juju deploy ubuntu
$ juju add-ssh-key "$(cat ~/.ssh/id_ed25519.pub)"
$ juju ssh 0 "sudo systemctl stop jujud-machine-0.service"
```
Now the status should show the machine `down` and ubuntu app and unit as `unknown` status.

After a first graceful destroy (`juju remove-application ubuntu`) we'll see that it just hangs, and on the logs we have:
```
machine-0: 12:08:21 INFO juju.worker.removal scheduling application job "10442cf7-83cb-4f1a-8b57-2b731aa9cebc"
machine-0: 12:08:21 INFO juju.worker.removal scheduling unit job "24c15f0c-d84e-4536-8abc-d55d12e0ce16"
machine-0: 12:08:21 INFO juju.worker.removal scheduling machine job "2fe9cff7-63ed-4d86-8129-1a81c1ff76df"
machine-0: 12:08:21 INFO juju.worker.removal runner "removal" starting worker "24c15f0c-d84e-4536-8abc-d55d12e0ce16"
machine-0: 12:08:21 INFO juju.worker.removal runner "removal" starting worker "10442cf7-83cb-4f1a-8b57-2b731aa9cebc"
machine-0: 12:08:21 INFO juju.worker.removal runner "removal" starting worker "2fe9cff7-63ed-4d86-8129-1a81c1ff76df"
```
If we then force the app removal, the application will end up being removed:
```
$ juju remove-application ubuntu --force
```
Another scenario is similar but with a relation included:
```
$ juju add-model m
$ juju deploy juju-qa-dummy-source --base ubuntu@22.04
$ juju deploy juju-qa-dummy-sink --base ubuntu@22.04
$ juju relate dummy-sink dummy-source
# Now stop one of the machine services
$ juju add-ssh-key "$(cat ~/.ssh/id_ed25519.pub)"
$ juju ssh 0 "sudo systemctl stop jujud-machine-0.service"
```
This will bring the `dummy-source` application to an `unknown` state so we can now perform the removal without and with force (which will remove the application).

The last scenario regards storage. 
We deploy an application with storage attached, and then try to remove the app with a failing unit (exactly like the previous scenarios). 
- First without the `--destroy-storage` flag, only force: this time the app will be removed but the storage won't.
- Second with `--destroy-storage`. This time everything will go away.
(The dummy-storage charm must be packed first with charmcraft)
```
$ juju deploy ./testcharms/charms/dummy-storage/dummy-storage_amd64.charm --storage single-fs=100M
$ juju status --storage
Model  Controller  Cloud/Region         Version  Timestamp
mmm    ccc         localhost/localhost  4.0.4.1  12:57:22+01:00

App            Version  Status  Scale  Charm          Channel  Rev  Exposed  Message
dummy-storage           active      1  dummy-storage             0  no       Stored token: /tmp/status

Unit              Workload  Agent  Machine  Public address  Ports  Message
dummy-storage/0*  active    idle   0        10.134.1.182           Stored token: /tmp/status

Machine  State    Address       Inst id        Base          AZ                                Message
0        started  10.134.1.182  juju-fd968a-0  ubuntu@24.04  nvinuesa-ThinkPad-P16s-Gen-4-AMD  Running
```
Now break the machine and try removing without --destroy-storage:
```
$ juju add-ssh-key "$(cat ~/.ssh/id_ed25519.pub)"
$ juju ssh 0 "sudo systemctl stop jujud-machine-0.service"
$ juju remove-application dummy-storage
# ...
$ juju remove-application dummy-storage --force
# ...
$ juju status --storage
Model  Controller  Cloud/Region         Version  Timestamp
mmm     ccc         localhost/localhost  4.0.4.1  13:02:35+01:00

Storage Unit  Storage ID   Type        Mountpoint  Size  Status    Message
              single-fs/0  filesystem                    attached  
```
If we do the same thing a second time, but this time we remove with `--destroy-storage`:
```
$ juju remove-application dummy-storage --destroy-storage
# ...
$ juju remove-application dummy-storage --destroy-storage --force
# ...
$ juju status --storage
Model  Controller  Cloud/Region         Version  Timestamp
mmm    ccc         localhost/localhost  4.0.4.1  13:03:44+01:00

Model "admin/mmm" is empty.
```
This shows that storage artifacts are correctly removed as well and it doesn't block the app removal.

## Links

**Issue:** Fixes #21257.

**Jira card:** [JUJU-8783](https://warthogs.atlassian.net/browse/JUJU-8783)

[JUJU-8783]: https://warthogs.atlassian.net/browse/JUJU-8783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/removal/service/application_test.go [hunk 1]
```diff
@@ -90,6 +90,118 @@ func (s *applicationSuite) TestRemoveApplicationForceWaitSuccess(c *tc.C) {
 	c.Assert(jobUUID.Validate(), tc.ErrorIsNil)
 }
 
+func (s *applicationSuite) TestRemoveApplicationRetrySchedulesRemovalJobs(c *tc.C) {
```
Comment (nvinuesa) [inline domain/removal/service/application_test.go:93]: These test isn't testing anything new, it just checks that on a second retry, the service still schedules removal for the app and every cascaded child kind (relation/unit/machine/storage artifacts) again, instead of dropping child jobs. I added it to enforce this.

File: domain/removal/service/application_test.go [hunk 2]
```diff
@@ -90,6 +90,118 @@ func (s *applicationSuite) TestRemoveApplicationForceWaitSuccess(c *tc.C) {
...
+	jobUUID1, err := s.newService(c).RemoveApplication(c.Context(), appUUID, false, false, 0)
+	c.Assert(err, tc.ErrorIsNil)
+	c.Assert(jobUUID1.Validate(), tc.ErrorIsNil)
+
+	jobUUID2, err := s.newService(c).RemoveApplication(c.Context(), appUUID, false, false, 0)
+	c.Assert(err, tc.ErrorIsNil)
+	c.Assert(jobUUID2.Validate(), tc.ErrorIsNil)
+}
+
+func (s *applicationSuite) TestRemoveApplicationRetryWithForceSchedulesRemovalJobs(c *tc.C) {
```
Comment (nvinuesa) [inline domain/removal/service/application_test.go:143]: Same here, this one just enforces that retry escalation (force=false then force=true) propagates force=true to all scheduled child jobs.

File: domain/removal/state/model/application.go [hunk 3]
```diff
@@ -209,9 +214,28 @@ AND    life_id = 0`, applicationUUID)
...
+	res.VolumeUUIDs = dedupeStrings(res.VolumeUUIDs)
+	res.StorageInstanceUUIDs = dedupeStrings(res.StorageInstanceUUIDs)
+
 	return res, nil
 }
 
+func dedupeStrings(in []string) []string {
+	if len(in) < 2 {
+		return in
+	}
```
Comment (SimonRichardson) [inline domain/removal/state/model/application.go]: I think we just remove this - `slices.Compact` already does this. I think it just pollutes what we're trying to do here.

File: domain/removal/state/model/machine.go [hunk 4]
```diff
@@ -239,10 +244,14 @@ AND    u.life_id = 0;`, machineUUID, uuids{})
...
 func (st *State) ensureMachineStorageInstancesNotAliveCascade(
-	ctx context.Context, tx *sqlair.TX, mUUID string,
+	ctx context.Context, tx *sqlair.TX, mUUID string, includeDying bool,
 ) (internal.CascadedStorageInstanceLives, error) {
 	var cascaded internal.CascadedStorageInstanceLives
 	machineUUID := entityUUID{UUID: mUUID}
+	storageInstanceLife := "= 0"
+	if includeDying {
+		storageInstanceLife = "< 2"
+	}
```
Comment (SimonRichardson) [inline domain/removal/state/model/machine.go]: No. We never want to do string interpolation here. If this is correct, just pass in an arg.

File: domain/removal/state/model/unit.go [hunk 5]
```diff
@@ -360,8 +377,34 @@ AND    life_id = 0`, entityUUID{})
 	if affected, err := outcome.Result().RowsAffected(); err != nil {
 		return "", cascaded, errors.Errorf("getting affected rows: %w", err)
 	} else if affected == 0 {
-		// The machine was already dying or dead.
-		return "", cascaded, nil
+		if !includeDying {
+			// The machine was already dying or dead.
+			return "", cascaded, nil
+		}
```
Comment (SimonRichardson) [inline domain/removal/state/model/unit.go]: I thought the whole point is to **always** return information, even if it's alive or dying. That way you don't or shouldn't even bale out here.

**Review by SimonRichardson — CHANGES_REQUESTED** [review]
This isn't right on two fronts:

 1. Never do string concatenation/interpolation when we can just pass a sqlair argument.
 2. We always want to return everything when doing a cascade even if it's alive or dying.

File: domain/removal/state/model/machine.go (hunk 4 above)
Comment (nvinuesa) [reply domain/removal/state/model/machine.go]: This was a mistake, I was already fixing before your review :rofl:. The original intent was to only change the `remove-application` path, without having to change the logic for machines, storage, etc. But after second thought, returning both alive and dying is always secure.

File: domain/removal/state/model/unit.go (hunk 5 above)
Comment (nvinuesa) [reply domain/removal/state/model/unit.go]: Yeah defo. https://github.com/juju/juju/pull/22008#discussion_r2939962771

File: domain/removal/state/model/application.go (hunk 3 above)
Comment (nvinuesa) [reply domain/removal/state/model/application.go]: Sure, done in 63b6223e839052b5a0aaf564ea07692aac7002b0.

**Comment by nvinuesa** [comment]
@SimonRichardson you correctly pointed out that we don't care if it's a retry or not, we always want to return the alive+dying artifacts. Second commit c45c86de433b949531e870be53b2c7b7ead57fe5 addresses this.

File: domain/removal/state/model/machine.go [hunk 6]
```diff
@@ -93,9 +93,9 @@ AND    life_id = 0;`, machineUUID)
 	selectContainerMachines, err := st.Prepare(`
 SELECT    mp.machine_uuid AS &entityUUID.uuid
 FROM      machine_parent AS mp
-JOIN      machine AS m ON mp.parent_uuid = m.uuid
+JOIN      machine AS m ON mp.machine_uuid = m.uuid
```
Comment (SimonRichardson) [inline domain/removal/state/model/machine.go]: Why was this changed, was it broken?

File: domain/removal/state/model/unit.go [hunk 7]
```diff
@@ -360,7 +369,6 @@ AND    life_id = 0`, entityUUID{})
 	if affected, err := outcome.Result().RowsAffected(); err != nil {
 		return "", cascaded, errors.Errorf("getting affected rows: %w", err)
 	} else if affected == 0 {
-		// The machine was already dying or dead.
 		return "", cascaded, nil
```
Comment (SimonRichardson) [inline domain/removal/state/model/unit.go]: If the machine has already transitioned to dying, we still need to return the cascaded information.

```suggestion
	cascaded, err = st.ensureMachineStorageInstancesNotAliveCascade(ctx, tx, result.UUID)
	if err != nil {
		return "", cascaded, errors.Errorf("advancing machine storage entity lives: %w", err)
	}

	return result.UUID, cascaded, nil
```

File: domain/removal/state/model/unit.go
Comment (SimonRichardson) [inline domain/removal/state/model/unit.go:351]: How do we handle storage dependencies here i.e. we need to ensure that we also return any child dependencies.

**Review by SimonRichardson — COMMENTED** [review]
Thanks for the turn around - we're getting close. We just need to verify that all shortcuts are now still valid, as we always want to return cascaded child entities.

File: domain/removal/state/model/machine.go (hunk 6 above)
Comment (nvinuesa) [reply domain/removal/state/model/machine.go]: Short answer yes it was broken, we were selecting based on the parent's life instead of the child. I fixed this while I was writing the tests (for the original change, i.e. child machine artifacts) but then I forgot to create a separate commit for it. 
Do you want me to open a separate patch with this fix, or just update this PR description with it?

File: domain/removal/state/model/unit.go (hunk 7 above)
Comment (nvinuesa) [reply domain/removal/state/model/unit.go]: of course! done.

File: domain/removal/state/model/machine.go (hunk 6 above)
Comment (SimonRichardson) [reply domain/removal/state/model/machine.go]: > Do you want me to open a separate patch with this fix

This one.

File: domain/removal/state/model/unit.go
Comment (nvinuesa) [reply domain/removal/state/model/unit.go:351]: The storage artifacts here are the ones related to the machine only (machine-owned volumes/filesystems), not the unit ones. 
These are correctly returned from the call to `ensureMachineStorageInstancesNotAliveCascade` inside `markMachineAsDyingIfAllUnitsAreNotAlive`. Then, the results from `markMachineAsDyingIfAllUnitsAreNotAlive` are merged with the rest of the cascaded storage artifacts in https://github.com/juju/juju/blob/78529496d3f72768f173b51286421c0eed0b393a/domain/removal/state/model/unit.go#L114, that part was untouched.
Before this fix of course, we would only return the cascaded artifacts once (when life was alive only).

I added a test to ensure no regression on this path `TestEnsureUnitNotAliveCascadeMachineAlreadyDyingReturnsStorageCascade`.

**Comment by SimonRichardson** [comment]
@nvinuesa can you have different QA steps - I'd like to see items with storage and relations.

**Comment by nvinuesa** [comment]
@SimonRichardson I added two more QA scenarios (one with relation, the other with storage) and they run successfully.

File: domain/removal/state/model/machine.go (hunk 6 above)
Comment (nvinuesa) [reply domain/removal/state/model/machine.go]: Done, reverted this small fix and will open a new PR with this.

**Review by SimonRichardson — APPROVED** [review]
Thanks for pushing this one over the line.

This will make removal more deterministic when calling `juju remove-application` multiple times, even with the use of force.

**Review by jack-w-shaw — APPROVED** [review]
LGTM once weirdness w/ static analysis is sorted
