### PR TITLE
fix: incorrect resource sql view for application

### LINKED ISSUE #21331: Incorrect resource sql view for application
### Description

In juju 4.0 there exists an sql view called `v_application_resource` which is supposed to provide all of the resources for each application in the model. The problem is it is left joined onto the application tables.

```
CREATE VIEW v_application_resource AS
SELECT
    r.uuid,
    r.name,
    r.created_at,
    r.revision,
    r.origin_type,
    r.state,
    r.retrieved_by,
    r.retrieved_by_type,
    r.path,
    r.description,
    r.kind_name,
    r.size,
    r.sha384,
    ar.application_uuid,
    a.name AS application_name
FROM v_resource AS r
LEFT JOIN application_resource AS ar ON r.uuid = ar.resource_uuid
LEFT JOIN application AS a ON ar.application_uuid = a.uuid;
```

Reviewing the usages of the view most usages are correctly coming at the problem with an application uuid context however there does exist some usages that should not being using this view at all:

**Ref 1:** `getResourceType` https://github.com/juju/juju/blob/1a8d84ec114c2e4f9921e30081e5a5549f7cbfc4/domain/resource/state/resource.go#L766

This has a resource uuid and just wants to know the type. It should just be going directly to the `v_resource` view or the table. There is no need for a view for this query and the implementation got haphazard.

The view needs to fixed to be a full join so it is actually fulfilling it's purpose and doesn't introduce subtle bugs down the road.

### Juju version

4.0

### Cloud

_No response_

### Expected behaviour

The view should be a full join no exceptions!

### Reproduce / Test

N/A

### Notes & References

N/A

### PR DESCRIPTION
**Pull request by hmlanigan**
First replace `v_application_resource` with a version containing JOIN rather than LEFT JOIN, there by requiring an application for the resource. Done in a db upgrade step. 

Note: The db upgrade step may require updating to juju 4.0.5 depending on when the juju 4.0.4 candidate is created.

Resources do not require an application to be created or uploaded into juju controller. Creating a resource does require the resource's charm to have been created on the juju controller. The application is required when the resource is actually used by a unit. Updated code paths in juju where an application is not required to new methods, to be explicit about when this should occur. 

There is not a current juju client code path where a resource is uploaded before an application is created. However the API allows for it: first call `AddCharm` via the charm API then `UploadPendingResource` or `AddPendingResources` and `Upload` via the resource API.

Three new state methods were added to the above. 
* `GetResourceMaybeApplication` is similar to `GetResource however the application name is only returned if one is available and will not cause the method to fail if one does not exist.
* `VerifyApplicationExistsForResource` verifies that an application exists with the resource.
* `GetResourceNameAndType` replaces a call to `GetResource` where an application is not required, nor is the majority of the `GetResource` result needed.

Drive by to push a calls to `GetResource` after `StoreResource*` into `StoreResource*` at the service level. Simplifying where the domain methods are used. 

Fixes #21331

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

With an lxd controller:
```
(cd tests ; ./main.sh resources)
```

Bootstrap a Kubernetes controller and deploy a charm.

## Links

**Jira card:** [JUJU-8882](https://warthogs.atlassian.net/browse/JUJU-8882)

[JUJU-8882]: https://warthogs.atlassian.net/browse/JUJU-8882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/resource/state/resource_test.go [hunk 1]
```diff
@@ -1726,6 +1740,121 @@ func (s *resourceSuite) TestGetResourceTypeNotFound(c *tc.C) {
...
+	})
+	c.Assert(err, tc.ErrorIsNil, tc.Commentf("(Arrange) failed to populate DB: %v", errors.ErrorStack(err)))
+
+	// Act.
+	name, resourceType, err := s.state.GetResourceNameAndType(c.Context(), coreresource.UUID(resID))
+
+	// Assert.
+	c.Assert(err, tc.ErrorIsNil, tc.Commentf("(Act) failed to get resource name and type: %v", errors.ErrorStack(err)))
+	c.Assert(name, tc.Equals, input.Name)
+	c.Assert(resourceType, tc.Equals, charmresource.TypeFile)
```
Comment (SimonRichardson) [inline domain/resource/state/resource_test.go]:
```suggestion
	c.Check(name, tc.Equals, input.Name)
	c.Check(resourceType, tc.Equals, charmresource.TypeFile)
```

Also do the rest of this file.

File: domain/resource/state/resource_test.go [hunk 2]
```diff
@@ -1726,6 +1740,121 @@ func (s *resourceSuite) TestGetResourceTypeNotFound(c *tc.C) {
...
+	resID := "resource-id"
+	input := resourceData{
+		UUID:            resID,
+		ApplicationUUID: s.constants.fakeApplicationUUID1,
+		Name:            "resource-name",
+		Type:            charmresource.TypeContainerImage,
+	}
+
+	err := s.TxnRunner().StdTxn(c.Context(), func(ctx context.Context, tx *sql.Tx) error {
+		return errors.Capture(input.insert(ctx, tx))
```
Comment (SimonRichardson) [inline domain/resource/state/resource_test.go]:
```suggestion
		return input.insert(ctx, tx)
```

nit: We don't need to capture in tests. It's a bit overkill.

File: domain/resource/state/resource.go [hunk 3]
```diff
@@ -2507,3 +2561,94 @@ WHERE  name = $applicationNameAndID.name
...
+		}
+		return nil
+	})
+	if err != nil {
+		return "", 0, errors.Capture(err)
+	}
+	kind, err := charmresource.ParseType(output.Kind)
+	if err != nil {
+		return "", 0, errors.Errorf("parsing resource type %q: %w", output.Kind, err)
+	}
```
Comment (SimonRichardson) [inline domain/resource/state/resource.go]: This should be in the service.

File: domain/resource/state/resource.go [hunk 4]
```diff
@@ -2507,3 +2561,94 @@ WHERE  name = $applicationNameAndID.name
...
+
+	stmt, err := st.Prepare(`
+SELECT found AS &existsResult.found
+FROM (
+    SELECT EXISTS (
+        SELECT 1
+        FROM application_resource
+        WHERE resource_uuid = $localUUID.uuid
+    ) AS found
+)
```
Comment (SimonRichardson) [inline domain/resource/state/resource.go:2592]:
```suggestion
SELECT COUNT(*) 
FROM application_resource
WHERE resource_uuid = $localUUID.uuid
```

If you use count, instead of a subselect you can also just check application not found once.

File: domain/resource/state/resource.go [hunk 5]
```diff
@@ -2507,3 +2561,94 @@ WHERE  name = $applicationNameAndID.name
...
+		if errors.Is(queryErr, sqlair.ErrNoRows) {
+			return applicationerrors.ApplicationNotFound
+		} else if queryErr != nil {
+			return queryErr
+		}
+		if !output.Found {
+			return applicationerrors.ApplicationNotFound
+		}
+		return nil
+	})
```
Comment (SimonRichardson) [inline domain/resource/state/resource.go:2607]: The output.Found would be better served outside of the transaction.

File: domain/resource/service/resource.go [hunk 6]
```diff
@@ -373,48 +412,47 @@ func (s *Service) StoreResource(
...
 	args resource.StoreResourceArgs,
-) error {
-	return s.storeResource(ctx, args, true)
+) (coreresource.Resource, error) {
+	if err := args.Validate(); err != nil {
+		return coreresource.Resource{}, errors.Capture(err)
+	}
+
+	if err := s.st.VerifyApplicationExistsForResource(ctx, args.ResourceUUID); err != nil {
+		return coreresource.Resource{}, errors.Errorf("application not found: %w", err)
```
Comment (SimonRichardson) [inline domain/resource/service/resource.go]: This will print `application not found: application not found`.

File: apiserver/internal/handlers/resources/resourcemigration.go [hunk 7]
```diff
@@ -154,20 +154,14 @@ func (h *resourcesMigrationUploadHandler) processPost(
 	// body matches the hash and size in the headers. However, there is a bug
 	// for container resources exported from 3.6 where the hash the header does
 	// not match the hash in the body. For this reason, we do not check it here.
-
-	err = resourceService.StoreResource(ctx, resource.StoreResourceArgs{
+	return resourceService.StoreResource(ctx, resource.StoreResourceArgs{
```
Comment (gfouillet) [inline apiserver/internal/handlers/resources/resourcemigration.go:157]: **question:** Removing the capture remove this callsite from the potential error stack. Is it what we want ?

File: domain/resource/service/resource.go [hunk 8]
```diff
@@ -373,48 +412,47 @@ func (s *Service) StoreResource(
...
-	}
-
-	res, err := s.st.GetResource(ctx, args.ResourceUUID)
+	resName, resType, err := s.st.GetResourceNameAndType(ctx, args.ResourceUUID)
 	if err != nil {
 		return errors.Errorf("getting resource: %w", err)
 	}
 
-	store, err := s.resourceStoreGetter.GetResourceStore(ctx, res.Type)
+	// Validate app exists
```
Comment (gfouillet) [inline domain/resource/service/resource.go]: **question:** I don't see what imply this comment (does the resourceGetter validate the application existence ? is it some code logic missing ?)

File: domain/resource/state/resource.go (hunk 4 above)
Comment (hmlanigan) [reply domain/resource/state/resource.go:2592]: exists is more efficient as it stops when 1 is hit.

File: apiserver/internal/handlers/resources/resourcemigration.go (hunk 7 above)
Comment (hmlanigan) [reply apiserver/internal/handlers/resources/resourcemigration.go:157]: The caller adds the Capture, as does the service. There is only one caller.

File: domain/resource/types.go [hunk 9]
```diff
@@ -71,6 +74,25 @@ type StoreResourceArgs struct {
 	Fingerprint charmresource.Fingerprint
 }
 
+func (a StoreResourceArgs) Validate() error {
```
Comment (SimonRichardson) [inline domain/resource/types.go:79]: Add comment.
