### PR TITLE
fix(charmrevisionner): refresh timer incorrectly reset on model-config change

### LINKED ISSUE #20638: charmrevisioner may not run if the config change daily
### Description

The charm revisioner may not be triggered if the configuration is regularly updated. 

#### Details

This select is incorrect:

https://github.com/juju/juju/blob/8ffc0b8b3249954069223f25f4c26ad428b7ff83/internal/worker/charmrevisioner/worker.go#L247-L309

To be more precise this pattern:

```go
select {
     // ...
     case <-w.config.Clock.After(jitter(w.config.Period)):
          // update charms
     case changes, ok := <-configWatcher.Changes():
          // update config
}
```

will cause the update code being delayed every tome the config will get an update, due to the way of `select` works; Each time the select will be evaluated, the method in the cases will be evaluated to retrieve the underlying channel:

* `<-w.config.Clock.After(jitter(w.config.Period))` will create a new channel which trigger after the period.

This mean that each time we got a config change, the update will be delayed.

The period is defined here:

https://github.com/juju/juju/blob/9d060c9cbc87670a0bd3dca2035ac71225da939d/cmd/jujud-controller/agent/machine.go#L709

Which means that if we got a config change once every 24h, we would never update the charm.

### Juju version

4.0-beta6

### Cloud

_No response_

### Expected behaviour

Updating configuration shouldn't refresh the update charm interval.

### Reproduce / Test

* Reduce the charm refresh interval to a more convenient convenient period and rebuild
* While observing the debug log, trigger model config changes
* No log showing that a charm update has been triggered unless we stop triggering config changes.

### Notes & References

* It is a two line changes, but will require a bit of works on unit tests, it is why I raised an issue.
* The right approach is to create the timer outside the loop and use a reset once the update is done.

```go
updateTimer :=  w.config.Clock.NewTimer(jitter(w.config.Period))
for{
  select {
       // ...
       case <-updateTimer.Chan():
            // update charms
            updateTimer.Reset(jitter(w.config.Period))
       case changes, ok := <-configWatcher.Changes():
            // update config
  }
}
```

For references, check the implementation of the operationpruner:

* https://github.com/juju/juju/blob/main/internal/worker/operationpruner/worker.go
* https://github.com/juju/juju/blob/main/internal/worker/operationpruner/worker_test.go

### PR DESCRIPTION
**Pull request by gfouillet**
The charmrevisioner worker used `Clock.After()` inside a select statement, causing the timer to reset on every config change. With a 24h update period and daily config changes, charm updates would never execute.

This PR fixes this behavior and add tests to enforce the correct one.

### Before
```go
for {
    select {
    case <-w.config.Clock.After(jitter(w.config.Period)):  // Creates new timer every iteration
        // update charms with 5 duplicate timer reset calls
    case changes := <-configWatcher.Changes():
        // process config
    }
}
```

### After
```go
updateTimer := w.config.Clock.NewTimer(jitter(w.config.Period))
defer updateTimer.Stop()

for {
    select {
    case <-updateTimer.Chan():
        w.processUpdate(ctx, charmhubClient)
        updateTimer.Reset(jitter(w.config.Period))  // Single reset call
    case changes := <-configWatcher.Changes():
        // process config (timer unaffected)
    }
}
```

As a fly-by, it removes the generated Clock mock in favor of more reliable testclock.Clock.

> ![NOTE]
> 
> This PR was partially done by copilot to test its abilities. However, I updated a lot of things manually in unit tests to achieve the right quality (especially verifying that the fetch is triggered several time and isn't effected by modelconfig changes).
>
> related Copilot PR is available on my personal repo: https://github.com/gfouillet/juju/pull/3

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- ~Integration tests, with comments saying what you're testing~
- ~doc.go added or updated in changed packages~

## QA steps

**Note:** Modify the default charm revision update interval to make testing faster, unless you want to wait ~24 hours between each update check.

In `cmd/jujud-controller/agent/machine.go` at line 720, temporarily change:
```go
CharmRevisionUpdateInterval:   24 * time.Hour,
```
to:
```go
CharmRevisionUpdateInterval:   2 * time.Minute,
```

1. Bootstrap a controller and add a model
2. Deploy some charms to the model (e.g., `juju deploy postgresql`)
3. Enable DEBUG logging for the charmrevisioner worker:
   ```sh
   juju model-config -m <model-name> logging-config="juju.worker.charmrevisioner=DEBUG"
   ```

4. Watch the model logs to see the charm revision update cycle:
   ```sh
   juju debug-log -m <model-name> --include juju.worker.charmrevisioner
   ```

   You should see log messages like:
   ```
   machine-0: 14:30:00 DEBUG juju.worker.charmrevisioner worker created with period 2m0s
   machine-0: 14:30:00 DEBUG juju.worker.charmrevisioner watching model config for changes to charmhub URL
   machine-0: 14:32:00 DEBUG juju.worker.charmrevisioner 2m0s elapsed, performing work
   machine-0: 14:32:01 DEBUG juju.worker.charmrevisioner revisions fetched for N applications
   ```

5. While the worker is running, make frequent model config changes (that don't affect charmhub URL):
   ```sh
   juju model-config -m <model-name> default-series=jammy
   juju model-config -m <model-name> default-series=focal
   juju model-config -m <model-name> default-series=jammy
   # Repeat several times within the 2-minute window
   ```

6. Verify that despite the config changes, the charm revision checks still occur every 2 minutes (or whatever interval you set). The timer should NOT reset when config changes occur.

7. The log should continue showing periodic updates at the expected interval:
   ```
   machine-0: 14:34:00 DEBUG juju.worker.charmrevisioner 2m0s elapsed, performing work
   machine-0: 14:36:00 DEBUG juju.worker.charmrevisioner 2m0s elapsed, performing work
   ```

**Expected behavior:** The `processUpdate` function is called at regular intervals regardless of how frequently non-charmhub config changes occur.

**Bug behavior (before fix):** Config changes would reset the timer, potentially preventing charm revision updates from ever running if changes occur frequently enough.

## Documentation changes

No user-facing documentation changes required. This is an internal worker bug fix.

## Links

**Issue:** Fixes #20638.

**Jira card:** [JUJU-8825](https://warthogs.atlassian.net/browse/JUJU-8825)

[JUJU-8825]: https://warthogs.atlassian.net/browse/JUJU-8825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: internal/worker/charmrevisioner/worker_test.go [hunk 1]
```diff
@@ -464,7 +553,7 @@ func (s *WorkerSuite) TestFetchInfoInvalidResponseLength(c *tc.C) {
 	}}, nil)
 
 	w := s.newWorker(c)
-	defer workertest.DirtyKill(c, w)
```
Comment (SimonRichardson) [inline internal/worker/charmrevisioner/worker_test.go:467]: These should all be kept as DirtyKill. If the test fails we don't really care about the state of the worker we just want it dead.

Comment (gfouillet) [reply internal/worker/charmrevisioner/worker_test.go:467]: Make sense, thanks.

**Comment by hpidcock** [comment]
Consider improving the PR title, e.g.

`fix: charmrevisioner refresh timer incorrectly reset on model-config change`
