### PR TITLE
fix(secret): allow RoleManage to satisfy RoleView access queries

### LINKED ISSUE #21457: Juju 4.0.1: Cannot deploy cluster PostgreSQL K8s. Second+ unit ops.model.ModelError: ERROR cannot access "aaabbbccc..."
### Description

Hi,

The following command works well on Juju 3.6.12 but fails on Juju 4.0.1 (rev33424 from 4.0/edge, 4.0.1-70f1b14):

```
juju deploy postgresql-k8s --channel 14/edge/juju4 --trust --base ubuntu@22.04 -n 3
```

Actual results:
```
ubuntu@juju401edge:~$ juju status
Model  Controller  Cloud/Region  Version  Timestamp
test4  ck8s        ck8s          4.0.1    22:43:04+01:00

App                  Version  Status   Scale  Charm                Channel        Rev  Address  Exposed  Message
postgresql-k8s                waiting      3  postgresql-k8s       14/edge/juju4  710           no       waiting for units to settle down

Unit                    Workload  Agent  Address     Ports          Message
postgresql-k8s/0*       active    idle   10.1.0.15   5432,8008/tcp  Primary (degraded)
postgresql-k8s/1        error     idle   10.1.0.247  5432,8008/tcp  hook failed: "config-changed"
postgresql-k8s/2        error     idle   10.1.0.162  5432,8008/tcp  hook failed: "config-changed"
```

It sounds similar to https://github.com/juju/juju/issues/21344 (but for K8s).

### Juju version

4.0.1

### Cloud

Kubernetes

### Expected behaviour

Expected results: proper and successful deployment for 4.0.1 (like on Juju 3.6).

### Reproduce / Test

See above

### Notes & References

Logs:
```
unit-postgresql-k8s-2: 22:41:06 ERROR unit.postgresql-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3637, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-postgresql-k8s-2/secret-get', '--label', 'database-peers.postgresql-k8s.app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/charm.py", line 2554, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 356, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 486, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 421, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 465, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 924, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 1030, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1153, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/charm.py", line 700, in _on_config_changed
    self._validate_config_options()
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1153, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/charm.py", line 2113, in _validate_config_options
    not in self.postgresql.get_postgresql_text_search_configs()
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/charm.py", line 452, in postgresql
    password=self.get_secret(APP_SCOPE, f"{USER}-password"),
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1153, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/charm.py", line 387, in get_secret
    if result := self.peer_relation_data(scope).fetch_my_relation_field(peers.id, key):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1732, in fetch_my_relation_field
    if relation_data := self.fetch_my_relation_data([relation_id], [field], relation_name):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1721, in fetch_my_relation_data
    data[relation.id] = self._fetch_my_specific_relation_data(relation, fields)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 656, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2613, in _fetch_my_specific_relation_data
    self.component, self.local_secret_fields, relation, fields
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2235, in local_secret_fields
    self.static_secret_fields if self.static_secret_fields else self.current_secret_fields
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2259, in current_secret_fields
    if content := self._get_group_secret_contents(relation, group):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2600, in _get_group_secret_contents
    result = super()._get_group_secret_contents(relation, group, secret_fields)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1452, in _get_group_secret_contents
    if (secret := self._get_relation_secret(relation.id, group)) and (
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 628, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2587, in _get_relation_secret
    return self.secrets.get(
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 934, in get
    if secret.meta:
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 764, in meta
    self._secret_meta = self._model.get_secret(label=self.label)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 325, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 4023, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 3639, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR cannot access "d4su25vmp25c765nk4fg-1"

unit-postgresql-test-app-0: 22:41:06 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-postgresql-k8s-2: 22:41:06 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

### PR DESCRIPTION
**Pull request by nvinuesa**
When querying for secrets accessible by a subject with RoleView access in ListGrantedSecretsForBackend, secrets where the subject has RoleManage were not being returned. This caused secondary (non-leader) units of K8s applications to fail with "cannot access" errors when trying to read application-owned secrets.

The issue occurred because:
- Application-owned secrets grant RoleManage to the owner application
- Non-leader units query for secrets with RoleView access
- The query used exact match (role_id = X) instead of (role_id >= X)
- Since RoleManage (2) != RoleView (1), secrets were not returned

This fix changes the query to use >= comparison, so RoleManage (which inherently includes view permissions) satisfies RoleView requirements.

## QA steps

The steps to reproduce described on https://github.com/juju/juju/issues/21457 should pass, however we currently hit another issue before being able to fully verify the bugfix:
```
./logsink.log:{"model-uuid":"7fe93481-34ff-4c68-8178-46810674acdf","timestamp":"2026-01-08T09:54:28.13957183Z","entity":"controller-0","level":"ERROR","module":"juju.worker.dependency","location":"/home/nicolas/go/pkg/mod/github.com/juju/worker/v4@v4.3.0/dependency/engine.go:709","message":"\"storage-provisioner\" manifold worker returned unexpected error: panic resulted in: duplicate key {unit-postgresql-k8s-2 filesystem-2}"}
./logsink.log:{"model-uuid":"7fe93481-34ff-4c68-8178-46810674acdf","timestamp":"2026-01-08T09:54:36.920545705Z","entity":"controller-0","level":"ERROR","module":"juju.worker.dependency","location":"/home/nicolas/go/pkg/mod/github.com/juju/worker/v4@v4.3.0/dependency/engine.go:709","message":"\"storage-provisioner\" manifold worker returned unexpected error: panic resulted in: duplicate key filesystem-0"}
```

## Links

**Issue:** Fixes #21457.

**Jira card:** [JUJU-8986](https://warthogs.atlassian.net/browse/JUJU-8986)

[JUJU-8986]: https://warthogs.atlassian.net/browse/JUJU-8986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/secret/state/state.go [hunk 1]
```diff
@@ -2963,7 +2963,7 @@ FROM   secret_metadata sm
 JOIN   secret_revision rev ON rev.secret_id = sm.secret_id
 JOIN   secret_value_ref svr ON svr.revision_uuid = rev.uuid
 JOIN   v_secret_permission sp ON sp.secret_id = sm.secret_id
-WHERE  sp.role_id = $secretAccessor.role_id
+WHERE  sp.role_id >= $secretAccessor.role_id
```
Comment (hpidcock) [inline domain/secret/state/state.go]: This is now business logic, we should instead pass in a slice of roles.

File: domain/secret/state/state.go
Comment (hpidcock) [inline domain/secret/state/state.go]: We need to change the role argument to be a slice of roles, so that we don't perform business logic in the state layer.

File: domain/secret/state/state.go [hunk 2]
```diff
@@ -2963,7 +2963,7 @@ FROM   secret_metadata sm
 JOIN   secret_revision rev ON rev.secret_id = sm.secret_id
 JOIN   secret_value_ref svr ON svr.revision_uuid = rev.uuid
 JOIN   v_secret_permission sp ON sp.secret_id = sm.secret_id
```
Comment (gfouillet) [inline domain/secret/state/state.go]: **suggestion:** This is a suggestion because not linked to the bug.

There is no need here to use the view `v_secret_permission`, since we are using only plain fields from the table `secret_permission`. 

Let's avoid useless compute load by just removing the `v_` prefix.

**Review by gfouillet — COMMENTED** [review]
Harry comments are mandatory and implies some change in the service layer so I can't approve as is. However I have an unrelated suggestion.

File: domain/secret/state/state.go (hunk 1 above)
Comment (nvinuesa) [reply domain/secret/state/state.go]: Ah yes indeed, good point. Done in 3c8b5878367f68c5daedfff77dab7bcdce6ad297.

File: domain/secret/state/state.go
Comment (nvinuesa) [reply domain/secret/state/state.go]: Answered above.

File: domain/secret/state/state.go (hunk 2 above)
Comment (nvinuesa) [reply domain/secret/state/state.go]: Done in cc2d9ab3c55c383bd1a4152007861dc3c3269cf6.

File: domain/secret/service/consume.go [hunk 3]
```diff
@@ -145,5 +145,23 @@ func (s *SecretService) ListGrantedSecretsForBackend(
...
+	switch role {
+	case secrets.RoleView:
+		// Manage implies view, so include both.
+		return []domainsecret.Role{domainsecret.RoleView, domainsecret.RoleManage}
+	case secrets.RoleManage:
+		return []domainsecret.Role{domainsecret.RoleManage}
+	default:
+		return nil
+	}
 }
```
[the remark this answers is not in the document]
Comment (nvinuesa) [reply domain/secret/service/consume.go:169]: Good robot, added tests in 27192d55dc.

File: domain/secret/state/state.go [hunk 4]
```diff
@@ -2962,19 +2963,22 @@ SELECT (sm.secret_id) AS (&secretInfo.*),
...
 JOIN   secret_revision rev ON rev.secret_id = sm.secret_id
 JOIN   secret_value_ref svr ON svr.revision_uuid = rev.uuid
-JOIN   v_secret_permission sp ON sp.secret_id = sm.secret_id
-WHERE  sp.role_id = $secretAccessor.role_id
+JOIN   secret_permission sp ON sp.secret_id = sm.secret_id
+LEFT JOIN unit suu ON sp.subject_uuid = suu.uuid AND sp.subject_type_id = $secretAccessorType.unit_type_id
+LEFT JOIN application sua ON sp.subject_uuid = sua.uuid AND sp.subject_type_id = $secretAccessorType.app_type_id
+WHERE  sp.role_id IN ($roles[:])
 AND    svr.backend_uuid = $secretBackendID.id
-AND    (subject_type_id = $secretAccessorType.unit_type_id AND subject_id IN ($units[:])
```
Comment (gfouillet) [inline domain/secret/state/state.go:3099]: Ok I got why we initially use the view, it was to figure out the subject_id which is different between each types. This version is a bit leaner, I could have been ok with just putting explicit `sp.subject_id` to avoid the same mistake i did in review.

Thanks.

File: domain/secret/service/consume.go [hunk 5]
```diff
@@ -145,5 +145,23 @@ func (s *SecretService) ListGrantedSecretsForBackend(
...
+	roles := expandRolesToMatch(role)
+
+	return s.secretState.ListGrantedSecretsForBackend(ctx, backendID, accessors, roles)
+}
+
+// expandRolesToMatch returns a slice of roles that satisfy the requested role.
+// RoleManage implies RoleView, so requesting view access returns both view and manage.
+func expandRolesToMatch(role secrets.SecretRole) []domainsecret.Role {
+	switch role {
+	case secrets.RoleView:
```
Comment (gfouillet) [inline domain/secret/service/consume.go]: **issue:** If you have `RoleRotate` this code will not have the expected behavior.

To me, the right specification here is:

* `RoleNone` should yield an empty array (it is not a db valid value anyway) => ✔️ 
* `RoleManage` implies that the owner has full right on a secret. Thus `RoleView` and `RoleRotate` should yield also secret where `RoleManage` has been granted to a owner.
* Other roles are exclusive.

So the right code would be to check that the role isn't RoleNone (and return an empty list if it is the case), then check if the role is Manage (and return a single element list with the role).
Otherwise, return a list that append the Manage role to the role in args.


If this is not the expected behavior (ie, if Roles are independant, or Manage isn't meant to include ANY OTHER ROLES, the right approach would be to pass the list of role in the service method and handle everything in the caller.

Comment (nvinuesa) [reply domain/secret/service/consume.go]: > Otherwise, return a list that append the Manage role to the role in args.

I think this is wrong. Looking at rbac.go:
```
func (r SecretRole) value() int {
	switch r {
	case RoleView:
		return 1
	case RoleRotate:
		return 2
	case RoleManage:
		return 3
	default:
		return -1
	}
}

func (r SecretRole) Allowed(wanted SecretRole) bool {
	v1, v2 := r.value(), wanted.value()
	if v1 < 0 || v2 < 0 {
		return false
	}
	return v1 >= v2
}
```
So it's basically `manage`>`rotate`>`view`.

In any case the problem is that we haven't defined rotate in the domain (it's beyond this bugfix anyways), so I'm not sure expanding rotate -> manage is the correct approach. 
It should maybe be expanding rotate -> view,manage.

Comment (gfouillet) [reply domain/secret/service/consume.go]: So manage imply Rotate and view, Rotate imply view, 

So the complete expand would be:
*  view => {Manage, Rotate, View}
*  Rotate => {Manage, Rotate}
*  Manage => {Manage}

Comment (nvinuesa) [reply domain/secret/service/consume.go]: > Rotate => {Manage, Rotate}

NO.

On the secret domain we only have:
```
const (
	RoleNone Role = iota
	RoleView
	RoleManage
)
```
Furthermore `secrets.RoleRotate` is never stored in the DB.

The only thing we can do is map `secrets.RoleRotate` to one or more domain roles. 
Although this doesn't make much sense for listing (or viewing) the secrets, what I can do is to map `secrets.RoleRotate`-> `[]domainsecret.Role{domainsecret.RoleView, domainsecret.RoleManage}`.

@wallyworld can you please verify this?

Comment (nvinuesa) [reply domain/secret/service/consume.go]: This is what I ended up doing (just to be defensive, since rotate is not modelled):
`secrets.RoleRotate`-> `[]domainsecret.Role{domainsecret.RoleView, domainsecret.RoleManage}`

File: domain/secret/service/consume.go [hunk 6]
```diff
@@ -145,5 +145,28 @@ func (s *SecretService) ListGrantedSecretsForBackend(
...
+	return s.secretState.ListGrantedSecretsForBackend(ctx, backendID, accessors, roles)
+}
+
+// expandRolesToMatch returns a slice of roles that satisfy the requested role.
+// The role hierarchy is: RoleManage > RoleRotate > RoleView.
+// Since RoleRotate is not stored in the database, only RoleManage can satisfy
+// rotate access queries. RoleManage implies both RoleRotate and RoleView.
+func expandRolesToMatch(role secrets.SecretRole) []domainsecret.Role {
+	switch role {
+	case secrets.RoleView, secrets.RoleRotate:
```
Comment (wallyworld) [inline domain/secret/service/consume.go]: Let's drop rotate (delete the go code). We only model "none', 'view', 'manage' in the db secret_role lookup table.
Nothing uses the rotate role. The concept for it got dropped in 3.6.

File: domain/secret/state/state_test.go [hunk 7]
```diff
@@ -3449,6 +3449,68 @@ func (s *stateSuite) TestListGrantedSecrets(c *tc.C) {
...
+	// Query with both RoleView and RoleManage (as the service layer would
+	// expand for a view request) - should return the secret.
+	result, err = s.state.ListGrantedSecretsForBackend(ctx, "backend-id", accessors, []domainsecret.Role{domainsecret.RoleView, domainsecret.RoleManage})
+	c.Assert(err, tc.ErrorIsNil)
+	c.Check(result, tc.DeepEquals, []*coresecrets.SecretRevisionRef{{
+		URI:        uri,
+		RevisionID: "revision-id",
+	}})
+
+	// Verify that a different application without any grants gets no results.
```
Comment (wallyworld) [inline domain/secret/state/state_test.go]: This could be a separate test

**Review by wallyworld — APPROVED** [review]
Logic looks ok. A could of small tasks.

File: domain/secret/state/state_test.go (hunk 7 above)
Comment (nvinuesa) [reply domain/secret/state/state_test.go]: Sure, good call. Done.

File: domain/secret/service/consume.go (hunk 6 above)
Comment (nvinuesa) [reply domain/secret/service/consume.go]: Oh good, I wasn't aware that this was dropped already. I removed it from core and from the tests that used as well.

File: domain/secret/service/consume.go (hunk 5 above)
Comment (nvinuesa) [reply domain/secret/service/consume.go]: @gfouillet as mentioned by @wallyworld this was removed, so I just cleaned up the code. We no longer have rotate.

**Review by gfouillet — APPROVED** [review]
Thanks.
