### PR TITLE
fix: wait for local storage mounts before starting jujud service

### LINKED ISSUE #21135: Juju-agent.service doesn't wait (Requires) for Juju Storage mounts (local-fs.target)
### Description

Hi,

This is a followup ticket after triaging [PostgreSQL issue](https://warthogs.atlassian.net/browse/DPE-8615?focusedCommentId=944776).

TL;DR: Juju sends `start` event before the Juju Storage mount points are mounted.
It creates internal races. While the proper way, IMHO, is to wait for all local-fs and networks targets to be fully and successfully mounted. Then and only then wakes up charm via juju-agent (in case of those target success only).

### Juju version

3.6.11

### Cloud

LXD

### Expected behaviour

Systemd juju-agent.service is currently starts After network only, ignoring mount targets state:
```
ubuntu@juju-3491b7-0:~$ systemctl cat jujud-machine-0.service
[Unit]
After=syslog.target
After=network.target
After=systemd-user-sessions.service
```

While expected behavior is (at least):
```
After=syslog.target
After=network.target
Requires=network.target
After=local-fs.target
Requires=local-fs.target
After=systemd-user-sessions.service
```

### Reproduce / Test
```
juju deploy postgresql --channel 16/stable # (revision 952)
# wait for deployment
lxc stop juju-3491b7-0 # LXD unit/machine ID
# wait for stop
lxc start juju-3491b7-0
```
AR: postgresql will be in state `(start) Data directory not attached`, then it will reboot several times and until Primary
ER: postgresql will be waked up with storage attached.

### Notes & References

https://github.com/canonical/postgresql-operator/issues/1250

### PR DESCRIPTION
**Pull request by wallyworld**
This is in response to [DPE-8615](https://warthogs.atlassian.net/browse/DPE-8615?focusedCommentId=944776)

When a lxd container or vm is restarted, the jujud agent can restart and run the start hook before all the storage is mounted. This affects the postgresql charm which wants to access storage in the start hook.

The fix is 2 fold:
1. update the jujud agent systemd conf file to come up after local-fs target
    we also add network target and optional lxd-agent target for completeness
2. add rootfs bind mounts and tmpfs mounts to fstab

The latter is needed so that the local-fs target accounts for all the required storage mounts.
Previously, only fstab entries for "managed" storage were added, ie filesystems created on block devices.

The workflow is to add fstab entries when storage is attached, and remove them when storage is detached.

Note: for all the cases, including rootfs and tmpfs, we were already removing fstab entries on detach. But for whatever reason, the entries weren't being added on attach.

The implementation here conforms with the approach already used by managed storage and relies on `systemd-fstab-generator` to translate fstab entries to native systemd units during boot, thus feeding the local-fs target dependency. 

## QA steps

`juju deploy postgresql --channel 16/stable --storage temp=tmpfs,100M`

```
$ cat /etc/fstab
/var/lib/juju/storage/rootfs/4/12 /var/snap/charmed-postgresql/common/data/archive none defaults,bind,nofail
/var/lib/juju/storage/rootfs/4/13 /var/snap/charmed-postgresql/common/var/lib/postgresql none defaults,bind,nofail
/var/lib/juju/storage/rootfs/4/14 /var/snap/charmed-postgresql/common/data/logs none defaults,bind,nofail
filesystem-4-15 /var/snap/charmed-postgresql/common/data/temp tmpfs size=100m,nofail
```

```
$ cat /etc/systemd/system/jujud-machine-4.service 
[Unit]
Description=juju agent for machine-4
Requires=network.target
Requires=local-fs.target
Wants=lxd-agent.target
After=syslog.target
After=network.target
After=local-fs.target
After=lxd-agent.target
After=systemd-user-sessions.service

[Service]
Environment="JUJU_DEV_FEATURE_FLAGS=actions-v2,developer-mode,image-metadata,secrets,secrets-stores"
LimitNOFILE=64000
ExecStart=/etc/systemd/system/jujud-machine-4-exec-start.sh
Restart=on-failure
TimeoutSec=300

[Install]
WantedBy=multi-user.target
```

Start and stop the lxd machine running postgresql and use `show-status-log postgresql/0` to see there's no longer a error related to unattached storage. 

## Links

**Issue:** Fixes #21135.

**Jira card:** [JUJU-8829](https://warthogs.atlassian.net/browse/JUJU-8829)

[DPE-8615]: https://warthogs.atlassian.net/browse/DPE-8615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JUJU-8829]: https://warthogs.atlassian.net/browse/JUJU-8829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: service/systemd/conf.go [hunk 1]
```diff
@@ -152,9 +152,34 @@ func serializeUnit(conf common.Conf) []*unit.UnitOption {
...
+		unitOptions = append(unitOptions, &unit.UnitOption{
+			Section: "Unit",
+			Name:    "Requires",
+			Value:   name,
+		})
+	}
+
+	wants := []string{
+		"lxd-agent.target",
+	}
```
Comment (adisazhar123) [inline service/systemd/conf.go:169]: would this still work for openstack deployments? they won't have `lxd-agent.target` i believe?

Comment (wallyworld) [reply service/systemd/conf.go:169]: `Wants` is an optional dependency, as opposed to `Requires`.
```
A weaker version of Requires=. Units listed in this option will be started if the configuring unit is. However, if the listed units fail to start or cannot be added to the transaction, this has no impact on the validity of the transaction as a whole
```

**Review by adisazhar123 — APPROVED** [review]
QA passes. Thanks!

I see the fstab entries.
```
cat /etc/fstab
/var/lib/juju/storage/rootfs/0/0 /var/snap/charmed-postgresql/common/data/archive none defaults,bind,nofail
/var/lib/juju/storage/rootfs/0/1 /var/snap/charmed-postgresql/common/var/lib/postgresql none defaults,bind,nofail
/var/lib/juju/storage/rootfs/0/2 /var/snap/charmed-postgresql/common/data/logs none defaults,bind,nofail
filesystem-0-3 /var/snap/charmed-postgresql/common/data/temp tmpfs size=100m,nofail
```
I see the unit dependencies.

```
cat /etc/systemd/system/jujud-machine-0.service

[Unit]
Description=juju agent for machine-0
Requires=network.target
Requires=local-fs.target
Wants=lxd-agent.target
After=syslog.target
After=network.target
After=local-fs.target
After=lxd-agent.target
After=systemd-user-sessions.service
...
```

And I don't see any errors after stopping and starting the lxd machine.

File: storage/provider/rootfs.go [hunk 2]
```diff
@@ -291,18 +293,84 @@ func (s *rootfsFilesystemSource) tryBindMount(source, target string) (bool, erro
...
+	// which describes the entry we want to create.
+	scanner := bufio.NewScanner(f)
+	for f != nil && scanner.Scan() {
+		line := scanner.Text()
+		fields := strings.Fields(line)
+		if len(fields) >= 2 &&
+			fields[0] == sourcePath &&
+			fields[1] == mountPoint {
+			addNewEntry = false
+			break
```
Comment (kian99) [inline storage/provider/rootfs.go]: Breaking early here means we won't create a full copy of the original `fstab` I think?
The best thing for clarity imo, would be to avoid scanning the file and creating a copy of the file in the same loop

File: storage/provider/rootfs_test.go [hunk 3]
```diff
@@ -182,9 +185,46 @@ func (s *rootfsSuite) TestAttachFilesystemsNoPathSpecified(c *gc.C) {
...
+func (s *rootfsSuite) createFsTab(c *gc.C, entries ...string) {
+	data := []byte(strings.Join(entries, "\n"))
+	err := os.WriteFile(filepath.Join(s.fakeEtcDir, "fstab"), data, 0644)
+	c.Assert(err, jc.ErrorIsNil)
+}
+
 func (s *rootfsSuite) TestAttachFilesystemsBind(c *gc.C) {
 	source := s.rootfsFilesystemSource(c)
 
+	existingFsTabEntry := "/src /dest none defaults,bind,nofail 0 0"
```
Comment (kian99) [inline storage/provider/rootfs_test.go]: We should test with multiple lines

**Review by CodingCookieRookie — APPROVED** [review]
QA passes for me too & LGTM thanks!

File: storage/provider/rootfs_test.go (hunk 3 above)
Comment (wallyworld) [reply storage/provider/rootfs_test.go]: Done, also added an extra test for where the entry exists

File: storage/provider/rootfs.go (hunk 2 above)
Comment (wallyworld) [reply storage/provider/rootfs.go]: Ah, the break was left over from then the code was copied and modified. Good pickup.
Removed the break

**Review by kian99 — APPROVED** [review]
