### PR TITLE
fix: deletion of user secrets on k8s models

### LINKED ISSUE #19784: deleting a user secret fails on k8s models
### Description

When deleting a user secret on k8s, the secret resource is not removed from the k8s namepace. 
There's also a client error
```
Unable to delete secret, got error: cannot ensure service account "user-9c14ce7b-1fb6-4648-b584-08e8f7989855@serviceaccount": ServiceAccount "user-9c14ce7b-1fb6-4648-b584-08e8f7989855@serviceaccount"
```

The juju logs show
```
controller-0: 09:17:43 ERROR juju.apiserver.client.secrets failed to delete secret "d0e7ddvmp25c7780fseg-1": secrets "d0e7ddvmp25c7780fseg-1" is forbidden: User "system:serviceaccount:dev-iam:model-dev-iam" cannot get resource "secrets" in API group "" in the namespace "dev-iam"
controller-0: 09:17:43 WARNING juju.secrets.provider.kubernetes error ensuring secret service account for "user-9c14ce7b-1fb6-4648-b584-08e8f7989855@serviceaccount": cannot ensure service account "user-9c14ce7b-1fb6-4648-b584-08e8f7989855@serviceaccount": ServiceAccount "user-9c14ce7b-1fb6-4648-b584-08e8f7989855@serviceaccount" is invalid: [metadata.name: Invalid value: "user-9c14ce7b-1fb6-4648-b584-08e8f7989855@serviceaccount": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "9c14ce7b-1fb6-4648-b584-08e8f7989855@serviceaccount": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
```

### Juju version

3.6.5

### Cloud

Kubernetes

### Expected behaviour

The secret should be deleted from the k8s namespace.

### Reproduce / Test

juju bootstrap microk8s
juju add-secret mine foo=bar
juju remove-secret mine

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by wallyworld**
When deleting secrets on a k8s model, a service account is used to enable the operation to proceed.
The tag of the entity which owns the secret is used to create the service account. When running the Cleanup operation for user secrets, the user tag of the authenticated user was being passed in instead of the model tag.

## QA steps

```
$ juju add-secret mine foo=bar
secret:d0jg427mp25c79d8c5b0
$ juju secrets
ID                    Name  Owner    Rotation  Revision  Last updated
d0jg427mp25c79d8c5b0  mine  <model>  never            1  2 seconds ago  
$ kubectl -n controller-test get secrets
NAME                            TYPE                                  DATA   AGE
controller-application-config   Opaque                                1      7m38s
controller-proxy                kubernetes.io/service-account-token   3      7m41s
controller-secret               Opaque                                2      7m40s
d0jg427mp25c79d8c5b0-1          Opaque                                1      20s
model-exec                      kubernetes.io/service-account-token   3      6m48s
$ juju remove-secret d0jg427mp25c79d8c5b0
$ kubectl -n controller-test get secrets
NAME                            TYPE                                  DATA   AGE
controller-application-config   Opaque                                1      7m52s
controller-proxy                kubernetes.io/service-account-token   3      7m55s
controller-secret               Opaque                                2      7m54s
model-exec                      kubernetes.io/service-account-token   3      7m2s
```

## Links

**Issue:** Fixes #19784.

### CODE REVIEW

File: apiserver/common/secrets/secrets.go [hunk 1]
```diff
@@ -745,7 +745,8 @@ func newCachedBackendGetter(adminConfigGetter BackendAdminConfigGetter) (*cached
 
 // removeSecretFromExternal removes the specified secret from its respective secret backends.
```
Comment (hpidcock) [inline apiserver/common/secrets/secrets.go:746]:
```suggestion
// removeUserSecretFromExternal removes the specified secret from its respective secret backends.
```

**Review by hpidcock — APPROVED** [review]
Thank-you. Can we add a shell test or modify an existing one (for 4.0's benefit)?

**Review by ycliuhw — APPROVED** [review]
LGTM, thanks for fixing this!
