### PR TITLE
fix: grouping ports issue

### LINKED ISSUE #22076: Open ports grouped incorrectly
### Description

When showing the open ports via, e.g., `juju status`, some groups of ports are displayed incorrectly. The root cause is the ports are sorted lexicographically, not numerically, when they are processed by the `printPorts` function: https://github.com/juju/juju/blob/main/cmd/juju/status/output_tabular.go#L319-L321

For example, if a unit has ports 9998/tcp, 9999/tcp, 10000/tcp, and 10001/tcp open, then `juju status` will display this as `9998-9999,10000-10001/tcp` rather than `9998-10001/tcp`.

### Juju version

3.6.19

### Cloud

_No response_

### Expected behaviour

Open ports should be grouped as contiguous blocks when displayed.

### Reproduce / Test

Deploy a unit of a charm that opens, e.g., TCP ports 9998, 9999, 10000, and 10001. Check the output of `juju status` and see the grouping is `9998-9999,10000-10001/tcp` instead of `9998-10001/tcp`.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by Deadinside101**
Fix port grouping in `juju status`.

Open ports were being sorted as strings before grouping, which breaks ranges that cross a digit boundary, like `9999` → `10000`. This change sorts ports numerically first, so contiguous ports are grouped correctly in the output.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Go unit tests, with comments saying what you're testing
- [x] Integration tests, with comments saying what you're testing

## QA steps

1. Run the unit tests for the status package.
2. Check that `juju status` now groups ports like `9998-10001/tcp` instead of splitting them at `10000`.

## Links

**Issue:** Fixes #22076.

### CODE REVIEW

File: cmd/juju/status/output_tabular.go [hunk 1]
```diff
@@ -354,7 +386,7 @@ type OutputWriter interface {
 
 func printPorts(w OutputWriter, ps []string) {
 	sorted := append([]string(nil), ps...)
-	sort.Strings(sorted)
+	sortPorts(sorted)
```
Comment (hpidcock) [inline cmd/juju/status/output_tabular.go]: This is the correct way to fix this rather than implement logic that doesn't handle errors well or try to parse during a sort.
```go
	sorted := append([]string(nil), ps...)
	sort.Sort(sortablePorts(sorted))
```

Comment (Deadinside101) [reply cmd/juju/status/output_tabular.go]: @hpidcock 
Yes, this will work and it's much better, I have applied this

File: cmd/juju/status/output_tabular_test.go [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+			},
+		},
+	}
+
+	buff := &bytes.Buffer{}
+	err := formatOneline(buff, false, fs, func(out io.Writer, format, uName string, u unitStatus, level int) {
+		fmt.Fprintf(out, format, uName, "running", level)
+	})
+	c.Assert(err, jc.ErrorIsNil)
+	log.Println("RAW OUTPUT:", buff.String())
```
Comment (SimonRichardson) [inline cmd/juju/status/output_tabular_test.go]: Delete the log line please.

Comment (Deadinside101) [reply cmd/juju/status/output_tabular_test.go]: @SimonRichardson 
Done

**Comment by SimonRichardson** [comment]
@Deadinside101 you need to pass the CLA check and your commits should be [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

File: cmd/juju/status/output_tabular_test.go [hunk 3]
```diff
@@ -0,0 +1,49 @@
+// Copyright 2015 Canonical Ltd.
```
Comment (SimonRichardson) [inline cmd/juju/status/output_tabular_test.go]: Tiny thing, this should be the correct year.

```suggestion
// Copyright 2026 Canonical Ltd.
```

**Review by SimonRichardson — APPROVED** [review]

**Review by wallyworld — APPROVED** [review]
