### PR TITLE
fix(removal): clean up FK references on app, unit, and relation delete

### LINKED ISSUE #21811: CMR removal errors
### Description

The following errors arise when removing a CMR application (the consuming one in this case):
```
juju.database constraint error running relation deletion: FOREIGN KEY constraint failed - running queries:
 BEGIN

SELECT a.uuid AS _sqlair_0
FROM   relation AS r
JOIN   relation_endpoint AS re ON r.uuid = re.relation_uuid
JOIN   application_endpoint AS ae ON re.endpoint_uuid = ae.uuid
JOIN   application AS a ON ae.application_uuid = a.uuid
JOIN   charm AS c ON a.charm_uuid = c.uuid
JOIN   charm_source AS cs ON c.source_id = cs.id
WHERE  r.uuid = @sqlair_0
AND    cs.name = 'cmr'

DELETE FROM relation_network_egress
WHERE  relation_uuid = @sqlair_0

DELETE FROM application_remote_offerer_relation_macaroon
WHERE  relation_uuid = @sqlair_0

DELETE FROM relation_application_setting
WHERE  relation_endpoint_uuid IN (
    SELECT uuid FROM relation_endpoint WHERE relation_uuid = @sqlair_0
)

DELETE FROM relation_application_settings_hash
WHERE  relation_endpoint_uuid IN (
    SELECT uuid FROM relation_endpoint WHERE relation_uuid = @sqlair_0
)
DELETE FROM relation_endpoint WHERE relation_uuid = @sqlair_0
DELETE FROM relation_unit_setting_archive WHERE relation_uuid = @sqlair_0
DELETE FROM relation_status WHERE relation_uuid = @sqlair_0

DELETE FROM secret_permission
WHERE  scope_type_id = 3
AND    scope_uuid = @sqlair_0
DELETE FROM relation WHERE uuid = @sqlair_0
```
but also:
```
 machine-0: 11:44:14 ERROR juju.database constraint error removing machine network: deleting net node in query "DELETE FROM net_node WHERE uuid = $node.uuid": FOREIGN KEY constraint failed - running queries:
   BEGIN

  SELECT life_id AS _sqlair_0
  FROM   machine
  WHERE  uuid = @sqlair_0;

  SELECT task_uuid AS _sqlair_0
  FROM   operation_machine_task
  WHERE  machine_uuid = @sqlair_0;
  DELETE FROM operation_action WHERE operation_uuid IN ()
  DELETE FROM operation_parameter WHERE operation_uuid IN ()
  DELETE FROM operation WHERE uuid IN ()

  SELECT life_id AS _sqlair_0
  FROM   machine_cloud_instance
  WHERE  machine_uuid = @sqlair_0;

  SELECT COUNT(*) AS _sqlair_0
  FROM machine_parent
  WHERE parent_uuid = @sqlair_0


  SELECT COUNT(*) AS _sqlair_0
  FROM unit
  JOIN machine ON machine.net_node_uuid = unit.net_node_uuid
  WHERE machine.uuid = @sqlair_0
  AND unit.life_id != 2


  SELECT SUM(count) AS _sqlair_0 FROM (
      SELECT    COUNT(*) AS count
      FROM      machine_filesystem mf
      WHERE     mf.machine_uuid = @sqlair_0
      UNION
      SELECT    COUNT(*) AS count
      FROM      storage_filesystem_attachment sfa
      JOIN      machine m ON m.net_node_uuid = sfa.net_node_uuid
      LEFT JOIN machine_filesystem mf ON mf.machine_uuid = m.uuid
      WHERE     m.uuid = @sqlair_1 AND
                mf.filesystem_uuid IS NULL
  )


  SELECT SUM(count) AS _sqlair_0 FROM (
      SELECT    COUNT(*) AS count
      FROM      machine_volume mv
      WHERE     mv.machine_uuid = @sqlair_0
      UNION
      SELECT    COUNT(*) AS count
      FROM      storage_volume_attachment sva
      JOIN      machine m ON m.net_node_uuid = sva.net_node_uuid
      LEFT JOIN machine_volume mv ON mv.machine_uuid = m.uuid
      WHERE     m.uuid = @sqlair_1 AND
                mv.volume_uuid IS NULL
  )

  DELETE FROM machine_manual WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_agent_version WHERE machine_uuid = @sqlair_0
  DELETE FROM instance_tag WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_status WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_cloud_instance_status WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_cloud_instance WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_container_type WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_platform WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_agent_version WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_constraint WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_requires_reboot WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_lxd_profile WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_agent_presence WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_container_type WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_ssh_host_key WHERE machine_uuid = @sqlair_0
  DELETE FROM machine_parent WHERE machine_uuid = @sqlair_0
  DELETE FROM block_device_link_device WHERE machine_uuid = @sqlair_0
  DELETE FROM block_device WHERE machine_uuid = @sqlair_0

  SELECT net_node_uuid AS _sqlair_0
  FROM   machine
  WHERE  uuid = @sqlair_0


  DELETE FROM machine
  WHERE uuid = @sqlair_0;


  DELETE FROM provider_ip_address
  WHERE address_uuid IN (
      SELECT uuid FROM ip_address WHERE net_node_uuid = @sqlair_0
  )
  DELETE FROM ip_address WHERE net_node_uuid = @sqlair_0

  SELECT uuid AS _sqlair_0
  FROM   link_layer_device
  WHERE  net_node_uuid = @sqlair_0
  DELETE FROM link_layer_device_parent WHERE device_uuid IN (@sqlair_0, @sqlair_1) OR parent_uuid IN (@sqlair_2, @sqlair_3)
  DELETE FROM provider_link_layer_device WHERE device_uuid IN (@sqlair_0, @sqlair_1)
  DELETE FROM link_layer_device_dns_domain WHERE device_uuid IN (@sqlair_0, @sqlair_1)
  DELETE FROM link_layer_device_dns_address WHERE device_uuid IN (@sqlair_0, @sqlair_1)
  DELETE FROM link_layer_device WHERE uuid IN (@sqlair_0, @sqlair_1)
  DELETE FROM net_node_fqdn_address WHERE net_node_uuid = @sqlair_0
  DELETE FROM net_node_hostname_address WHERE net_node_uuid = @sqlair_0
  DELETE FROM net_node WHERE uuid = @sqlair_0
```
The machine eventually gets removed though.

### Juju version

4.0.1

### Cloud

LXD

### Expected behaviour

When removing a consuming application we should see no foreign key errors in the controller logs.

### Reproduce / Test

Deploy a and relate cross-models:
```
$ juju add-model offering
$ juju deploy juju-qa-dummy-source --config token=abc
$ juju offer dummy-source:sink
$ juju add-model consuming
$ juju deploy juju-qa-dummy-sink
$ juju relate dummy-sink admin/offering.dummy-source
```
Once it's stable, remove dummy-sink. There should be no errors on the controller logs and the application, unit and machine (because it was the last unit on it) should be correctly removed.
```
$ juju remove-application dummy-sink
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
This patch resolves two different batch of issues that arise when trying to remove an application which is related to another cross-model.

The first one fixes foreign key errors related to the relation removal itself. This is the first commit:
Ensure all foreign key references are deleted when removing
applications,
units, or relations to prevent constraint failures. Add regression tests
for deletion relation, and network records.

The second batch of fixes can be seen only after the first batch of fixes is there, which is the removal of the machine (in this case because there are no more units left):
Prevent FOREIGN KEY constraint failures on net_node deletion by ensuring
all unit rows (including dead-but-not-yet-deleted ones) are gone before
a machine's net_node is removed. Dead units still hold a net_node_uuid
FK reference, so DeleteMachine now returns RemovalJobIncomplete when any
unit references the machine's net_node, allowing the machine removal job
to retry after the unit removal job completes.

Also clean up net_node_fqdn_address and net_node_hostname_address rows
before deleting net_nodes in the machine, k8s cloud service, and CMR
synthetic unit removal paths.

Finally, the application removal now checks for units and relations being removed, independently from force being used or not.

## QA steps

Deploy a and relate cross-models:
```
$ juju add-model offering
$ juju deploy juju-qa-dummy-source --config token=abc
$ juju offer dummy-source:sink
$ juju add-model consuming
$ juju deploy juju-qa-dummy-sink
$ juju relate dummy-sink admin/offering.dummy-source
```
Once it's stable, remove dummy-sink. There should be no errors on the controller logs and the application, unit and machine (because it was the last unit on it) should be correctly removed.
```
$ juju remove-application dummy-sink
```

## Links

**Issue:** Fixes #21811.

**Jira card:** [JUJU-9243](https://warthogs.atlassian.net/browse/JUJU-9243)

[JUJU-9243]: https://warthogs.atlassian.net/browse/JUJU-9243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/removal/state/model/application.go [hunk 1]
```diff
@@ -383,6 +383,10 @@ WHERE  uuid = $entityUUID.uuid;`, applicationUUID)
 			return errors.Errorf("deleting application resources: %w", err)
 		}
 
+		if err := st.deleteApplicationRelations(ctx, tx, aUUID); err != nil {
+			return errors.Errorf("deleting application relations: %w", err)
+		}
```
Comment (jack-w-shaw) [inline domain/removal/state/model/application.go]: relations are entities with their own life and removal process. They should be removed via the cascade, not here right? We should return an `Incomplete` error here right?

File: domain/removal/state/model/application.go [hunk 2]
```diff
@@ -629,6 +659,35 @@ WHERE  uuid = $entityUUID.uuid`, appID)
 	return nil
 }
 
+func (st *State) deleteApplicationRelations(ctx context.Context, tx *sqlair.TX, aUUID string) error {
```
Comment (manadart) [inline domain/removal/state/model/application.go]: This is polluting the way that removals should be thought about. It is the same with `deleteApplicationUnits` that is already called for applications.

We should not cross-cut these concerns.

If an application has had its removal invoked with `--force`, it will already have cascaded forced removal jobs to its relations and units.

We should not be strafing around random deletions in the removal domain, for concerns not owned by the entity being removed.

It should not be possible for these FKs to be things blocking application removal.

File: domain/removal/state/model/machine.go [hunk 3]
```diff
@@ -802,6 +829,27 @@ WHERE  net_node_uuid = $node.uuid`
...
+
+	for _, query := range deleteNetNodeAddresses {
+		stmt, err := st.Prepare(query, node{})
+		if err != nil {
+			return errors.Capture(err)
+		}
+
+		if err := tx.Query(ctx, stmt, netNodeUUIDRec).Run(); err != nil {
+			removeErr := errors.Errorf("deleting net node addresses in query %q: %w", query, err)
+			if database.IsErrConstraintForeignKey(err) {
```
Comment (jack-w-shaw) [inline domain/removal/state/model/machine.go]: When would we see a foreign key constraint violation here?

File: domain/removal/state/model/relation.go [hunk 4]
```diff
@@ -302,6 +302,42 @@ AND    scope_uuid = $entityUUID.uuid`, relationUUID)
...
+)`, relationUUID)
+	if err != nil {
+		return errors.Errorf("preparing remote consumer deletion: %w", err)
+	}
+
+	offerConnectionStmt, err := st.Prepare(
+		"DELETE FROM offer_connection WHERE remote_relation_uuid = $entityUUID.uuid", relationUUID)
+	if err != nil {
+		return errors.Errorf("preparing offer connection deletion: %w", err)
+	}
```
Comment (jack-w-shaw) [inline domain/removal/state/model/relation.go]: Don't we have specific `removeRemoteRelation(Consumer|Offerer)` methods for this?

**Review by jack-w-shaw — DISMISSED** [review]

File: domain/removal/state/model/unit.go [hunk 5]
```diff
@@ -869,6 +869,9 @@ func (st *State) deleteForeignKeyUnitReferences(ctx context.Context, tx *sqlair.
 		"DELETE FROM unit_storage_directive WHERE unit_uuid = $entityUUID.uuid",
 		"DELETE FROM unit_agent_presence WHERE unit_uuid = $entityUUID.uuid",
 		"DELETE FROM secret_unit_consumer WHERE unit_uuid = $entityUUID.uuid",
+		"DELETE FROM relation_unit_setting WHERE relation_unit_uuid IN (SELECT uuid FROM relation_unit WHERE unit_uuid = $entityUUID.uuid)",
```
Comment (manadart) [inline domain/removal/state/model/unit.go]: The same goes for here. This is blasting deletions around hopefully.

File: domain/removal/state/model/application.go (hunk 2 above)
Comment (nvinuesa) [reply domain/removal/state/model/application.go]: After discussing it offline (cc @jack-w-shaw ) I have reworked how we remove application relations and units (with or without --force).

File: domain/removal/state/model/application.go (hunk 1 above)
Comment (nvinuesa) [reply domain/removal/state/model/application.go]: https://github.com/juju/juju/pull/21813#discussion_r2832113182

File: domain/removal/state/model/relation.go (hunk 4 above)
Comment (nvinuesa) [reply domain/removal/state/model/relation.go]: Good catch, moved it to `DeleteRelationWithRemoteOfferer()`.

File: domain/removal/state/model/unit.go (hunk 5 above)
Comment (nvinuesa) [reply domain/removal/state/model/unit.go]: Fixed, this is done in relation removal.

File: domain/removal/state/model/application.go [hunk 6]
```diff
@@ -324,33 +324,29 @@ WHERE  uuid = $entityUUID.uuid;`, applicationUUID)
...
+		// completed.
+		var numUnits count
+		err = tx.Query(ctx, unitsStmt, applicationUUID).Get(&numUnits)
+		if err != nil {
+			return errors.Errorf("querying application units: %w", err)
+		} else if numUnits := numUnits.Count; numUnits > 0 {
+			return errors.Errorf("cannot delete application as it still has %d unit(s)", numUnits).
+				Add(applicationerrors.ApplicationHasUnits).
+				Add(removalerrors.RemovalJobIncomplete)
+		}
```
Comment (jack-w-shaw) [inline domain/removal/state/model/application.go:340]: Ace

File: domain/removal/state/model/machine.go [hunk 7]
```diff
@@ -582,6 +582,33 @@ WHERE uuid = $machine.uuid;
...
+			var unitNodeCount count
+			if err := tx.Query(ctx, countUnitsOnNetNodeStmt, node).Get(&unitNodeCount); err != nil {
+				return errors.Errorf("checking units on net node: %w", err)
+			} else if unitNodeCount.Count > 0 {
+				return errors.Errorf(
+					"machine net node still referenced by %d unit(s), waiting for unit removal",
+					unitNodeCount.Count,
+				).Add(removalerrors.RemovalJobIncomplete)
+			}
+		}
```
Comment (jack-w-shaw) [inline domain/removal/state/model/machine.go:609]: What about if we do force? How do we avoid the FK violation?

File: domain/removal/state/model/relationwithremoteofferer.go [hunk 8]
```diff
@@ -222,6 +222,22 @@ WHERE  relation_uuid = $entityUUID.uuid`, entityUUID{})
...
+		return errors.Errorf("preparing remote consumer deletion: %w", err)
+	}
+
+	deleteOfferConnectionStmt, err := st.Prepare(`
+DELETE FROM offer_connection
+WHERE  remote_relation_uuid = $entityUUID.uuid`, entityUUID{})
+	if err != nil {
+		return errors.Errorf("preparing offer connection deletion: %w", err)
+	}
+
```
Comment (jack-w-shaw) [inline domain/removal/state/model/relationwithremoteofferer.go:240]: @SimonRichardson @manadart is this the right place for this?

File: domain/removal/state/model/unit.go [hunk 9]
```diff
@@ -869,6 +869,7 @@ func (st *State) deleteForeignKeyUnitReferences(ctx context.Context, tx *sqlair.
 		"DELETE FROM unit_storage_directive WHERE unit_uuid = $entityUUID.uuid",
 		"DELETE FROM unit_agent_presence WHERE unit_uuid = $entityUUID.uuid",
 		"DELETE FROM secret_unit_consumer WHERE unit_uuid = $entityUUID.uuid",
+		"DELETE FROM relation_unit WHERE unit_uuid = $entityUUID.uuid",
```
Comment (jack-w-shaw) [inline domain/removal/state/model/unit.go]: This still seems wrong. The relation should be cleaned up before we try and remove a unit

File: domain/removal/state/model/relationwithremoteofferer.go (hunk 8 above)
Comment (nvinuesa) [reply domain/removal/state/model/relationwithremoteofferer.go:240]: The `application_remote_consumer` table for sure gets populated on the consumer side, so it's the right place. Regarding `offer_connection`, maybe I should move it to `EnsureRelationWithRemoteConsumerNotAliveCascade`? I wasn't sure about this one.

File: domain/removal/state/model/unit.go (hunk 9 above)
Comment (nvinuesa) [reply domain/removal/state/model/unit.go]: I removed all these in my last commit, I don't know why this one is still here. I'm fixing this and the failing tests at the same time.

File: domain/removal/state/model/machine.go (hunk 7 above)
Comment (nvinuesa) [reply domain/removal/state/model/machine.go:609]: Yeah good catch. Fixed the same way we did with apps.

Comment (nvinuesa) [reply domain/removal/state/model/machine.go:609]: Also, add a test to cover unit/machine references when forced.

File: domain/removal/state/model/relationwithremoteofferer.go (hunk 8 above)
Comment (jack-w-shaw) [reply domain/removal/state/model/relationwithremoteofferer.go:240]: I suspect you should only be able to remove a relation with an offer connection using force

I would like @SimonRichardson or @manadart to approve this

**Review by jack-w-shaw — APPROVED** [review]
LGTM,  so long as @SimonRichardson or @manadart approve the offer_connection bit

File: domain/removal/state/model/relationwithremoteofferer.go (hunk 8 above)
Comment (nvinuesa) [reply domain/removal/state/model/relationwithremoteofferer.go:240]: > I suspect you should only be able to remove a relation with an offer connection using force

This means that every CMR should be removed with --force? I disagree.

Comment (manadart) [reply domain/removal/state/model/relationwithremoteofferer.go:240]: Yes, an offer connection is an indication of the other side involved, but it is wholly at the offerer's discretion whether to allow you to continue being related.

**Review by manadart — APPROVED** [review]
