### PR TITLE
fix(cloudimagemetadata): add parentheses to SQL OR clause in FindMetadata query

### LINKED ISSUE #21655: Juju HA on Openstack fails to install
### Description

Juju bootstrapped on Openstack
`juju bind -m foundation-openstack:controller controller alpha`
`juju add-unit -m foundation-openstack:controller controller -n 2`

two new units are added but install fails, actualy it fails to import yaml module
The reason is while first unit is 24.04 additional units are 20.04 or 22.04
But juju status shows all three to be 24.04
```
$ juju status -m controller
Model       Controller            Cloud/Region                Version  Timestamp
controller  foundation-openstack  openstack_cloud/prodstack6  4.0.1    08:56:32Z

App         Version  Status  Scale  Charm            Channel     Rev  Exposed  Message
controller           error       3  juju-controller  4.0/stable  157  no       hook failed: "install"

Unit           Workload  Agent  Machine  Public address  Ports  Message
controller/0*  active    idle   0        10.141.135.218         
controller/1   error     idle   1        10.141.135.91          hook failed: "install"
controller/2   error     idle   2        10.141.135.160         hook failed: "install"

Machine  State    Address         Inst id                               Base          AZ                   Message
0        started  10.141.135.218  354ad48d-fbfc-4997-9652-7409386d7378  ubuntu@24.04  availability-zone-1  ACTIVE
1        started  10.141.135.91   28a36ef0-719b-4e7b-9159-04867741fd7d  ubuntu@24.04  availability-zone-3  ACTIVE
2        started  10.141.135.160  576fae94-2e10-47ad-92cc-6b08076ba63a  ubuntu@24.04  availability-zone-2  ACTIVE

$ for i in 0 1 2; do juju ssh -m controller $i cat /etc/os-release|grep VERSION_ID ; done 2>/dev/null
VERSION_ID="24.04"
VERSION_ID="22.04"
VERSION_ID="22.04"
```

### Juju version

4.0.1

### Cloud

OpenStack

### Expected behaviour

All three units use 24.04 and controller installation on other two units works

### Reproduce / Test

Described above.
I am hitting this 100% of time on PS6 Openstack and on Sunbeam.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
The WHERE clause in FindMetadata joined conditions with AND, but the first clause "source = 'custom' OR created_at >= ..." lacked parentheses. Due to SQL operator precedence (AND before OR), all custom-source rows bypassed every subsequent filter (version, region, stream, etc.).

When custom image metadata was provided at bootstrap via --metadata-source, entries for all Ubuntu versions (20.04, 22.04, 24.04) were stored with source='custom'. The provisioner querying for version 24.04 would get back all versions, and since the Image struct used for selection carries no version field, it could pick the wrong image ID, resulting in HA controller machines running the wrong Ubuntu release while Juju reported them as 24.04.

## QA steps

There is a new unit test that tests this fix so it should pass. 
For the QA scenario, as it's run on prodstack, you'll need to bootstrap passing image metadata containing more than one ubuntu version (for example:
```
{
    "index": {
        "com.ubuntu.cloud:custom": {
            "updated": "Thu, 12 Feb 2026 10:04:07 +0000",
            "format": "products:1.0",
            "datatype": "image-ids",
            "cloudname": "custom",
            "clouds": [
                {
                    "region": "RegionOne",
                    "endpoint": "http://x.x.x.x/openstack-keystone/v3"
                }
            ],
            "path": "streams/v1/com.ubuntu.cloud-released-imagemetadata.json",
            "products": [
                "com.ubuntu.cloud:server:20.04:amd64",
                "com.ubuntu.cloud:server:22.04:amd64",
                "com.ubuntu.cloud:server:24.04:amd64"
            ]
        }
    },
    "updated": "Thu, 12 Feb 2026 10:04:07 +0000",
    "format": "index:1.0"
}
```
And then add 2 units to turn the controller HA. 

The three units should be 24.04 *and* the actual ubuntu version in the machine should be 24.04:
```
ubuntu@juju-486071-controller-0:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.4 LTS"
```

## Links

**Issue:** Fixes #21655.

**Jira card:** [JUJU-9103](https://warthogs.atlassian.net/browse/JUJU-9103)

[JUJU-9103]: https://warthogs.atlassian.net/browse/JUJU-9103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jack-w-shaw — APPROVED** [review]

File: domain/cloudimagemetadata/state/state.go [hunk 1]
```diff
@@ -271,7 +271,10 @@ func (s *State) FindMetadata(ctx context.Context, criteria cloudimagemetadata.Me
 	// clauses will collect all required clauses to build the final WHERE ... AND ... clause
 	clauses := []string{
 		// Ignores expired metadata in case of non custom source.
-		`source = $inputMetadata.source OR cloud_image_metadata.created_at >=  $ttl.expires_at`,
+		// The parentheses are critical: without them, SQL operator
+		// precedence causes custom-source rows to bypass all subsequent filter
+		// clauses (version, region, etc).
+		`(source = $inputMetadata.source OR cloud_image_metadata.created_at >= $ttl.expires_at)`,
```
Comment (gfouillet) [inline domain/cloudimagemetadata/state/state.go]: **suggestion:** Another approach, less fragile, would be to add parenthesis in the `WHERE` and `JOIN` clauses.

```go
findMetadataQuery := fmt.Sprintf(`
WITH arch(id, architecture_name) AS (
	SELECT id, name FROM architecture
)
SELECT &outputMetadata.* 
FROM cloud_image_metadata
JOIN arch ON cloud_image_metadata.architecture_id = arch.id
WHERE (%s);`, strings.Join(clauses, `) AND (`))
```

This enforce the intent of having a list of "AND" clauses which can contains litteraly anything without breaking the expected precedence.

**Review by gfouillet — APPROVED** [review]
This works, however i suggested a slightly more reliable approach.

File: domain/cloudimagemetadata/state/state.go (hunk 1 above)
Comment (manadart) [reply domain/cloudimagemetadata/state/state.go]: Can we check if this works?

```sql
  WITH arch(id, architecture_name) AS (
      SELECT id, name FROM architecture
  )
  SELECT &outputMetadata.*
  FROM cloud_image_metadata
  JOIN arch ON cloud_image_metadata.architecture_id = arch.id
  WHERE
      (source = $inputMetadata.source OR cloud_image_metadata.created_at >= $ttl.expires_at)
  AND ($metadataFilter.region = '' OR cloud_image_metadata.region = $metadataFilter.region)
  AND ($metadataFilter.stream = '' OR cloud_image_metadata.stream = $metadataFilter.stream)
  AND ($metadataFilter.virt_type = '' OR cloud_image_metadata.virt_type = $metadataFilter.virt_type)
  AND ($metadataFilter.root_storage_type = '' OR cloud_image_metadata.root_storage_type = $metadataFilter.root_storage_type)
  AND ($findFlags.has_versions = 0 OR cloud_image_metadata.version IN ($versions[:]))
  AND ($findFlags.has_arches = 0 OR arch.architecture_name IN ($arches[:]));
```

Comment (nvinuesa) [reply domain/cloudimagemetadata/state/state.go]: @manadart your suggestion is very good. I was able to remove the dynamic query thanks to it. Way better now, haven't had to modify any tests.
See 1c585348963d5a08c73172c865536a93b302ea16
