### PR TITLE
fix: ensure secret rotate policy can be updated

### LINKED ISSUE #20928: Hook command cannot change secret rotation policy
### Description

- When a secret is created, a rotation policy can be specified
- When a existing secret doesn't have a rotation policy, it can be set
- When a policy is set, trying to change it fails with odd error

I suspect that the hook command (or unit agent) is expected to fetch the current rotation roll-over time and send that with the new rotation policy to unit agent (or to the controller).

### Juju version

3.6.9

### Cloud

_No response_

### Expected behaviour

I should be able to:
- set rotation policy
- set it again to same policy
- change rotation policy
- reset rotation policy

### Reproduce / Test

```command

# Start with a secret without a rotation policy

⋊> dima@bb ⋊> ~/c/c/postgresql-charm on master ◦ juju exec --unit test-secrets/0 'secret-info-get d3nkv17mp25c786f8hd0'
d3nkv17mp25c786f8hd0:
  revision: 1
  label: ""
  owner: application
  rotation: never
⋊> dima@bb ⋊> ~/c/c/postgresql-charm on master ◦ juju exec --unit test-secrets/0 'secret-set d3nkv17mp25c786f8hd0 --rotate daily'
⋊> dima@bb ⋊> ~/c/c/postgresql-charm on master ◦ juju exec --unit test-secrets/0 'secret-set d3nkv17mp25c786f8hd0 --rotate daily'
updating secrets: must specify a secret rotate time

# Why ⚠️

⋊> dima@bb ⋊> ~/c/c/postgresql-charm on master ◦ juju exec --unit test-secrets/0 'secret-info-get d3nkv17mp25c786f8hd0'
d3nkv17mp25c786f8hd0:
  revision: 1
  label: ""
  owner: application
  rotation: daily
  rotates: 2025-10-18T03:18:13Z

# Ah, apparently when rotation policy is set, it must be changed together with a roll-over timestamp?

⋊> dima@bb ⋊> ~/c/c/postgresql-charm on master ◦ juju exec --unit test-secrets/0 'secret-set d3nkv17mp25c786f8hd0 --rotate daily'
updating secrets: must specify a secret rotate time
⋊> dima@bb ⋊> ~/c/c/postgresql-charm on master ◦ juju exec --unit test-secrets/0 'secret-set d3nkv17mp25c786f8hd0 --rotate monthly'
updating secrets: must specify a secret rotate time

# Changing to a different policy doesn't help

⋊> dima@bb ⋊> ~/c/c/postgresql-charm on master ◦ juju exec --unit test-secrets/0 'secret-set d3nkv17mp25c786f8hd0 --rotate ""'
⋊> dima@bb ⋊> ~/c/c/postgresql-charm on master ◦ juju exec --unit test-secrets/0 'secret-info-get d3nkv17mp25c786f8hd0'
d3nkv17mp25c786f8hd0:
  revision: 1
  label: ""
  owner: application
  rotation: daily
  rotates: 2025-10-18T03:18:13Z

# Attempting to reset the rotation policy doesn't work

⋊> dima@bb ⋊> ~/c/c/postgresql-charm on master ◦ juju exec --unit test-secrets/0 'secret-set d3nkv17mp25c786f8hd0 --help'
Usage: secret-set [options] <ID> [key[#base64]=value...]

Summary:
Update an existing secret.

Options:
--description (= "")
    the secret description
--expire (= "")
    either a duration or time when the secret should expire
--file (= "")
    a YAML file containing secret key values
--label (= "")
    a label used to identify the secret in hooks
--owner (= "application")
    the owner of the secret, either the application or unit
--rotate (= "")
    the secret rotation policy

Details:
Update a secret with a list of key values, or set new metadata.
If a value has the '#base64' suffix, it is already in base64 format and no
encoding will be performed, otherwise the value will be base64 encoded
prior to being stored.
To just update selected metadata like rotate policy, do not specify any secret value.

Examples:

    secret-set secret:9m4e2mr0ui3e8a215n4g token=34ae35facd4
    secret-set secret:9m4e2mr0ui3e8a215n4g key#base64 AA==
    secret-set secret:9m4e2mr0ui3e8a215n4g --rotate monthly token=s3cret
    secret-set secret:9m4e2mr0ui3e8a215n4g --expire 24h
    secret-set secret:9m4e2mr0ui3e8a215n4g --expire 24h token=s3cret
    secret-set secret:9m4e2mr0ui3e8a215n4g --expire 2025-01-01T06:06:06 token=s3cret
    secret-set secret:9m4e2mr0ui3e8a215n4g --label db-password \
        --description "my database password" \
        data#base64 s3cret==
    secret-set secret:9m4e2mr0ui3e8a215n4g --label db-password \
        --description "my database password"
    secret-set secret:9m4e2mr0ui3e8a215n4g --label db-password \
        --description "my database password" \
        --file=/path/to/file

# There's no command line flag to pass rotation roll-over timestamp to the hook tool
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by wallyworld**
There was an error trying to change the secret rotate policy.
The logic was meant to stop a secret next rotate time from being changed if it were to occur after any current rotate time already recorded.

This PR fixes that and adds a ci test for rotation. The existing ci test that was enhanced has the changed from 4.0 backported so that better charms are used.

## QA steps

`./main.sh -v secrets_iaas test_secrets_juju`

## Links

**Issue:** Fixes #20928.

**Jira card:** [JUJU-](https://warthogs.atlassian.net/browse/JUJU-)

### CODE REVIEW

File: state/secrets.go [hunk 1]
```diff
@@ -3265,11 +3265,17 @@ func (s *secretsStore) secretRotationOps(uri *secrets.URI, owner string, rotateP
 	} else if err != nil {
 		return nil, errors.Trace(err)
 	}
+	// Only update the rotation time if the new time is before
+	// the current rotate time.
+	newRotateTime := nextRotateTime.Round(time.Second).UTC()
+	if newRotateTime.After(doc.NextRotateTime) {
+		return nil, nil
+	}
```
Comment (adisazhar123) [inline state/secrets.go:3273]: curious, able to share some context why we only update when the new time is earlier?

Comment (wallyworld) [reply state/secrets.go:3273]: We always want to rotate at the earliest configured time. If the policy was hourly and we update to daily, then we still want to rotate 1 hour from now before we then start to rotate daily. If the policy was daily and we switch to hourly, then we should start to rotate hourly and that comes before the daily time so need to use that.
