### PR TITLE
fix: mount correct location for workload containers

### LINKED ISSUE #21254: Juju 4.0 doesn't respect charm container workload mount point
### Description

When a charm defines a set of storage requirements it also has the ability to define where it would like the storage mounted within the workload container. This can be different to any location suggested by the charm yaml.

As an example this is the case with the vault-k8s operator, [see here](https://github.com/canonical/vault-k8s-operator/blob/main/k8s/charmcraft.yaml).

What we are doing in 4.0 is looking at the location information specified on the charm storage defs to inform the attachment point. This is the correct approach when attaching the storage to the charm container, however when attaching to the workload container we MUST be following what has been set on the container directives in the charm yaml.

This does introduce an interesting business logic problem we will be faced with in the future. We in theory support having multiple storage instances in kubernetes but at the moment it is broken in 3.6 and 4.0 due to a logic bug we have in Kubernetes.

However when we fix this if the charm author allows for multiple storage instances and has specified a specific mount point on the container we will have conflicting scenario to deal with. That is the mount points need to be unique and we can't honour the exact location asked for by the charm.

### Juju version

4.0.0

### Cloud

Kubernetes

### Expected behaviour

When the charm has asked for the storage to be mounted at a specific location within the workload container we MUST use this over what ever value has been calculated for the attachment location onto the rest of the containers.

When it comes to supporting multiple storage instances we will have to solve this in a separate manner later on.

### Reproduce / Test

Deploy vault-k8s and watch the errors from the workload container as pebble cannot find the mount location.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by adisazhar123**
A workload container can specify a location to mount a volume. This is done by specifying a `location` field  (`containers.<container_name>.mounts[].location`) in the metadata / charmcraft.yaml ([ref](https://documentation.ubuntu.com/ops/latest/howto/manage-storage/#declare-the-storage)).

Unfortunately, we ended up mounting the charm container’s path onto the workload container. Charms were expecting a path to exist in their workload container but that path wasn't there because we weren't mounting it.

This PR correctly looks up the intended mount location of the workload container and appends that in the podspec template.

In the unit tests, I've made a change to reflect that a path for the workload container can be different from the one in `KubernetesFilesystemAttachmentParams.Path` (which is constructed for charms container). Initially both had the same path value so it wasn't explicit they could have different values.

This PR doesn't account for when multiple storage for a workload may exist (also existing bug in 3.6). Will be done separately.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

1. bootstrap k8s controller

```
make minikube-operator-update
juju bootstrap minikube 8780-testing
```

2. add model

```
juju add-model testing
```

3. deploy zinc and vault

```
juju deploy zinc-k8s

juju deploy vault-k8s --channel 1.17/stable
```

6. check the volume mounts for zinc

You should see `/var/lib/zincsearch` mountpath.  
```
kubectl get sts/zinc-k8s -n testing -o json | jq '.spec.template.spec.containers[] | select(.name == "zinc") | .volumeMounts'
```

```
[
  {
    "mountPath": "/charm/bin/pebble",
    "name": "charm-data",
    "readOnly": true,
    "subPath": "charm/bin/pebble"
  },
  {
    "mountPath": "/charm/container",
    "name": "charm-data",
    "subPath": "charm/containers/zinc"
  },
  {
    "mountPath": "/var/lib/zincsearch",
    "name": "zinc-k8s-data-e7377f"
  }
]
```

The deployment should succeed without errors below:

```
2025-11-27T04:29:43.820Z [container-agent]     2025/11/27 04:29:43 failed to create log file /var/lib/zincsearch/zinc.log: open /var/lib/zincsearch/zinc.log: no such file or directory
```

7. check the volume mounts for vault

You should see `/vault/certs`, `/vault/config`, `/tmp`, and `/vault/raft` mountpath. The deployment for vault will fail because of another bug but we're interested in the correct mount path here.

```
kubectl get sts/vault-k8s -n testing5 -o json | jq '.spec.template.spec.containers[] | select(.name == "vault") | .volumeMounts'
```

```
[
  {
    "mountPath": "/charm/bin/pebble",
    "name": "charm-data",
    "readOnly": true,
    "subPath": "charm/bin/pebble"
  },
  {
    "mountPath": "/charm/container",
    "name": "charm-data",
    "subPath": "charm/containers/vault"
  },
  {
    "mountPath": "/vault/certs",
    "name": "vault-k8s-certs-375ecc"
  },
  {
    "mountPath": "/vault/config",
    "name": "vault-k8s-config-375ecc"
  },
  {
    "mountPath": "/tmp",
    "name": "vault-k8s-tmp-375ecc"
  },
  {
    "mountPath": "/vault/raft",
    "name": "vault-k8s-vault-raft-375ecc"
  }
]

```

There is an error due to a bug in the model storage provisioner. This will be dealt separately.

```
kubectl logs sts/vault-k8s -n testing
```
```
2025-11-27T04:30:22.695Z [container-agent] OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /var/lib/juju/storage/55497d59-2f07-4cec-85f3-5be50f1bbcb7/ca.pem

```

## Links

**Issue:** Fixes #21254.

**Jira card:** [JUJU-8780](https://warthogs.atlassian.net/browse/JUJU-8780)

[JUJU-8780]: https://warthogs.atlassian.net/browse/JUJU-8780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: internal/provider/kubernetes/application/application.go [hunk 1]
```diff
@@ -224,13 +224,19 @@ func (a *app) Ensure(config caas.ApplicationConfig) (err error) {
...
+			// The location where we mount is defined in the YAML of the charm.
+			// This location is already organized in the `Mounts.Path` field of each
+			// container.
 			for _, mount := range config.Containers[name].Mounts {
 				if mount.StorageName == storageName {
 					volumeMountCopy := m
+					volumeMountCopy.MountPath = mount.Path
 					// TODO(sidecar): volumeMountCopy.MountPath was defined in `caas.ApplicationConfig.Filesystems[*].Attachment.Path`.
 					// Consolidate `caas.ApplicationConfig.Filesystems[*].Attachment.Path` and `caas.ApplicationConfig.Containers[*].Mounts[*].Path`!!!
 					//volumeMountCopy.MountPath = mount.Path
```
Comment (hpidcock) [inline internal/provider/kubernetes/application/application.go]:
```suggestion
```

**Comment by adisazhar123** [comment]
@CodingCookieRookie 

> Just curious what is this issue that is still not accounted for multiple storage raised in the PR overview?

in the charms yaml you can specify a storage to have multiple counts. this "count" or id will be appended to the path mounted in the charm container so that it's unique. however, we don't have this feature for workload containers.

**Comment by CodingCookieRookie** [comment]
> @CodingCookieRookie
> 
> > Just curious what is this issue that is still not accounted for multiple storage raised in the PR overview?
> 
> in the charms yaml you can specify a storage to have multiple counts. this "count" or id will be appended to the path mounted in the charm container so that it's unique. however, we don't have this feature for workload containers.

ah i see, so if we were decide to mount more storage, if they were to have the same path i.e /var/log, the first one would be mounted at something like /var/log1 and the second would be /var/log2?

**Comment by adisazhar123** [comment]
> ah i see, so if we were decide to mount more storage, if they were to have the same path i.e /var/log, the first one would be mounted at something like /var/log1 and the second would be /var/log2?

@CodingCookieRookie  yes, that's right. that's what we do for charm container. eventually, we want to do something similar for workload container.

File: internal/provider/kubernetes/application/application.go (hunk 1 above)
Comment (adisazhar123) [reply internal/provider/kubernetes/application/application.go]: I believe that comment is still necessary because we have not eliminated the two places where the mount paths are stored / constructed. 

I can move the comment above `volumeMountCopy.MountPath = mount.Path`. I didn't realize `volumeMountCopy.MountPath = mount.Path` was commented out.
