### PR TITLE
fix: cross-controller CMR between 3.6 and 4.0

### LINKED ISSUE #22081: Cross controller CMR between 3.6 and 4.0 stuck at joining
### Description

When creating a offer on a 3.6 controller (using the QA charm `dummy-source`) and consuming + relating it on a 4.0 controller (using the QA charm `dummy-sink`), the relation gets stuck at `joining`:
```
$ juju status --relations                
Model  Controller  Cloud/Region         Version  Timestamp
m      c403        localhost/localhost  4.0.3    11:38:17+01:00

SAAS         Status  Store  URL
dummy-offer  active  c36    admin/m.dummy-offer

App         Version  Status   Scale  Charm               Channel        Rev  Exposed  Message
dummy-sink           waiting      1  juju-qa-dummy-sink  latest/stable    7  no       Waiting for token

Unit           Workload  Agent  Machine  Public address  Ports  Message
dummy-sink/0*  waiting   idle   0        10.134.1.168           Waiting for token

Machine  State    Address       Inst id        Base          AZ                                Message
0        started  10.134.1.168  juju-4abb9a-0  ubuntu@20.04  nvinuesa-ThinkPad-P16s-Gen-4-AMD  Running

Integration provider  Requirer          Interface    Type     Message
dummy-sink:source     dummy-offer:sink  dummy-token  regular  joining  
```
even though the consume and relate steps work fine.

### Juju version

4.0.3

### Cloud

_No response_

### Expected behaviour

The relation should be `joined` and the token be received by `dummy-sink`.

### Reproduce / Test

Bootstrap a 3.6 controller, deploy dummy-source, offer it and set the config for the token. Bootstrap a 4.0 controller, deploy dummy-sink, consume the 3.6 offer, relate it.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
When a Juju 4.0 controller consumes an offer from a Juju 3.6 controller, the relation gets stuck at
"joining" status. The consuming unit's charm never receives the data it expects via relation-get,
because the offering unit's relation-joined hook never fires.

The issue is that when the 4.0 consumer published relation changes to the remote model, it sent the `offerUUID` as the 
`ApplicationOrOfferToken`. A 4.0 offerer handles this fine because its domain layer has fallback logic to resolve
offer UUIDs. But a 3.6 offerer calls `GetRemoteEntity(token)`, which only knows about the consuming application's
UUID — the token it imported during `registerRemoteRelation`. Since the `offerUUID` doesn't match any remote entity,
the lookup returns `NotFound`, `applicationTag` becomes nil, and `PublishRelationChange` silently returns without
calling `EnterScope` for any units. The offering unit never enters scope, so relation-joined never fires on the
offering charm.

The fix carries the consuming application UUID in the offerer unit relation worker alongside the macaroon and
relation UUID it already owns, and uses it as `ApplicationOrOfferToken` in every relation change event published to
the offering model. This also removes a previous map-based approach that had a data race between the worker loop
(writes) and PublishModelDying (reads).

## QA steps

Create a CMR between an offering 3.6 controller and a 4.0 consuming controller.
```
$ juju_36 bootstrap lxd c36
$ juju_36 add-model m
$ juju_36 deploy juju-qa-dummy-source
$ juju_36 config dummy-source token=abc
$ juju_36 offer dummy-source:sink
 
# build juju on this branch
$ juju bootstrap lxd c40
$ juju add-model consume-model
$ juju consume c36:admin/m.dummy-source
$ juju deploy juju-qa-dummy-sink
$ juju relate dummy-sink dummy-source
# wait until relation joins, then check the token from status and exec 
$ juju status --relations 
$ juju exec --unit dummy-sink/0 -- cat /var/run/dummy-sink/token
abc
```

Also check that 4.0->4.0 cross-controller CMRs still work:
```
# build juju on this branch

$ juju bootstrap lxd offering
$ juju add-model m
$ juju deploy juju-qa-dummy-source
$ juju config dummy-source token=abc
$ juju offer dummy-source:sink
 
$ juju bootstrap lxd consuming
$ juju add-model m
$ juju consume offering:admin/m.dummy-source
$ juju deploy juju-qa-dummy-sink
$ juju relate dummy-sink dummy-source
# wait until relation joins, then check the token from status and exec 
$ juju status --relations 
$ juju exec --unit dummy-sink/0 -- cat /var/run/dummy-sink/token
abc
```

## Links

**Issue:** Fixes #22081.

**Jira card:** [JUJU-9496](https://warthogs.atlassian.net/browse/JUJU-9496)

[JUJU-9496]: https://warthogs.atlassian.net/browse/JUJU-9496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by manadart — DISMISSED** [review]
Want to hold this one while I take a look.

**Comment by nvinuesa** [comment]
@manadart I'm putting this one back to draft until I can discuss the approach with @SimonRichardson

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 1]
```diff
@@ -797,7 +822,7 @@ func (w *localConsumerWorker) handleRelationDying(
 	change := params.RemoteRelationChangeEvent{
 		RelationToken:           relationUUID.String(),
 		Life:                    life.Dying,
-		ApplicationOrOfferToken: w.offerUUID,
+		ApplicationOrOfferToken: w.consumerAppTokenForRelation(relationUUID),
```
Comment (manadart) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]: We should just change this so it's always the application, and remove the processing ambiguity if we can always assume it's going to be `ApplicationToken`.

**Review by manadart — COMMENTED** [review]
You may have already discussed with Simon, but we should go a little step further in cleaning up the logic.

That plus guarding against concurrent access.

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 2]
```diff
@@ -146,6 +146,11 @@ type localConsumerWorker struct {
 	// consume the remote application to which this worker pertains.
 	offerMacaroon *macaroon.Macaroon
 
+	// consumerAppUUIDs maps relation UUIDs to the consuming application
+	// UUID for that relation. This is used as the application token when
+	// publishing changes to the offering model.
+	consumerAppUUIDs map[corerelation.UUID]application.UUID
+
```
[the remark this answers is not in the document]
Comment (gfouillet) [reply internal/worker/remoterelationconsumer/localconsumerworker.go]: **issue:** This is a valid point. External call to loop-managed struct should pass through the worker loop. You can look how it is done in various Report function (basically a request chanel to fetch whatever is required to keep read & write into the loop)

**Review by gfouillet — CHANGES_REQUESTED** [review]
Copilot had valid point.

The method `publishRelationDyingChange` need to be refactored to get the consumerAppUUIDs, in order to ensure:

* when called from the loop, access to the map will be monitored, so this is ok
* when called from PublishModelDying (exported), a request channel should added into the worker to fetch the correct UUID, handled by another case in the loop.

Also, copilot pointed that the new map will only grows, if it is not relevant I would be curious to have the explanation (I am unsure of the lifetime of the worker ATM)

**Review by SimonRichardson — CHANGES_REQUESTED** [review]
I'd like to tackle this as two PRs - as I have issues with using a map.

**Comment by nvinuesa** [comment]
@manadart @SimonRichardson @gfouillet I have changed the approach here, we now only pass a single app UUID that was already known by the consumerunitrelations worker anyways.

**Review by gfouillet — APPROVED** [review]
QA OK, thanks

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 3]
```diff
@@ -604,13 +608,15 @@ func (w *localConsumerWorker) publishRelationDyingForRemovedRelation(ctx context
 
 	type MacaroonGetter interface {
 		Macaroon() *macaroon.Macaroon
+		ConsumerApplicationUUID() application.UUID
 	}
```
Comment (SimonRichardson) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]: This needs renaming. It's no longer a `MacaroonGetter`.

File: internal/worker/remoterelationconsumer/localconsumerworker.go [hunk 4]
```diff
@@ -625,8 +631,13 @@ func (w *localConsumerWorker) publishRelationDyingForRemovedRelation(ctx context
 // the removal worker. Uses a fresh context since the catacomb context may be
 // cancelled. This is a best-effort notification: errors are logged but not
 // propagated.
-func (w *localConsumerWorker) publishRelationDyingWithMacaroon(relationUUID corerelation.UUID, mac *macaroon.Macaroon) {
+func (w *localConsumerWorker) publishRelationDyingWithMacaroon(
+	relationUUID corerelation.UUID,
+	mac *macaroon.Macaroon,
+	consumerAppUUID application.UUID,
```
Comment (SimonRichardson) [inline internal/worker/remoterelationconsumer/localconsumerworker.go]: Be consistent with ordering of params. `publishRelationDyingWithMacaroon` does `relationUUID, mac, consumerAppUUID`, but `publishRelationDyingChange` does `consumerAppUUID, relationUUID, mac`. Keeping things consistent makes it a lot easier to read.

**Review by SimonRichardson — COMMENTED** [review]
The following fails:

```sh
$ juju bootstrap lxd offering
$ juju add-model m
$ juju deploy juju-qa-dummy-source
$ juju config dummy-source token=abc
$ juju offer dummy-source:sink
 
$ juju bootstrap lxd consuming
$ juju add-model m
$ juju consume offering:admin/m.dummy-source
$ juju deploy juju-qa-dummy-sink
$ juju relate dummy-sink dummy-source
# wait until relation joins, then check the token from status and exec 
$ juju status --relations 
```

Now do:

```sh
$ juju remove-saas dummy-source
$ juju consume offering:admin/m.dummy-source
$ juju relate dummy-sink dummy-source
$ juju config -m consuming:m dummy-source token=edf
```

**Comment by nvinuesa** [comment]
@SimonRichardson 
> Now do:
```
$ juju remove-saas dummy-source
$ juju consume offering:admin/m.dummy-source
$ juju relate dummy-sink dummy-source
$ juju config -m consuming:m dummy-source token=edf
```

This is already broken in 4.0. I'm taking a look nonetheless. I'm pretty sure this patch is not the cause of this, so I propose to open a new issue and fix it separately.

**Review by SimonRichardson — APPROVED** [review]
