### PR TITLE
fix(cmr): populate offer connection details in list-offers API response

### LINKED ISSUE #21964: Offer connection details not returned by API
### Description

In the Juju Terraform provider we have noticed an issue where an offer's connection details are not returned, a small piece of code to illustrate is below,
```go
import (
	"context"
	"github.com/juju/juju/api/client/applicationoffers"
)

func offerConnections() {
	client := applicationoffers.NewClient(getConnection())
	offer, _ := client.ApplicationOffer(context.Background(), "<offer-url>")

	if len(offer.Connections) > 0 {
		// Never enters here
	}
}
```
Reproducing this with the CLI and comparing with 3.6, it's clear that some information is missing when requesting offer details.

The CLI command `juju list-offers --format yaml` shows the offer and its connections.

For a model with an offer that has 1 active connection:
- In 3.6 the output is,
```
$ juju list-offers --format yaml
dummy-source:
  application: dummy-source
  store: test-3-6
  charm: ch:amd64/juju-qa-dummy-source-6
  offer-url: admin/offering.dummy-source
  endpoints:
    sink:
      interface: dummy-token
      role: requirer
  connections:
  - source-model-uuid: 202341de-b4aa-49d7-8ed5-bb1dec896203
    username: admin
    relation-id: 0
    endpoint: sink
    status:
      current: joined
      since: 2 minutes ago
  users:
    admin:
      display-name: admin
      access: admin
    everyone@external:
      access: read
```

- In 4.0.3 the output is,
```
$ juju list-offers --format yaml
dummy-source:
  application: dummy-source
  store: test-4
  charm: ch:amd64/juju-qa-dummy-source-6
  offer-url: admin/offering.dummy-source
  endpoints:
    sink:
      interface: dummy-token
      role: requirer
  users:
    admin:
      display-name: admin
      access: admin
```

### Juju version

4.0.3

### Cloud

LXD

### Expected behaviour

Expected offer connection details to be present.

### Reproduce / Test

- juju add-model offering
- juju add-model consuming
- juju switch offering
- juju deploy juju-qa-dummy-source --config token=abc
- juju offer dummy-source:sink
- juju switch consuming
- juju deploy juju-qa-dummy-sink 
- juju relate dummy-sink admin/offering.dummy-source
- juju switch offering
- juju list-offers --format yaml

The output should show the `dummy-source` offer with 1 connection, but the field is missing.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by nvinuesa**
In Juju 3.6, running `juju list-offers --format yaml` would show a `connections` section with details about each consuming model—relation ID, status, ingress subnets, and username. After the 4.0 migration to DQlite, this data was never wired up: a TODO placeholder sat where the connection-fetching logic should have been, so the API always returned empty connection lists.

This patch adds that behaviour: a new `GetOfferConnections` state query joins the offer_connection, relation, relation_status, and relation_network_ingress tables to fetch every active connection for a batch of offer UUIDs, a thin service method exposes it, and the facade fills in `params.OfferConnection` entries for admin users.

The admin check semantics from 3.6 are kept:
A soft gate, adding per-offer access checks that walk the permission hierarchy
(superuser, model admin, then offer-level admin/consume/read), and tracking admin status per-offer so that connection details are populated for any offer the caller has admin access to.

## QA steps

The original QA steps from the issue should now work fine:
```
juju bootstrap c
juju add-model offering
juju add-model consuming
juju switch offering
juju deploy juju-qa-dummy-source --config token=abc
juju offer dummy-source:sink
juju switch consuming
juju deploy juju-qa-dummy-sink
juju relate dummy-sink admin/offering.dummy-source
juju switch offering
```
Then:
```
$ juju list-offers --format yaml
dummy-source:
  application: dummy-source
  store: c
  charm: ch:amd64/juju-qa-dummy-source-6
  offer-url: admin/offering.dummy-source
  endpoints:
    sink:
      interface: dummy-token
      role: requirer
  connections:
  - source-model-uuid: 36881c65-c08e-4c4c-8907-c7dc12fdcc9e
    username: admin
    relation-id: 0
    endpoint: sink
    status:
      current: joined
      since: 2 hours ago
  users:
    admin:
      display-name: admin
      access: admin
```
Which now includes the `connections` section.

## Links

**Issue:** Fixes #21964.

**Jira card:** [JUJU-9304](https://warthogs.atlassian.net/browse/JUJU-9304)

[JUJU-9304]: https://warthogs.atlassian.net/browse/JUJU-9304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apiserver/facades/client/applicationoffers/applicationoffers.go [hunk 1]
```diff
@@ -384,10 +403,73 @@ func (api *OffersAPI) applicationOffersFromModel(
...
+			return nil, errors.Capture(err)
+		}
+		for _, conn := range connections {
+			idx, ok := offerIndexByUUID[conn.OfferUUID]
+			if !ok {
+				continue
+			}
+			results[idx].Connections = append(results[idx].Connections, makeOfferConnection(conn))
+		}
 	}
```
Comment (kian99) [inline apiserver/facades/client/applicationoffers/applicationoffers.go]: It seems like it would be easier to return this as part of the call to `api.makeOfferParams` since in there you already know if the user is an admin of the offer. Then you don't need to jump through all these hoops with the map and getting the index, etc.

File: domain/crossmodelrelation/state/model/offer.go [hunk 2]
```diff
@@ -486,6 +486,121 @@ WHERE  offer_uuid = $uuid.uuid`, uuid{})
...
+	if err != nil {
+		return nil, errors.Capture(err)
+	}
+
+	type uuids []string
+
+	// Query connection details: relation id, username, consumer model UUID,
+	// endpoint name, and relation status.
+	connStmt, err := st.Prepare(`
+SELECT oc.offer_uuid            AS &offerConnectionDetail.offer_uuid,
```
Comment (kian99) [inline domain/crossmodelrelation/state/model/offer.go:508]: How do you go about writing these sql queries? The select part seems easy enough, we know the db model. For the joins are you just adding joins iteratively until you can get all the fields you need to satisfy the select and where clauses?

File: domain/crossmodelrelation/state/model/offer.go [hunk 3]
```diff
@@ -486,6 +486,121 @@ WHERE  offer_uuid = $uuid.uuid`, uuid{})
...
+JOIN   relation AS r ON oc.remote_relation_uuid = r.uuid
+JOIN   application_remote_consumer AS arc ON oc.uuid = arc.offer_connection_uuid
+JOIN   relation_endpoint AS re ON r.uuid = re.relation_uuid
+JOIN   application_endpoint AS ae
+       ON re.endpoint_uuid = ae.uuid
+       AND ae.application_uuid = arc.offerer_application_uuid
+JOIN   charm_relation AS cr ON ae.charm_relation_uuid = cr.uuid
+JOIN   relation_status AS rs ON r.uuid = rs.relation_uuid
+JOIN   relation_status_type AS rst ON rs.relation_status_type_id = rst.id
+WHERE  oc.offer_uuid IN ($uuids[:])
```
[the remark this answers is not in the document]
Comment (nvinuesa) [reply domain/crossmodelrelation/state/model/offer.go:526]: Wrong. This patch implements 3.6 behavior, and in 3.6 we don't filter offer connections by the relation life.

File: domain/crossmodelrelation/state/model/offer.go [hunk 4]
```diff
@@ -486,6 +486,121 @@ WHERE  offer_uuid = $uuid.uuid`, uuid{})
...
+
+	// Query ingress subnets separately to avoid row multiplication.
+	ingressStmt, err := st.Prepare(`
+SELECT oc.offer_uuid   AS &offerConnectionIngress.offer_uuid,
+       r.relation_id   AS &offerConnectionIngress.relation_id,
+       rni.cidr         AS &offerConnectionIngress.cidr
+FROM   offer_connection AS oc
+JOIN   relation AS r ON oc.remote_relation_uuid = r.uuid
+JOIN   relation_network_ingress AS rni ON oc.remote_relation_uuid = rni.relation_uuid
+WHERE  oc.offer_uuid IN ($uuids[:])
```
[the remark this answers is not in the document]
Comment (nvinuesa) [reply domain/crossmodelrelation/state/model/offer.go:540]: Same here, in 3.6 we never filter by relation life.

File: apiserver/facades/client/applicationoffers/applicationoffers.go [hunk 5]
```diff
@@ -384,10 +403,73 @@ func (api *OffersAPI) applicationOffersFromModel(
...
+	user names.UserTag,
+	controllerTag names.ControllerTag,
+	modelTag names.ModelTag,
+	offerUUID string,
+) (permission.Access, error) {
+	// If the authenticated user is controller superuser we return admin.
+	err := api.authorizer.EntityHasPermission(ctx, user, permission.SuperuserAccess, controllerTag)
+	if err != nil && !errors.Is(err, authentication.ErrorEntityMissingPermission) {
+		return permission.NoAccess, errors.Capture(err)
+	} else if err == nil {
```
[the remark this answers is not in the document]
Comment (nvinuesa) [reply apiserver/facades/client/applicationoffers/applicationoffers.go]: Although this optimization could be valid, this patch implements 3.6 behavior as-is for admin/superuser checks for correctness. We could do this on a follow-up.

File: domain/crossmodelrelation/state/model/offer.go (hunk 2 above)
Comment (nvinuesa) [reply domain/crossmodelrelation/state/model/offer.go:508]: I don't know if I'm addressing your question correctly, but usually we simply follow the relational algebra over the defined schema. In this case you need some JOINs to complete the returned struct as you correctly said.

Comment (kian99) [reply domain/crossmodelrelation/state/model/offer.go:508]: I was just curious what your personal process is for writing the SQL as it seems like it can be tricky to formulate.

File: apiserver/facades/client/applicationoffers/applicationoffers_test.go [hunk 6]
```diff
@@ -1148,12 +1174,11 @@ func (s *offerSuite) TestFindApplicationOffersPermission(c *tc.C) {
...
 	// Act
-	_, err := offerAPI.FindApplicationOffers(c.Context(), filters)
+	obtained, err := offerAPI.FindApplicationOffers(c.Context(), filters)
 
-	// Assert
-	c.Assert(err, tc.DeepEquals, &params.Error{
-		Message: "permission denied", Code: "unauthorized access"},
-	)
+	// Assert — non-admin user with no offer access sees no results.
+	c.Assert(err, tc.IsNil)
```
Comment (jack-w-shaw) [inline apiserver/facades/client/applicationoffers/applicationoffers_test.go]: `tc.ErrorIsNil` pls throughout

File: apiserver/facades/client/applicationoffers/applicationoffers_test.go [hunk 7]
```diff
@@ -1508,17 +1525,185 @@ func (s *offerSuite) TestApplicationOffersNotFound(c *tc.C) {
...
+				OfferName:      "hosted-db2",
+			},
+		},
+	}
+
+	// Act
+	obtained, err := offerAPI.ListApplicationOffers(c.Context(), filters)
+
+	// Assert
+	c.Assert(err, tc.IsNil)
```
Comment (jack-w-shaw) [inline apiserver/facades/client/applicationoffers/applicationoffers_test.go]: e.g. here as well, etc.

File: domain/crossmodelrelation/state/model/offer_test.go [hunk 8]
```diff
@@ -662,6 +664,116 @@ func (s *modelOfferSuite) setupOfferConnection(c *tc.C) (string, string) {
...
+	s.query(c, `
+INSERT INTO relation_network_ingress (relation_uuid, cidr) VALUES (?, '10.0.0.0/24')`, relUUID)
+	s.query(c, `
+INSERT INTO relation_network_ingress (relation_uuid, cidr) VALUES (?, '192.168.1.0/24')`, relUUID)
+
+	// Act
+	connections, err := s.state.GetOfferConnections(c.Context(), []string{offerUUID})
+
+	// Assert
+	c.Assert(err, tc.IsNil)
```
Comment (jack-w-shaw) [inline domain/crossmodelrelation/state/model/offer_test.go]: Here as well

**Review by jack-w-shaw — APPROVED** [review]

File: apiserver/facades/client/applicationoffers/applicationoffers_test.go (hunk 6 above)
Comment (nvinuesa) [reply apiserver/facades/client/applicationoffers/applicationoffers_test.go]: Yeah I copied from older tests here. Replaced everywhere now.

**Review by kian99 — APPROVED** [review]

File: apiserver/facades/client/applicationoffers/applicationoffers.go [hunk 9]
```diff
@@ -348,7 +346,12 @@ func (api *OffersAPI) applicationOffersFromModel(
 	requiredAccess permission.Access,
 	filters []crossmodelrelationservice.OfferFilter,
 ) ([]params.ApplicationOfferAdminDetailsV5, error) {
-	if err := api.checkModelPermission(ctx, apiUser, model.UUID(modelUUID), requiredAccess); err != nil {
+	// If the user is a controller superuser or model admin, they are
+	// considered admin and can see all offers and their connections.
+	isAdmin := api.checkAPIUserAdmin(ctx, model.UUID(modelUUID)) == nil
```
Comment (hmlanigan) [inline apiserver/facades/client/applicationoffers/applicationoffers.go]: issue: this changes the behavior, a person without read access can now get the data.

File: apiserver/facades/client/applicationoffers/applicationoffers.go [hunk 10]
```diff
@@ -363,16 +366,32 @@ func (api *OffersAPI) applicationOffersFromModel(
...
+		if !isAdmin {
+			userAccess, err := api.checkOfferAccess(ctx, apiUser, controllerTag, modelTag, appOffer.OfferUUID)
+			if err != nil {
+				return nil, errors.Capture(err)
+			}
+			if userAccess == permission.NoAccess {
+				continue
+			}
+			isOfferAdmin = userAccess == permission.AdminAccess
+		}
```
Comment (hmlanigan) [inline apiserver/facades/client/applicationoffers/applicationoffers.go]: issue: offer admins cannot list offers, nor see the connections.

```
$ juju grant simon admin admin/offering.dummy-source
$ juju grant simon write offering
$  juju login -u simon
$ juju list-offers --format yaml
{}
ERROR permission denied (unauthorized access)
```

**Review by hmlanigan — CHANGES_REQUESTED** [review]
The entirety of offer permissions needs to be specified and implemented. There are questions like, why can't an offer admin see an offer? It's best to start with what we want for all of the offer commands and work from there.

The 3.6 permission implementation was messy. The initial 4.0 permission implementation was an improvement, in that it used the authorizer rather than permission from the juju db, however not great either. The permission changes here add redundant calls and do not work as advertised, an offer admin cannot `list-offers`. 

To resolve the bug and keep parity with 3.6, you can go back to the starting permissions and add connections where `requiredAccess` is Admin. This will resolve the bug listed for admin users.

The QA steps must include different users when changing permission code.

File: apiserver/facades/client/applicationoffers/applicationoffers.go (hunk 10 above)
Comment (nvinuesa) [reply apiserver/facades/client/applicationoffers/applicationoffers.go]: As discussed, this is already broken on 3.6 as well so no new behavior here. Restored the permissions.

**Review by hmlanigan — APPROVED** [review]
