### PR TITLE
fix(network): make address selection deterministic across layers

### LINKED ISSUE #21809: IP Address Lists *Must* be Sorted
### Description

In Juju versions <= 3.6, we maintained a preferred public and private (actually local-cloud) address on machine documents. This was in effect a cache to get this information quickly, but it also ensured that in the event of multiple candidate addresses, the same one was returned each time.

There are now various analogues to this machine public/private address in Juju 4, but many have incorrect logic. This also goes for unit addresses reported as public/private address and ingress addresses for the response to `network-get`.

Incorrect logic occurs in the following places:
- _domain/network/state/unitinfo.go_. `AllMatchingScope` is used to get `sortedIngressAddresses`, but this is not a sort. It only orders by _scope_ preference. Multiple IPs could still result in inconsistent returns. The uniter API picks the zero index from the return. Note also that the network state should not contain this logic - it belongs in the service.
- _domain/network/service/machineaddress.go_ uses `OneMatchingScope` for public and private addresses. There is no sorting here, and so no guarantee of consistency.
- In _domain/network/service/unitaddress.go_, the fallback when there are no scope matches selects index 0 without sorting.
- _domain/status/state/model/modelstate.go_ loops over machine addresses, omitting non-public scopes before sorting, but this is incorrect. We should just sort then take index zero, as that will already prefer IP public scoped addresses. This goes for other places above returning a singular public address.

### Juju version

4.0 HEAD

### Cloud

_No response_

### Expected behaviour

All of these code paths should return the same address, based on the same list of candidate addresses.

### Reproduce / Test

No reproduction. These are logical errors.

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by iyiguncevik**
This PR fixes non-deterministic address selection by making scope-based
matching deterministic and by clarifying layer responsibilities between network
state and service code.

The issue is that callers often select the first matching address; when
candidate order is unstable, selected addresses can vary across runs.

What changed:

1. `domain/network/state/unitinfo.go` + `domain/network/service/unitinfo.go` —no change. This was fixed in #22054

2. `core/network/address.go`: Updated `SpaceAddresses.AllMatchingScope` to return deterministically sorted matches —this is the most important change.

3. `domain/network/service/unitaddress.go`:  GetUnitPrivateAddress now:
- returns first cloud-local match when available;
- otherwise sorts all candidates and returns a deterministic fallback.

4. `domain/status/state/model/modelstate.go` —no change. It is intentionally left unchanged in this PR because `GetMachineFullStatuses` currently has downstream expectations on that shape/contract, so “fixing” it here would break expected behavior.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Setup network interfaces: 

```sh
❯ lxc network create lxdbr1 \
  ipv4.address=10.155.6.1/24 \
  ipv4.nat=true \
  ipv6.address=none
❯ lxc network create lxdbr2 \
  ipv4.address=10.155.2.1/24 \
  ipv4.nat=true \
  ipv6.address=none
❯ lxc network create lxdbr3 \
  ipv4.address=10.155.3.1/24 \
  ipv4.nat=true \
  ipv6.address=none
    
❯ lxc network list

❯ lxc profile device add default eth1 nic \
  network=lxdbr1 name=eth1
❯ lxc profile device add default eth2 nic \
  network=lxdbr2 name=eth2
❯ lxc profile device add default eth3 nic \
  network=lxdbr3 name=eth3

❯ lxc profile show default | yq '.devices'
eth0:
  name: eth0
  network: lxdbr0
  type: nic
eth1:
  name: eth1
  network: lxdbr1
  type: nic
eth2:
  name: eth2
  network: lxdbr2
  type: nic
eth3:
  name: eth3
  network: lxdbr3
  type: nic
root:
  path: /
  pool: default
  type: disk

❯ juju bootstrap lxd src
```

Verify IP addresses

```sh
❯ juju show-machine -m controller 0 | yq '.machines["0"].network-interfaces'
eth0:
  ip-addresses:
    - 10.179.172.166/24
    - fd42:4d03:34fb:4185:216:3eff:febc:bb6b/64
  mac-address: 00:16:3e:bc:bb:6b
  gateway: 10.179.172.1
  space: alpha
  is-up: true
eth1:
  ip-addresses:
    - 10.155.6.24/24
  mac-address: 00:16:3e:2f:35:f3
  space: alpha
  is-up: true
eth2:
  ip-addresses:
    - 10.155.2.157/24
  mac-address: 00:16:3e:17:73:e9
  space: alpha
  is-up: true
eth3:
  ip-addresses:
    - 10.155.3.114/24
  mac-address: 00:16:3e:49:12:d9
  space: alpha
  is-up: true

❯ juju add-model m
❯ juju add-ssh-key "$(cat ${JUJU_DATA}/ssh/juju_id_ed25519.pub)"
❯ juju deploy ubuntu-lite qa

❯ juju ssh 0 'ip -4 addr' | grep inet
    inet 127.0.0.1/8 scope host lo
    inet 10.179.172.74/24 metric 100 brd 10.179.172.255 scope global dynamic eth0
    inet 10.155.6.93/24 metric 110 brd 10.155.6.255 scope global dynamic eth1
    inet 10.155.2.190/24 metric 120 brd 10.155.2.255 scope global dynamic eth2
    inet 10.155.3.238/24 metric 130 brd 10.155.3.255 scope global dynamic eth3

❯ juju show-unit qa/0 --format=yaml | yq '."qa/0".public-address'
10.155.2.190

❯ juju exec --unit qa/0 -- unit-get private-address
10.155.2.190                                                  

❯ juju exec --unit qa/0 -- unit-get public-address
10.155.2.190

❯ juju status --format=json | jq -r '.machines["0"]."ip-addresses"[]'
10.155.2.190
10.155.3.238
10.155.6.93
10.179.172.74
fd42:4d03:34fb:4185:216:3eff:fe5e:e9ef

# try 100 times
❯ for i in {1..100}; do juju status --format=json | jq -r '.machines["0"]."ip-addresses"[]'; done | paste - - - - - | sort | uniq -c
    100 10.155.2.190	10.155.3.238	10.155.6.93	10.179.172.74	fd42:4d03:34fb:4185:216:3eff:fe5e:e9ef 
```

## Links

**Issue:** Fixes #21809

**Jira card:** [JUJU-9244](https://warthogs.atlassian.net/browse/JUJU-9244)

[JUJU-9244]: https://warthogs.atlassian.net/browse/JUJU-9244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: domain/network/service/unitaddress.go [hunk 1]
```diff
@@ -38,16 +38,16 @@ func (s *Service) GetUnitPrivateAddress(ctx context.Context, unitName unit.Name)
...
+	if len(matchedAddrs) > 0 {
+		return matchedAddrs[0], nil
 	}
-	// Then sort by origin.
-	sort.Slice(matchedAddrs, matchedAddrs.Less)
 
-	return matchedAddrs[0], nil
+	// If no address matches cloud-local scope, pick a deterministic first
+	// address from all candidates.
+	sortedAddrs := append(network.SpaceAddresses(nil), addrs...)
```
Comment (manadart) [inline domain/network/service/unitaddress.go]: This part is not right. `addrs.AllMatchingScope(network.ScopeMatchCloudLocal)` will already fall back to a public address if there is no cloud-local address, no the only thing that can remain are localhost and link-local addresses, which are not suitable. From here we should return `network.NoAddressError("private")`.

File: domain/network/service/unitaddress.go [hunk 2]
```diff
@@ -38,16 +37,15 @@ func (s *Service) GetUnitPrivateAddress(ctx context.Context, unitName unit.Name)
...
+	if len(matchedAddrs) > 0 {
+		return matchedAddrs[0], nil
 	}
-	// Then sort by origin.
-	sort.Slice(matchedAddrs, matchedAddrs.Less)
 
-	return matchedAddrs[0], nil
+	// AllMatchingScope already falls back to public addresses if no
+	// cloud-local address exists. If we still have no match, only
+	// unsuitable addresses (localhost, link-local) remain.
```
Comment (nvinuesa) [inline domain/network/service/unitaddress.go:47]: As @manadart mentioned, this will probably follow the same kind of implementation as `GetUnitPublicAddresses()` (i.e. handle the matching/sorting on the state layer with proper SQL).
