### PR TITLE
fix: consult charm container volume mounts for the correct mount path

### LINKED ISSUE #21379: Storage Provisioner reports wrong mount point for filesystem attachment on CAAS units.
### Description

**Backstory:**
In 3.6 we have two storage provisioners in a controller. One for CAAS storage and one for everything else. In reality the CAAS storage provisioner did nothing and was a bunch of NOOP operations. For Juju 4.0 we made the decision to delete the CAAS storage provisioner and converge on the a single storage provisioner. This could be done because we now had storage for CAAS units modelled correctly and so the storage information we have for any unit regardless of model type can be used in the same storage provisioner.

The split in storage provisioners was mostly to do with watchers and the mechanisms used in Mongo to find storage that needed to be watched. This work was done in PR #20105 and #21108 to cut over storage provisioner use.

As part of 4.0 we also change the underlying implementation of the Kubernetes storage provider to offer up filesystem sources over volume sources. This is the way it should have always been as Kubernetes from Juju perspective only talks in terms of filesystems. PR #20628 did this work.

For CAAS filesystem attachments the mount point for which they are mounted inside of a charm container is calculated slightly differently to that of IAAS models. The main reason for this is because when we tell Kubernetes to create filesystem attachments onto a unit we are doing it via a template that applies to all units not just one. We there for use a unique index for the mount point instead of the UUID of the attachment. This is so that for multiple storage instances of the same charm storage they always get mounted at a unique location within the charm.

**Problem:**
@adisazhar123 noticed while performing the work in #21339 that the storage provisioner is getting the filesystem params from the controller via [this](https://github.com/juju/juju/blob/9de91620dee26e1919f0e4df3f39f8ec79173083/domain/storageprovisioning/service/filesystem.go#L345) service method.

At the moment this params result is only considering mount points from an IAAS context and not a CAAS one. This results in the storage provisioner reporting the wrong mount location back to the controller and in turn feeds the hook result to the charm.

### Juju version

4.0

### Cloud

_No response_

### Expected behaviour

We should use the index approach to filesystem attachment mount points on charm containers in CAAS scenarios.

### Reproduce / Test

Deploy vault-k8s and watch the errors from the charm.

### Notes & References

I think we can fix this in the Kubernetes provider filesystem source by making it report backwards into the storage provisioner.

### PR DESCRIPTION
**Pull request by adisazhar123**
We have a bug where the storage provisioner was getting an incorrect mount path, in turn when the hook is triggered supplying the mount path, the charm assumes that the mount path exists, and in reality it doesn't. An example can be seen when deploying `vault-k8s`, the charm tries to lookup a certificate file `ca.pem` but fails to find it because the directory isn't mounted in the charm container.

```
...
2025-12-16T03:40:26.654Z [container-agent]     raise OSError(
2025-12-16T03:40:26.654Z [container-agent] OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /var/lib/juju/storage/09f5ee7d-4cb7-4866-876a-4216014e1283/ca.pem
...
```

The correct mount point is actually `/var/lib/juju/storage/<storage-name>-<uniqueid>` which can be grabbed by searching through the volume mounts of the charm container.

As you can see the `/var/lib/juju/storage/certs-0` directory has the following files

```
root@vault-k8s-0:/var/lib/juju/storage/certs-0# ls
ca.pem  cert.pem  key.pem
```

Therefore, this PR contributes to how we report the mount path.

1. In the AttachFilesystems func, we are given a slice of `FilesystemAttachmentParams` in which it contains:
   -  `ProviderId` which corresponds to the pvc name 
   - `InstanceId` which corresponds to the pod name
2. We then get the pod by its name
3. Looking at the pod's volumes, we can match the claim name by the pvc name
4. Once we know the volume (and its name), we search through the charm container's volume mounts (we have the pod from step 2) and match it by the volume name. Once the volume mount is found, we return its mount path.

In this PR's implementation, the `InstanceId` is still missing. This is because the existing implementation assumes that `InstanceId` is a machine identifier. What should happen next is to populate the `InstanceId` with the kubernetes pod's name. This will happen in the next PR https://github.com/juju/juju/pull/21487.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Run unit test for now. Once the followup PR to populate the `InstanceId` lands, we can test a deployment.

## Documentation changes

N/A

## Links

**Issue:** Fixes #21379.

**Jira card:** [JUJU-8923](https://warthogs.atlassian.net/browse/JUJU-8923)

[JUJU-8923]: https://warthogs.atlassian.net/browse/JUJU-8923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: internal/provider/kubernetes/storage_test.go [hunk 1]
```diff
@@ -237,3 +240,431 @@ func (s *storageSuite) TestImportFilesystemAlreadyBound(c *tc.C) {
...
+						},
+					},
+				},
+			},
+		},
+	}, nil)
+
+	res, err := fs.AttachFilesystems(c.Context(), params)
+	c.Check(err, tc.ErrorIsNil)
+	c.Check(res, tc.HasLen, 1)
```
Comment (CodingCookieRookie) [inline internal/provider/kubernetes/storage_test.go]: nit: we should change this to assert to prevent test panics if len is 0, same for the rest below

File: internal/provider/kubernetes/storage_test.go [hunk 2]
```diff
@@ -237,3 +240,431 @@ func (s *storageSuite) TestImportFilesystemAlreadyBound(c *tc.C) {
...
+	c.Check(res[0].Error, tc.ErrorIsNil)
+	c.Check(*res[0].FilesystemAttachment, tc.DeepEquals, storage.FilesystemAttachment{
```
Comment (CodingCookieRookie) [inline internal/provider/kubernetes/storage_test.go]: nit: since we are using deepEquals we should be able to compare pointers without dereferencing, in the event that res.FilesystemAttachment is nil, i.e we can use &storage.FilesystemAttachment{.. instead

**Review by CodingCookieRookie — APPROVED** [review]
LGTM, just some minor nits thanks adis!

File: internal/provider/kubernetes/storage.go [hunk 3]
```diff
@@ -629,7 +638,7 @@ func (v *filesystemSource) AttachFilesystems(
 }
 
 func (v *filesystemSource) getPersistentVolumeClaim(
-	ctx context.Context, pvcName string, mountPath string, readOnly bool,
+	ctx context.Context, pvcName string, readOnly bool, instanceID string,
```
Comment (tlm) [inline internal/provider/kubernetes/storage.go]: when we get to this part in the provider I think we should swap to podID. i.e get more domain specific so the value has more meaning.

File: internal/provider/kubernetes/storage.go [hunk 4]
```diff
@@ -643,10 +652,53 @@ func (v *filesystemSource) getPersistentVolumeClaim(
...
+			instanceID,
+		).Add(coreerrors.NotFound)
+	} else if err != nil {
+		return jujustorage.FilesystemAttachmentInfo{}, errors.Errorf(
+			"getting kubernetes Pod %q: %w", instanceID, err,
+		)
+	}
+
+	containerIdx := slices.IndexFunc(pod.Spec.Containers, func(container core.Container) bool {
+		return container.Name == "charm"
```
Comment (tlm) [inline internal/provider/kubernetes/storage.go]: Do we have a constant for "charm" in the provider? If we do probably best to use that. Just a double check.

File: internal/provider/kubernetes/storage.go [hunk 5]
```diff
@@ -643,10 +652,53 @@ func (v *filesystemSource) getPersistentVolumeClaim(
...
+	})
+	if containerIdx == -1 {
+		return jujustorage.FilesystemAttachmentInfo{}, errors.New(
+			"charm container fot found").Add(coreerrors.NotFound)
```
Comment (tlm) [inline internal/provider/kubernetes/storage.go]: Should this be a not provisioned error do you think?

File: internal/provider/kubernetes/storage.go [hunk 6]
```diff
@@ -643,10 +652,53 @@ func (v *filesystemSource) getPersistentVolumeClaim(
...
+	}
+
+	charmContainer := pod.Spec.Containers[containerIdx]
+	volIdx := slices.IndexFunc(pod.Spec.Volumes, func(volume core.Volume) bool {
```
Comment (tlm) [inline internal/provider/kubernetes/storage.go:680]: I was worried about this and that it wouldn't work for tmpfs filesystems but I realised that this will be fine because this provider doesn't deal with these aspects.

File: internal/provider/kubernetes/storage.go [hunk 7]
```diff
@@ -643,10 +652,53 @@ func (v *filesystemSource) getPersistentVolumeClaim(
...
+		return volume.PersistentVolumeClaim.ClaimName == pvcName
+	})
+	if volIdx == -1 {
+		return jujustorage.FilesystemAttachmentInfo{}, errors.Errorf(
+			"pod volume which references claim %q not found", pvcName,
+		).Add(coreerrors.NotFound)
```
Comment (tlm) [inline internal/provider/kubernetes/storage.go]: Same comments as above re not provisioned. I am not sure just brain dumping here for the moment.

File: internal/provider/kubernetes/storage.go [hunk 8]
```diff
@@ -643,10 +652,53 @@ func (v *filesystemSource) getPersistentVolumeClaim(
...
+	if volumeMountIdx == -1 {
+		return jujustorage.FilesystemAttachmentInfo{}, errors.Errorf(
+			"pod volume mount %q not found", volumeName,
+		).Add(coreerrors.NotFound)
+	}
+	volumeMount := charmContainer.VolumeMounts[volumeMountIdx]
+
 	fsAttachment := jujustorage.FilesystemAttachmentInfo{
-		Path:     mountPath,
+		Path:     volumeMount.MountPath,
```
Comment (tlm) [inline internal/provider/kubernetes/storage.go:701]: Crisp implementation!

File: internal/provider/kubernetes/storage_test.go (hunk 1 above)
Comment (adisazhar123) [reply internal/provider/kubernetes/storage_test.go]: Done

File: internal/provider/kubernetes/storage_test.go (hunk 2 above)
Comment (adisazhar123) [reply internal/provider/kubernetes/storage_test.go]: Ah good one. Done.

File: internal/provider/kubernetes/storage.go (hunk 3 above)
Comment (adisazhar123) [reply internal/provider/kubernetes/storage.go]: Renamed to podName. Done.

File: internal/provider/kubernetes/storage.go (hunk 4 above)
Comment (adisazhar123) [reply internal/provider/kubernetes/storage.go]: We do. Done.

File: internal/provider/kubernetes/storage.go (hunk 5 above)
Comment (adisazhar123) [reply internal/provider/kubernetes/storage.go]: Yup, it makes sense. Done.
